LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionDateTime Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionDateTime Class Reference
test action datetime
Public Member Functions
final void applyplus (final Triple< IAction, Pair< ZonedDateTime, Integer >, String > p_value)
test apply-days plus
final void applysminus (final Triple< IAction, Pair< ZonedDateTime, Integer >, String > p_value)
test apply-days minus
final void between (final Triple< IAction, Stream< ITerm >, Stream< Number >> p_value)
test between
final void build ()
test build
final void create ()
test create
final void createerror ()
test create error
final void time ()
test time
final void zoneid ()
test zone-id
Static Public Member Functions
static Object [] generateapplyminus ()
data provider generator of apply-minus tests
static Object [] generateapplyplus ()
data provider generator of apply-plus tests
static Object [] generatebetween ()
data provider generator of between tests
Static Private Member Functions
static Object testcaseapply (final IAction p_action, final String p_datetime, final int p_value, final String p_result)
generate test-case of apply definition
static Object testcasebetween (final IAction p_action, final Stream< String > p_datetime, final Stream< Number > p_results)
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 71 of file TestCActionDateTime.java.
Member Function Documentation
applyplus()
final void org.lightjason.agentspeak.action.builtin.TestCActionDateTime.applyplus (final Triple< IAction, Pair< ZonedDateTime, Integer >, String > p_value)
Parameters
p_value tripel action, input data and result
Definition at line 353 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
applysminus()
final void org.lightjason.agentspeak.action.builtin.TestCActionDateTime.applysminus (final Triple< IAction, Pair< ZonedDateTime, Integer >, String > p_value)
Parameters
p_value tripel action, input data and result
Definition at line 332 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
between()
final void org.lightjason.agentspeak.action.builtin.TestCActionDateTime.between (final Triple< IAction, Stream< ITerm >, Stream< Number >> p_value)
Parameters
p_value tripel action, input data and result
Definition at line 374 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN.
build()
final void org.lightjason.agentspeak.action.builtin.TestCActionDateTime.build ()
Definition at line 251 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.datetime.CBuild.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionDateTime.create ()
Definition at line 228 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
createerror()
final void org.lightjason.agentspeak.action.builtin.TestCActionDateTime.createerror ()
Definition at line 213 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
generateapplyminus()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionDateTime.generateapplyminus () static
Returns
data
Definition at line 79 of file TestCActionDateTime.java.
generateapplyplus()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionDateTime.generateapplyplus () static
Returns
data
Definition at line 98 of file TestCActionDateTime.java.
generatebetween()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionDateTime.generatebetween () static
Returns
data
Definition at line 118 of file TestCActionDateTime.java.
testcaseapply()
static Object org.lightjason.agentspeak.action.builtin.TestCActionDateTime.testcaseapply (final IAction p_action, final String p_datetime, final int p_value, final String p_result) static private
Parameters
p_action used-action
p_datetime referenced date-time
p_value value of the action arguments
p_result result time string
Returns
test object
Definition at line 189 of file TestCActionDateTime.java.
testcasebetween()
static Object org.lightjason.agentspeak.action.builtin.TestCActionDateTime.testcasebetween (final IAction p_action, final Stream< String > p_datetime, final Stream< Number > p_results) static private
Parameters
p_action used-action
p_datetime date-time values
p_results between results of tuples
Returns
test obejct
Definition at line 202 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
time()
final void org.lightjason.agentspeak.action.builtin.TestCActionDateTime.time ()
Definition at line 283 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
zoneid()
final void org.lightjason.agentspeak.action.builtin.TestCActionDateTime.zoneid ()
Definition at line 308 of file TestCActionDateTime.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.datetime.IDateTime.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().