LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionBinding Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionBinding Class Reference
test action binding
Classes
class CClassBindingBlacklist
test class with blacklist binding
class CClassBindingDefault
test class with default binding
class CClassBindingWhitelist
test class with whitelist binding
class CMethodBindingBlacklist
test class with blacklist binding
class CMethodBindingDefault
test class with default binding
class CMethodBindingWhitelist
test class with whitelist binding
Public Member Functions
final void classbinding ()
test class binding
final void methodblacklist ()
test method blacklist binding
final void methoddefault ()
test method default binding
final void methodwhitelist ()
test method whitelist binding
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 41 of file TestCActionBinding.java.
Member Function Documentation
classbinding()
final void org.lightjason.agentspeak.action.builtin.TestCActionBinding.classbinding ()
Definition at line 48 of file TestCActionBinding.java.
References org.lightjason.agentspeak.common.CCommon.actionsFromAgentClass().
methodblacklist()
final void org.lightjason.agentspeak.action.builtin.TestCActionBinding.methodblacklist ()
Definition at line 80 of file TestCActionBinding.java.
References org.lightjason.agentspeak.common.CCommon.actionsFromAgentClass().
methoddefault()
final void org.lightjason.agentspeak.action.builtin.TestCActionBinding.methoddefault ()
Definition at line 67 of file TestCActionBinding.java.
References org.lightjason.agentspeak.common.CCommon.actionsFromAgentClass().
methodwhitelist()
final void org.lightjason.agentspeak.action.builtin.TestCActionBinding.methodwhitelist ()
Definition at line 93 of file TestCActionBinding.java.
References org.lightjason.agentspeak.common.CCommon.actionsFromAgentClass().