LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> Class Template Reference
org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> Class Template Reference abstract
on-demand beliefbase for creating trigger-events without any percistency
Public Member Functions
ILiteral add (@Nonnull final ILiteral p_literal)
adds a literal
final IView add (@Nonnull final IView p_view)
adds a view
final IBeliefbase clear ()
clears all elements
boolean containsLiteral (@Nonnull final String p_key)
contains a multi-element
final boolean containsView (@Nonnull final String p_key)
contains a single-element
boolean empty ()
checks if the structure empty
Collection< ILiteral > literal (@Nonnull final String p_key)
returns a literal by the name
ILiteral remove (@Nonnull final ILiteral p_literal)
removes a literal
final IView remove (@Nonnull final IView p_view)
removes a view
int size ()
returns the size of literals
Stream< ILiteral > streamLiteral ()
returns a stream over all literals
final Stream< IView > streamView ()
returns a stream over all views
final IView view (@Nonnull final String p_key)
returns a view element
final IView viewOrDefault (@Nonnull final String p_key, final IView p_default)
Public Member Functions inherited from org.lightjason.agentspeak.beliefbase.IBaseBeliefbase
ILiteral add (@Nonnull final ILiteral p_literal)
adds a literal
final IView create (@Nonnull final String p_name)
returns a new view of the belief base
final IView create (@Nonnull final String p_name, final IView p_parent)
ILiteral remove (@Nonnull final ILiteral p_literal)
removes a literal
Stream< ITrigger > trigger (@Nonnull final IView p_view)
returns all trigger of the beliefbase
IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
Public Member Functions inherited from org.lightjason.agentspeak.beliefbase.IBeliefbase
IView create (@Nonnull final String p_name, @Nullable final IView p_parent)
returns a new view of the belief base
IView viewOrDefault (@Nonnull final String p_key, @Nullable final IView p_default)
returns a view element
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.beliefbase.IBeliefbase
IBeliefbase EMPY
empty beliefbase
Protected Member Functions inherited from org.lightjason.agentspeak.beliefbase.IBaseBeliefbase
final Stream< ITrigger > cleartrigger (final IView p_view)
copy of all trigger values
ILiteral event (final ITrigger.EType p_event, final ILiteral p_literal)
push an event and literal to the event map
IView eventreference (final IView p_view)
adds a view to the event referencing structure
final IView internalremove (final IView p_view)
removes the interal view references
Detailed Description
Definition at line 42 of file IBeliefbaseOnDemand.java.
Member Function Documentation
add() [1/2]
ILiteral org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.add (@Nonnull final ILiteral p_literal)
Parameters
p_literal literal without path
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 66 of file IBeliefbaseOnDemand.java.
add() [2/2]
final IView org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.add (@Nonnull final IView p_view)
Parameters
p_view view
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 120 of file IBeliefbaseOnDemand.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
clear()
final IBeliefbase org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.clear ()
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 113 of file IBeliefbaseOnDemand.java.
containsLiteral()
boolean org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.containsLiteral (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 79 of file IBeliefbaseOnDemand.java.
containsView()
final boolean org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.containsView (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 133 of file IBeliefbaseOnDemand.java.
empty()
boolean org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.empty ()
Returns
empty boolean
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 46 of file IBeliefbaseOnDemand.java.
literal()
Collection<ILiteral> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.literal (@Nonnull final String p_key)
Parameters
p_key name of the literal
Returns
collection of pairs with negated and literal
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 86 of file IBeliefbaseOnDemand.java.
remove() [1/2]
ILiteral org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.remove (@Nonnull final ILiteral p_literal)
Parameters
p_literal without path
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 73 of file IBeliefbaseOnDemand.java.
remove() [2/2]
final IView org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.remove (@Nonnull final IView p_view)
Parameters
p_view view
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 127 of file IBeliefbaseOnDemand.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
size()
int org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.size ()
Returns
size
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 52 of file IBeliefbaseOnDemand.java.
streamLiteral()
Stream<ILiteral> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.streamLiteral ()
Returns
literal stream
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 59 of file IBeliefbaseOnDemand.java.
streamView()
final Stream<IView> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.streamView ()
Returns
view stream
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 106 of file IBeliefbaseOnDemand.java.
view()
final IView org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.view (@Nonnull final String p_key)
Parameters
p_key name of the view
Returns
view or null
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 93 of file IBeliefbaseOnDemand.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
viewOrDefault()
final IView org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.viewOrDefault (@Nonnull final String p_key, final IView p_default)
Definition at line 99 of file IBeliefbaseOnDemand.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().