LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.IPlan Interface Reference
org.lightjason.agentspeak.language.instantiable.plan.IPlan Interface Reference
interface of plan
Public Member Functions
IFuzzyValue< Boolean > condition (final IContext p_context)
execute the plan condition
ITrigger trigger ()
returns the trigger event
Public Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IInstantiable
IContext instantiate (@Nonnull final IAgent<?> p_agent, @Nonnull final Stream< IVariable<?>> p_variable)
creates an individual execution context
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.IExecution
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Attributes
IPlan EMPTY
empty plan
Detailed Description
Definition at line 43 of file IPlan.java.
Member Function Documentation
condition()
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.instantiable.plan.IPlan.condition (final IContext p_context)
Parameters
p_context execution context
Returns
execution result
Implemented in org.lightjason.agentspeak.action.builtin.TestCActionAgent.CEmptyPlan, and org.lightjason.agentspeak.language.instantiable.plan.CPlan.
trigger()
ITrigger org.lightjason.agentspeak.language.instantiable.plan.IPlan.trigger ()
Returns
trigger event
Implemented in org.lightjason.agentspeak.action.builtin.TestCActionAgent.CEmptyPlan, and org.lightjason.agentspeak.language.instantiable.plan.CPlan.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.getplan(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist(), and org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplan().
Member Data Documentation
EMPTY
IPlan org.lightjason.agentspeak.language.instantiable.plan.IPlan.EMPTY
Definition at line 48 of file IPlan.java.