LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.graph.CEdges Class Reference
org.lightjason.agentspeak.action.builtin.graph.CEdges Class Reference
returns for a graph all edges.
Public Member Functions
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int minimalArgumentNumber ()
minimum number of arguments
Public Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Static Private Attributes
static final long serialVersionUID = 2290182024313887326L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
IBuiltinAction ()
ctor
IBuiltinAction (final int p_length)
ctor
Static Protected Attributes inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
static final Logger LOGGER = CCommon.logger(IBuiltinAction.class)
logger
Static Protected Attributes inherited from org.lightjason.agentspeak.action.IBaseAction
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Detailed Description
The action returns for all graph arguments a list of edges, the action never fails. The return argument is an unmodifyable list
[E1|E2] = graph/edges(Graph1, Graph2);
Definition at line 50 of file CEdges.java.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.action.builtin.graph.CEdges.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 66 of file CEdges.java.
References org.lightjason.agentspeak.language.CCommon.flatten(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionGraph.edges().
minimalArgumentNumber()
final int org.lightjason.agentspeak.action.builtin.graph.CEdges.minimalArgumentNumber ()
Returns
number of minimal arguments
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 59 of file CEdges.java.
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.action.builtin.graph.CEdges.serialVersionUID = 2290182024313887326L static private
Definition at line 55 of file CEdges.java.