LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CLambdaExpression Class Reference
org.lightjason.agentspeak.language.execution.action.CLambdaExpression Class Reference
lambda expression definition
Public Member Functions
CLambdaExpression (final boolean p_parallel, @Nonnull final IExecution p_initialize, @Nonnull final IVariable<?> p_iterator, @Nonnull final List< IExecution > p_body)
ctor
CLambdaExpression (final boolean p_parallel, @Nonnull final IExecution p_initialize, @Nonnull final IVariable<?> p_iterator, @Nullable final IVariable<?> p_return, @Nonnull final List< IExecution > p_body)
ctor
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IVariable<?> >
final T getValue ()
returns the value of the action
final boolean isValueAssignableTo (final Class<?> p_class)
checkes assinable of the value
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Member Functions
List<?> executeParallel (@Nonnull final IContext p_context, @Nonnull final List< ITerm > p_input)
run parallel execution
List<?> executeSequential (@Nonnull final IContext p_context, @Nonnull final List< ITerm > p_input)
run sequential execution
Triple< IContext, IVariable<?>, IVariable<?> > getLocalContext (@Nonnull final IContext p_context)
create the local context structure of the expression
Private Attributes
final List< IExecution > m_body
execution body
final IExecution m_initialize
initialization expression
final boolean m_parallel
flag of parallel execution
final IVariable<?> m_return
return variable
Static Private Attributes
static final long serialVersionUID = 5128636076731831236L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IVariable<?> >
IBaseExecution (@Nullable final T p_value)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IVariable<?> >
final T m_value
data
Detailed Description
Definition at line 53 of file CLambdaExpression.java.
Constructor & Destructor Documentation
CLambdaExpression() [1/2]
org.lightjason.agentspeak.language.execution.action.CLambdaExpression.CLambdaExpression (final boolean p_parallel, @Nonnull final IExecution p_initialize, @Nonnull final IVariable<?> p_iterator, @Nonnull final List< IExecution > p_body)
Parameters
p_parallel parallel execution flag
p_initialize expression
p_iterator iteration variable
p_body execution body
Definition at line 85 of file CLambdaExpression.java.
CLambdaExpression() [2/2]
org.lightjason.agentspeak.language.execution.action.CLambdaExpression.CLambdaExpression (final boolean p_parallel, @Nonnull final IExecution p_initialize, @Nonnull final IVariable<?> p_iterator, @Nullable final IVariable<?> p_return, @Nonnull final List< IExecution > p_body)
Parameters
p_parallel parallel execution flag
p_initialize expression
p_iterator iteration variable
p_return return variable
p_body execution body
Definition at line 100 of file CLambdaExpression.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.action.CLambdaExpression.equals (final Object p_object)
Definition at line 135 of file CLambdaExpression.java.
References org.lightjason.agentspeak.language.execution.action.CLambdaExpression.hashCode().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CLambdaExpression.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Definition at line 112 of file CLambdaExpression.java.
References org.lightjason.agentspeak.language.execution.IExecution.execute(), org.lightjason.agentspeak.language.execution.action.CLambdaExpression.executeParallel(), org.lightjason.agentspeak.language.execution.action.CLambdaExpression.executeSequential(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), and org.lightjason.agentspeak.language.variable.IVariable< T >.set().
executeParallel()
List<?> org.lightjason.agentspeak.language.execution.action.CLambdaExpression.executeParallel (@Nonnull final IContext p_context, @Nonnull final List< ITerm > p_input) private
Parameters
p_context execution context
p_input input list
Returns
return list
Definition at line 194 of file CLambdaExpression.java.
References org.lightjason.agentspeak.language.execution.action.CLambdaExpression.getLocalContext().
Referenced by org.lightjason.agentspeak.language.execution.action.CLambdaExpression.execute().
executeSequential()
List<?> org.lightjason.agentspeak.language.execution.action.CLambdaExpression.executeSequential (@Nonnull final IContext p_context, @Nonnull final List< ITerm > p_input) private
Parameters
p_context execution context
p_input input list
Returns
return list
Definition at line 166 of file CLambdaExpression.java.
References org.lightjason.agentspeak.language.execution.action.CLambdaExpression.getLocalContext().
Referenced by org.lightjason.agentspeak.language.execution.action.CLambdaExpression.execute().
getLocalContext()
Triple<IContext, IVariable<?>, IVariable<?> > org.lightjason.agentspeak.language.execution.action.CLambdaExpression.getLocalContext (@Nonnull final IContext p_context) private
Parameters
p_context local context
Returns
tripel with context, iterator variable and return variable
Definition at line 222 of file CLambdaExpression.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< IVariable<?> >.m_value, and org.lightjason.agentspeak.language.execution.IExecution.variables().
Referenced by org.lightjason.agentspeak.language.execution.action.CLambdaExpression.executeParallel(), and org.lightjason.agentspeak.language.execution.action.CLambdaExpression.executeSequential().
hashCode()
final int org.lightjason.agentspeak.language.execution.action.CLambdaExpression.hashCode ()
Definition at line 129 of file CLambdaExpression.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< IVariable<?> >.m_value.
Referenced by org.lightjason.agentspeak.language.execution.action.CLambdaExpression.equals().
toString()
final String org.lightjason.agentspeak.language.execution.action.CLambdaExpression.toString ()
Definition at line 153 of file CLambdaExpression.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< IVariable<?> >.m_value.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CLambdaExpression.variables ()
Definition at line 142 of file CLambdaExpression.java.
References org.lightjason.agentspeak.language.execution.IExecution.variables().
Member Data Documentation
m_body
final List<IExecution> org.lightjason.agentspeak.language.execution.action.CLambdaExpression.m_body private
Definition at line 66 of file CLambdaExpression.java.
m_initialize
final IExecution org.lightjason.agentspeak.language.execution.action.CLambdaExpression.m_initialize private
Definition at line 62 of file CLambdaExpression.java.
m_parallel
final boolean org.lightjason.agentspeak.language.execution.action.CLambdaExpression.m_parallel private
Definition at line 70 of file CLambdaExpression.java.
m_return
final IVariable<?> org.lightjason.agentspeak.language.execution.action.CLambdaExpression.m_return private
Definition at line 74 of file CLambdaExpression.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.CLambdaExpression.serialVersionUID = 5128636076731831236L static private
Definition at line 58 of file CLambdaExpression.java.