LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.IAction Interface Reference
org.lightjason.agentspeak.action.IAction Interface Reference
external action interface
Public Member Functions
default int minimalArgumentNumber ()
minimum number of arguments
IPath name ()
returns the name with path of the action
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.IExecution
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Public Attributes
long serialVersionUID = -6374480398439703170L
serial id
Detailed Description
Definition at line 38 of file IAction.java.
Member Function Documentation
minimalArgumentNumber()
default int org.lightjason.agentspeak.action.IAction.minimalArgumentNumber ()
Returns
number of minimal arguments
Implemented in org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPop, org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPush, org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerSize, org.lightjason.agentspeak.agent.TestCHanoiTowers.CStop, org.lightjason.agentspeak.agent.TestCHanoiTowers.CEmptyPrint, org.lightjason.agentspeak.agent.TestCAgentExecution.CLog, org.lightjason.agentspeak.agent.TestCAgentExecution.CStop, org.lightjason.agentspeak.beliefbase.TestCViewMap.CTestResult, org.lightjason.agentspeak.agent.TestCAgent.CTestResult, org.lightjason.agentspeak.beliefbase.TestCViewMap.CEmptyPrint, org.lightjason.agentspeak.agent.TestCAgent.CEmptyPrint, org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution, org.lightjason.agentspeak.action.binding.CMethodAction, org.lightjason.agentspeak.action.builtin.storage.CRemove, org.lightjason.agentspeak.action.builtin.storage.CAdd, org.lightjason.agentspeak.action.builtin.storage.CExists, org.lightjason.agentspeak.action.builtin.math.linearprogram.CSolve, org.lightjason.agentspeak.action.builtin.graph.CAdjacencyMatrix, org.lightjason.agentspeak.action.builtin.math.interpolate.CCreate, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CPerronFrobenius, org.lightjason.agentspeak.action.builtin.crypto.CHash, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CParse, org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL, org.lightjason.agentspeak.action.builtin.graph.CCreate, org.lightjason.agentspeak.action.builtin.math.linearprogram.CCreate, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToBlas, org.lightjason.agentspeak.action.builtin.collection.list.CRange, org.lightjason.agentspeak.action.builtin.collection.list.CSymmetricDifference, org.lightjason.agentspeak.action.builtin.math.bit.vector.CToBlas, org.lightjason.agentspeak.action.builtin.math.blas.CElementWise, org.lightjason.agentspeak.action.builtin.math.blas.vector.CParse, org.lightjason.agentspeak.action.builtin.math.linearprogram.CValueConstraint, org.lightjason.agentspeak.action.builtin.math.statistic.CAddStatisticValue, org.lightjason.agentspeak.action.builtin.math.statistic.CRandomSample, org.lightjason.agentspeak.action.builtin.agent.CGetPlan, org.lightjason.agentspeak.action.builtin.collection.list.CRemove, org.lightjason.agentspeak.action.builtin.collection.list.CSubList, org.lightjason.agentspeak.action.builtin.collection.list.CZip, org.lightjason.agentspeak.action.builtin.math.bit.vector.CRange, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCreate, org.lightjason.agentspeak.action.builtin.math.blas.vector.CFromList, org.lightjason.agentspeak.action.builtin.math.linearprogram.CEquationConstraint, org.lightjason.agentspeak.action.builtin.math.statistic.CMultipleStatisticValue, org.lightjason.agentspeak.action.builtin.math.statistic.CSingleStatisticValue, org.lightjason.agentspeak.action.builtin.collection.list.CComplement, org.lightjason.agentspeak.action.builtin.collection.list.CIntersect, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CBoolValue, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CNumericValue, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CAssign, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CGet, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CGraphLaplacian, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNormalizedGraphLaplacian, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CPower, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSingularValue, org.lightjason.agentspeak.action.builtin.math.blas.vector.CAssign, org.lightjason.agentspeak.action.builtin.math.blas.vector.CCreate, org.lightjason.agentspeak.action.builtin.math.blas.vector.CDotProduct, org.lightjason.agentspeak.action.builtin.math.interpolate.CMultipleInterpolate, org.lightjason.agentspeak.action.builtin.math.interpolate.CSingleInterpolate, org.lightjason.agentspeak.action.builtin.math.shape.CInCircle, org.lightjason.agentspeak.action.builtin.math.shape.CInRectangle, org.lightjason.agentspeak.action.builtin.web.rest.IBaseRest, org.lightjason.agentspeak.action.builtin.collection.list.CUnion, org.lightjason.agentspeak.action.builtin.collection.multimap.CAsMap, org.lightjason.agentspeak.action.builtin.graph.CSpanningTree, org.lightjason.agentspeak.action.builtin.math.bit.vector.CNumericValue, org.lightjason.agentspeak.action.builtin.math.bit.vector.CSet, org.lightjason.agentspeak.action.builtin.math.bit.vector.CToList, org.lightjason.agentspeak.action.builtin.math.blas.CMultiply, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CEigen, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRow, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CToList, org.lightjason.agentspeak.action.builtin.math.blas.vector.CToList, org.lightjason.agentspeak.action.builtin.math.shape.CInTriangle, org.lightjason.agentspeak.action.builtin.math.statistic.ISelection, org.lightjason.agentspeak.action.builtin.collection.list.CFlatConcat, org.lightjason.agentspeak.action.builtin.collection.list.CUnique, org.lightjason.agentspeak.action.builtin.collection.map.CRemove, org.lightjason.agentspeak.action.builtin.collection.map.CValues, org.lightjason.agentspeak.action.builtin.collection.multimap.CValues, org.lightjason.agentspeak.action.builtin.collection.set.CContains, org.lightjason.agentspeak.action.builtin.collection.tuple.CCreate, org.lightjason.agentspeak.action.builtin.generic.type.CIs, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CCreate, org.lightjason.agentspeak.action.builtin.math.bit.vector.CBoolValue, org.lightjason.agentspeak.action.builtin.math.bit.vector.CClear, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumn, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CInfinityNorm, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSet, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSubMatrix, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTwoNorm, org.lightjason.agentspeak.action.builtin.math.blas.vector.CGet, org.lightjason.agentspeak.action.builtin.math.blas.vector.CSet, org.lightjason.agentspeak.action.builtin.collection.list.CGet, org.lightjason.agentspeak.action.builtin.collection.list.CReverse, org.lightjason.agentspeak.action.builtin.collection.map.CKeys, org.lightjason.agentspeak.action.builtin.collection.multimap.CKeys, org.lightjason.agentspeak.action.builtin.collection.set.CRemove, org.lightjason.agentspeak.action.builtin.collection.set.CToList, org.lightjason.agentspeak.action.builtin.collection.tuple.CFlat, org.lightjason.agentspeak.action.builtin.crypto.CEncrypt, org.lightjason.agentspeak.action.builtin.datetime.IBetween, org.lightjason.agentspeak.action.builtin.generic.type.CCreateLiteral, org.lightjason.agentspeak.action.builtin.generic.type.CFuzzyReturn, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CCopy, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CSize, org.lightjason.agentspeak.action.builtin.math.bit.vector.CCopy, org.lightjason.agentspeak.action.builtin.math.bit.vector.CCreate, org.lightjason.agentspeak.action.builtin.math.bit.vector.CSize, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumns, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumnSum, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCondition, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCopy, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDeterminant, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDiagonal, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CInvert, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CMatrixNorm, org.lightjason.agentspeak.action.builtin.math.blas.matrix.COneNorm, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRank, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRows, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRowSum, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTrace, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTranspose, org.lightjason.agentspeak.action.builtin.math.blas.vector.CCopy, org.lightjason.agentspeak.action.builtin.agent.CRemovePlan, org.lightjason.agentspeak.action.builtin.bool.CEqual, org.lightjason.agentspeak.action.builtin.crypto.CDecrypt, org.lightjason.agentspeak.action.builtin.generic.type.CIsNull, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CColumns, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CDimension, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CFalseCount, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CNot, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CRows, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CTrueCount, org.lightjason.agentspeak.action.builtin.math.bit.vector.CFalseCount, org.lightjason.agentspeak.action.builtin.math.bit.vector.CNot, org.lightjason.agentspeak.action.builtin.math.bit.vector.CTrueCount, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDimension, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CIdentity, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSum, org.lightjason.agentspeak.action.builtin.math.blas.vector.CNonZero, org.lightjason.agentspeak.action.builtin.math.blas.vector.CSum, org.lightjason.agentspeak.action.builtin.math.statistic.CClearStatistic, org.lightjason.agentspeak.action.builtin.collection.IMapApplyMultiple< T >, org.lightjason.agentspeak.action.builtin.collection.list.CSet, org.lightjason.agentspeak.action.builtin.collection.set.CAdd, org.lightjason.agentspeak.action.builtin.datetime.IPlusMinus, org.lightjason.agentspeak.action.builtin.generic.type.CIsNumeric, org.lightjason.agentspeak.action.builtin.generic.type.ICast, org.lightjason.agentspeak.action.builtin.math.bit.matrix.IRowColumn, org.lightjason.agentspeak.action.builtin.math.blas.CSize, org.lightjason.agentspeak.action.builtin.math.statistic.CMultiplePercentile, org.lightjason.agentspeak.action.builtin.math.statistic.CSinglePercentile, org.lightjason.agentspeak.action.builtin.agent.CPlanStatistic, org.lightjason.agentspeak.action.builtin.collection.list.CAdd, org.lightjason.agentspeak.action.builtin.generic.type.CIsString, org.lightjason.agentspeak.action.builtin.generic.type.CType, org.lightjason.agentspeak.action.builtin.graph.IApplyPathAlgorithm, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSolve, org.lightjason.agentspeak.action.builtin.string.CLevenshtein, org.lightjason.agentspeak.action.builtin.collection.IMapApplySingle< T >, org.lightjason.agentspeak.action.builtin.collection.IMapGetMultiple< T >, org.lightjason.agentspeak.action.builtin.collection.IMapGetSingle< T >, org.lightjason.agentspeak.action.builtin.crypto.CCreateKey, org.lightjason.agentspeak.action.builtin.collection.CSize, org.lightjason.agentspeak.action.builtin.datetime.CBuild, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToVector, org.lightjason.agentspeak.action.builtin.math.bit.matrix.IOperator, org.lightjason.agentspeak.action.builtin.math.bit.vector.IOperator, org.lightjason.agentspeak.action.builtin.math.CSigmoid, org.lightjason.agentspeak.action.builtin.math.CStirling, org.lightjason.agentspeak.action.builtin.string.CNCD, org.lightjason.agentspeak.action.builtin.collection.CIsEmpty, org.lightjason.agentspeak.action.builtin.generic.type.IParse, org.lightjason.agentspeak.action.builtin.graph.CContainsEdge, org.lightjason.agentspeak.action.builtin.graph.CContainsVertex, org.lightjason.agentspeak.action.builtin.graph.CEdges, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CHammingDistance, org.lightjason.agentspeak.action.builtin.math.bit.vector.CHammingDistance, org.lightjason.agentspeak.action.builtin.math.CBinomial, org.lightjason.agentspeak.action.builtin.math.CMaxIndex, org.lightjason.agentspeak.action.builtin.math.CMinIndex, org.lightjason.agentspeak.action.builtin.math.CPrimeFactors, org.lightjason.agentspeak.action.builtin.string.CBase64Decode, org.lightjason.agentspeak.action.builtin.bool.CAllMatch, org.lightjason.agentspeak.action.builtin.bool.CAnyMatch, org.lightjason.agentspeak.action.builtin.graph.CVertices, org.lightjason.agentspeak.action.builtin.math.CIsPrime, org.lightjason.agentspeak.action.builtin.math.CNextPrime, org.lightjason.agentspeak.action.builtin.string.CBase64Encode, org.lightjason.agentspeak.action.builtin.string.CRandom, org.lightjason.agentspeak.action.builtin.string.CReplace, org.lightjason.agentspeak.action.builtin.agent.CAddPlan, org.lightjason.agentspeak.action.builtin.bool.CAnd, org.lightjason.agentspeak.action.builtin.bool.CNot, org.lightjason.agentspeak.action.builtin.bool.COr, org.lightjason.agentspeak.action.builtin.bool.CXor, org.lightjason.agentspeak.action.builtin.collection.CClear, org.lightjason.agentspeak.action.builtin.collection.list.CFlat, org.lightjason.agentspeak.action.builtin.graph.CEdgeCount, org.lightjason.agentspeak.action.builtin.graph.CVertexCount, org.lightjason.agentspeak.action.builtin.math.CAverage, org.lightjason.agentspeak.action.builtin.math.CFactorial, org.lightjason.agentspeak.action.builtin.math.CGeometricMean, org.lightjason.agentspeak.action.builtin.math.CHarmonicMean, org.lightjason.agentspeak.action.builtin.math.CLog, org.lightjason.agentspeak.action.builtin.math.CMax, org.lightjason.agentspeak.action.builtin.math.CMin, org.lightjason.agentspeak.action.builtin.math.CPow, org.lightjason.agentspeak.action.builtin.math.CRound, org.lightjason.agentspeak.action.builtin.math.CTan, org.lightjason.agentspeak.action.builtin.string.CConcat, org.lightjason.agentspeak.action.builtin.collection.tuple.CSet, org.lightjason.agentspeak.action.builtin.math.CACos, org.lightjason.agentspeak.action.builtin.math.CASin, org.lightjason.agentspeak.action.builtin.math.CATan, org.lightjason.agentspeak.action.builtin.math.CCeil, org.lightjason.agentspeak.action.builtin.math.CCosh, org.lightjason.agentspeak.action.builtin.math.CDegrees, org.lightjason.agentspeak.action.builtin.math.CExp, org.lightjason.agentspeak.action.builtin.math.CFloor, org.lightjason.agentspeak.action.builtin.math.CHypot, org.lightjason.agentspeak.action.builtin.math.CLog10, org.lightjason.agentspeak.action.builtin.math.CRadians, org.lightjason.agentspeak.action.builtin.math.CSignum, org.lightjason.agentspeak.action.builtin.math.CSinh, org.lightjason.agentspeak.action.builtin.math.CTanh, org.lightjason.agentspeak.action.builtin.string.CContains, org.lightjason.agentspeak.action.builtin.string.CEndsWith, org.lightjason.agentspeak.action.builtin.string.CStartsWith, org.lightjason.agentspeak.action.builtin.bool.CCountFalse, org.lightjason.agentspeak.action.builtin.generic.CThrow, org.lightjason.agentspeak.action.builtin.math.CAbs, org.lightjason.agentspeak.action.builtin.math.CCos, org.lightjason.agentspeak.action.builtin.math.CSin, org.lightjason.agentspeak.action.builtin.math.CSqrt, org.lightjason.agentspeak.action.builtin.string.CLower, org.lightjason.agentspeak.action.builtin.string.CReverse, org.lightjason.agentspeak.action.builtin.string.CSize, org.lightjason.agentspeak.action.builtin.string.CUpper, org.lightjason.agentspeak.action.builtin.bool.CCountTrue, org.lightjason.agentspeak.action.builtin.math.CSum, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple, and org.lightjason.agentspeak.action.builtin.graph.IApplySingle.
Definition at line 59 of file IAction.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.CActionWrapper().
name()
IPath org.lightjason.agentspeak.action.IAction.name ()
Returns
path (literal functor)
Implemented in org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPop, org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPush, org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerSize, org.lightjason.agentspeak.agent.TestCHanoiTowers.CStop, org.lightjason.agentspeak.agent.TestCHanoiTowers.CEmptyPrint, org.lightjason.agentspeak.agent.TestCAgentExecution.CLog, org.lightjason.agentspeak.agent.TestCAgentExecution.CStop, org.lightjason.agentspeak.beliefbase.TestCViewMap.CTestResult, org.lightjason.agentspeak.agent.TestCAgent.CTestResult, org.lightjason.agentspeak.beliefbase.TestCViewMap.CEmptyPrint, org.lightjason.agentspeak.agent.TestCAgent.CEmptyPrint, org.lightjason.agentspeak.action.binding.CMethodAction, and org.lightjason.agentspeak.action.builtin.IBuiltinAction.
Referenced by org.lightjason.agentspeak.common.CCommon.actionusable(), org.lightjason.agentspeak.action.IBaseAction.hashCode(), and org.lightjason.agentspeak.action.IBaseAction.toString().
variables()
default Stream<IVariable<?> > org.lightjason.agentspeak.action.IAction.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 66 of file IAction.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.variables().
Member Data Documentation
serialVersionUID
long org.lightjason.agentspeak.action.IAction.serialVersionUID = -6374480398439703170L
Definition at line 43 of file IAction.java.