LightJason - AgentSpeak(L++): org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser > Class Template Reference
org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser > Class Template Reference abstract
generic default parser
Protected Member Functions
IBaseParser (@Nonnull final ANTLRErrorListener p_errorlistener) throws NoSuchMethodException
ctor
abstract Class< L > lexerclass ()
returns the lexer class reference
final P parser (@Nonnull final InputStream p_stream) throws IOException, IllegalAccessException, InvocationTargetException, InstantiationException
returns a parser component
abstract Class< P > parserclass ()
returns the parser class reference
Private Attributes
final Constructor< L > m_ctorlexer
ctor lexer reference
final Constructor< P > m_ctorparser
ctor parser reference
final ANTLRErrorListener m_errorlistener
error listener
Additional Inherited Members
Public Member Functions inherited from org.lightjason.agentspeak.grammar.IParser< T >
T parse (final InputStream p_stream) throws Exception
parsing code
Detailed Description
Definition at line 44 of file IBaseParser.java.
Constructor & Destructor Documentation
IBaseParser()
org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser >.IBaseParser (@Nonnull final ANTLRErrorListener p_errorlistener) throws NoSuchMethodException protected
Parameters
p_errorlistener listener instance
Exceptions
NoSuchMethodException on ctor-method call
Definition at line 66 of file IBaseParser.java.
Member Function Documentation
lexerclass()
abstract Class<L> org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser >.lexerclass () abstract protected
Returns
class of lexer
Referenced by org.lightjason.agentspeak.grammar.IBaseParser< IASTVisitorType, TypeLexer, TypeParser >.IBaseParser(), and org.lightjason.agentspeak.grammar.IBaseParser< IASTVisitorType, TypeLexer, TypeParser >.parser().
parser()
final P org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser >.parser (@Nonnull final InputStream p_stream) throws IOException, IllegalAccessException, InvocationTargetException, InstantiationException protected
Parameters
p_stream input stream
Returns
parser (for using in visitor interface)
Exceptions
IOException on io-stream errors
IllegalAccessException on lexer / parser method access error
InvocationTargetException on lexer / parser invocation error
InstantiationException on lexer / parser instantiation error
Definition at line 84 of file IBaseParser.java.
Referenced by org.lightjason.agentspeak.language.CLiteral.CParser.parse().
parserclass()
abstract Class<P> org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser >.parserclass () abstract protected
Returns
class of parser
Referenced by org.lightjason.agentspeak.grammar.IBaseParser< IASTVisitorType, TypeLexer, TypeParser >.IBaseParser(), and org.lightjason.agentspeak.grammar.IBaseParser< IASTVisitorType, TypeLexer, TypeParser >.parser().
Member Data Documentation
m_ctorlexer
final Constructor<L> org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser >.m_ctorlexer private
Definition at line 53 of file IBaseParser.java.
m_ctorparser
final Constructor<P> org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser >.m_ctorparser private
Definition at line 57 of file IBaseParser.java.
m_errorlistener
final ANTLRErrorListener org.lightjason.agentspeak.grammar.IBaseParser< T extends IASTVisitor, L extends Lexer, P extends Parser >.m_errorlistener private
Definition at line 49 of file IBaseParser.java.