LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.CPlan Class Reference
org.lightjason.agentspeak.language.instantiable.plan.CPlan Class Reference
plan structure
Public Member Functions
CPlan (@Nonnull final ITrigger p_event, @Nonnull final List< IExecution > p_body, @Nonnull final Set< IAnnotation<?>> p_annotation)
ctor
CPlan (@Nonnull final ITrigger p_event, @Nonnull final IExpression p_condition, @Nonnull final List< IExecution > p_body, @Nonnull final Set< IAnnotation<?>> p_annotation)
ctor
final IFuzzyValue< Boolean > condition (final IContext p_context)
execute the plan condition
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final String toString ()
final ITrigger trigger ()
returns the trigger event
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
final boolean equals (final Object p_object)
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int hashCode ()
final IContext instantiate (@Nonnull final IAgent<?> p_agent, @Nonnull final Stream< IVariable<?>> p_variable)
creates an individual execution context
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final IExpression m_condition
execution condition / expression
final ITrigger m_triggerevent
trigger event
Static Private Attributes
static final long serialVersionUID = -8130277494195919583L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.instantiable.plan.IPlan
IPlan EMPTY
empty plan
Protected Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
IBaseInstantiable (final List< IExecution > p_action, final Set< IAnnotation<?>> p_annotation, final int p_hash)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
final List< IExecution > m_action
action list
final Map< IAnnotation.EType, IAnnotation<?> > m_annotation
map with annotation (enum value for getting annotation object)
Detailed Description
Definition at line 53 of file language/instantiable/plan/CPlan.java.
Constructor & Destructor Documentation
CPlan() [1/2]
org.lightjason.agentspeak.language.instantiable.plan.CPlan.CPlan (@Nonnull final ITrigger p_event, @Nonnull final List< IExecution > p_body, @Nonnull final Set< IAnnotation<?>> p_annotation)
Parameters
p_event trigger event
p_body plan body
p_annotation annotations
Definition at line 76 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.execution.expression.IExpression.EMPTY.
CPlan() [2/2]
org.lightjason.agentspeak.language.instantiable.plan.CPlan.CPlan (@Nonnull final ITrigger p_event, @Nonnull final IExpression p_condition, @Nonnull final List< IExecution > p_body, @Nonnull final Set< IAnnotation<?>> p_annotation)
Parameters
p_event trigger event
p_condition execution condition
p_body plan body
p_annotation annotations
Definition at line 89 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.CCommon.streamconcat().
Member Function Documentation
condition()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.instantiable.plan.CPlan.condition (final IContext p_context)
Parameters
p_context execution context
Returns
execution result
Implements org.lightjason.agentspeak.language.instantiable.plan.IPlan.
Definition at line 134 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.execution.IExecution.execute(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.instantiable.plan.CPlan.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 119 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEGOAL, org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.literal(), and org.lightjason.agentspeak.language.ILiteral.unify().
toString()
final String org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString ()
Definition at line 159 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action, org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation, and org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent.
trigger()
final ITrigger org.lightjason.agentspeak.language.instantiable.plan.CPlan.trigger ()
Returns
trigger event
Implements org.lightjason.agentspeak.language.instantiable.plan.IPlan.
Definition at line 112 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 173 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.CCommon.flattenrecursive(), org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.literal(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation, org.lightjason.agentspeak.language.ILiteral.orderedvalues(), org.lightjason.agentspeak.language.CCommon.streamconcat(), org.lightjason.agentspeak.language.execution.IExecution.variables(), and org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.variables().
Member Data Documentation
m_condition
final IExpression org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_condition private
Definition at line 66 of file language/instantiable/plan/CPlan.java.
m_triggerevent
final ITrigger org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent private
Definition at line 62 of file language/instantiable/plan/CPlan.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.trigger().
serialVersionUID
final long org.lightjason.agentspeak.language.instantiable.plan.CPlan.serialVersionUID = -8130277494195919583L static private
Definition at line 58 of file language/instantiable/plan/CPlan.java.