LightJason - AgentSpeak(L++): org.lightjason.agentspeak.common.TestCPath Class Reference
org.lightjason.agentspeak.common.TestCPath Class Reference
test of path structure
Public Member Functions
final void collector ()
test stream collector
final void collision ()
test hash collision
final void comparing ()
compare string and path
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 36 of file TestCPath.java.
Member Function Documentation
collector()
final void org.lightjason.agentspeak.common.TestCPath.collector ()
Definition at line 43 of file TestCPath.java.
References org.lightjason.agentspeak.common.CPath.collect().
collision()
final void org.lightjason.agentspeak.common.TestCPath.collision ()
Definition at line 52 of file TestCPath.java.
References org.lightjason.agentspeak.common.CPath.from().
comparing()
final void org.lightjason.agentspeak.common.TestCPath.comparing ()
Definition at line 64 of file TestCPath.java.
References org.lightjason.agentspeak.common.CPath.from().