LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify Class Reference
org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify Class Reference
unify action
Public Member Functions
CDefaultUnify (final boolean p_parallel, @Nonnull final ILiteral p_literal)
ctor
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
final T getValue ()
returns the value of the action
final boolean isValueAssignableTo (final Class<?> p_class)
checkes assinable of the value
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Protected Attributes
final boolean m_parallel
parallel unification
final long m_variablenumber
number of variables
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
final T m_value
data
Static Private Attributes
static final long serialVersionUID = -2858968840990978860L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
IBaseExecution (@Nullable final T p_value)
ctor
Detailed Description
Note
parallel is ignored
Definition at line 48 of file CDefaultUnify.java.
Constructor & Destructor Documentation
CDefaultUnify()
org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.CDefaultUnify (final boolean p_parallel, @Nonnull final ILiteral p_literal)
Parameters
p_parallel parallel execution
p_literal literal
Definition at line 69 of file CDefaultUnify.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.CCommon.variablefrequency().
Member Function Documentation
execute()
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 94 of file CDefaultUnify.java.
References org.lightjason.agentspeak.language.execution.expression.IExpression.EMPTY, and org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value.
toString()
String org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.toString ()
Definition at line 87 of file CDefaultUnify.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value.
variables()
Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 109 of file CDefaultUnify.java.
References org.lightjason.agentspeak.language.CCommon.flattenrecursive(), org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value, and org.lightjason.agentspeak.language.ITerm.term().
Member Data Documentation
m_parallel
final boolean org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.m_parallel protected
Definition at line 57 of file CDefaultUnify.java.
Referenced by org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.execute(), org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.toString(), and org.lightjason.agentspeak.language.execution.action.unify.CVariableUnify.toString().
m_variablenumber
final long org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.m_variablenumber protected
Definition at line 61 of file CDefaultUnify.java.
Referenced by org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.execute(), and org.lightjason.agentspeak.language.execution.action.unify.CVariableUnify.execute().
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.serialVersionUID = -2858968840990978860L static private
Definition at line 53 of file CDefaultUnify.java.