LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T > Class Template Reference
org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T > Class Template Reference
class for a mutex relocated variable
Public Member Functions
CRelocateMutexVariable (final IVariable<?> p_variable)
ctor
CRelocateMutexVariable (@Nonnull final IPath p_functor, @Nonnull final IVariable<?> p_relocate)
ctor
final ITerm deepcopy (final IPath... p_prefix)
final ITerm deepcopysuffix ()
final IVariable<?> relocate ()
sets the value into the relocated variable and returns the modifed variable
final IVariable< T > shallowcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
final IVariable< T > shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Public Member Functions inherited from org.lightjason.agentspeak.language.variable.CMutexVariable< T >
CMutexVariable (final String p_functor)
ctor
CMutexVariable (final String p_functor, final T p_value)
ctor
CMutexVariable (final IPath p_functor)
ctor
CMutexVariable (@Nonnull final IPath p_functor, @Nullable final T p_value)
ctor
final synchronized boolean allocated ()
returns allocated state
final boolean mutex ()
flag to check if variable has is concurrency- / thread-safe
final synchronized< N > N raw ()
cast to any raw value type
final synchronized IVariable< T > set (final T p_value)
IVariable< T > shallowcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
IVariable< T > shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
final synchronized IVariable< T > thrownotallocated () throws IllegalStateException
throws an illegal state exception iif the variable is not allocated
final synchronized IVariable< T > throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
final synchronized String toString ()
final synchronized boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Public Member Functions inherited from org.lightjason.agentspeak.language.variable.CVariable< T >
CVariable (@Nonnull final String p_functor)
ctor
CVariable (@Nonnull final String p_functor, @Nullable final T p_value)
ctor
CVariable (@Nonnull final IPath p_functor)
ctor
CVariable (@Nonnull final IPath p_functor, @Nullable final T p_value)
ctor
boolean allocated ()
returns allocated state
final boolean any ()
flag to define a "any variable"
ITerm deepcopy (final IPath... p_prefix)
ITerm deepcopysuffix ()
final boolean equals (final Object p_object)
final IPath fqnfunctor ()
returns the full-qualified functor with path and name
final String functor ()
returns the functor without path
final IPath functorpath ()
returns the path of the functor
final int hashCode ()
final boolean hasVariable ()
checks if the literal has variables
boolean mutex ()
flag to check if variable has is concurrency- / thread-safe
IVariable< T > set (@Nullable final T p_value)
sets the value
IVariable< T > shallowcopy (final IPath... p_prefix)
IVariable< T > shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
final int structurehash ()
returns a hash value which defines a hash ove rthe structure
IVariable< T > thrownotallocated () throws IllegalStateException
throws an illegal state exception iif the variable is not allocated
IVariable< T > throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
String toString ()
boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Public Member Functions inherited from org.lightjason.agentspeak.language.ITerm
default< T extends ITerm > T term ()
casts the object to a term-type
Public Member Functions inherited from org.lightjason.agentspeak.language.IDeepCopy< ITerm >
T deepcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T deepcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Private Member Functions
CRelocateMutexVariable (@Nonnull final IPath p_functor, @Nonnull final IVariable<?> p_variable, @Nullable final T p_value)
private ctor for creating object-copy
Private Attributes
final IVariable<?> m_relocate
reference to relocated variable
Static Private Attributes
static final long serialVersionUID = 6680660424006072619L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.ITerm
ITerm EMPTY
empty term
long serialVersionUID = -3640918490398129717L
serial id
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Protected Attributes inherited from org.lightjason.agentspeak.language.variable.CVariable< T >
final boolean m_any
boolean flag, that defines an variable which matchs always
final IPath m_functor
variable / functor name
T m_value
value of the variable
Package Functions inherited from org.lightjason.agentspeak.language.variable.CVariable< T >
public< N > N raw ()
cast to any raw value type
Detailed Description
Template Parameters
T variable type
Definition at line 41 of file CRelocateMutexVariable.java.
Constructor & Destructor Documentation
CRelocateMutexVariable() [1/3]
org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.CRelocateMutexVariable (final IVariable<?> p_variable)
Parameters
p_variable variable which should be reloacted
Definition at line 58 of file CRelocateMutexVariable.java.
CRelocateMutexVariable() [2/3]
org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.CRelocateMutexVariable (@Nonnull final IPath p_functor, @Nonnull final IVariable<?> p_relocate)
Parameters
p_functor variable name
p_relocate variable which should be relocated
Definition at line 69 of file CRelocateMutexVariable.java.
CRelocateMutexVariable() [3/3]
org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.CRelocateMutexVariable (@Nonnull final IPath p_functor, @Nonnull final IVariable<?> p_variable, @Nullable final T p_value) private
Parameters
p_functor functor
p_variable referenced variable
p_value value
Definition at line 82 of file CRelocateMutexVariable.java.
Member Function Documentation
deepcopy()
final ITerm org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopy (final IPath... p_prefix)
Definition at line 116 of file CRelocateMutexVariable.java.
References org.lightjason.agentspeak.common.IPath.append(), org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.m_relocate, and org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
deepcopysuffix()
final ITerm org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopysuffix ()
Definition at line 109 of file CRelocateMutexVariable.java.
References org.lightjason.agentspeak.common.CPath.from(), org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, org.lightjason.agentspeak.language.variable.CVariable< T >.m_value, and org.lightjason.agentspeak.common.IPath.suffix().
relocate()
final IVariable<?> org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.relocate ()
Returns
relocated variable
Implements org.lightjason.agentspeak.language.variable.IRelocateVariable.
Definition at line 90 of file CRelocateMutexVariable.java.
References org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.m_relocate, org.lightjason.agentspeak.language.variable.CMutexVariable< T >.raw(), and org.lightjason.agentspeak.language.variable.IVariable< T >.set().
shallowcopy()
final IVariable<T> org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.shallowcopy (@Nullable final IPath... p_prefix)
Parameters
p_prefix add a path (only one path element is supported) to the functor or returns a shallow-copy
Returns
new instance of the object
Implements org.lightjason.agentspeak.language.IShallowCopy< T >.
Definition at line 100 of file CRelocateMutexVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.m_relocate, and org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
shallowcopysuffix()
final IVariable<T> org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.shallowcopysuffix ()
Returns
new instance of the object
Implements org.lightjason.agentspeak.language.IShallowCopy< T >.
Definition at line 129 of file CRelocateMutexVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, and org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.m_relocate.
Member Data Documentation
m_relocate
final IVariable<?> org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.m_relocate private
Definition at line 50 of file CRelocateMutexVariable.java.
Referenced by org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopy(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.relocate(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.shallowcopy(), and org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.shallowcopysuffix().
serialVersionUID
final long org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.serialVersionUID = 6680660424006072619L static private
Definition at line 46 of file CRelocateMutexVariable.java.