LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionGraph Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionGraph Class Reference
test graph actions
Public Member Functions
final void addedgemultiple ()
test add-edge multiple
final void addedgesingle ()
test add-edge single
final void addvertexmultiple ()
test add-vertex multiple
final void addvertexsingle ()
test add-vertex single
final void adjacencymatrix ()
test adjacency matrix
final void containsedge ()
test contains-edge
final void containsvertex ()
test contains-vertex
final void create ()
test graph creating
final void degreemultiple ()
test degree multiple
final void degreesingle ()
test degree single
final void distancepath ()
test distance-path
final void edgecount ()
test edge-count
final void edgelistmultiple ()
test edgelist multiple
final void edgelistsingle ()
test edgelist single
final void edges ()
test edges
final void endpointmultiple ()
test endpoint multiple
final void endpointsingle ()
test endpoint single
final void findedgemultiple ()
test find-edge multiple
final void findedgesingle ()
test find-edge single
final void incidentcountmultiple ()
test incident-count single
final void incidentcountsingle ()
test incident-count single
final void incidentverticesmultiple ()
test incident-vertices multiple
final void incidentverticessingle ()
test incident-vertices single
final void indegreemultiple ()
test in-degree multiple
final void indegreesingle ()
test in-degree single
final void inedgesmultiple ()
test in-edge
final void inedgessingle ()
test in-edge
final void isincidentmultiple ()
test is-incident multiple
final void isincidentsingle ()
test is-incident single
final void isneighbormultiple ()
test is-neighbor multiple
final void isneighborsingle ()
test is-neighbor single
final void ispredecessormultiple ()
test is-predecessor multiple
final void ispredecessorsingle ()
test is-predecessor single
final void issuccesormultiple ()
test is-successor multiple
final void issuccessorsingle ()
test is-successor single
final void neigborsmultiple ()
test neigbors multiple
final void neigborssingle ()
test neigbors single
final void neighborscountmultiple ()
test neighborscount single
final void neighborscountsingle ()
test neighborscount single
final void oppositemultiple ()
test opposite multiple
final void oppositesingle ()
test opposite single
final void outdegreemultiple ()
test out-degree single
final void outdegreesingle ()
test out-degree single
final void outedgemultiple ()
test outedges multiple
final void outedgessingle ()
test outedges single
final void predecessorcountmultiple ()
test predecessor count multiple
final void predecessorcountsingle ()
test predecessor count single
final void removeedgemultiple ()
test remove edge multiple
final void removeedgesingle ()
test remove edge single
final void shortestpath ()
test shortest-path
final void spanningtree ()
test spanning-tree action
final void successorcountmultiple ()
test successor count multiple
final void successorcountsingle ()
test successor count single
final void vertexcount ()
test vertex-count
final void vertexremovemultiple ()
test remove vertex multiple
final void vertextremovesingle ()
test remove vertex single
final void vertices ()
test vertices
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 111 of file TestCActionGraph.java.
Member Function Documentation
addedgemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.addedgemultiple ()
Definition at line 209 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
addedgesingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.addedgesingle ()
Definition at line 181 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
addvertexmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.addvertexmultiple ()
Definition at line 162 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
addvertexsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.addvertexsingle ()
Definition at line 139 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
adjacencymatrix()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.adjacencymatrix ()
Definition at line 327 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.CAdjacencyMatrix.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
containsedge()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.containsedge ()
Definition at line 365 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.CContainsEdge.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
containsvertex()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.containsvertex ()
Definition at line 395 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.CContainsVertex.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.create ()
Definition at line 118 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
degreemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.degreemultiple ()
Definition at line 425 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
degreesingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.degreesingle ()
Definition at line 460 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
distancepath()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.distancepath ()
Definition at line 488 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyPathAlgorithm.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
edgecount()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.edgecount ()
Definition at line 252 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.CEdgeCount.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
edgelistmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.edgelistmultiple ()
Definition at line 721 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
edgelistsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.edgelistsingle ()
Definition at line 678 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
edges()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.edges ()
Definition at line 302 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.CEdges.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
endpointmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.endpointmultiple ()
Definition at line 787 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
endpointsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.endpointsingle ()
Definition at line 763 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
findedgemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.findedgemultiple ()
Definition at line 653 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
findedgesingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.findedgesingle ()
Definition at line 629 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
incidentcountmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentcountmultiple ()
Definition at line 1015 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
incidentcountsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentcountsingle ()
Definition at line 991 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
incidentverticesmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentverticesmultiple ()
Definition at line 1078 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
incidentverticessingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentverticessingle ()
Definition at line 1038 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
indegreemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.indegreemultiple ()
Definition at line 838 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
indegreesingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.indegreesingle ()
Definition at line 811 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
inedgesmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.inedgesmultiple ()
Definition at line 902 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
inedgessingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.inedgessingle ()
Definition at line 861 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
isincidentmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.isincidentmultiple ()
Definition at line 1446 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
isincidentsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.isincidentsingle ()
Definition at line 1417 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
isneighbormultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.isneighbormultiple ()
Definition at line 1304 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
isneighborsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.isneighborsingle ()
Definition at line 1275 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
ispredecessormultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.ispredecessormultiple ()
Definition at line 1194 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
ispredecessorsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.ispredecessorsingle ()
Definition at line 1169 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
issuccesormultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.issuccesormultiple ()
Definition at line 1144 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
issuccessorsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.issuccessorsingle ()
Definition at line 1119 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
neigborsmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.neigborsmultiple ()
Definition at line 1375 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
neigborssingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.neigborssingle ()
Definition at line 1332 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
neighborscountmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.neighborscountmultiple ()
Definition at line 1248 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
neighborscountsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.neighborscountsingle ()
Definition at line 1219 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
oppositemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.oppositemultiple ()
Definition at line 1497 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
oppositesingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.oppositesingle ()
Definition at line 1473 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
outdegreemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.outdegreemultiple ()
Definition at line 967 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
outdegreesingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.outdegreesingle ()
Definition at line 942 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
outedgemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.outedgemultiple ()
Definition at line 1562 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
outedgessingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.outedgessingle ()
Definition at line 1520 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
predecessorcountmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.predecessorcountmultiple ()
Definition at line 1629 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
predecessorcountsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.predecessorcountsingle ()
Definition at line 1603 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
removeedgemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.removeedgemultiple ()
Definition at line 1787 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
removeedgesingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.removeedgesingle ()
Definition at line 1760 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
shortestpath()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.shortestpath ()
Definition at line 512 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyPathAlgorithm.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
spanningtree()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.spanningtree ()
Definition at line 536 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.CSpanningTree.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
successorcountmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.successorcountmultiple ()
Definition at line 1736 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
successorcountsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.successorcountsingle ()
Definition at line 1708 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
vertexcount()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.vertexcount ()
Definition at line 228 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.CVertexCount.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
vertexremovemultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.vertexremovemultiple ()
Definition at line 1654 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
vertextremovesingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.vertextremovesingle ()
Definition at line 1678 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
vertices()
final void org.lightjason.agentspeak.action.builtin.TestCActionGraph.vertices ()
Definition at line 278 of file TestCActionGraph.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.graph.CVertices.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().