LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.CBeliefbase Class Reference
org.lightjason.agentspeak.beliefbase.CBeliefbase Class Reference
beliefbase to generate any event-based data by reference counting
Public Member Functions
CBeliefbase (@Nonnull final IStorage< ILiteral, IView > p_storage)
ctor
final ILiteral add (@Nonnull final ILiteral p_literal)
adds a literal
final IView add (@Nonnull final IView p_view)
adds a view
final IBeliefbase clear ()
clears all elements
final boolean containsLiteral (@Nonnull final String p_key)
contains a multi-element
final boolean containsView (@Nonnull final String p_key)
contains a single-element
final boolean empty ()
checks if the structure empty
final boolean equals (final Object p_object)
final int hashCode ()
final Collection< ILiteral > literal (@Nonnull final String p_key)
returns a literal by the name
final IView remove (@Nonnull final IView p_view)
removes a view
final ILiteral remove (@Nonnull final ILiteral p_literal)
removes a literal
final int size ()
returns the size of literals
final Stream< ILiteral > streamLiteral ()
returns a stream over all literals
final Stream< IView > streamView ()
returns a stream over all views
final String toString ()
final Stream< ITrigger > trigger (@Nonnull final IView p_view)
returns all trigger of the beliefbase
final IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
final IView view (@Nonnull final String p_key)
returns a view element
final IView viewOrDefault (@Nonnull final String p_key, @Nullable final IView p_default)
returns a view element
Public Member Functions inherited from org.lightjason.agentspeak.beliefbase.IBaseBeliefbase
ILiteral add (@Nonnull final ILiteral p_literal)
adds a literal
final IView create (@Nonnull final String p_name)
returns a new view of the belief base
final IView create (@Nonnull final String p_name, final IView p_parent)
ILiteral remove (@Nonnull final ILiteral p_literal)
removes a literal
Stream< ITrigger > trigger (@Nonnull final IView p_view)
returns all trigger of the beliefbase
IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
Public Member Functions inherited from org.lightjason.agentspeak.beliefbase.IBeliefbase
IView create (@Nonnull final String p_name, @Nullable final IView p_parent)
returns a new view of the belief base
Private Attributes
final IStorage< ILiteral, IView > m_storage
storage with data
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.beliefbase.IBeliefbase
IBeliefbase EMPY
empty beliefbase
Protected Member Functions inherited from org.lightjason.agentspeak.beliefbase.IBaseBeliefbase
final Stream< ITrigger > cleartrigger (final IView p_view)
copy of all trigger values
ILiteral event (final ITrigger.EType p_event, final ILiteral p_literal)
push an event and literal to the event map
IView eventreference (final IView p_view)
adds a view to the event referencing structure
final IView internalremove (final IView p_view)
removes the interal view references
Detailed Description
Definition at line 41 of file CBeliefbase.java.
Constructor & Destructor Documentation
CBeliefbase()
org.lightjason.agentspeak.beliefbase.CBeliefbase.CBeliefbase (@Nonnull final IStorage< ILiteral, IView > p_storage)
Parameters
p_storage storage
Definition at line 53 of file CBeliefbase.java.
Member Function Documentation
add() [1/2]
final ILiteral org.lightjason.agentspeak.beliefbase.CBeliefbase.add (@Nonnull final ILiteral p_literal)
Parameters
p_literal literal without path
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 72 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.putMultiElement().
add() [2/2]
final IView org.lightjason.agentspeak.beliefbase.CBeliefbase.add (@Nonnull final IView p_view)
Parameters
p_view view
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 81 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.putSingleElement().
clear()
final IBeliefbase org.lightjason.agentspeak.beliefbase.CBeliefbase.clear ()
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 148 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.clear(), org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEBELIEF, org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.event(), org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamMultiElements(), and org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamSingleElements().
containsLiteral()
final boolean org.lightjason.agentspeak.beliefbase.CBeliefbase.containsLiteral (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 105 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.containsMultiElement().
containsView()
final boolean org.lightjason.agentspeak.beliefbase.CBeliefbase.containsView (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 111 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.containsSingleElement().
empty()
final boolean org.lightjason.agentspeak.beliefbase.CBeliefbase.empty ()
Returns
empty boolean
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 163 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.empty().
equals()
final boolean org.lightjason.agentspeak.beliefbase.CBeliefbase.equals (final Object p_object)
Definition at line 65 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.CBeliefbase.hashCode().
hashCode()
final int org.lightjason.agentspeak.beliefbase.CBeliefbase.hashCode ()
Definition at line 59 of file CBeliefbase.java.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.equals().
literal()
final Collection<ILiteral> org.lightjason.agentspeak.beliefbase.CBeliefbase.literal (@Nonnull final String p_key)
Parameters
p_key name of the literal
Returns
collection of pairs with negated and literal
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 132 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.getMultiElement().
remove() [1/2]
final IView org.lightjason.agentspeak.beliefbase.CBeliefbase.remove (@Nonnull final IView p_view)
Parameters
p_view view
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 89 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.internalremove(), and org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.removeSingleElement().
remove() [2/2]
final ILiteral org.lightjason.agentspeak.beliefbase.CBeliefbase.remove (@Nonnull final ILiteral p_literal)
Parameters
p_literal without path
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 97 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.removeMultiElement().
size()
final int org.lightjason.agentspeak.beliefbase.CBeliefbase.size ()
Returns
size
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 169 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.IStructure.size(), org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.size(), and org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamSingleElements().
streamLiteral()
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.CBeliefbase.streamLiteral ()
Returns
literal stream
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 186 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamMultiElements().
streamView()
final Stream<IView> org.lightjason.agentspeak.beliefbase.CBeliefbase.streamView ()
Returns
view stream
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 193 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamSingleElements().
toString()
final String org.lightjason.agentspeak.beliefbase.CBeliefbase.toString ()
Definition at line 199 of file CBeliefbase.java.
trigger()
final Stream<ITrigger> org.lightjason.agentspeak.beliefbase.CBeliefbase.trigger (@Nonnull final IView p_view)
Parameters
p_view mask for events
Returns
set with trigger events
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 176 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamSingleElements(), and org.lightjason.agentspeak.beliefbase.view.IView.trigger().
update()
final IAgent<?> org.lightjason.agentspeak.beliefbase.CBeliefbase.update (@Nonnull final IAgent<?> p_agent)
Parameters
p_agent agent which runs the update call
Returns
agent
Warning
call update on a storage and on all storage-view, if exists different views which are point to the same storage, the update is called more than once, so the storage must limit the number of update calls
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 139 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamSingleElements(), and org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.update().
view()
final IView org.lightjason.agentspeak.beliefbase.CBeliefbase.view (@Nonnull final String p_key)
Parameters
p_key name of the view
Returns
view or null
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 118 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.getSingleElement().
viewOrDefault()
final IView org.lightjason.agentspeak.beliefbase.CBeliefbase.viewOrDefault (@Nonnull final String p_key, @Nullable final IView p_default)
Parameters
p_key name of the view
p_default view
Returns
view or default element
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 125 of file CBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.getSingleElementOrDefault().
Member Data Documentation
m_storage
final IStorage<ILiteral, IView> org.lightjason.agentspeak.beliefbase.CBeliefbase.m_storage private
Definition at line 46 of file CBeliefbase.java.