LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.variable.CMutexVariable< T > Class Template Reference
org.lightjason.agentspeak.language.variable.CMutexVariable< T > Class Template Reference
thread-safe variable
Public Member Functions
CMutexVariable (final String p_functor)
ctor
CMutexVariable (final String p_functor, final T p_value)
ctor
CMutexVariable (final IPath p_functor)
ctor
CMutexVariable (@Nonnull final IPath p_functor, @Nullable final T p_value)
ctor
final synchronized boolean allocated ()
returns allocated state
final boolean mutex ()
flag to check if variable has is concurrency- / thread-safe
final synchronized< N > N raw ()
cast to any raw value type
final synchronized IVariable< T > set (final T p_value)
IVariable< T > shallowcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
IVariable< T > shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
final synchronized IVariable< T > thrownotallocated () throws IllegalStateException
throws an illegal state exception iif the variable is not allocated
final synchronized IVariable< T > throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
final synchronized String toString ()
final synchronized boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Public Member Functions inherited from org.lightjason.agentspeak.language.variable.CVariable< T >
CVariable (@Nonnull final String p_functor)
ctor
CVariable (@Nonnull final String p_functor, @Nullable final T p_value)
ctor
CVariable (@Nonnull final IPath p_functor)
ctor
CVariable (@Nonnull final IPath p_functor, @Nullable final T p_value)
ctor
boolean allocated ()
returns allocated state
final boolean any ()
flag to define a "any variable"
ITerm deepcopy (final IPath... p_prefix)
ITerm deepcopysuffix ()
final boolean equals (final Object p_object)
final IPath fqnfunctor ()
returns the full-qualified functor with path and name
final String functor ()
returns the functor without path
final IPath functorpath ()
returns the path of the functor
final int hashCode ()
final boolean hasVariable ()
checks if the literal has variables
boolean mutex ()
flag to check if variable has is concurrency- / thread-safe
IVariable< T > set (@Nullable final T p_value)
sets the value
IVariable< T > shallowcopy (final IPath... p_prefix)
IVariable< T > shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
final int structurehash ()
returns a hash value which defines a hash ove rthe structure
IVariable< T > thrownotallocated () throws IllegalStateException
throws an illegal state exception iif the variable is not allocated
IVariable< T > throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
String toString ()
boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Public Member Functions inherited from org.lightjason.agentspeak.language.ITerm
default< T extends ITerm > T term ()
casts the object to a term-type
Public Member Functions inherited from org.lightjason.agentspeak.language.IDeepCopy< ITerm >
T deepcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T deepcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Static Private Attributes
static final long serialVersionUID = 9040218112516254186L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.ITerm
ITerm EMPTY
empty term
long serialVersionUID = -3640918490398129717L
serial id
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Protected Attributes inherited from org.lightjason.agentspeak.language.variable.CVariable< T >
final boolean m_any
boolean flag, that defines an variable which matchs always
final IPath m_functor
variable / functor name
T m_value
value of the variable
Package Functions inherited from org.lightjason.agentspeak.language.variable.CVariable< T >
public< N > N raw ()
cast to any raw value type
Detailed Description
Template Parameters
T data type
Definition at line 38 of file CMutexVariable.java.
Constructor & Destructor Documentation
CMutexVariable() [1/4]
org.lightjason.agentspeak.language.variable.CMutexVariable< T >.CMutexVariable (final String p_functor)
Parameters
p_functor name
Definition at line 50 of file CMutexVariable.java.
CMutexVariable() [2/4]
org.lightjason.agentspeak.language.variable.CMutexVariable< T >.CMutexVariable (final String p_functor, final T p_value)
Parameters
p_functor name
p_value value
Definition at line 61 of file CMutexVariable.java.
CMutexVariable() [3/4]
org.lightjason.agentspeak.language.variable.CMutexVariable< T >.CMutexVariable (final IPath p_functor)
Parameters
p_functor name
Definition at line 71 of file CMutexVariable.java.
CMutexVariable() [4/4]
org.lightjason.agentspeak.language.variable.CMutexVariable< T >.CMutexVariable (@Nonnull final IPath p_functor, @Nullable final T p_value)
Parameters
p_functor name
p_value value
Definition at line 82 of file CMutexVariable.java.
Member Function Documentation
allocated()
final synchronized boolean org.lightjason.agentspeak.language.variable.CMutexVariable< T >.allocated ()
Returns
boolean flag
Implements org.lightjason.agentspeak.language.IRawStructure< T >.
Definition at line 115 of file CMutexVariable.java.
mutex()
final boolean org.lightjason.agentspeak.language.variable.CMutexVariable< T >.mutex ()
Returns
mutex flag
Implements org.lightjason.agentspeak.language.variable.IVariable< T >.
Definition at line 149 of file CMutexVariable.java.
raw()
final synchronized<N> N org.lightjason.agentspeak.language.variable.CMutexVariable< T >.raw ()
Template Parameters
raw type
Returns
any type
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 95 of file CMutexVariable.java.
Referenced by org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.relocate().
set()
final synchronized IVariable<T> org.lightjason.agentspeak.language.variable.CMutexVariable< T >.set (final T p_value)
Definition at line 89 of file CMutexVariable.java.
References org.lightjason.agentspeak.language.variable.IVariable< T >.set().
shallowcopy()
IVariable<T> org.lightjason.agentspeak.language.variable.CMutexVariable< T >.shallowcopy (@Nullable final IPath... p_prefix)
Parameters
p_prefix add a path (only one path element is supported) to the functor or returns a shallow-copy
Returns
new instance of the object
Implements org.lightjason.agentspeak.language.IShallowCopy< T >.
Definition at line 134 of file CMutexVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, and org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
shallowcopysuffix()
IVariable<T> org.lightjason.agentspeak.language.variable.CMutexVariable< T >.shallowcopysuffix ()
Returns
new instance of the object
Implements org.lightjason.agentspeak.language.IShallowCopy< T >.
Definition at line 143 of file CMutexVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, org.lightjason.agentspeak.language.variable.CVariable< T >.m_value, and org.lightjason.agentspeak.common.IPath.suffix().
thrownotallocated()
final synchronized IVariable<T> org.lightjason.agentspeak.language.variable.CMutexVariable< T >.thrownotallocated () throws IllegalStateException
Returns
object itself
Exceptions
IllegalStateException on non-allocated
Implements org.lightjason.agentspeak.language.IRawStructure< T >.
Definition at line 102 of file CMutexVariable.java.
throwvaluenotassignableto()
final synchronized IVariable<T> org.lightjason.agentspeak.language.variable.CMutexVariable< T >.throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
Parameters
p_class assignable class
Returns
object itself
Exceptions
IllegalArgumentException on assignable error
Implements org.lightjason.agentspeak.language.IAssignable< T >.
Definition at line 109 of file CMutexVariable.java.
toString()
final synchronized String org.lightjason.agentspeak.language.variable.CMutexVariable< T >.toString ()
Definition at line 127 of file CMutexVariable.java.
valueassignableto()
final synchronized boolean org.lightjason.agentspeak.language.variable.CMutexVariable< T >.valueassignableto (@Nonnull final Class<?>... p_class)
Parameters
p_class class
Returns
assignable (on null always true)
Implements org.lightjason.agentspeak.language.IAssignable< T >.
Definition at line 121 of file CMutexVariable.java.
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.language.variable.CMutexVariable< T >.serialVersionUID = 9040218112516254186L static private
Definition at line 43 of file CMutexVariable.java.