LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction Enum Reference
org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction Enum Reference
belief action definition
Public Member Functions
EAction (@Nonnull final String p_name)
ctor
final String toString ()
Public Attributes
ADD =("+")
DELETE =("-")
Private Attributes
final String m_name
name
Detailed Description
Definition at line 95 of file CBeliefAction.java.
Constructor & Destructor Documentation
EAction()
org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.EAction (@Nonnull final String p_name)
Parameters
p_name string represenation
Definition at line 109 of file CBeliefAction.java.
Member Function Documentation
toString()
final String org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.toString ()
Definition at line 115 of file CBeliefAction.java.
Member Data Documentation
ADD
org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.ADD =("+")
Definition at line 97 of file CBeliefAction.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBelief_action(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBelief_action().
DELETE
org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.DELETE =("-")
Definition at line 98 of file CBeliefAction.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBelief_action(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBelief_action().
m_name
final String org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.m_name private
Definition at line 102 of file CBeliefAction.java.