LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expression.IBaseUnary Class Reference
org.lightjason.agentspeak.language.execution.expression.IBaseUnary Class Reference abstract
base unary expression
Public Member Functions
final boolean equals (final Object p_object)
final IExpression expression ()
returns the expression
final int hashCode ()
final EOperator operator ()
return expression operator
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.IExecution
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Protected Member Functions
IBaseUnary (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_expression)
ctor
Protected Attributes
final IExpression m_expression
left-hand-side argument
final EOperator m_operator
expression operator
Static Private Attributes
static final long serialVersionUID = -8992581726613099958L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.execution.expression.IExpression
IExpression EMPTY
empty expression, is always true
Detailed Description
Definition at line 38 of file IBaseUnary.java.
Constructor & Destructor Documentation
IBaseUnary()
org.lightjason.agentspeak.language.execution.expression.IBaseUnary.IBaseUnary (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_expression) protected
Parameters
p_operator operator
p_expression expression
Definition at line 60 of file IBaseUnary.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.expression.IBaseUnary.equals (final Object p_object)
Definition at line 90 of file IBaseUnary.java.
References org.lightjason.agentspeak.language.execution.expression.IBaseUnary.hashCode().
expression()
final IExpression org.lightjason.agentspeak.language.execution.expression.IBaseUnary.expression ()
Returns
expression
Implements org.lightjason.agentspeak.language.execution.expression.IUnaryExpression.
Definition at line 71 of file IBaseUnary.java.
References org.lightjason.agentspeak.language.execution.expression.IBaseUnary.m_expression.
hashCode()
final int org.lightjason.agentspeak.language.execution.expression.IBaseUnary.hashCode ()
Definition at line 84 of file IBaseUnary.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.IBaseUnary.equals().
operator()
final EOperator org.lightjason.agentspeak.language.execution.expression.IBaseUnary.operator ()
Returns
operator
Implements org.lightjason.agentspeak.language.execution.expression.IUnaryExpression.
Definition at line 78 of file IBaseUnary.java.
References org.lightjason.agentspeak.language.execution.expression.IBaseUnary.m_operator.
toString()
final String org.lightjason.agentspeak.language.execution.expression.IBaseUnary.toString ()
Definition at line 96 of file IBaseUnary.java.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.expression.IBaseUnary.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 103 of file IBaseUnary.java.
References org.lightjason.agentspeak.language.execution.IExecution.variables().
Member Data Documentation
m_expression
final IExpression org.lightjason.agentspeak.language.execution.expression.IBaseUnary.m_expression protected
Definition at line 51 of file IBaseUnary.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.logical.CUnary.execute(), and org.lightjason.agentspeak.language.execution.expression.IBaseUnary.expression().
m_operator
final EOperator org.lightjason.agentspeak.language.execution.expression.IBaseUnary.m_operator protected
Definition at line 47 of file IBaseUnary.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.logical.CUnary.CUnary(), org.lightjason.agentspeak.language.execution.expression.logical.CUnary.execute(), and org.lightjason.agentspeak.language.execution.expression.IBaseUnary.operator().
serialVersionUID
final long org.lightjason.agentspeak.language.execution.expression.IBaseUnary.serialVersionUID = -8992581726613099958L static private
Definition at line 43 of file IBaseUnary.java.