LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase Class Reference
org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase Class Reference
test agent with beliebase properties
Classes
class CAgent
agent class
Public Member Functions
final void belieflist () throws Exception
test beliefs exists
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 45 of file TestCPropertyBeliefbase.java.
Member Function Documentation
belieflist()
final void org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.belieflist () throws Exception
Exceptions
Exception is thrown on intialization error
Definition at line 54 of file TestCPropertyBeliefbase.java.
References org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.beliefbase(), org.lightjason.agentspeak.language.CRawTerm< T >.EMPTY, org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.CAgent.CAgentGenerator.generatesingle(), org.lightjason.agentspeak.IBaseTest.PRINTENABLE, and org.lightjason.agentspeak.beliefbase.view.IView.stream().