LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix Class Reference
test math bit matrix functions
Public Member Functions
final void action (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
test all input actions
final void boolValue ()
test boolean value
final void column ()
test column
final void create ()
test create
final void initialize ()
initialize
final void numericvalue ()
test numericvalue
final void row ()
test row
final void tobitvector ()
test toBitVector
final void toblas ()
test toblas
Static Public Member Functions
static Object [] generator ()
data provider generator
Static Private Member Functions
static Stream< Object > testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult)
method to generate test-cases
Static Private Attributes
static final BitMatrix MATRIX1 = new BitMatrix(2, 2)
testing matrix
static final BitMatrix MATRIX2 = new BitMatrix(2, 2)
testing matrix
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 78 of file TestCActionMathBitMatrix.java.
Member Function Documentation
action()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.action (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
Parameters
p_input tripel with input, actions classes and results
Exceptions
IllegalAccessException is thrwon on instantiation error
InstantiationException is thrwon on instantiation error
NoSuchMethodException is thrwon on instantiation error
InvocationTargetException is thrwon on instantiation error
Definition at line 186 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.ITerm.raw().
boolValue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.boolValue ()
Definition at line 321 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CBoolValue.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
column()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.column ()
Definition at line 256 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.IRowColumn.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.create ()
Definition at line 209 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
generator()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.generator () static
Returns
data
Definition at line 114 of file TestCActionMathBitMatrix.java.
initialize()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.initialize ()
Definition at line 96 of file TestCActionMathBitMatrix.java.
numericvalue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.numericvalue ()
Definition at line 304 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CNumericValue.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
row()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.row ()
Definition at line 280 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.IRowColumn.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
testcase()
static Stream<Object> org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult) static private
Parameters
p_input input data
p_classes matching test-classes / test-cases
p_classresult result for each class
Returns
test-object
Definition at line 163 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
tobitvector()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.tobitvector ()
Definition at line 230 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToVector.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
toblas()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.toblas ()
Definition at line 338 of file TestCActionMathBitMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToBlas.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
Member Data Documentation
MATRIX1
final BitMatrix org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.MATRIX1 = new BitMatrix(2, 2) static private
Note
static because of usage in data-provider and test-initialize
Definition at line 84 of file TestCActionMathBitMatrix.java.
MATRIX2
final BitMatrix org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.MATRIX2 = new BitMatrix(2, 2) static private
Note
static because of usage in data-provider and test-initialize
Definition at line 89 of file TestCActionMathBitMatrix.java.