LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionBool Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionBool Class Reference
test for boolean actions
Public Member Functions
final void equal ()
test equal
final void execute (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
generic test-case
final void notequal ()
test not-equal
Static Public Member Functions
static Object [] generate ()
data provider generator
Static Private Member Functions
static Stream< Object > testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult)
method to generate test-cases
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 66 of file TestCActionBool.java.
Member Function Documentation
equal()
final void org.lightjason.agentspeak.action.builtin.TestCActionBool.equal ()
Definition at line 195 of file TestCActionBool.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.bool.CEqual.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
execute()
final void org.lightjason.agentspeak.action.builtin.TestCActionBool.execute (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
Parameters
p_input test-case data
Exceptions
IllegalAccessException is thrwon on instantiation error
InstantiationException is thrwon on instantiation error
NoSuchMethodException is thrwon on instantiation error
InvocationTargetException is thrwon on instantiation error
Definition at line 174 of file TestCActionBool.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.ITerm.raw().
generate()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionBool.generate () static
Returns
data
Definition at line 74 of file TestCActionBool.java.
notequal()
final void org.lightjason.agentspeak.action.builtin.TestCActionBool.notequal ()
Definition at line 242 of file TestCActionBool.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.bool.CEqual.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
testcase()
static Stream<Object> org.lightjason.agentspeak.action.builtin.TestCActionBool.testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult) static private
Parameters
p_input input data
p_classes matching test-classes / test-cases
p_classresult result for each class
Returns
test-object
Definition at line 152 of file TestCActionBool.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().