LightJason - AgentSpeak(L++): org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak Interface Reference
org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak Interface Reference
interface of visitor structure
Public Member Functions
Set< ILiteral > initialbeliefs ()
returns initial beliefs
Set< IPlan > plans ()
get a multimap with event-plan matching
Set< IRule > rules ()
returns the rules / principles
Detailed Description
Definition at line 37 of file IASTVisitorAgentSpeak.java.
Member Function Documentation
initialbeliefs()
Set<ILiteral> org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.initialbeliefs ()
Returns
set with initial beliefs
Implemented in org.lightjason.agentspeak.grammar.CASTVisitorAgent, and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.
Referenced by org.lightjason.agentspeak.generator.IBaseAgentGenerator< IAgent<?> >.IBaseAgentGenerator(), and org.lightjason.agentspeak.generator.IBasePlanBundleGenerator.IBasePlanBundleGenerator().
plans()
Set<IPlan> org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.plans ()
Returns
plan set
Implemented in org.lightjason.agentspeak.grammar.CASTVisitorAgent, and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.
Referenced by org.lightjason.agentspeak.generator.IBaseAgentGenerator< IAgent<?> >.IBaseAgentGenerator(), and org.lightjason.agentspeak.generator.IBasePlanBundleGenerator.IBasePlanBundleGenerator().
rules()
Set<IRule> org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.rules ()
Returns
rule set
Implemented in org.lightjason.agentspeak.grammar.CASTVisitorAgent, and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.
Referenced by org.lightjason.agentspeak.generator.IBaseAgentGenerator< IAgent<?> >.IBaseAgentGenerator(), and org.lightjason.agentspeak.generator.IBasePlanBundleGenerator.IBasePlanBundleGenerator().