LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.TestCTermVariablesConstant Class Reference
org.lightjason.agentspeak.language.TestCTermVariablesConstant Class Reference
test for language components
Public Member Functions
final void constant ()
test constant structure
final void constantaccess ()
test constant access structure
final void constantcopy ()
test constant copy
final void literal ()
test literal structure
final void rawterm ()
test raw-term structure
final void relocatevariablemutex ()
test realocated variable
final void relocatevariablerelocate ()
test realocated variable
final void variable ()
checks the variable structure
final void variableany ()
check any variable
final void variablecopy ()
test variable shallow-copy
final void variableequals ()
variable equals
final void variablefunctor ()
test variable functor
final void variablemutex ()
check the mutex variable
final void variabletostring ()
test tostring
final void variablevalueassignable ()
test exception on value asiable
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 44 of file TestCTermVariablesConstant.java.
Member Function Documentation
constant()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.constant ()
Definition at line 114 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.ITerm.functor(), org.lightjason.agentspeak.language.ITerm.hasVariable(), and org.lightjason.agentspeak.language.ITerm.raw().
constantaccess()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.constantaccess ()
Definition at line 104 of file TestCTermVariablesConstant.java.
constantcopy()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.constantcopy ()
Definition at line 130 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.common.CPath.from(), and org.lightjason.agentspeak.language.variable.CVariable< T >.toString().
literal()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.literal ()
Definition at line 51 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.ILiteral.emptyValues(), org.lightjason.agentspeak.language.ITerm.fqnfunctor(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.common.CPath.from(), org.lightjason.agentspeak.language.ITerm.functor(), org.lightjason.agentspeak.language.ILiteral.hasAt(), and org.lightjason.agentspeak.language.ILiteral.values().
rawterm()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.rawterm ()
Definition at line 83 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
relocatevariablemutex()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex ()
Definition at line 324 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.IRawStructure< T >.allocated(), org.lightjason.agentspeak.language.variable.CVariable< T >.allocated(), org.lightjason.agentspeak.language.ITerm.functor(), org.lightjason.agentspeak.language.variable.CVariable< T >.functor(), org.lightjason.agentspeak.language.ITerm.hasVariable(), org.lightjason.agentspeak.language.variable.CVariable< T >.hasVariable(), org.lightjason.agentspeak.language.variable.CVariable< T >.mutex(), org.lightjason.agentspeak.language.ITerm.raw(), org.lightjason.agentspeak.language.variable.CVariable< T >.raw(), and org.lightjason.agentspeak.language.variable.CVariable< T >.set().
relocatevariablerelocate()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate ()
Definition at line 292 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.IRawStructure< T >.allocated(), org.lightjason.agentspeak.language.variable.CVariable< T >.allocated(), org.lightjason.agentspeak.language.ITerm.functor(), org.lightjason.agentspeak.language.variable.CVariable< T >.functor(), org.lightjason.agentspeak.language.ITerm.hasVariable(), org.lightjason.agentspeak.language.variable.CVariable< T >.hasVariable(), org.lightjason.agentspeak.language.variable.CVariable< T >.mutex(), org.lightjason.agentspeak.language.ITerm.raw(), org.lightjason.agentspeak.language.variable.CVariable< T >.raw(), and org.lightjason.agentspeak.language.variable.CVariable< T >.set().
variable()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.variable ()
Definition at line 199 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.IRawStructure< T >.allocated(), org.lightjason.agentspeak.language.ITerm.functor(), org.lightjason.agentspeak.language.ITerm.hasVariable(), org.lightjason.agentspeak.language.variable.IVariable< T >.mutex(), org.lightjason.agentspeak.language.ITerm.raw(), and org.lightjason.agentspeak.language.variable.IVariable< T >.set().
variableany()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.variableany ()
Definition at line 147 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.variable.IVariable< T >.any().
variablecopy()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablecopy ()
Definition at line 270 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.ITerm.fqnfunctor(), and org.lightjason.agentspeak.common.CPath.from().
variableequals()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.variableequals ()
Definition at line 171 of file TestCTermVariablesConstant.java.
variablefunctor()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablefunctor ()
Definition at line 230 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.common.CPath.from().
variablemutex()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablemutex ()
Definition at line 242 of file TestCTermVariablesConstant.java.
References org.lightjason.agentspeak.language.IRawStructure< T >.allocated(), org.lightjason.agentspeak.language.ITerm.functor(), org.lightjason.agentspeak.language.ITerm.hasVariable(), org.lightjason.agentspeak.language.variable.IVariable< T >.mutex(), org.lightjason.agentspeak.language.ITerm.raw(), and org.lightjason.agentspeak.language.variable.IVariable< T >.set().
variabletostring()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.variabletostring ()
Definition at line 188 of file TestCTermVariablesConstant.java.
variablevalueassignable()
final void org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablevalueassignable ()
Definition at line 162 of file TestCTermVariablesConstant.java.