LightJason - AgentSpeak(L++): org.lightjason.agentspeak.common.CPath.CPathCollector Class Reference
org.lightjason.agentspeak.common.CPath.CPathCollector Class Reference
path collector
Inherits Collector< String, IPath, IPath >.
Public Member Functions
final BiConsumer< IPath, String > accumulator ()
final Set< Characteristics > characteristics ()
final BinaryOperator< IPath > combiner ()
final Function< IPath, IPath > finisher ()
final Supplier< IPath > supplier ()
Detailed Description
Definition at line 514 of file CPath.java.
Member Function Documentation
accumulator()
final BiConsumer<IPath, String> org.lightjason.agentspeak.common.CPath.CPathCollector.accumulator ()
Definition at line 524 of file CPath.java.
References org.lightjason.agentspeak.common.IPath.pushback().
characteristics()
final Set<Characteristics> org.lightjason.agentspeak.common.CPath.CPathCollector.characteristics ()
Definition at line 542 of file CPath.java.
combiner()
final BinaryOperator<IPath> org.lightjason.agentspeak.common.CPath.CPathCollector.combiner ()
Definition at line 530 of file CPath.java.
References org.lightjason.agentspeak.common.IPath.pushback().
finisher()
final Function<IPath, IPath> org.lightjason.agentspeak.common.CPath.CPathCollector.finisher ()
Definition at line 536 of file CPath.java.
supplier()
final Supplier<IPath> org.lightjason.agentspeak.common.CPath.CPathCollector.supplier ()
Definition at line 518 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().