LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm > Class Template Reference
org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm > Class Template Reference
inner class for encapsulating term values (variable / raw terms)
Public Member Functions
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Package Functions
CTermWrapper (@Nonnull final T p_value)
ctor
Private Member Functions
Stream< IVariable<?> > getVariableSet (final T p_value)
returns a variable set based on the generic type
Private Attributes
final T m_value
term value
Static Private Attributes
static final long serialVersionUID = 6984535096829821628L
serial id
Detailed Description
Definition at line 102 of file CProxyAction.java.
Constructor & Destructor Documentation
CTermWrapper()
org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.CTermWrapper (@Nonnull final T p_value) package
Parameters
p_value any static term
Definition at line 118 of file CProxyAction.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.equals (final Object p_object)
Definition at line 136 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.hashCode().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 143 of file CProxyAction.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
getVariableSet()
Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.getVariableSet (final T p_value) private
Parameters
p_value term type
Returns
variable set (empty)
Definition at line 165 of file CProxyAction.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.variables().
hashCode()
final int org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.hashCode ()
Definition at line 124 of file CProxyAction.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.equals(), and org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.equals().
toString()
final String org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.toString ()
Definition at line 130 of file CProxyAction.java.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 153 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.getVariableSet().
Member Data Documentation
m_value
final T org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.m_value private
Definition at line 111 of file CProxyAction.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.serialVersionUID = 6984535096829821628L static private
Definition at line 107 of file CProxyAction.java.