LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.web.IBaseWeb Class Reference
org.lightjason.agentspeak.action.builtin.web.IBaseWeb Class Reference abstract
web base action class
Protected Member Functions
IBaseWeb (final int p_length)
ctor
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
IBuiltinAction ()
ctor
IBuiltinAction (final int p_length)
ctor
Static Protected Member Functions
static ITerm baseliteral (@Nonnull final Stream< String > p_functor, @Nonnull final Stream< ITerm > p_values)
creates a literal structure from a stream of string elements, the string stream will be build in a tree structure
static Stream< ITerm > flatterm (@Nullable final Object p_object)
converts an object into a term stream
static HttpGet httpget (@Nonnull final String p_url)
returns a http-get connection
static String httpgetexecute (@Nonnull final String p_url) throws IOException
execute http-get request
static String httpgetexecute (@Nonnull final HttpGet p_get) throws IOException
execute http-get request
static HttpPost httppost (@Nonnull final String p_url)
returns a http-post connection
static String httppostexecute (@Nonnull final HttpPost p_post) throws IOException
execute http-post request
Static Private Member Functions
static Stream< ITerm > flatcollection (@Nonnull final Collection<?> p_collection)
transforms a collection into a term stream
static Stream< ITerm > flatmap (@Nonnull final Map< String, ?> p_map)
transformas a map into a literal
static< T extends HttpRequestBase > T header (@Nonnull final T p_request)
sets the default header definition
Static Private Attributes
static final long serialVersionUID = 4839156213009145751L
serial id
Additional Inherited Members
Public Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default int minimalArgumentNumber ()
minimum number of arguments
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.IExecution
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Static Protected Attributes inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
static final Logger LOGGER = CCommon.logger(IBuiltinAction.class)
logger
Static Protected Attributes inherited from org.lightjason.agentspeak.action.IBaseAction
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Detailed Description
Definition at line 53 of file IBaseWeb.java.
Constructor & Destructor Documentation
IBaseWeb()
org.lightjason.agentspeak.action.builtin.web.IBaseWeb.IBaseWeb (final int p_length) protected
Parameters
p_length length
Definition at line 65 of file IBaseWeb.java.
Member Function Documentation
baseliteral()
static ITerm org.lightjason.agentspeak.action.builtin.web.IBaseWeb.baseliteral (@Nonnull final Stream< String > p_functor, @Nonnull final Stream< ITerm > p_values) static protected
Parameters
p_functor stream with functor strings
p_values value stream
Returns
term
Definition at line 159 of file IBaseWeb.java.
References org.lightjason.agentspeak.language.CLiteral.from().
Referenced by org.lightjason.agentspeak.action.builtin.web.rest.CXMLObject.execute(), org.lightjason.agentspeak.action.builtin.web.rest.CJsonObject.execute(), org.lightjason.agentspeak.action.builtin.web.rest.CJsonList.execute(), and org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL.execute().
flatcollection()
static Stream<ITerm> org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatcollection (@Nonnull final Collection<?> p_collection) static private
Parameters
p_collection collection
Returns
term stream
Definition at line 218 of file IBaseWeb.java.
References org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatterm().
Referenced by org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatterm().
flatmap()
static Stream<ITerm> org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatmap (@Nonnull final Map< String, ?> p_map) static private
Parameters
p_map input map
Returns
term stream
Definition at line 199 of file IBaseWeb.java.
References org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatterm(), and org.lightjason.agentspeak.language.CLiteral.from().
Referenced by org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatterm().
flatterm()
static Stream<ITerm> org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatterm (@Nullable final Object p_object) static protected
Parameters
p_object object
Returns
term stream
Definition at line 178 of file IBaseWeb.java.
References org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatcollection(), org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatmap(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
Referenced by org.lightjason.agentspeak.action.builtin.web.rest.CXMLObject.execute(), org.lightjason.agentspeak.action.builtin.web.rest.CJsonObject.execute(), org.lightjason.agentspeak.action.builtin.web.rest.CJsonList.execute(), org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatcollection(), org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatmap(), and org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL.sendquery().
header()
static <T extends HttpRequestBase> T org.lightjason.agentspeak.action.builtin.web.IBaseWeb.header (@Nonnull final T p_request) static private
Parameters
p_request request
Template Parameters
T request type
Returns
input request
Definition at line 99 of file IBaseWeb.java.
References org.lightjason.agentspeak.common.CCommon.configuration(), and org.lightjason.agentspeak.common.CCommon.PACKAGEROOT.
Referenced by org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httpget(), and org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httppost().
httpget()
static HttpGet org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httpget (@Nonnull final String p_url) static protected
Parameters
p_url url
Returns
request
Definition at line 87 of file IBaseWeb.java.
References org.lightjason.agentspeak.action.builtin.web.IBaseWeb.header().
Referenced by org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httpgetexecute().
httpgetexecute() [1/2]
static String org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httpgetexecute (@Nonnull final String p_url) throws IOException static protected
Parameters
p_url url
Returns
url data
Exceptions
IOException is thrown on connection errors
Definition at line 121 of file IBaseWeb.java.
References org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httpget().
Referenced by org.lightjason.agentspeak.action.builtin.web.rest.IBaseRest.json(), and org.lightjason.agentspeak.action.builtin.web.rest.IBaseRest.xml().
httpgetexecute() [2/2]
static String org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httpgetexecute (@Nonnull final HttpGet p_get) throws IOException static protected
Parameters
p_get get request
Returns
output data as string
Exceptions
IOException is thrown on connection errors
Definition at line 133 of file IBaseWeb.java.
httppost()
static HttpPost org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httppost (@Nonnull final String p_url) static protected
Parameters
p_url url
Returns
request
Definition at line 76 of file IBaseWeb.java.
References org.lightjason.agentspeak.action.builtin.web.IBaseWeb.header().
Referenced by org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL.sendquery().
httppostexecute()
static String org.lightjason.agentspeak.action.builtin.web.IBaseWeb.httppostexecute (@Nonnull final HttpPost p_post) throws IOException static protected
Parameters
p_post post request
Returns
output data as string
Exceptions
IOException is thrown on connection errors
Definition at line 145 of file IBaseWeb.java.
Referenced by org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL.sendquery().
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.action.builtin.web.IBaseWeb.serialVersionUID = 4839156213009145751L static private
Definition at line 58 of file IBaseWeb.java.