LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector Class Reference
test math blas vector functions
Public Member Functions
final void action (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
test all input actions
final void assignscalar ()
test assign scalar
final void assignvector ()
test assign vector
final void copy ()
test copy
final void create ()
test create
final void fromlist ()
test fromlist
final void get ()
test get
final void parse ()
test parse
final void set ()
test set
final void tolist ()
test toList
Static Public Member Functions
static Object [] generator ()
data provider generator
Static Private Member Functions
static Stream< Object > testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult)
method to generate test-cases
Static Private Attributes
static final DoubleMatrix1D VECTOR1 = new DenseDoubleMatrix1D(new double[]{2, 5, 3, 8})
testing vector
static final DoubleMatrix1D VECTOR2 = new DenseDoubleMatrix1D(new double[]{8, 6, 2, 1})
testing vector
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 67 of file TestCActionMathBlasVector.java.
Member Function Documentation
action()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.action (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
Parameters
p_input tripel input data, actions and results
Exceptions
IllegalAccessException is thrwon on instantiation error
InstantiationException is thrwon on instantiation error
NoSuchMethodException is thrwon on instantiation error
InvocationTargetException is thrwon on instantiation error
Definition at line 140 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.ITerm.raw().
assignscalar()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.assignscalar ()
Definition at line 225 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CAssign.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
assignvector()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.assignvector ()
Definition at line 242 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CAssign.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
copy()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.copy ()
Definition at line 279 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CCopy.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.create ()
Definition at line 162 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
fromlist()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.fromlist ()
Definition at line 322 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.vector.CFromList.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
generator()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.generator () static
Returns
data
Definition at line 88 of file TestCActionMathBlasVector.java.
get()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.get ()
Definition at line 260 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CGet.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
parse()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.parse ()
Definition at line 297 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CParse.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
set()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.set ()
Definition at line 187 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CSet.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
testcase()
static Stream<Object> org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult) static private
Parameters
p_input input data
p_classes matching test-classes / test-cases
p_classresult result for each class
Returns
test-object
Definition at line 117 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
tolist()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.tolist ()
Definition at line 204 of file TestCActionMathBlasVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.set.CToList.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
Member Data Documentation
VECTOR1
final DoubleMatrix1D org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.VECTOR1 = new DenseDoubleMatrix1D(new double[]{2, 5, 3, 8}) static private
Note
static because of usage in data-provider
Definition at line 74 of file TestCActionMathBlasVector.java.
VECTOR2
final DoubleMatrix1D org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.VECTOR2 = new DenseDoubleMatrix1D(new double[]{8, 6, 2, 1}) static private
Note
static because of usage in data-provider
Definition at line 80 of file TestCActionMathBlasVector.java.