LightJason - AgentSpeak(L++): org.lightjason.agentspeak.grammar.CCommon Class Reference
org.lightjason.agentspeak.grammar.CCommon Class Reference
common parser components
Static Package Functions
static IExpression createLogicalBinaryExpression (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_lefthandside, @Nonnull final Collection< IExpression > p_righthandside)
creates a logical expression concationation with single operator
Static Package Attributes
static final Map< String, Double > NUMERICCONSTANT
numeric constant values - infinity is defined manually
Private Member Functions
CCommon ()
ctor
Detailed Description
Definition at line 45 of file grammar/CCommon.java.
Constructor & Destructor Documentation
CCommon()
org.lightjason.agentspeak.grammar.CCommon.CCommon () private
Definition at line 94 of file grammar/CCommon.java.
Member Function Documentation
createLogicalBinaryExpression()
static IExpression org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_lefthandside, @Nonnull final Collection< IExpression > p_righthandside) static package
Parameters
p_operator operator
p_lefthandside left-hand-side expression
p_righthandside right-hand-side expressions
Returns
concat expression
Definition at line 106 of file grammar/CCommon.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_and(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_and(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_xor(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_xor().
Member Data Documentation
NUMERICCONSTANT
final Map<String, Double> org.lightjason.agentspeak.grammar.CCommon.NUMERICCONSTANT static package
Definition at line 51 of file grammar/CCommon.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.numericonstant(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.numericonstant(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.numericonstant().