LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral Class Reference
org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral Class Reference
achievement for rule-literal execution
Public Member Functions
CAchievementRuleLiteral (@Nonnull final ILiteral p_literal)
ctor
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
final String toString ()
final Stream< IVariable<?> > variables ()
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.achievement_test.IAchievementRule< ILiteral >
final boolean equals (final Object p_object)
final int hashCode ()
Static Private Attributes
static final long serialVersionUID = -1575197582635138960L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.achievement_test.IAchievementRule< ILiteral >
IAchievementRule (@Nonnull final T p_type)
ctor
Static Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.achievement_test.IAchievementRule< ILiteral >
static IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final ILiteral p_value)
execute rule from context
Detailed Description
Definition at line 43 of file CAchievementRuleLiteral.java.
Constructor & Destructor Documentation
CAchievementRuleLiteral()
org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral.CAchievementRuleLiteral (@Nonnull final ILiteral p_literal)
Parameters
p_literal literal of the call
Definition at line 55 of file CAchievementRuleLiteral.java.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Definition at line 62 of file CAchievementRuleLiteral.java.
References org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral.execute().
Referenced by org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral.execute().
toString()
final String org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral.toString ()
Definition at line 82 of file CAchievementRuleLiteral.java.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral.variables ()
Definition at line 71 of file CAchievementRuleLiteral.java.
References org.lightjason.agentspeak.language.CCommon.flattenrecursive().
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementRuleLiteral.serialVersionUID = -1575197582635138960L static private
Definition at line 48 of file CAchievementRuleLiteral.java.