LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.view.CView Class Reference
org.lightjason.agentspeak.beliefbase.view.CView Class Reference
view of a beliefbase
Public Member Functions
CView (@Nonnull final String p_name, @Nonnull final IBeliefbase p_beliefbase)
ctor
CView (@Nonnull final String p_name, @Nonnull final IBeliefbase p_beliefbase, final IView p_parent)
ctor
final IView add (@Nonnull final Stream< ILiteral > p_literal)
adds a literal in the current structure
final IView add (@Nonnull final ILiteral... p_literal)
adds a literal in the current structure
final IView add (@Nonnull final IView... p_view)
adds view in the current structure
final IBeliefbase beliefbase ()
returns the beliefbase
final IView clear (@Nullable final IPath... p_path)
clears all elements
final boolean containsLiteral (@Nonnull final IPath p_path)
checks if a literal exists
final boolean containsView (@Nonnull final IPath p_path)
view existing check
final boolean empty ()
checks if the structure empty
final boolean equals (final Object p_object)
final IView generate (@Nonnull final IViewGenerator p_generator, @Nonnull final IPath... p_paths)
generates path structure
final int hashCode ()
final boolean hasParent ()
check if the view has got a parent
final String name ()
returns only the element name
final IView parent ()
returns the parent of the view
final IPath path ()
returns the full path
final IView remove (@Nonnull final IView... p_view)
removes a view in the current structure
final IView remove (@Nonnull final Stream< ILiteral > p_literal)
removes a literal in the current structure
final IView remove (@Nonnull final ILiteral... p_literal)
removes a literal in the current structure
final Stream< IView > root ()
returns a stream to the root node,
final int size ()
returns the size of literals
final Stream< ILiteral > stream (@Nullable final IPath... p_path)
returns stream of literal
final Stream< ILiteral > stream (final boolean p_negated, @Nullable final IPath... p_path)
returns stream of literal
final String toString ()
final Stream< ITrigger > trigger ()
retruns all trigger of the beliefbase
final IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
final Stream< IView > walk (@Nonnull final IPath p_path, @Nullable final IViewGenerator... p_generator)
streams path walking
Private Member Functions
IView leafview (@Nonnull final Stream< IView > p_stream)
returns the leaf of a view path
Stream< IView > walkdown (@Nonnull final IPath p_path, @Nullable final IViewGenerator... p_generator)
inner walking structure of views
Private Attributes
final IBeliefbase m_beliefbase
reference to the beliefbase context
final String m_name
view name
final IView m_parent
parent name
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.beliefbase.view.IView
IView EMPTY
empty view
Detailed Description
Template Parameters
T agent type
Definition at line 48 of file CView.java.
Constructor & Destructor Documentation
CView() [1/2]
org.lightjason.agentspeak.beliefbase.view.CView.CView (@Nonnull final String p_name, @Nonnull final IBeliefbase p_beliefbase)
Parameters
p_name view name
p_beliefbase reference to the beliefbase context
Definition at line 71 of file CView.java.
CView() [2/2]
org.lightjason.agentspeak.beliefbase.view.CView.CView (@Nonnull final String p_name, @Nonnull final IBeliefbase p_beliefbase, final IView p_parent)
Parameters
p_name view name
p_beliefbase reference to the beliefbase context
p_parent reference to the parent view
Definition at line 84 of file CView.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Function Documentation
add() [1/3]
final IView org.lightjason.agentspeak.beliefbase.view.CView.add (@Nonnull final Stream< ILiteral > p_literal)
Parameters
p_literal literal stream
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 123 of file CView.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.add(), org.lightjason.agentspeak.beliefbase.view.IView.beliefbase(), org.lightjason.agentspeak.beliefbase.view.CView.leafview(), and org.lightjason.agentspeak.beliefbase.view.CView.walk().
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add().
add() [2/3]
final IView org.lightjason.agentspeak.beliefbase.view.CView.add (@Nonnull final ILiteral... p_literal)
Parameters
p_literal literal
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 132 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.add().
add() [3/3]
final IView org.lightjason.agentspeak.beliefbase.view.CView.add (@Nonnull final IView... p_view)
Parameters
p_view existing view
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 140 of file CView.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.add(), org.lightjason.agentspeak.beliefbase.view.CView.beliefbase(), org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, org.lightjason.agentspeak.beliefbase.view.CView.root(), and org.lightjason.agentspeak.beliefbase.view.IView.stream().
beliefbase()
final IBeliefbase org.lightjason.agentspeak.beliefbase.view.CView.beliefbase ()
Returns
beliefbase
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 332 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add().
clear()
final IView org.lightjason.agentspeak.beliefbase.view.CView.clear (@Nullable final IPath... p_path)
Parameters
p_path path values
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 185 of file CView.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.clear(), org.lightjason.agentspeak.beliefbase.view.CView.leafview(), org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, and org.lightjason.agentspeak.beliefbase.view.CView.walk().
containsLiteral()
final boolean org.lightjason.agentspeak.beliefbase.view.CView.containsLiteral (@Nonnull final IPath p_path)
Parameters
p_path path to a literal (suffix is literal name)
Returns
existance boolean
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 208 of file CView.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CView.leafview(), org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, and org.lightjason.agentspeak.beliefbase.view.CView.walk().
containsView()
final boolean org.lightjason.agentspeak.beliefbase.view.CView.containsView (@Nonnull final IPath p_path)
Parameters
p_path path to a view
Returns
existance boolean
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 197 of file CView.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.containsView(), org.lightjason.agentspeak.beliefbase.view.CView.leafview(), org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, and org.lightjason.agentspeak.beliefbase.view.CView.walk().
empty()
final boolean org.lightjason.agentspeak.beliefbase.view.CView.empty ()
Returns
empty boolean
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 338 of file CView.java.
References org.lightjason.agentspeak.beliefbase.IStructure.empty(), and org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase.
equals()
final boolean org.lightjason.agentspeak.beliefbase.view.CView.equals (final Object p_object)
Definition at line 392 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.hashCode().
generate()
final IView org.lightjason.agentspeak.beliefbase.view.CView.generate (@Nonnull final IViewGenerator p_generator, @Nonnull final IPath... p_paths)
Parameters
p_generator generator for views
p_paths paths items
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 264 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.IView.stream(), and org.lightjason.agentspeak.beliefbase.view.CView.walk().
hashCode()
final int org.lightjason.agentspeak.beliefbase.view.CView.hashCode ()
Definition at line 386 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, and org.lightjason.agentspeak.beliefbase.view.CView.m_name.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.equals().
hasParent()
final boolean org.lightjason.agentspeak.beliefbase.view.CView.hasParent ()
Returns
boolean flag of the parent
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 380 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_parent.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.root().
leafview()
IView org.lightjason.agentspeak.beliefbase.view.CView.leafview (@Nonnull final Stream< IView > p_stream) private
Parameters
p_stream stream of views
Returns
last / leaf view
Definition at line 317 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.IView.EMPTY.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add(), org.lightjason.agentspeak.beliefbase.view.CView.clear(), org.lightjason.agentspeak.beliefbase.view.CView.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CView.containsView(), org.lightjason.agentspeak.beliefbase.view.CView.remove(), and org.lightjason.agentspeak.beliefbase.view.CView.stream().
name()
final String org.lightjason.agentspeak.beliefbase.view.CView.name ()
Returns
name
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 360 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_name.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.toString().
parent()
final IView org.lightjason.agentspeak.beliefbase.view.CView.parent ()
Returns
parent object or null
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 374 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_parent.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.root().
path()
final IPath org.lightjason.agentspeak.beliefbase.view.CView.path ()
Returns
path
Note
the path is relative to the root node, exclusive root element
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 367 of file CView.java.
References org.lightjason.agentspeak.common.CPath.collect(), org.lightjason.agentspeak.beliefbase.view.IView.name(), and org.lightjason.agentspeak.beliefbase.view.CView.root().
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.stream(), and org.lightjason.agentspeak.beliefbase.view.CView.trigger().
remove() [1/3]
final IView org.lightjason.agentspeak.beliefbase.view.CView.remove (@Nonnull final IView... p_view)
Parameters
p_view view
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 161 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.IView.stream().
remove() [2/3]
final IView org.lightjason.agentspeak.beliefbase.view.CView.remove (@Nonnull final Stream< ILiteral > p_literal)
Parameters
p_literal literal stream
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 169 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.IView.beliefbase(), org.lightjason.agentspeak.beliefbase.view.CView.leafview(), org.lightjason.agentspeak.beliefbase.IBeliefbase.remove(), and org.lightjason.agentspeak.beliefbase.view.CView.walk().
remove() [3/3]
final IView org.lightjason.agentspeak.beliefbase.view.CView.remove (@Nonnull final ILiteral... p_literal)
Parameters
p_literal literal
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 178 of file CView.java.
root()
final Stream<IView> org.lightjason.agentspeak.beliefbase.view.CView.root ()
Returns
stream of views
Note
the stream is exclusive of the root node and starts with the current node
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 351 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.hasParent(), org.lightjason.agentspeak.beliefbase.view.CView.parent(), and org.lightjason.agentspeak.beliefbase.view.IView.root().
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add(), and org.lightjason.agentspeak.beliefbase.view.CView.path().
size()
final int org.lightjason.agentspeak.beliefbase.view.CView.size ()
Returns
size
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 344 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, and org.lightjason.agentspeak.beliefbase.IStructure.size().
stream() [1/2]
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.CView.stream (@Nullable final IPath... p_path)
Parameters
p_path paths of the literals
Returns
literal stream
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 227 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.IView.beliefbase(), org.lightjason.agentspeak.beliefbase.view.CView.leafview(), org.lightjason.agentspeak.beliefbase.IBeliefbase.literal(), org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, org.lightjason.agentspeak.beliefbase.view.CView.path(), org.lightjason.agentspeak.beliefbase.IBeliefbase.streamLiteral(), org.lightjason.agentspeak.beliefbase.IBeliefbase.streamView(), and org.lightjason.agentspeak.beliefbase.view.CView.walk().
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.stream().
stream() [2/2]
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.CView.stream (final boolean p_negated, @Nullable final IPath... p_path)
Parameters
p_negated negated flag
p_path paths of the literals
Returns
literal stream
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 240 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.IView.beliefbase(), org.lightjason.agentspeak.beliefbase.view.CView.leafview(), org.lightjason.agentspeak.beliefbase.IBeliefbase.literal(), org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, org.lightjason.agentspeak.beliefbase.view.CView.path(), org.lightjason.agentspeak.beliefbase.view.CView.stream(), org.lightjason.agentspeak.beliefbase.IBeliefbase.streamLiteral(), org.lightjason.agentspeak.beliefbase.IBeliefbase.streamView(), and org.lightjason.agentspeak.beliefbase.view.CView.walk().
toString()
final String org.lightjason.agentspeak.beliefbase.view.CView.toString ()
Definition at line 398 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, and org.lightjason.agentspeak.beliefbase.view.CView.name().
trigger()
final Stream<ITrigger> org.lightjason.agentspeak.beliefbase.view.CView.trigger ()
Returns
set with trigger events
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 100 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, org.lightjason.agentspeak.beliefbase.view.CView.path(), org.lightjason.agentspeak.common.IPath.remove(), and org.lightjason.agentspeak.beliefbase.IBeliefbase.trigger().
update()
final IAgent<?> org.lightjason.agentspeak.beliefbase.view.CView.update (@Nonnull final IAgent<?> p_agent)
Parameters
p_agent agent which runs the update call
Returns
agent
Warning
call update on a storage and on all storage-view, if exists different views which are point to the same storage, the update is called more than once, so the storage must limit the number of update calls
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 110 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, and org.lightjason.agentspeak.beliefbase.IStructure.update().
walk()
final Stream<IView> org.lightjason.agentspeak.beliefbase.view.CView.walk (@Nonnull final IPath p_path, @Nullable final IViewGenerator... p_generator)
Parameters
p_path path
p_generator generator for view creating (first argument is used, orther elements will be ignored)
Returns
stream of views
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 257 of file CView.java.
References org.lightjason.agentspeak.beliefbase.view.CView.walkdown().
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add(), org.lightjason.agentspeak.beliefbase.view.CView.clear(), org.lightjason.agentspeak.beliefbase.view.CView.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CView.containsView(), org.lightjason.agentspeak.beliefbase.view.CView.generate(), org.lightjason.agentspeak.beliefbase.view.CView.remove(), and org.lightjason.agentspeak.beliefbase.view.CView.stream().
walkdown()
Stream<IView> org.lightjason.agentspeak.beliefbase.view.CView.walkdown (@Nonnull final IPath p_path, @Nullable final IViewGenerator... p_generator) private
Parameters
p_path path
p_generator generator (first argument is used, other elements will be ignored)
Returns
view stream
Definition at line 280 of file CView.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.add(), org.lightjason.agentspeak.beliefbase.IStructure.empty(), org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase, org.lightjason.agentspeak.beliefbase.IBeliefbase.viewOrDefault(), and org.lightjason.agentspeak.beliefbase.view.IView.walk().
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.walk().
Member Data Documentation
m_beliefbase
final IBeliefbase org.lightjason.agentspeak.beliefbase.view.CView.m_beliefbase private
Definition at line 57 of file CView.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add(), org.lightjason.agentspeak.beliefbase.view.CView.beliefbase(), org.lightjason.agentspeak.beliefbase.view.CView.clear(), org.lightjason.agentspeak.beliefbase.view.CView.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CView.containsView(), org.lightjason.agentspeak.beliefbase.view.CView.empty(), org.lightjason.agentspeak.beliefbase.view.CView.hashCode(), org.lightjason.agentspeak.beliefbase.view.CView.size(), org.lightjason.agentspeak.beliefbase.view.CView.stream(), org.lightjason.agentspeak.beliefbase.view.CView.toString(), org.lightjason.agentspeak.beliefbase.view.CView.trigger(), org.lightjason.agentspeak.beliefbase.view.CView.update(), and org.lightjason.agentspeak.beliefbase.view.CView.walkdown().
m_name
final String org.lightjason.agentspeak.beliefbase.view.CView.m_name private
Definition at line 53 of file CView.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.hashCode(), and org.lightjason.agentspeak.beliefbase.view.CView.name().
m_parent
final IView org.lightjason.agentspeak.beliefbase.view.CView.m_parent private
Definition at line 61 of file CView.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.hasParent(), and org.lightjason.agentspeak.beliefbase.view.CView.parent().