LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionAgent Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionAgent Class Reference
test agent action
Classes
class CAgent
agent class
class CEmptyPlan
empty plan
Public Member Functions
final void addplan ()
test add plan
final void belieflist ()
test belieflist
final void clearbeliefbase ()
test clear-beliefbase
final void cycletime ()
test cycle-time
final void getplan ()
test get plan
void initialize () throws Exception
initialize
final void planlist ()
test plan list
final void removeplan ()
test remove plan
final void removeplanerror ()
test remove plan error
Static Package Functions
[static initializer]
Private Member Functions
IContext next ()
execute agent cycle
Private Attributes
IContext m_context
agent context
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 75 of file TestCActionAgent.java.
Member Function Documentation
[static initializer]()
org.lightjason.agentspeak.action.builtin.TestCActionAgent.[static initializer] () static package
addplan()
final void org.lightjason.agentspeak.action.builtin.TestCActionAgent.addplan ()
Definition at line 148 of file TestCActionAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL, org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.agent.CAddPlan.execute(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.plan(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.plans().
belieflist()
final void org.lightjason.agentspeak.action.builtin.TestCActionAgent.belieflist ()
Definition at line 283 of file TestCActionAgent.java.
References org.lightjason.agentspeak.beliefbase.view.IView.add(), org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.beliefbase(), org.lightjason.agentspeak.action.builtin.agent.CBeliefList.execute(), org.lightjason.agentspeak.language.CLiteral.from(), and org.lightjason.agentspeak.beliefbase.IStructure.size().
clearbeliefbase()
final void org.lightjason.agentspeak.action.builtin.TestCActionAgent.clearbeliefbase ()
Definition at line 259 of file TestCActionAgent.java.
References org.lightjason.agentspeak.beliefbase.view.IView.add(), org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.beliefbase(), org.lightjason.agentspeak.action.builtin.agent.CClearBeliefbase.execute(), org.lightjason.agentspeak.language.CLiteral.from(), and org.lightjason.agentspeak.beliefbase.IStructure.size().
cycletime()
final void org.lightjason.agentspeak.action.builtin.TestCActionAgent.cycletime ()
Definition at line 170 of file TestCActionAgent.java.
References org.lightjason.agentspeak.action.builtin.agent.CCycleTime.execute(), and org.lightjason.agentspeak.action.builtin.TestCActionAgent.next().
getplan()
final void org.lightjason.agentspeak.action.builtin.TestCActionAgent.getplan ()
Definition at line 190 of file TestCActionAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL, org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.agent.CGetPlan.execute(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.from(), org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.plans(), and org.lightjason.agentspeak.language.instantiable.plan.IPlan.trigger().
initialize()
void org.lightjason.agentspeak.action.builtin.TestCActionAgent.initialize () throws Exception
Exceptions
Exception on initialize error
Definition at line 96 of file TestCActionAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL, org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), and org.lightjason.agentspeak.language.CLiteral.from().
next()
IContext org.lightjason.agentspeak.action.builtin.TestCActionAgent.next () private
Returns
execution context
Definition at line 318 of file TestCActionAgent.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), and org.lightjason.agentspeak.action.builtin.TestCActionAgent.m_context.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.cycletime().
planlist()
final void org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist ()
Definition at line 110 of file TestCActionAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL, org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.agent.CPlanList.execute(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.from(), org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.literal(), org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.plans(), org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.sequence(), org.lightjason.agentspeak.language.instantiable.plan.IPlan.trigger(), and org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.type().
removeplan()
final void org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplan ()
Definition at line 224 of file TestCActionAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL, org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.from(), org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.plans(), and org.lightjason.agentspeak.language.instantiable.plan.IPlan.trigger().
removeplanerror()
final void org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplanerror ()
Definition at line 243 of file TestCActionAgent.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
Member Data Documentation
m_context
IContext org.lightjason.agentspeak.action.builtin.TestCActionAgent.m_context private
Definition at line 80 of file TestCActionAgent.java.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.next().