LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue Enum Reference
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue Enum Reference
enum of statistic value types
Public Member Functions
final double value (@Nonnull final SummaryStatistics p_statistic)
returns a statistic value
final double value (@Nonnull final DescriptiveStatistics p_statistic)
returns a statistic value
Static Public Member Functions
static EStatisticValue from (@Nonnull final String p_value)
additional factory
Public Attributes
COUNT
GEOMETRICMEAN
MAX
MEAN
MIN
POPULATIONVARIANCE
QUADRATICMEAN
SECONDMOMENT
STANDARDDEVIATION
SUM
SUMLOG
SUMSQUARE
VARIANCE
Detailed Description
Definition at line 37 of file EStatisticValue.java.
Member Function Documentation
from()
static EStatisticValue org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.from (@Nonnull final String p_value) static
Parameters
p_value string
Returns
enum
Definition at line 61 of file EStatisticValue.java.
Referenced by org.lightjason.agentspeak.action.builtin.math.statistic.CMultipleStatisticValue.execute(), and org.lightjason.agentspeak.action.builtin.math.statistic.CSingleStatisticValue.execute().
value() [1/2]
final double org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.value (@Nonnull final SummaryStatistics p_statistic)
Parameters
p_statistic statistic object
Returns
statistic value
Definition at line 72 of file EStatisticValue.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.action.builtin.math.statistic.CSingleStatisticValue.execute().
value() [2/2]
final double org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.value (@Nonnull final DescriptiveStatistics p_statistic)
Parameters
p_statistic statistic object
Returns
statistic value
Definition at line 126 of file EStatisticValue.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Data Documentation
COUNT
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.COUNT
Definition at line 42 of file EStatisticValue.java.
GEOMETRICMEAN
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.GEOMETRICMEAN
Definition at line 39 of file EStatisticValue.java.
MAX
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.MAX
Definition at line 40 of file EStatisticValue.java.
MEAN
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.MEAN
Definition at line 51 of file EStatisticValue.java.
MIN
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.MIN
Definition at line 41 of file EStatisticValue.java.
POPULATIONVARIANCE
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.POPULATIONVARIANCE
Definition at line 43 of file EStatisticValue.java.
QUADRATICMEAN
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.QUADRATICMEAN
Definition at line 44 of file EStatisticValue.java.
SECONDMOMENT
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.SECONDMOMENT
Definition at line 45 of file EStatisticValue.java.
STANDARDDEVIATION
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.STANDARDDEVIATION
Definition at line 46 of file EStatisticValue.java.
SUM
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.SUM
Definition at line 47 of file EStatisticValue.java.
SUMLOG
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.SUMLOG
Definition at line 48 of file EStatisticValue.java.
SUMSQUARE
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.SUMSQUARE
Definition at line 49 of file EStatisticValue.java.
VARIANCE
org.lightjason.agentspeak.action.builtin.math.statistic.EStatisticValue.VARIANCE
Definition at line 50 of file EStatisticValue.java.