LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.unify.CUnifier Class Reference
org.lightjason.agentspeak.language.unify.CUnifier Class Reference
unification algorithm
Public Member Functions
CUnifier ()
ctor
CUnifier (@Nonnull final IUnifier.IAlgorithm p_hashbased, @Nonnull final IUnifier.IAlgorithm p_recursive)
ctor
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
final Set< IVariable<?> > unify (@Nonnull final ILiteral p_source, @Nonnull final ILiteral p_target)
unifies a literal
IFuzzyValue< Boolean > unify (@Nonnull final IContext p_context, @Nonnull final ILiteral p_literal, final long p_variables, @Nonnull final IExpression p_expression, final boolean p_parallel)
unifies the literal with the expression
Private Member Functions
List< Set< IVariable<?> > > variables (final IAgent<?> p_agent, final ILiteral p_literal, final long p_variablenumber)
search all relevant literals within the agent beliefbase and unifies the variables
Static Private Member Functions
static boolean evaluateexpression (final IContext p_context, final IExpression p_expression, final Set< IVariable<?>> p_variables)
evaluate expression
static< T > Stream< T > parallelstream (final Stream< T > p_stream, final boolean p_parallel)
execute stream in parallel
Private Attributes
final IAlgorithm m_hashbased
hash-based unify algorithm
final IAlgorithm m_recursive
recursive unify algorithm
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.unify.IUnifier
IUnifier EMPTY
empty unifier
Detailed Description
Definition at line 50 of file CUnifier.java.
Constructor & Destructor Documentation
CUnifier() [1/2]
org.lightjason.agentspeak.language.unify.CUnifier.CUnifier ()
Definition at line 64 of file CUnifier.java.
CUnifier() [2/2]
org.lightjason.agentspeak.language.unify.CUnifier.CUnifier (@Nonnull final IUnifier.IAlgorithm p_hashbased, @Nonnull final IUnifier.IAlgorithm p_recursive)
Parameters
p_hashbased hash-based unification algorithm
p_recursive recursive-based unification algorithm
Definition at line 75 of file CUnifier.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.unify.CUnifier.equals (final Object p_object)
Definition at line 141 of file CUnifier.java.
References org.lightjason.agentspeak.language.unify.CUnifier.hashCode().
evaluateexpression()
static boolean org.lightjason.agentspeak.language.unify.CUnifier.evaluateexpression (final IContext p_context, final IExpression p_expression, final Set< IVariable<?>> p_variables) static private
Parameters
p_context execution context (will be duplicated)
p_expression expression
p_variables current variables
Returns
boolean for correct evaluation
Definition at line 173 of file CUnifier.java.
References org.lightjason.agentspeak.language.execution.IContext.duplicate(), org.lightjason.agentspeak.language.execution.IExecution.execute(), and org.lightjason.agentspeak.language.CCommon.updatecontext().
Referenced by org.lightjason.agentspeak.language.unify.CUnifier.unify().
hashCode()
final int org.lightjason.agentspeak.language.unify.CUnifier.hashCode ()
Definition at line 134 of file CUnifier.java.
Referenced by org.lightjason.agentspeak.language.unify.CUnifier.equals().
parallelstream()
static <T> Stream<T> org.lightjason.agentspeak.language.unify.CUnifier.parallelstream (final Stream< T > p_stream, final boolean p_parallel) static private
Parameters
p_stream stream
p_parallel parallel
Template Parameters
T stream elements
Returns
modified stream
Definition at line 160 of file CUnifier.java.
Referenced by org.lightjason.agentspeak.language.unify.CUnifier.unify().
toString()
final String org.lightjason.agentspeak.language.unify.CUnifier.toString ()
Definition at line 147 of file CUnifier.java.
unify() [1/2]
final Set<IVariable<?> > org.lightjason.agentspeak.language.unify.CUnifier.unify (@Nonnull final ILiteral p_source, @Nonnull final ILiteral p_target)
Parameters
p_source source literal (with data)
p_target target literal (with variables)
Returns
set with allocated variables
Note
check input literal and result of correct unification
Implements org.lightjason.agentspeak.language.unify.IUnifier.
Definition at line 85 of file CUnifier.java.
References org.lightjason.agentspeak.language.CCommon.flattenrecursive(), and org.lightjason.agentspeak.language.unify.IUnifier.IAlgorithm.unify().
Referenced by org.lightjason.agentspeak.language.unify.CUnifier.variables().
unify() [2/2]
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.unify.CUnifier.unify (@Nonnull final IContext p_context, @Nonnull final ILiteral p_literal, final long p_variables, @Nonnull final IExpression p_expression, final boolean p_parallel)
Parameters
p_context running context
p_literal literal with variables (creates a deep-copy)
p_variables number of unified variables
p_expression expression
p_parallel parallel executon
Returns
boolean if a unify can be done
Implements org.lightjason.agentspeak.language.unify.IUnifier.
Definition at line 109 of file CUnifier.java.
References org.lightjason.agentspeak.language.unify.CUnifier.evaluateexpression(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), org.lightjason.agentspeak.language.unify.CUnifier.parallelstream(), org.lightjason.agentspeak.language.CCommon.updatecontext(), and org.lightjason.agentspeak.language.unify.CUnifier.variables().
variables()
List<Set<IVariable<?> > > org.lightjason.agentspeak.language.unify.CUnifier.variables (final IAgent<?> p_agent, final ILiteral p_literal, final long p_variablenumber) private
Parameters
p_agent agent
p_literal literal search
p_variablenumber number of unified variables
Returns
list of literal sets
Definition at line 193 of file CUnifier.java.
References org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.beliefbase(), org.lightjason.agentspeak.language.IDeepCopy< T >.deepcopy(), org.lightjason.agentspeak.language.ILiteral.emptyValues(), org.lightjason.agentspeak.language.ITerm.fqnfunctor(), org.lightjason.agentspeak.language.ILiteral.negated(), org.lightjason.agentspeak.beliefbase.view.IView.stream(), and org.lightjason.agentspeak.language.unify.CUnifier.unify().
Referenced by org.lightjason.agentspeak.language.unify.CUnifier.unify().
Member Data Documentation
m_hashbased
final IAlgorithm org.lightjason.agentspeak.language.unify.CUnifier.m_hashbased private
Definition at line 55 of file CUnifier.java.
m_recursive
final IAlgorithm org.lightjason.agentspeak.language.unify.CUnifier.m_recursive private
Definition at line 59 of file CUnifier.java.