LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.CContext Class Reference
org.lightjason.agentspeak.language.execution.CContext Class Reference
execution context
Public Member Functions
CContext (@Nonnull final IAgent<?> p_agent, @Nonnull final IInstantiable p_instance, @Nonnull final Collection< IVariable<?>> p_variables)
ctor
final IAgent<?> agent ()
returns the agent of the context
final IContext duplicate ()
duplicates the context with a shallow-copy
final boolean equals (final Object p_object)
final int hashCode ()
final IInstantiable instance ()
returns the instance object
final Map< IPath, IVariable<?> > instancevariables ()
returns the variables names and their current value
final String toString ()
Private Attributes
final IAgent<?> m_agent
agent of the running context
final IInstantiable m_instance
current instance object
final Map< IPath, IVariable<?> > m_variables
plan variables with their data
Static Private Attributes
static final long serialVersionUID = 2813094837634259389L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.execution.IContext
IContext EMPTYPLAN
empty context with plan
IContext EMPTYRULE
empty context with rule
Detailed Description
Template Parameters
T instance type (plan or rule)
Definition at line 44 of file CContext.java.
Constructor & Destructor Documentation
CContext()
org.lightjason.agentspeak.language.execution.CContext.CContext (@Nonnull final IAgent<?> p_agent, @Nonnull final IInstantiable p_instance, @Nonnull final Collection< IVariable<?>> p_variables)
Parameters
p_agent agent
p_instance instance object
p_variables instance variables
Definition at line 71 of file CContext.java.
References org.lightjason.agentspeak.language.ITerm.fqnfunctor().
Referenced by org.lightjason.agentspeak.language.execution.CContext.duplicate().
Member Function Documentation
agent()
final IAgent<?> org.lightjason.agentspeak.language.execution.CContext.agent ()
Returns
agent
Implements org.lightjason.agentspeak.language.execution.IContext.
Definition at line 87 of file CContext.java.
References org.lightjason.agentspeak.language.execution.CContext.m_agent.
duplicate()
final IContext org.lightjason.agentspeak.language.execution.CContext.duplicate ()
Returns
shallow-copy of the context
Implements org.lightjason.agentspeak.language.execution.IContext.
Definition at line 80 of file CContext.java.
References org.lightjason.agentspeak.language.execution.CContext.CContext().
equals()
final boolean org.lightjason.agentspeak.language.execution.CContext.equals (final Object p_object)
Definition at line 113 of file CContext.java.
References org.lightjason.agentspeak.language.execution.CContext.hashCode().
hashCode()
final int org.lightjason.agentspeak.language.execution.CContext.hashCode ()
Definition at line 107 of file CContext.java.
Referenced by org.lightjason.agentspeak.language.execution.CContext.equals().
instance()
final IInstantiable org.lightjason.agentspeak.language.execution.CContext.instance ()
Returns
instance object plan or rule
Implements org.lightjason.agentspeak.language.execution.IContext.
Definition at line 94 of file CContext.java.
References org.lightjason.agentspeak.language.execution.CContext.m_instance.
instancevariables()
final Map<IPath, IVariable<?> > org.lightjason.agentspeak.language.execution.CContext.instancevariables ()
Returns
variable names and their current value
Implements org.lightjason.agentspeak.language.execution.IContext.
Definition at line 101 of file CContext.java.
References org.lightjason.agentspeak.language.execution.CContext.m_variables.
toString()
final String org.lightjason.agentspeak.language.execution.CContext.toString ()
Definition at line 119 of file CContext.java.
References org.lightjason.agentspeak.language.execution.CContext.m_agent, and org.lightjason.agentspeak.language.execution.CContext.m_instance.
Member Data Documentation
m_agent
final IAgent<?> org.lightjason.agentspeak.language.execution.CContext.m_agent private
Definition at line 53 of file CContext.java.
Referenced by org.lightjason.agentspeak.language.execution.CContext.agent(), and org.lightjason.agentspeak.language.execution.CContext.toString().
m_instance
final IInstantiable org.lightjason.agentspeak.language.execution.CContext.m_instance private
Definition at line 57 of file CContext.java.
Referenced by org.lightjason.agentspeak.language.execution.CContext.instance(), and org.lightjason.agentspeak.language.execution.CContext.toString().
m_variables
final Map<IPath, IVariable<?> > org.lightjason.agentspeak.language.execution.CContext.m_variables private
Definition at line 61 of file CContext.java.
Referenced by org.lightjason.agentspeak.language.execution.CContext.instancevariables().
serialVersionUID
final long org.lightjason.agentspeak.language.execution.CContext.serialVersionUID = 2813094837634259389L static private
Definition at line 49 of file CContext.java.