LightJason - AgentSpeak(L++): org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle Class Reference
org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle Class Reference
default abstract-syntax-tree (AST) visitor for plan-bundles scripts
Public Member Functions
CASTVisitorPlanBundle (@Nonnull final Set< IAction > p_actions)
ctor
final Set< ILiteral > initialbeliefs ()
returns initial beliefs
final Set< IPlan > plans ()
get a multimap with event-plan matching
final Set< IRule > rules ()
returns the rules / principles
final Object visitAchievement_goal_action (final PlanBundleParser.Achievement_goal_actionContext p_context)
final Object visitAnnotation_atom (final PlanBundleParser.Annotation_atomContext p_context)
final Object visitAnnotation_literal (final PlanBundleParser.Annotation_literalContext p_context)
Object visitAnnotation_value_literal (final PlanBundleParser.Annotation_value_literalContext p_context)
final Object visitAnnotations (final PlanBundleParser.AnnotationsContext p_context)
final Object visitAssignment_expression (final PlanBundleParser.Assignment_expressionContext p_context)
final Object visitAssignment_expression_multivariable (final PlanBundleParser.Assignment_expression_multivariableContext p_context)
final Object visitAssignment_expression_singlevariable (final PlanBundleParser.Assignment_expression_singlevariableContext p_context)
final Object visitAtom (final PlanBundleParser.AtomContext p_context)
final Object visitBelief (final PlanBundleParser.BeliefContext p_context)
final Object visitBelief_action (final PlanBundleParser.Belief_actionContext p_context)
final Object visitBinary_expression (final PlanBundleParser.Binary_expressionContext p_context)
final Object visitBlock_formula (final PlanBundleParser.Block_formulaContext p_context)
final Object visitBody (final PlanBundleParser.BodyContext p_context)
final Object visitBody_formula (final PlanBundleParser.Body_formulaContext p_context)
final Object visitDeconstruct_expression (final PlanBundleParser.Deconstruct_expressionContext p_context)
final Object visitDigitsequence (final PlanBundleParser.DigitsequenceContext p_context)
final Object visitExecutable_action (final PlanBundleParser.Executable_actionContext p_context)
final Object visitExecutable_rule (final PlanBundleParser.Executable_ruleContext p_context)
final Object visitExecutable_term (final PlanBundleParser.Executable_termContext p_context)
final Object visitExpression (final PlanBundleParser.ExpressionContext p_context)
final Object visitExpression_bracket (final PlanBundleParser.Expression_bracketContext p_context)
final Object visitExpression_logical_and (final PlanBundleParser.Expression_logical_andContext p_context)
final Object visitExpression_logical_element (final PlanBundleParser.Expression_logical_elementContext p_context)
final Object visitExpression_logical_negation (final PlanBundleParser.Expression_logical_negationContext p_context)
final Object visitExpression_logical_xor (final PlanBundleParser.Expression_logical_xorContext p_context)
final Object visitExpression_numeric (final PlanBundleParser.Expression_numericContext p_context)
final Object visitExpression_numeric_additive (final PlanBundleParser.Expression_numeric_additiveContext p_context)
final Object visitExpression_numeric_element (final PlanBundleParser.Expression_numeric_elementContext p_context)
final Object visitExpression_numeric_multiplicative (final PlanBundleParser.Expression_numeric_multiplicativeContext p_context)
final Object visitExpression_numeric_power (final PlanBundleParser.Expression_numeric_powerContext p_context)
final Object visitExpression_numeric_relation (final PlanBundleParser.Expression_numeric_relationContext p_context)
final Object visitLambda (final PlanBundleParser.LambdaContext p_context)
final Object visitLambda_initialization (final PlanBundleParser.Lambda_initializationContext p_context)
final Object visitLambda_return (final PlanBundleParser.Lambda_returnContext p_context)
final Object visitLiteral (final PlanBundleParser.LiteralContext p_context)
final Object visitLogicalruledefinition (final PlanBundleParser.LogicalruledefinitionContext p_context)
final Object visitLogicrule (final PlanBundleParser.LogicruleContext p_context)
final Object visitLogicrules (final PlanBundleParser.LogicrulesContext p_context)
final Object visitNumber (final PlanBundleParser.NumberContext p_context)
final Object visitPlan (final PlanBundleParser.PlanContext p_context)
final Object visitPlan_belief_trigger (final PlanBundleParser.Plan_belief_triggerContext p_context)
final Object visitPlan_goal_trigger (final PlanBundleParser.Plan_goal_triggerContext p_context)
final Object visitPlan_trigger (final PlanBundleParser.Plan_triggerContext p_context)
final Object visitPlanbundle (final PlanBundleParser.PlanbundleContext p_context)
final Object visitPlandefinition (final PlanBundleParser.PlandefinitionContext p_context)
final Object visitPlans (final PlanBundleParser.PlansContext p_context)
final Object visitRepair_formula (final PlanBundleParser.Repair_formulaContext p_context)
final Object visitTerm (final PlanBundleParser.TermContext p_context)
final Object visitTermlist (final PlanBundleParser.TermlistContext p_context)
final Object visitTernary_operation (final PlanBundleParser.Ternary_operationContext p_context)
final Object visitTernary_operation_false (final PlanBundleParser.Ternary_operation_falseContext p_context)
final Object visitTernary_operation_true (final PlanBundleParser.Ternary_operation_trueContext p_context)
final Object visitTest_action (final PlanBundleParser.Test_actionContext p_context)
final Object visitUnary_expression (final PlanBundleParser.Unary_expressionContext p_context)
final Object visitUnification (final PlanBundleParser.UnificationContext p_context)
final Object visitUnification_constraint (final PlanBundleParser.Unification_constraintContext p_context)
final Object visitVariable (final PlanBundleParser.VariableContext p_context)
final Object visitVariable_evaluate (final PlanBundleParser.Variable_evaluateContext p_context)
final Object visitVariableatom (final PlanBundleParser.VariableatomContext p_context)
final Object visitVariablelist (final PlanBundleParser.VariablelistContext p_context)
Protected Member Functions
Object visitLogicrulePlaceHolder (final PlanBundleParser.LogicruleContext p_context)
create a rule placeholder object
Static Private Member Functions
static boolean logicalvalue (@Nonnull final String p_value)
converts a string token to the type
static Number numericonstant (@Nonnull final String p_value)
returns the value of a numeric constant
static String stringvalue (@Nonnull final String p_value)
create a string value without quotes
Private Attributes
final Map< IPath, IAction > m_actions
map with action definition
final Set< ILiteral > m_initialbeliefs = new LinkedHashSet<>()
set with initial beliefs
final Set< IPlan > m_plans = new HashSet<>()
map with plans
final Multimap< IPath, IRule > m_rules = LinkedHashMultimap.create()
map with logical rules
Static Private Attributes
static final Logger LOGGER = CCommon.logger(IASTVisitorAgent.class)
logger
Detailed Description
Note
methods are implemented twice agent and plan-bundle, because both use equal AgentSpeak(L) grammer, but AntLR visitor does not support inheritance by the grammar definition
Definition at line 111 of file CASTVisitorPlanBundle.java.
Constructor & Destructor Documentation
CASTVisitorPlanBundle()
org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.CASTVisitorPlanBundle (@Nonnull final Set< IAction > p_actions)
Parameters
p_actions set with actions
Definition at line 139 of file CASTVisitorPlanBundle.java.
Member Function Documentation
initialbeliefs()
final Set<ILiteral> org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.initialbeliefs ()
Returns
set with initial beliefs
Implements org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.
Definition at line 1029 of file CASTVisitorPlanBundle.java.
logicalvalue()
static boolean org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.logicalvalue (@Nonnull final String p_value) static private
Parameters
p_value string value
Returns
boolean value
Definition at line 1006 of file CASTVisitorPlanBundle.java.
numericonstant()
static Number org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.numericonstant (@Nonnull final String p_value) static private
Parameters
p_value constant name
Returns
number value
Definition at line 991 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.grammar.CCommon.NUMERICCONSTANT.
plans()
final Set<IPlan> org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.plans ()
Returns
plan set
Implements org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.
Definition at line 1036 of file CASTVisitorPlanBundle.java.
rules()
final Set<IRule> org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.rules ()
Returns
rule set
Implements org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.
Definition at line 1043 of file CASTVisitorPlanBundle.java.
stringvalue()
static String org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.stringvalue (@Nonnull final String p_value) static private
Parameters
p_value string
Returns
string without quotes
Definition at line 1017 of file CASTVisitorPlanBundle.java.
visitAchievement_goal_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAchievement_goal_action (final PlanBundleParser.Achievement_goal_actionContext p_context)
Definition at line 548 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitAnnotation_atom()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAnnotation_atom (final PlanBundleParser.Annotation_atomContext p_context)
Definition at line 265 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.ATOMIC, org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.PARALLEL.
visitAnnotation_literal()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAnnotation_literal (final PlanBundleParser.Annotation_literalContext p_context)
Definition at line 277 of file CASTVisitorPlanBundle.java.
visitAnnotation_value_literal()
Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAnnotation_value_literal (final PlanBundleParser.Annotation_value_literalContext p_context)
Definition at line 283 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.CONSTANT, and org.lightjason.agentspeak.common.CCommon.languagestring().
visitAnnotations()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAnnotations (final PlanBundleParser.AnnotationsContext p_context)
Definition at line 247 of file CASTVisitorPlanBundle.java.
visitAssignment_expression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAssignment_expression (final PlanBundleParser.Assignment_expressionContext p_context)
Definition at line 494 of file CASTVisitorPlanBundle.java.
visitAssignment_expression_multivariable()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAssignment_expression_multivariable (final PlanBundleParser.Assignment_expression_multivariableContext p_context)
Definition at line 509 of file CASTVisitorPlanBundle.java.
visitAssignment_expression_singlevariable()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAssignment_expression_singlevariable (final PlanBundleParser.Assignment_expression_singlevariableContext p_context)
Definition at line 500 of file CASTVisitorPlanBundle.java.
visitAtom()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAtom (final PlanBundleParser.AtomContext p_context)
Definition at line 698 of file CASTVisitorPlanBundle.java.
visitBelief()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBelief (final PlanBundleParser.BeliefContext p_context)
Definition at line 159 of file CASTVisitorPlanBundle.java.
visitBelief_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBelief_action (final PlanBundleParser.Belief_actionContext p_context)
Definition at line 594 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.ADD, org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.DELETE, and org.lightjason.agentspeak.common.CCommon.languagestring().
visitBinary_expression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBinary_expression (final PlanBundleParser.Binary_expressionContext p_context)
Definition at line 535 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.from(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
visitBlock_formula()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBlock_formula (final PlanBundleParser.Block_formulaContext p_context)
Definition at line 420 of file CASTVisitorPlanBundle.java.
visitBody()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBody (final PlanBundleParser.BodyContext p_context)
Definition at line 333 of file CASTVisitorPlanBundle.java.
visitBody_formula()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBody_formula (final PlanBundleParser.Body_formulaContext p_context)
Definition at line 346 of file CASTVisitorPlanBundle.java.
visitDeconstruct_expression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitDeconstruct_expression (final PlanBundleParser.Deconstruct_expressionContext p_context)
Definition at line 606 of file CASTVisitorPlanBundle.java.
visitDigitsequence()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitDigitsequence (final PlanBundleParser.DigitsequenceContext p_context)
Definition at line 692 of file CASTVisitorPlanBundle.java.
visitExecutable_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExecutable_action (final PlanBundleParser.Executable_actionContext p_context)
Definition at line 943 of file CASTVisitorPlanBundle.java.
visitExecutable_rule()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExecutable_rule (final PlanBundleParser.Executable_ruleContext p_context)
Definition at line 949 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExecutable_term()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExecutable_term (final PlanBundleParser.Executable_termContext p_context)
Definition at line 471 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression (final PlanBundleParser.ExpressionContext p_context)
Definition at line 716 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression(), and org.lightjason.agentspeak.language.execution.expression.EOperator.OR.
visitExpression_bracket()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_bracket (final PlanBundleParser.Expression_bracketContext p_context)
Definition at line 733 of file CASTVisitorPlanBundle.java.
visitExpression_logical_and()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_and (final PlanBundleParser.Expression_logical_andContext p_context)
Definition at line 739 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.AND, and org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression().
visitExpression_logical_element()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_element (final PlanBundleParser.Expression_logical_elementContext p_context)
Definition at line 778 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression_logical_negation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_negation (final PlanBundleParser.Expression_logical_negationContext p_context)
Definition at line 772 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.NEGATION.
visitExpression_logical_xor()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_xor (final PlanBundleParser.Expression_logical_xorContext p_context)
Definition at line 751 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression(), org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.execution.expression.EOperator.XOR.
visitExpression_numeric()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric (final PlanBundleParser.Expression_numericContext p_context)
Definition at line 799 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.EQUAL, org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.execution.expression.EOperator.NOTEQUAL.
visitExpression_numeric_additive()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_additive (final PlanBundleParser.Expression_numeric_additiveContext p_context)
Definition at line 859 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.MINUS, and org.lightjason.agentspeak.language.execution.expression.EOperator.PLUS.
visitExpression_numeric_element()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_element (final PlanBundleParser.Expression_numeric_elementContext p_context)
Definition at line 925 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression_numeric_multiplicative()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_multiplicative (final PlanBundleParser.Expression_numeric_multiplicativeContext p_context)
Definition at line 882 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.DIVIDE, org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.MODULO, and org.lightjason.agentspeak.language.execution.expression.EOperator.MULTIPLY.
visitExpression_numeric_power()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_power (final PlanBundleParser.Expression_numeric_powerContext p_context)
Definition at line 912 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.POWER.
visitExpression_numeric_relation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_relation (final PlanBundleParser.Expression_numeric_relationContext p_context)
Definition at line 822 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.GREATER, org.lightjason.agentspeak.language.execution.expression.EOperator.GREATEREQUAL, org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.LESS, and org.lightjason.agentspeak.language.execution.expression.EOperator.LESSEQUAL.
visitLambda()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLambda (final PlanBundleParser.LambdaContext p_context)
Definition at line 433 of file CASTVisitorPlanBundle.java.
visitLambda_initialization()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLambda_initialization (final PlanBundleParser.Lambda_initializationContext p_context)
Definition at line 453 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitLambda_return()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLambda_return (final PlanBundleParser.Lambda_returnContext p_context)
Definition at line 465 of file CASTVisitorPlanBundle.java.
visitLiteral()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLiteral (final PlanBundleParser.LiteralContext p_context)
Definition at line 620 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CPath.from().
visitLogicalruledefinition()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLogicalruledefinition (final PlanBundleParser.LogicalruledefinitionContext p_context)
Definition at line 212 of file CASTVisitorPlanBundle.java.
visitLogicrule()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLogicrule (final PlanBundleParser.LogicruleContext p_context)
Definition at line 203 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.IDeepCopy< T >.deepcopy().
visitLogicrulePlaceHolder()
Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLogicrulePlaceHolder (final PlanBundleParser.LogicruleContext p_context) protected
Parameters
p_context logical rule context
Returns
placeholder rule
Definition at line 980 of file CASTVisitorPlanBundle.java.
visitLogicrules()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLogicrules (final PlanBundleParser.LogicrulesContext p_context)
Definition at line 180 of file CASTVisitorPlanBundle.java.
visitNumber()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitNumber (final PlanBundleParser.NumberContext p_context)
Definition at line 680 of file CASTVisitorPlanBundle.java.
visitPlan()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlan (final PlanBundleParser.PlanContext p_context)
Definition at line 218 of file CASTVisitorPlanBundle.java.
visitPlan_belief_trigger()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlan_belief_trigger (final PlanBundleParser.Plan_belief_triggerContext p_context)
Definition at line 321 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDBELIEF, org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEBELIEF, and org.lightjason.agentspeak.common.CCommon.languagestring().
visitPlan_goal_trigger()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlan_goal_trigger (final PlanBundleParser.Plan_goal_triggerContext p_context)
Definition at line 309 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL, org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEGOAL, and org.lightjason.agentspeak.common.CCommon.languagestring().
visitPlan_trigger()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlan_trigger (final PlanBundleParser.Plan_triggerContext p_context)
Definition at line 303 of file CASTVisitorPlanBundle.java.
visitPlanbundle()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlanbundle (final PlanBundleParser.PlanbundleContext p_context)
Definition at line 149 of file CASTVisitorPlanBundle.java.
visitPlandefinition()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlandefinition (final PlanBundleParser.PlandefinitionContext p_context)
Definition at line 237 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.execution.expression.IExpression.EMPTY.
visitPlans()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlans (final PlanBundleParser.PlansContext p_context)
Definition at line 169 of file CASTVisitorPlanBundle.java.
visitRepair_formula()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitRepair_formula (final PlanBundleParser.Repair_formulaContext p_context)
Definition at line 352 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitTerm()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTerm (final PlanBundleParser.TermContext p_context)
Definition at line 631 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitTermlist()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTermlist (final PlanBundleParser.TermlistContext p_context)
Definition at line 656 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
visitTernary_operation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTernary_operation (final PlanBundleParser.Ternary_operationContext p_context)
Definition at line 563 of file CASTVisitorPlanBundle.java.
visitTernary_operation_false()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTernary_operation_false (final PlanBundleParser.Ternary_operation_falseContext p_context)
Definition at line 579 of file CASTVisitorPlanBundle.java.
visitTernary_operation_true()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTernary_operation_true (final PlanBundleParser.Ternary_operation_trueContext p_context)
Definition at line 573 of file CASTVisitorPlanBundle.java.
visitTest_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTest_action (final PlanBundleParser.Test_actionContext p_context)
Definition at line 585 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CPath.from().
visitUnary_expression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitUnary_expression (final PlanBundleParser.Unary_expressionContext p_context)
Definition at line 519 of file CASTVisitorPlanBundle.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitUnification()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitUnification (final PlanBundleParser.UnificationContext p_context)
Definition at line 383 of file CASTVisitorPlanBundle.java.
visitUnification_constraint()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitUnification_constraint (final PlanBundleParser.Unification_constraintContext p_context)
Definition at line 405 of file CASTVisitorPlanBundle.java.
visitVariable()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitVariable (final PlanBundleParser.VariableContext p_context)
Definition at line 704 of file CASTVisitorPlanBundle.java.
visitVariable_evaluate()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitVariable_evaluate (final PlanBundleParser.Variable_evaluateContext p_context)
Definition at line 961 of file CASTVisitorPlanBundle.java.
visitVariableatom()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitVariableatom (final PlanBundleParser.VariableatomContext p_context)
Definition at line 710 of file CASTVisitorPlanBundle.java.
visitVariablelist()
final Object org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitVariablelist (final PlanBundleParser.VariablelistContext p_context)
Definition at line 669 of file CASTVisitorPlanBundle.java.
Member Data Documentation
LOGGER
final Logger org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.LOGGER = CCommon.logger(IASTVisitorAgent.class) static private
Definition at line 116 of file CASTVisitorPlanBundle.java.
m_actions
final Map<IPath, IAction> org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.m_actions private
Definition at line 132 of file CASTVisitorPlanBundle.java.
m_initialbeliefs
final Set<ILiteral> org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.m_initialbeliefs = new LinkedHashSet<>() private
Definition at line 120 of file CASTVisitorPlanBundle.java.
m_plans
final Set<IPlan> org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.m_plans = new HashSet<>() private
Definition at line 124 of file CASTVisitorPlanBundle.java.
m_rules
final Multimap<IPath, IRule> org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.m_rules = LinkedHashMultimap.create() private
Definition at line 128 of file CASTVisitorPlanBundle.java.