LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expression.numerical.CRelational Class Reference
org.lightjason.agentspeak.language.execution.expression.numerical.CRelational Class Reference
numerical relation expression
Public Member Functions
CRelational (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_lefthandside, @Nonnull final IExpression p_righthandside)
ctor
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.expression.IBaseBinary
final boolean equals (final Object p_object)
final int hashCode ()
final IExpression leftHandSide ()
returns the left-hand expression side
final EOperator operator ()
return expression operator
final IExpression rightHandSide ()
returns the right-hand expression side
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Static Private Member Functions
static int compare (@Nonnull final ITerm p_left, @Nonnull final ITerm p_right)
compares term types
static< T extends Number &Comparable< T > int comparenumber (@Nonnull final T p_left, @Nonnull final T p_right)
compare method for any number type
static< T extends Comparable< T > int compareobject (@Nonnull final T p_left, @Nonnull final T p_right)
compare method for any object type
static< N, M > N map (@Nonnull final M p_value)
type mapping method
Static Private Attributes
static final long serialVersionUID = -5844609255203908714L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.execution.expression.IExpression
IExpression EMPTY
empty expression, is always true
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.expression.IBaseBinary
IBaseBinary (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_lefthandside, @Nonnull final IExpression p_righthandside)
ctor
final boolean executearguments (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument) throws IllegalArgumentException
execute expression arguments
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.expression.IBaseBinary
final IExpression m_lefthandside
left-hand-side argument
final EOperator m_operator
expression operator
final IExpression m_righthandside
right-hand-side argument
Detailed Description
Definition at line 45 of file CRelational.java.
Constructor & Destructor Documentation
CRelational()
org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.CRelational (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_lefthandside, @Nonnull final IExpression p_righthandside)
Parameters
p_operator operator
p_lefthandside left-hand-side argument
p_righthandside right-hand-side
Definition at line 59 of file CRelational.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.isRelational(), org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.execution.expression.IBaseBinary.m_operator.
Member Function Documentation
compare()
static int org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.compare (@Nonnull final ITerm p_left, @Nonnull final ITerm p_right) static private
Parameters
p_left left argument
p_right right argument
Returns
default compare values [-1,1]
Definition at line 114 of file CRelational.java.
References org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.comparenumber(), org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.compareobject(), org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.map(), and org.lightjason.agentspeak.language.CCommon.rawvalueAssignableTo().
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.execute().
comparenumber()
static <T extends Number & Comparable<T> int org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.comparenumber (@Nonnull final T p_left, @Nonnull final T p_right) static private
Parameters
p_left left argument
p_right right argument
Returns
default compare values [-1,1]
Template Parameters
T number type
Definition at line 131 of file CRelational.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.compare().
compareobject()
static <T extends Comparable<T> int org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.compareobject (@Nonnull final T p_left, @Nonnull final T p_right) static private
Parameters
p_left left argument
p_right right argument
Returns
default compare values [-1,1]
Template Parameters
T object type
Definition at line 146 of file CRelational.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.compare().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 69 of file CRelational.java.
References org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.compare(), org.lightjason.agentspeak.language.execution.expression.IBaseBinary.executearguments(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), and org.lightjason.agentspeak.language.execution.expression.IBaseBinary.m_operator.
map()
static <N, M> N org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.map (@Nonnull final M p_value) static private
Parameters
p_value value
Template Parameters
N return type
M value type
Returns
casted value
Definition at line 164 of file CRelational.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.compare().
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.serialVersionUID = -5844609255203908714L static private
Definition at line 50 of file CRelational.java.