LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution > Class Template Reference
org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution > Class Template Reference
assignment action of a multi-variable list
Public Member Functions
CMultiAssignment (@Nonnull final List< IVariable<?>> p_lefthand, @Nonnull final M p_righthand)
ctor
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >
final T getValue ()
returns the value of the action
final boolean isValueAssignableTo (final Class<?> p_class)
checkes assinable of the value
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final M m_righthand
right-hand argument
Static Private Attributes
static final long serialVersionUID = -6123210880356077509L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >
IBaseExecution (@Nullable final T p_value)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >
final T m_value
data
Detailed Description
Definition at line 48 of file CMultiAssignment.java.
Constructor & Destructor Documentation
CMultiAssignment()
org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.CMultiAssignment (@Nonnull final List< IVariable<?>> p_lefthand, @Nonnull final M p_righthand)
Parameters
p_lefthand left-hand variable list
p_righthand right-hand argument
Definition at line 65 of file CMultiAssignment.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.equals (final Object p_object)
Definition at line 105 of file CMultiAssignment.java.
References org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.hashCode().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Definition at line 73 of file CMultiAssignment.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >.m_value, and org.lightjason.agentspeak.language.variable.IVariable< T >.set().
hashCode()
final int org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.hashCode ()
Definition at line 99 of file CMultiAssignment.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >.m_value.
Referenced by org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.equals().
toString()
final String org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.toString ()
Definition at line 111 of file CMultiAssignment.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >.m_value.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.variables ()
Definition at line 118 of file CMultiAssignment.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >.m_value.
Member Data Documentation
m_righthand
final M org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.m_righthand private
Definition at line 57 of file CMultiAssignment.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.serialVersionUID = -6123210880356077509L static private
Definition at line 53 of file CMultiAssignment.java.