LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm > Class Template Reference
org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm > Class Template Reference
deconstruct assignment
Public Member Functions
CDeconstruct (@Nonnull final List< IVariable<?>> p_lefthand, @Nonnull final M p_righthand)
ctor
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >
final T getValue ()
returns the value of the action
final boolean isValueAssignableTo (final Class<?> p_class)
checkes assinable of the value
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Member Functions
void set (@Nonnull final List< ITerm > p_assignment, @Nonnull final ILiteral p_term)
sets the values
Private Attributes
final M m_righthand
right-hand argument (literal)
Static Private Attributes
static final long serialVersionUID = 6234582899813921890L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >
IBaseExecution (@Nullable final T p_value)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >
final T m_value
data
Detailed Description
Definition at line 46 of file CDeconstruct.java.
Constructor & Destructor Documentation
CDeconstruct()
org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.CDeconstruct (@Nonnull final List< IVariable<?>> p_lefthand, @Nonnull final M p_righthand)
Parameters
p_lefthand left-hand variable list
p_righthand right-hand argument
Definition at line 64 of file CDeconstruct.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.equals (final Object p_object)
Definition at line 86 of file CDeconstruct.java.
References org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.hashCode().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Definition at line 72 of file CDeconstruct.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), and org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >.m_value.
hashCode()
final int org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.hashCode ()
Definition at line 80 of file CDeconstruct.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >.m_value.
Referenced by org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.equals().
set()
void org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.set (@Nonnull final List< ITerm > p_assignment, @Nonnull final ILiteral p_term) private
Parameters
p_assignment variable list
p_term term
Definition at line 110 of file CDeconstruct.java.
References org.lightjason.agentspeak.language.variable.IVariable< T >.set().
toString()
final String org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.toString ()
Definition at line 92 of file CDeconstruct.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >.m_value.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.variables ()
Definition at line 99 of file CDeconstruct.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< List< IVariable<?> > >.m_value.
Member Data Documentation
m_righthand
final M org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.m_righthand private
Definition at line 55 of file CDeconstruct.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.serialVersionUID = 6234582899813921890L static private
Definition at line 51 of file CDeconstruct.java.