LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase Class Reference
org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase Class Reference
wrapper beliefbase
Public Member Functions
final ILiteral add (@Nonnull final ILiteral p_literal)
adds a literal
final IView add (@Nonnull final IView p_view)
adds a view
final IBeliefbase clear ()
clears all elements
final boolean containsLiteral (@Nonnull final String p_key)
contains a multi-element
boolean containsView (@Nonnull final String p_key)
contains a single-element
final IView create (@Nonnull final String p_name)
returns a new view of the belief base
final IView create (@Nonnull final String p_name, @Nullable final IView p_parent)
returns a new view of the belief base
final boolean empty ()
checks if the structure empty
final Collection< ILiteral > literal (@Nonnull final String p_key)
returns a literal by the name
final ILiteral remove (@Nonnull final ILiteral p_literal)
removes a literal
final IView remove (@Nonnull final IView p_view)
removes a view
final int size ()
returns the size of literals
final Stream< ILiteral > streamLiteral ()
returns a stream over all literals
final Stream< IView > streamView ()
returns a stream over all views
final Stream< ITrigger > trigger (@Nonnull final IView p_view)
returns all trigger of the beliefbase
final IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
final IView view (@Nonnull final String p_key)
returns a view element
final IView viewOrDefault (@Nonnull final String p_key, @Nullable final IView p_default)
returns a view element
Private Member Functions
Stream< ITerm > toterm (final Object p_value)
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.beliefbase.IBeliefbase
IBeliefbase EMPY
empty beliefbase
Detailed Description
Definition at line 413 of file CViewMap.java.
Member Function Documentation
add() [1/2]
final ILiteral org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.add (@Nonnull final ILiteral p_literal)
Parameters
p_literal literal without path
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 483 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_addliteralconsumer, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_literaltokey.
add() [2/2]
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.add (@Nonnull final IView p_view)
Parameters
p_view view
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 491 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_addviewconsumer, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_keytoliteral.
clear()
final IBeliefbase org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.clear ()
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 475 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data.
containsLiteral()
final boolean org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.containsLiteral (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 514 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_literaltokey.
containsView()
boolean org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.containsView (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 521 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_literaltokey.
create() [1/2]
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.create (@Nonnull final String p_name)
Parameters
p_name name of the view
Returns
created view
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 558 of file CViewMap.java.
create() [2/2]
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.create (@Nonnull final String p_name, @Nullable final IView p_parent)
Parameters
p_name name of the view
p_parent parent view
Returns
view
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 565 of file CViewMap.java.
empty()
final boolean org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.empty ()
Returns
empty boolean
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 417 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data.
literal()
final Collection<ILiteral> org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.literal (@Nonnull final String p_key)
Parameters
p_key name of the literal
Returns
collection of pairs with negated and literal
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 536 of file CViewMap.java.
References org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_literaltokey.
remove() [1/2]
final ILiteral org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.remove (@Nonnull final ILiteral p_literal)
Parameters
p_literal without path
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 499 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_literaltokey, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_removeliteralconsumer.
remove() [2/2]
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.remove (@Nonnull final IView p_view)
Parameters
p_view view
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 507 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_literaltokey, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_removeviewconsumer.
size()
final int org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.size ()
Returns
size
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 424 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.CViewMap(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data.
streamLiteral()
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.streamLiteral ()
Returns
literal stream
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 454 of file CViewMap.java.
References org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_keytoliteral, and org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.toterm().
streamView()
final Stream<IView> org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.streamView ()
Returns
view stream
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 465 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.CViewMap(), org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_keytoliteral.
toterm()
Stream<ITerm> org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.toterm (final Object p_value) private
Definition at line 571 of file CViewMap.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_keytoliteral.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.streamLiteral().
trigger()
final Stream<ITrigger> org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.trigger (@Nonnull final IView p_view)
Parameters
p_view mask for events
Returns
set with trigger events
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 446 of file CViewMap.java.
update()
final IAgent<?> org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.update (@Nonnull final IAgent<?> p_agent)
Parameters
p_agent agent which runs the update call
Returns
agent
Warning
call update on a storage and on all storage-view, if exists different views which are point to the same storage, the update is called more than once, so the storage must limit the number of update calls
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 439 of file CViewMap.java.
view()
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.view (@Nonnull final String p_key)
Parameters
p_key name of the view
Returns
view or null
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 529 of file CViewMap.java.
viewOrDefault()
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.viewOrDefault (@Nonnull final String p_key, @Nullable final IView p_default)
Parameters
p_key name of the view
p_default view
Returns
view or default element
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 551 of file CViewMap.java.