LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.math.blas.EType Enum Reference
org.lightjason.agentspeak.action.builtin.math.blas.EType Enum Reference
blas types
Static Public Member Functions
static boolean exists (final String p_name)
check method to check if a enum value with a name exists
static EType from (final String p_name)
additional factory
Public Attributes
SPARSE
Static Private Attributes
static final Set< String > NAMES = Collections.unmodifiableSet(Arrays.stream(EType.values()).map(i -> i.name()).collect(Collectors.toSet()))
set with names
Detailed Description
Definition at line 37 of file EType.java.
Member Function Documentation
exists()
static boolean org.lightjason.agentspeak.action.builtin.math.blas.EType.exists (final String p_name) static
Parameters
p_name name as string
Returns
boolean if enum value exists
Definition at line 64 of file EType.java.
Referenced by org.lightjason.agentspeak.action.builtin.math.blas.vector.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CFromList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CParse.execute(), and org.lightjason.agentspeak.action.builtin.math.blas.matrix.CParse.execute().
from()
static EType org.lightjason.agentspeak.action.builtin.math.blas.EType.from (final String p_name) static
Parameters
p_name name as string
Returns
enum
Definition at line 53 of file EType.java.
Referenced by org.lightjason.agentspeak.action.builtin.math.blas.matrix.CIdentity.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDiagonal.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRowSum.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumnSum.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CFromList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CParse.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CToBlas.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToBlas.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CParse.execute(), and org.lightjason.agentspeak.action.builtin.graph.CAdjacencyMatrix.execute().
Member Data Documentation
NAMES
static final Set<String> org.lightjason.agentspeak.action.builtin.math.blas.EType.NAMES = Collections.unmodifiableSet(Arrays.stream(EType.values()).map(i -> i.name()).collect(Collectors.toSet())) static private
Definition at line 45 of file EType.java.
SPARSE
org.lightjason.agentspeak.action.builtin.math.blas.EType.SPARSE
Definition at line 39 of file EType.java.
Referenced by org.lightjason.agentspeak.action.builtin.math.blas.matrix.CIdentity.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDiagonal.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CToBlas.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToBlas.execute(), and org.lightjason.agentspeak.action.builtin.graph.CAdjacencyMatrix.execute().