LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator Enum Reference
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator Enum Reference
number generator
Public Member Functions
final RandomGenerator get ()
returns a number generator
Static Public Member Functions
static EGenerator from (@Nonnull final String p_value)
additional factory
Public Attributes
INTERNAL
ISAAC
MERSENNETWISTER
SYNCHRONIZEDINTERNAL
SYNCHRONIZEDISAAC
SYNCHRONIZEDMERSENNETWISTER
SYNCHRONIZEDWELL1024A
SYNCHRONIZEDWELL19937A
SYNCHRONIZEDWELL19937C
SYNCHRONIZEDWELL4449A
SYNCHRONIZEDWELL512A
WELL1024A
WELL19937A
WELL19937C
WELL44497B
WELL4449A
WELL512A
Detailed Description
Definition at line 374 of file CCreateDistribution.java.
Member Function Documentation
from()
static EGenerator org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.from (@Nonnull final String p_value) static
Parameters
p_value string
Returns
enum
Definition at line 402 of file CCreateDistribution.java.
Referenced by org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute().
get()
final RandomGenerator org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.get ()
Returns
generator
Definition at line 413 of file CCreateDistribution.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute().
Member Data Documentation
INTERNAL
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.INTERNAL
Definition at line 380 of file CCreateDistribution.java.
ISAAC
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.ISAAC
Definition at line 378 of file CCreateDistribution.java.
MERSENNETWISTER
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.MERSENNETWISTER
Definition at line 376 of file CCreateDistribution.java.
Referenced by org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute().
SYNCHRONIZEDINTERNAL
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.SYNCHRONIZEDINTERNAL
Definition at line 381 of file CCreateDistribution.java.
SYNCHRONIZEDISAAC
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.SYNCHRONIZEDISAAC
Definition at line 379 of file CCreateDistribution.java.
SYNCHRONIZEDMERSENNETWISTER
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.SYNCHRONIZEDMERSENNETWISTER
Definition at line 377 of file CCreateDistribution.java.
SYNCHRONIZEDWELL1024A
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.SYNCHRONIZEDWELL1024A
Definition at line 385 of file CCreateDistribution.java.
SYNCHRONIZEDWELL19937A
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.SYNCHRONIZEDWELL19937A
Definition at line 387 of file CCreateDistribution.java.
SYNCHRONIZEDWELL19937C
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.SYNCHRONIZEDWELL19937C
Definition at line 389 of file CCreateDistribution.java.
SYNCHRONIZEDWELL4449A
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.SYNCHRONIZEDWELL4449A
Definition at line 391 of file CCreateDistribution.java.
SYNCHRONIZEDWELL512A
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.SYNCHRONIZEDWELL512A
Definition at line 383 of file CCreateDistribution.java.
WELL1024A
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.WELL1024A
Definition at line 384 of file CCreateDistribution.java.
WELL19937A
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.WELL19937A
Definition at line 386 of file CCreateDistribution.java.
WELL19937C
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.WELL19937C
Definition at line 388 of file CCreateDistribution.java.
WELL44497B
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.WELL44497B
Definition at line 392 of file CCreateDistribution.java.
WELL4449A
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.WELL4449A
Definition at line 390 of file CCreateDistribution.java.
WELL512A
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.WELL512A
Definition at line 382 of file CCreateDistribution.java.