LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.TestCAgentExecution.CLog Class Reference
org.lightjason.agentspeak.agent.TestCAgentExecution.CLog Class Reference
log action
Public Member Functions
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int minimalArgumentNumber ()
minimum number of arguments
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Static Private Attributes
static final long serialVersionUID = 4536335097194230205L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Static Protected Attributes inherited from org.lightjason.agentspeak.action.IBaseAction
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Detailed Description
Definition at line 277 of file TestCAgentExecution.java.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.TestCAgentExecution.CLog.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 300 of file TestCAgentExecution.java.
References org.lightjason.agentspeak.agent.TestCAgentExecution.CAgent.cycle(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
minimalArgumentNumber()
final int org.lightjason.agentspeak.agent.TestCAgentExecution.CLog.minimalArgumentNumber ()
Returns
number of minimal arguments
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 293 of file TestCAgentExecution.java.
name()
final IPath org.lightjason.agentspeak.agent.TestCAgentExecution.CLog.name ()
Returns
path (literal functor)
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 286 of file TestCAgentExecution.java.
References org.lightjason.agentspeak.common.CPath.from().
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.agent.TestCAgentExecution.CLog.serialVersionUID = 4536335097194230205L static private
Definition at line 282 of file TestCAgentExecution.java.