LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMath Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMath Class Reference
test math functions
Public Member Functions
final void aggregationvalueaction (final Triple< List< ITerm >, Class<? extends IAction >, Function< Stream< Number >, ?>> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
test all aggregation-value actions
final void binomial ()
test binomial
final void factorial ()
test factorial
final void geometricmean ()
test geometricmean
final void harmonicmean ()
test harmonicmean
final void hypot ()
test hypot
final void maxIndex ()
test max index
final void minIndex ()
test min index
final void pow ()
test power
final void primefactors ()
test primefactors
final void sigmoid ()
test sigmoid
final void singlevalueaction (final Triple< List< ITerm >, Class<? extends IAction >, Function< Number, ?>> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
test all single-value actions
final void stirling ()
test stirling
Static Public Member Functions
static Object [] aggregationvaluegenerate ()
data provider generator for aggregation-value tests
static Object [] singlevaluegenerate ()
data provider generator for single-value tests
Static Private Member Functions
static Stream< Object > aggregationvaluetestcase (final Stream< Number > p_input, final Stream< Class<? extends IAction >> p_class, final Function< Stream< Number >, ?>... p_result)
create test case
static Stream< Object > singlevaluetestcase (final Stream< Number > p_input, final Stream< Class<? extends IAction >> p_class, final Function< Number, ?>... p_result)
create test case
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 94 of file TestCActionMath.java.
Member Function Documentation
aggregationvalueaction()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.aggregationvalueaction (final Triple< List< ITerm >, Class<? extends IAction >, Function< Stream< Number >, ?>> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
Parameters
p_input test data
Exceptions
IllegalAccessException is thrwon on instantiation error
InstantiationException is thrwon on instantiation error
NoSuchMethodException is thrwon on instantiation error
InvocationTargetException is thrwon on instantiation error
Definition at line 259 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN.
aggregationvaluegenerate()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionMath.aggregationvaluegenerate () static
Returns
data
Definition at line 177 of file TestCActionMath.java.
aggregationvaluetestcase()
static Stream<Object> org.lightjason.agentspeak.action.builtin.TestCActionMath.aggregationvaluetestcase (final Stream< Number > p_input, final Stream< Class<? extends IAction >> p_class, final Function< Stream< Number >, ?>... p_result) static private
Parameters
p_input input data
p_class action class
p_result result function
Returns
test-case data
Definition at line 234 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
binomial()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.binomial ()
Definition at line 310 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CBinomial.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
factorial()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.factorial ()
Definition at line 329 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CFactorial.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
geometricmean()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.geometricmean ()
Definition at line 429 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CGeometricMean.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
harmonicmean()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.harmonicmean ()
Definition at line 448 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CHarmonicMean.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
hypot()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.hypot ()
Definition at line 466 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CHypot.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
maxIndex()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.maxIndex ()
Definition at line 493 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CMaxIndex.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
minIndex()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.minIndex ()
Definition at line 511 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CMinIndex.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
pow()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.pow ()
Definition at line 408 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CPow.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
primefactors()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.primefactors ()
Definition at line 351 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CPrimeFactors.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
sigmoid()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.sigmoid ()
Definition at line 370 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CSigmoid.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
singlevalueaction()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.singlevalueaction (final Triple< List< ITerm >, Class<? extends IAction >, Function< Number, ?>> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
Parameters
p_input test data
Exceptions
IllegalAccessException is thrwon on instantiation error
InstantiationException is thrwon on instantiation error
NoSuchMethodException is thrwon on instantiation error
InvocationTargetException is thrwon on instantiation error
Definition at line 287 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.ITerm.raw().
singlevaluegenerate()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionMath.singlevaluegenerate () static
Returns
data
Definition at line 102 of file TestCActionMath.java.
singlevaluetestcase()
static Stream<Object> org.lightjason.agentspeak.action.builtin.TestCActionMath.singlevaluetestcase (final Stream< Number > p_input, final Stream< Class<? extends IAction >> p_class, final Function< Number, ?>... p_result) static private
Parameters
p_input input data
p_class action class
p_result result function
Returns
test-case data
Definition at line 211 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
stirling()
final void org.lightjason.agentspeak.action.builtin.TestCActionMath.stirling ()
Definition at line 390 of file TestCActionMath.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.CStirling.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().