LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm Enum Reference
org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm Enum Reference
enum with encrypting types
Public Member Functions
EAlgorithm (@Nonnull final String p_cipher, @Nonnull final String p_key)
ctor
final Pair< Key, Key > generateKey () throws NoSuchAlgorithmException
generates a key
final Cipher getDecryptCipher (@Nonnull final Key p_key) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException
final Cipher getEncryptCipher (@Nonnull final Key p_key) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException
returns encrypt cipher
Static Public Member Functions
static EAlgorithm from (@Nonnull final String p_value)
additional factory
Public Attributes
AES =("AES/ECB/PKCS5Padding", "AES")
DES =("DES/ECB/PKCS5Padding", "DES")
RSA =("RSA/ECB/PKCS1Padding", "RSA")
Private Attributes
final String m_cipher
chipher name
final String m_key
key name
Detailed Description
Definition at line 46 of file EAlgorithm.java.
Constructor & Destructor Documentation
EAlgorithm()
org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.EAlgorithm (@Nonnull final String p_cipher, @Nonnull final String p_key)
Parameters
p_cipher chipher name
p_key name of the key
Definition at line 67 of file EAlgorithm.java.
Member Function Documentation
from()
static EAlgorithm org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.from (@Nonnull final String p_value) static
Parameters
p_value string value
Returns
enum
Definition at line 141 of file EAlgorithm.java.
Referenced by org.lightjason.agentspeak.action.builtin.crypto.CCreateKey.execute(), org.lightjason.agentspeak.action.builtin.crypto.CDecrypt.execute(), and org.lightjason.agentspeak.action.builtin.crypto.CEncrypt.execute().
generateKey()
final Pair<Key, Key> org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.generateKey () throws NoSuchAlgorithmException
Returns
key pair object (public key / private key or null)
Exceptions
NoSuchAlgorithmException on algorithm error
Definition at line 81 of file EAlgorithm.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
getDecryptCipher()
final Cipher org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.getDecryptCipher (@Nonnull final Key p_key) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException
returns decrypt cipher
Parameters
p_key key object
Returns
cipher
Exceptions
NoSuchPaddingException on padding error
NoSuchAlgorithmException on algorithm error
InvalidKeyException on key invalid
Definition at line 127 of file EAlgorithm.java.
getEncryptCipher()
final Cipher org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.getEncryptCipher (@Nonnull final Key p_key) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException
Parameters
p_key key object
Returns
cipher
Exceptions
NoSuchPaddingException on padding error
NoSuchAlgorithmException on algorithm error
InvalidKeyException on key invalid
Definition at line 109 of file EAlgorithm.java.
Member Data Documentation
AES
org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.AES =("AES/ECB/PKCS5Padding", "AES")
Definition at line 48 of file EAlgorithm.java.
DES
org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.DES =("DES/ECB/PKCS5Padding", "DES")
Definition at line 49 of file EAlgorithm.java.
m_cipher
final String org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.m_cipher private
Definition at line 55 of file EAlgorithm.java.
m_key
final String org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.m_key private
Definition at line 59 of file EAlgorithm.java.
RSA
org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.RSA =("RSA/ECB/PKCS1Padding", "RSA")
Definition at line 50 of file EAlgorithm.java.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionCrypto.decryptexecutionerror().