LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.TestCViewMap Class Reference
org.lightjason.agentspeak.beliefbase.TestCViewMap Class Reference
test of map-view
Classes
class CAgent
agent class
class CEmptyPrint
empty print action
class CTestResult
test action
Public Member Functions
final void containsliteral ()
test contains literal
final void containsview ()
test contains view
final void inagent () throws Exception
test in-agent definition
final void initialize () throws IOException
initialize
final void stream ()
test stream
Static Package Functions
[static initializer]
Private Attributes
final Set< IAction > m_actions
actions
Map< String, Object > m_data
map reference
List< Pair< Boolean, String > > m_testlog
list with successful plans
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 71 of file TestCViewMap.java.
Member Function Documentation
[static initializer]()
org.lightjason.agentspeak.beliefbase.TestCViewMap.[static initializer] () static package
containsliteral()
final void org.lightjason.agentspeak.beliefbase.TestCViewMap.containsliteral ()
Definition at line 140 of file TestCViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.IView.containsLiteral(), org.lightjason.agentspeak.common.CPath.from(), and org.lightjason.agentspeak.beliefbase.TestCViewMap.m_data.
containsview()
final void org.lightjason.agentspeak.beliefbase.TestCViewMap.containsview ()
Definition at line 154 of file TestCViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.IView.containsView(), org.lightjason.agentspeak.common.CPath.from(), and org.lightjason.agentspeak.beliefbase.TestCViewMap.m_data.
inagent()
final void org.lightjason.agentspeak.beliefbase.TestCViewMap.inagent () throws Exception
Exceptions
Exception is thrown on execution error
Definition at line 169 of file TestCViewMap.java.
References org.lightjason.agentspeak.beliefbase.TestCViewMap.CAgent.CAgentGenerator.generatesingle(), org.lightjason.agentspeak.beliefbase.TestCViewMap.m_data, and org.lightjason.agentspeak.beliefbase.TestCViewMap.m_testlog.
initialize()
final void org.lightjason.agentspeak.beliefbase.TestCViewMap.initialize () throws IOException
Exceptions
IOException is thrown on parsing error
Definition at line 104 of file TestCViewMap.java.
stream()
final void org.lightjason.agentspeak.beliefbase.TestCViewMap.stream ()
Definition at line 117 of file TestCViewMap.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), and org.lightjason.agentspeak.beliefbase.TestCViewMap.m_data.
Member Data Documentation
m_actions
final Set<IAction> org.lightjason.agentspeak.beliefbase.TestCViewMap.m_actions private
Initial value:
= Stream.concat(
        PRINTENABLE
        ? Stream.of( new CTestResult() )
        : Stream.of( new CTestResult(), new CEmptyPrint() ),
        CCommon.actionsFromPackage()
    ).collect( Collectors.toSet() )
Definition at line 76 of file TestCViewMap.java.
m_data
Map<String, Object> org.lightjason.agentspeak.beliefbase.TestCViewMap.m_data private
Definition at line 85 of file TestCViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.TestCViewMap.containsliteral(), org.lightjason.agentspeak.beliefbase.TestCViewMap.containsview(), org.lightjason.agentspeak.beliefbase.TestCViewMap.inagent(), and org.lightjason.agentspeak.beliefbase.TestCViewMap.stream().
m_testlog
List<Pair<Boolean, String> > org.lightjason.agentspeak.beliefbase.TestCViewMap.m_testlog private
Definition at line 89 of file TestCViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.TestCViewMap.CTestResult.execute(), and org.lightjason.agentspeak.beliefbase.TestCViewMap.inagent().