LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.IBaseBeliefbase Class Reference
org.lightjason.agentspeak.beliefbase.IBaseBeliefbase Class Reference abstract
default behaviour of a beliefbase
Public Member Functions
ILiteral add (@Nonnull final ILiteral p_literal)
adds a literal
final IView create (@Nonnull final String p_name)
returns a new view of the belief base
final IView create (@Nonnull final String p_name, final IView p_parent)
ILiteral remove (@Nonnull final ILiteral p_literal)
removes a literal
Stream< ITrigger > trigger (@Nonnull final IView p_view)
returns all trigger of the beliefbase
IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
Public Member Functions inherited from org.lightjason.agentspeak.beliefbase.IBeliefbase
IView add (@Nonnull final IView p_view)
adds a view
IBeliefbase clear ()
clears all elements
boolean containsLiteral (@Nonnull final String p_key)
contains a multi-element
boolean containsView (@Nonnull final String p_key)
contains a single-element
IView create (@Nonnull final String p_name, @Nullable final IView p_parent)
returns a new view of the belief base
Collection< ILiteral > literal (@Nonnull final String p_key)
returns a literal by the name
IView remove (@Nonnull final IView p_view)
removes a view
Stream< ILiteral > streamLiteral ()
returns a stream over all literals
Stream< IView > streamView ()
returns a stream over all views
IView view (@Nonnull final String p_key)
returns a view element
IView viewOrDefault (@Nonnull final String p_key, @Nullable final IView p_default)
returns a view element
Public Member Functions inherited from org.lightjason.agentspeak.beliefbase.IStructure
boolean empty ()
checks if the structure empty
int size ()
returns the size of literals
Protected Member Functions
final Stream< ITrigger > cleartrigger (final IView p_view)
copy of all trigger values
ILiteral event (final ITrigger.EType p_event, final ILiteral p_literal)
push an event and literal to the event map
IView eventreference (final IView p_view)
adds a view to the event referencing structure
final IView internalremove (final IView p_view)
removes the interal view references
Private Attributes
final Multimap< IView, ITrigger > m_events = Multimaps.synchronizedSetMultimap(HashMultimap.create())
map with events for a mask
final ReferenceQueue< IView > m_maskreference = new ReferenceQueue<>()
weak reference queue of all masks to avoid memory-leaks of belief events
final Set< IView > m_views = Collections.synchronizedSet(new HashSet<>())
set with all current views
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.beliefbase.IBeliefbase
IBeliefbase EMPY
empty beliefbase
Detailed Description
Template Parameters
T agent type
Todo:
check reference counting on delete views
See also
http://docs.oracle.com/javase/8/docs/api/java/lang/ref/PhantomReference.html
http://docs.oracle.com/javase/8/docs/api/java/lang/ref/WeakReference.html
https://community.oracle.com/blogs/enicholas/2006/05/04/understanding-weak-references
Definition at line 58 of file IBaseBeliefbase.java.
Member Function Documentation
add()
ILiteral org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.add (@Nonnull final ILiteral p_literal)
Parameters
p_literal literal without path
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 91 of file IBaseBeliefbase.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDBELIEF.
cleartrigger()
final Stream<ITrigger> org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.cleartrigger (final IView p_view) protected
Parameters
p_view trigger of this view
Returns
set with trigger values
Definition at line 174 of file IBaseBeliefbase.java.
create() [1/2]
final IView org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.create (@Nonnull final String p_name)
Parameters
p_name name of the view
Returns
created view
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 77 of file IBaseBeliefbase.java.
Referenced by org.lightjason.agentspeak.beliefbase.TestCView.CGenerator.apply(), org.lightjason.agentspeak.consistency.TestCMetric.CGenerator.apply(), org.lightjason.agentspeak.configuration.CDefaultAgentConfiguration< T extends IAgent<?>.beliefbase(), org.lightjason.agentspeak.beliefbase.TestCView.testManual(), and org.lightjason.agentspeak.beliefbase.TestCView.testTree().
create() [2/2]
final IView org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.create (@Nonnull final String p_name, final IView p_parent)
Definition at line 84 of file IBaseBeliefbase.java.
event()
ILiteral org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.event (final ITrigger.EType p_event, final ILiteral p_literal) protected
Parameters
p_event event
p_literal literal
Definition at line 135 of file IBaseBeliefbase.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from().
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.clear().
eventreference()
IView org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.eventreference (final IView p_view) protected
Parameters
p_view view
Returns
input view
Definition at line 161 of file IBaseBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.view.IView.add().
internalremove()
final IView org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.internalremove (final IView p_view) protected
Parameters
p_view view to remove
Returns
view
Definition at line 148 of file IBaseBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.view.IView.remove().
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.remove().
remove()
ILiteral org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.remove (@Nonnull final ILiteral p_literal)
Parameters
p_literal without path
Returns
beliefbase reference
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 98 of file IBaseBeliefbase.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEBELIEF.
trigger()
Stream<ITrigger> org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.trigger (@Nonnull final IView p_view)
Parameters
p_view mask for events
Returns
set with trigger events
Implements org.lightjason.agentspeak.beliefbase.IBeliefbase.
Definition at line 123 of file IBaseBeliefbase.java.
update()
IAgent<?> org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.update (@Nonnull final IAgent<?> p_agent)
Parameters
p_agent agent which runs the update call
Returns
agent
Warning
call update on a storage and on all storage-view, if exists different views which are point to the same storage, the update is called more than once, so the storage must limit the number of update calls
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 105 of file IBaseBeliefbase.java.
References org.lightjason.agentspeak.beliefbase.view.IView.remove().
Member Data Documentation
m_events
final Multimap<IView, ITrigger> org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.m_events = Multimaps.synchronizedSetMultimap(HashMultimap.create()) private
Definition at line 64 of file IBaseBeliefbase.java.
m_maskreference
final ReferenceQueue<IView> org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.m_maskreference = new ReferenceQueue<>() private
Definition at line 72 of file IBaseBeliefbase.java.
m_views
final Set<IView> org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.m_views = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 68 of file IBaseBeliefbase.java.