LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expression.IBaseBinary Class Reference
org.lightjason.agentspeak.language.execution.expression.IBaseBinary Class Reference abstract
binary expression
Public Member Functions
final boolean equals (final Object p_object)
final int hashCode ()
final IExpression leftHandSide ()
returns the left-hand expression side
final EOperator operator ()
return expression operator
final IExpression rightHandSide ()
returns the right-hand expression side
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.IExecution
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Protected Member Functions
IBaseBinary (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_lefthandside, @Nonnull final IExpression p_righthandside)
ctor
final boolean executearguments (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument) throws IllegalArgumentException
execute expression arguments
Protected Attributes
final IExpression m_lefthandside
left-hand-side argument
final EOperator m_operator
expression operator
final IExpression m_righthandside
right-hand-side argument
Static Private Attributes
static final long serialVersionUID = 1630029294068548691L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.execution.expression.IExpression
IExpression EMPTY
empty expression, is always true
Detailed Description
Definition at line 42 of file IBaseBinary.java.
Constructor & Destructor Documentation
IBaseBinary()
org.lightjason.agentspeak.language.execution.expression.IBaseBinary.IBaseBinary (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_lefthandside, @Nonnull final IExpression p_righthandside) protected
Parameters
p_operator operator
p_lefthandside left-hand-side argument
p_righthandside right-hand-side
Definition at line 70 of file IBaseBinary.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.expression.IBaseBinary.equals (final Object p_object)
Definition at line 137 of file IBaseBinary.java.
References org.lightjason.agentspeak.language.execution.expression.IBaseBinary.hashCode().
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CComparable.checkequal().
executearguments()
final boolean org.lightjason.agentspeak.language.execution.expression.IBaseBinary.executearguments (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument) throws IllegalArgumentException protected
Parameters
p_parallel parallel execution
p_context execution context
p_argument returning arguments of the expressions
Returns
boolean of successfully execution
Exceptions
IllegalArgumentException is thrown if more than two arguments are returned
Definition at line 89 of file IBaseBinary.java.
References org.lightjason.agentspeak.language.execution.IExecution.execute(), and org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.language.execution.expression.logical.CBinary.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CPower.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CComparable.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CMultiplicative.execute(), and org.lightjason.agentspeak.language.execution.expression.numerical.CAdditive.execute().
hashCode()
final int org.lightjason.agentspeak.language.execution.expression.IBaseBinary.hashCode ()
Definition at line 131 of file IBaseBinary.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.IBaseBinary.equals().
leftHandSide()
final IExpression org.lightjason.agentspeak.language.execution.expression.IBaseBinary.leftHandSide ()
Returns
left-hand-side
Implements org.lightjason.agentspeak.language.execution.expression.IBinaryExpression.
Definition at line 111 of file IBaseBinary.java.
References org.lightjason.agentspeak.language.execution.expression.IBaseBinary.m_lefthandside.
operator()
final EOperator org.lightjason.agentspeak.language.execution.expression.IBaseBinary.operator ()
Returns
operator
Implements org.lightjason.agentspeak.language.execution.expression.IBinaryExpression.
Definition at line 125 of file IBaseBinary.java.
References org.lightjason.agentspeak.language.execution.expression.IBaseBinary.m_operator.
rightHandSide()
final IExpression org.lightjason.agentspeak.language.execution.expression.IBaseBinary.rightHandSide ()
Returns
right-hand-side
Implements org.lightjason.agentspeak.language.execution.expression.IBinaryExpression.
Definition at line 118 of file IBaseBinary.java.
References org.lightjason.agentspeak.language.execution.expression.IBaseBinary.m_righthandside.
toString()
final String org.lightjason.agentspeak.language.execution.expression.IBaseBinary.toString ()
Definition at line 143 of file IBaseBinary.java.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.expression.IBaseBinary.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 150 of file IBaseBinary.java.
References org.lightjason.agentspeak.language.execution.IExecution.variables().
Member Data Documentation
m_lefthandside
final IExpression org.lightjason.agentspeak.language.execution.expression.IBaseBinary.m_lefthandside protected
Definition at line 55 of file IBaseBinary.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.IBaseBinary.leftHandSide().
m_operator
final EOperator org.lightjason.agentspeak.language.execution.expression.IBaseBinary.m_operator protected
Definition at line 51 of file IBaseBinary.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CAdditive.CAdditive(), org.lightjason.agentspeak.language.execution.expression.logical.CBinary.CBinary(), org.lightjason.agentspeak.language.execution.expression.numerical.CComparable.CComparable(), org.lightjason.agentspeak.language.execution.expression.numerical.CMultiplicative.CMultiplicative(), org.lightjason.agentspeak.language.execution.expression.numerical.CPower.CPower(), org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.CRelational(), org.lightjason.agentspeak.language.execution.expression.numerical.CPower.execute(), org.lightjason.agentspeak.language.execution.expression.logical.CBinary.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CComparable.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CMultiplicative.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CAdditive.execute(), and org.lightjason.agentspeak.language.execution.expression.IBaseBinary.operator().
m_righthandside
final IExpression org.lightjason.agentspeak.language.execution.expression.IBaseBinary.m_righthandside protected
Definition at line 59 of file IBaseBinary.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.IBaseBinary.rightHandSide().
serialVersionUID
final long org.lightjason.agentspeak.language.execution.expression.IBaseBinary.serialVersionUID = 1630029294068548691L static private
Definition at line 47 of file IBaseBinary.java.