LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics Class Reference
test for statistics actions
Public Member Functions
final void addstatisticvalue ()
test add statistics value
final void clear ()
test clear
final void createdistribution ()
test create distribution
final void createstatistics ()
test create statistics
final void descriptivemultiplestatisticvalue ()
test multiple statistics value of descriptive
final void exponentialselectionlazy ()
test exponential selection with lazy parameter
final void exponentialselectionstrict ()
test exponential selection with strict parameter
final void initialize ()
initialize
final void linearselection ()
test linear selection
final void percentile ()
test percentile
final void randomsample ()
test add random sample
final void randomsimple ()
test random simple
final void singlestatisticvalue ()
test single statistics value
final void summarymultiplestatisticvalue ()
test multiple statistics value of summary
Private Attributes
DescriptiveStatistics m_descriptivestatistic
testing descriptive statistic
SummaryStatistics m_summarystatistic
testing summary statistic
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 77 of file TestCActionMathStatistics.java.
Member Function Documentation
addstatisticvalue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.addstatisticvalue ()
Definition at line 239 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CAddStatisticValue.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
clear()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.clear ()
Definition at line 169 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CClearStatistic.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
createdistribution()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.createdistribution ()
Definition at line 185 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
createstatistics()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.createstatistics ()
Definition at line 110 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CCreateStatistic.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
descriptivemultiplestatisticvalue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.descriptivemultiplestatisticvalue ()
Definition at line 290 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CMultipleStatisticValue.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
exponentialselectionlazy()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.exponentialselectionlazy ()
Definition at line 415 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
exponentialselectionstrict()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.exponentialselectionstrict ()
Definition at line 382 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
initialize()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.initialize ()
Definition at line 93 of file TestCActionMathStatistics.java.
linearselection()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.linearselection ()
Definition at line 447 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
percentile()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.percentile ()
Definition at line 136 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CMultiplePercentile.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CSinglePercentile.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
randomsample()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.randomsample ()
Definition at line 325 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CRandomSample.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
randomsimple()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.randomsimple ()
Definition at line 344 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CRandomSimple.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
singlestatisticvalue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.singlestatisticvalue ()
Definition at line 363 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CSingleStatisticValue.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
summarymultiplestatisticvalue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.summarymultiplestatisticvalue ()
Definition at line 255 of file TestCActionMathStatistics.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.statistic.CMultipleStatisticValue.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
Member Data Documentation
m_descriptivestatistic
DescriptiveStatistics org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.m_descriptivestatistic private
Definition at line 87 of file TestCActionMathStatistics.java.
m_summarystatistic
SummaryStatistics org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.m_summarystatistic private
Definition at line 82 of file TestCActionMathStatistics.java.