LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet Class Reference
collection set tests
Public Member Functions
final void add ()
test add
final void contains ()
test contains
final void create ()
test create
final void createsynchronized ()
test create synchronized
final void remove ()
test remove
final void tolist ()
test to-list
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 50 of file TestCActionCollectionSet.java.
Member Function Documentation
add()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.add ()
Definition at line 96 of file TestCActionCollectionSet.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CAdd.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
contains()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.contains ()
Definition at line 113 of file TestCActionCollectionSet.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.set.CContains.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.create ()
Definition at line 57 of file TestCActionCollectionSet.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
createsynchronized()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.createsynchronized ()
Definition at line 76 of file TestCActionCollectionSet.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
remove()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.remove ()
Definition at line 131 of file TestCActionCollectionSet.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CRemove.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
tolist()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.tolist ()
Definition at line 150 of file TestCActionCollectionSet.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.set.CToList.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().