LightJason - AgentSpeak(L++): org.lightjason.agentspeak.consistency.filter.IBaseFilter Class Reference
org.lightjason.agentspeak.consistency.filter.IBaseFilter Class Reference abstract
default metric with an optional set of path values
Public Member Functions
final Collection< IPath > getSelector ()
returns the selectors
Protected Member Functions
IBaseFilter (final IPath... p_paths)
ctor
IBaseFilter (final Collection< IPath > p_paths)
ctor
Protected Attributes
final Set< IPath > m_paths = new HashSet<>()
set with paths
Detailed Description
Definition at line 38 of file IBaseFilter.java.
Constructor & Destructor Documentation
IBaseFilter() [1/2]
org.lightjason.agentspeak.consistency.filter.IBaseFilter.IBaseFilter (final IPath... p_paths) protected
Parameters
p_paths for reading agent value
Definition at line 50 of file IBaseFilter.java.
IBaseFilter() [2/2]
org.lightjason.agentspeak.consistency.filter.IBaseFilter.IBaseFilter (final Collection< IPath > p_paths) protected
Parameters
p_paths collection of path
Definition at line 61 of file IBaseFilter.java.
Member Function Documentation
getSelector()
final Collection<IPath> org.lightjason.agentspeak.consistency.filter.IBaseFilter.getSelector ()
Returns
selector
Definition at line 72 of file IBaseFilter.java.
References org.lightjason.agentspeak.consistency.filter.IBaseFilter.m_paths.
Member Data Documentation
m_paths
final Set<IPath> org.lightjason.agentspeak.consistency.filter.IBaseFilter.m_paths = new HashSet<>() protected
Definition at line 43 of file IBaseFilter.java.
Referenced by org.lightjason.agentspeak.consistency.filter.CBelief.apply(), org.lightjason.agentspeak.consistency.filter.CAll.apply(), and org.lightjason.agentspeak.consistency.filter.IBaseFilter.getSelector().