LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expression.logical.CUnary Class Reference
org.lightjason.agentspeak.language.execution.expression.logical.CUnary Class Reference
logical unary expression
Public Member Functions
CUnary (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_expression)
ctor
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.expression.IBaseUnary
final boolean equals (final Object p_object)
final IExpression expression ()
returns the expression
final int hashCode ()
final EOperator operator ()
return expression operator
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Static Private Attributes
static final long serialVersionUID = -5203681823131507779L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.execution.expression.IExpression
IExpression EMPTY
empty expression, is always true
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.expression.IBaseUnary
IBaseUnary (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_expression)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.expression.IBaseUnary
final IExpression m_expression
left-hand-side argument
final EOperator m_operator
expression operator
Detailed Description
Definition at line 45 of file CUnary.java.
Constructor & Destructor Documentation
CUnary()
org.lightjason.agentspeak.language.execution.expression.logical.CUnary.CUnary (@Nonnull final EOperator p_operator, @Nonnull final IExpression p_expression)
Parameters
p_operator operator
p_expression expression
Definition at line 58 of file CUnary.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.isLogical(), org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.execution.expression.IBaseUnary.m_operator.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.expression.logical.CUnary.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 67 of file CUnary.java.
References org.lightjason.agentspeak.language.execution.IExecution.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), org.lightjason.agentspeak.language.execution.expression.IBaseUnary.m_expression, and org.lightjason.agentspeak.language.execution.expression.IBaseUnary.m_operator.
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.language.execution.expression.logical.CUnary.serialVersionUID = -5203681823131507779L static private
Definition at line 50 of file CUnary.java.