LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T > Class Template Reference
org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T > Class Template Reference
mutable fuzzy boolean
Public Member Functions
CFuzzyValueMutable (@Nonnull final T p_value)
ctor
CFuzzyValueMutable (@Nonnull final IFuzzyValue< T > p_value)
ctor
CFuzzyValueMutable (@Nonnull final T p_value, final double p_fuzzy)
ctor
final IFuzzyValueMutable< T > fuzzy (final double p_value)
sets the weight
final double fuzzy ()
returns the fuzziness
final IFuzzyValue< T > immutable ()
returns an immutable instance of the object
final T throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
final IFuzzyValueMutable< T > value (@Nullable final T p_value)
final T value ()
returns the result
final boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Public Member Functions inherited from org.lightjason.agentspeak.language.fuzzy.IFuzzyValueMutable< T >
IFuzzyValueMutable< T > value (final T p_value)
sets the fuzzy value
Static Public Member Functions
static< N > IFuzzyValueMutable< N > from (@Nonnull final N p_value)
factory
static< N > IFuzzyValueMutable< N > from (@Nonnull final N p_value, final double p_fuzzy)
factory
Private Attributes
double m_fuzzy
fuzzy value
T m_value
value
Detailed Description
Definition at line 38 of file CFuzzyValueMutable.java.
Constructor & Destructor Documentation
CFuzzyValueMutable() [1/3]
org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.CFuzzyValueMutable (@Nonnull final T p_value)
Parameters
p_value value
Definition at line 54 of file CFuzzyValueMutable.java.
CFuzzyValueMutable() [2/3]
org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.CFuzzyValueMutable (@Nonnull final IFuzzyValue< T > p_value)
Parameters
p_value fuzzy value
Definition at line 64 of file CFuzzyValueMutable.java.
CFuzzyValueMutable() [3/3]
org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.CFuzzyValueMutable (@Nonnull final T p_value, final double p_fuzzy)
Parameters
p_value value
p_fuzzy fuzzy value
Definition at line 76 of file CFuzzyValueMutable.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Function Documentation
from() [1/2]
static <N> IFuzzyValueMutable<N> org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.from (@Nonnull final N p_value) static
Parameters
p_value value
Returns
fuzzy value
Template Parameters
N fuzzy type
Definition at line 148 of file CFuzzyValueMutable.java.
Referenced by org.lightjason.agentspeak.language.fuzzy.operator.bool.CIntersection.factory(), org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.factory(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.immutable().
from() [2/2]
static <N> IFuzzyValueMutable<N> org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.from (@Nonnull final N p_value, final double p_fuzzy) static
Parameters
p_value value
p_fuzzy fuzzy value
Returns
fuzzy value
Template Parameters
N fuzzy type
Definition at line 163 of file CFuzzyValueMutable.java.
fuzzy() [1/2]
final IFuzzyValueMutable<T> org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.fuzzy (final double p_value)
Parameters
p_value weight
Returns
self reference
Implements org.lightjason.agentspeak.language.fuzzy.IFuzzyValueMutable< T >.
Definition at line 95 of file CFuzzyValueMutable.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
fuzzy() [2/2]
final double org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.fuzzy ()
Returns
fuzzy value in [0,1]
Implements org.lightjason.agentspeak.language.fuzzy.IFuzzyValue< T >.
Definition at line 118 of file CFuzzyValueMutable.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.m_fuzzy.
immutable()
final IFuzzyValue<T> org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.immutable ()
Returns
immutable instance
Implements org.lightjason.agentspeak.language.fuzzy.IFuzzyValueMutable< T >.
Definition at line 105 of file CFuzzyValueMutable.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.from().
throwvaluenotassignableto()
final T org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
Parameters
p_class assignable class
Returns
object itself
Exceptions
IllegalArgumentException on assignable error
Implements org.lightjason.agentspeak.language.IAssignable< T >.
Definition at line 131 of file CFuzzyValueMutable.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.m_value, and org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.valueassignableto().
value() [1/2]
final IFuzzyValueMutable<T> org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.value (@Nullable final T p_value)
Definition at line 87 of file CFuzzyValueMutable.java.
value() [2/2]
final T org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.value ()
Returns
value
Implements org.lightjason.agentspeak.language.fuzzy.IFuzzyValue< T >.
Definition at line 112 of file CFuzzyValueMutable.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.m_value.
valueassignableto()
final boolean org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.valueassignableto (@Nonnull final Class<?>... p_class)
Parameters
p_class class
Returns
assignable (on null always true)
Implements org.lightjason.agentspeak.language.IAssignable< T >.
Definition at line 124 of file CFuzzyValueMutable.java.
Referenced by org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.throwvaluenotassignableto().
Member Data Documentation
m_fuzzy
double org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.m_fuzzy private
Definition at line 47 of file CFuzzyValueMutable.java.
Referenced by org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.fuzzy().
m_value
T org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.m_value private
Definition at line 43 of file CFuzzyValueMutable.java.
Referenced by org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.throwvaluenotassignableto(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.value().