LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number > Class Template Reference
org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number > Class Template Reference
unary increment
Public Member Functions
CDecrement (@Nonnull final IVariable< T > p_variable)
ctor
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final IVariable< T > m_variable
variable
Static Private Attributes
static final long serialVersionUID = -5980848121313572183L
serial id
Detailed Description
Definition at line 41 of file CDecrement.java.
Constructor & Destructor Documentation
CDecrement()
org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.CDecrement (@Nonnull final IVariable< T > p_variable)
Parameters
p_variable variable
Definition at line 58 of file CDecrement.java.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 71 of file CDecrement.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), org.lightjason.agentspeak.language.CCommon.replaceFromContext(), org.lightjason.agentspeak.language.variable.IVariable< T >.set(), org.lightjason.agentspeak.language.IRawStructure< T >.thrownotallocated(), and org.lightjason.agentspeak.language.IAssignable< T >.valueassignableto().
toString()
final String org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.toString ()
Definition at line 64 of file CDecrement.java.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 83 of file CDecrement.java.
Member Data Documentation
m_variable
final IVariable<T> org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.m_variable private
Definition at line 50 of file CDecrement.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.serialVersionUID = -5980848121313572183L static private
Definition at line 46 of file CDecrement.java.