LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero Class Reference
org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero Class Reference
returns the number of non-zero cells.
Public Member Functions
CNonZero ()
ctor
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int minimalArgumentNumber ()
minimum number of arguments
Public Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Static Private Attributes
static final long serialVersionUID = 1257446954877857977L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
IBuiltinAction ()
ctor
IBuiltinAction (final int p_length)
ctor
Static Protected Attributes inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
static final Logger LOGGER = CCommon.logger(IBuiltinAction.class)
logger
Static Protected Attributes inherited from org.lightjason.agentspeak.action.IBaseAction
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Detailed Description
Gets the number of non-zero cells on each matrix input and returns the value, the action never fails
[NZ1|NZ2] = math/blas/matrix/nonzero(M1,M2);
Definition at line 47 of file matrix/CNonZero.java.
Constructor & Destructor Documentation
CNonZero()
org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero.CNonZero ()
Definition at line 57 of file matrix/CNonZero.java.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 71 of file matrix/CNonZero.java.
References org.lightjason.agentspeak.language.CCommon.flatten(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
minimalArgumentNumber()
final int org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero.minimalArgumentNumber ()
Returns
number of minimal arguments
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 64 of file matrix/CNonZero.java.
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero.serialVersionUID = 1257446954877857977L static private
Definition at line 52 of file matrix/CNonZero.java.