LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.rule.CRule Class Reference
org.lightjason.agentspeak.language.instantiable.rule.CRule Class Reference
rule structure
Public Member Functions
CRule (@Nonnull final ILiteral p_id, @Nonnull final List< IExecution > p_action)
ctor
final ILiteral identifier ()
returns the identifier of the rule
final IRule replaceplaceholder (@Nonnull final Multimap< IPath, IRule > p_rules)
replaces all placeholder objects and reinstantiate object
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
final boolean equals (final Object p_object)
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int hashCode ()
final IContext instantiate (@Nonnull final IAgent<?> p_agent, @Nonnull final Stream< IVariable<?>> p_variable)
creates an individual execution context
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final ILiteral m_id
identifier of the rule
Static Private Attributes
static final long serialVersionUID = -1165818799700126229L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.instantiable.rule.IRule
IRule EMPTY
empty rule
Protected Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
IBaseInstantiable (final List< IExecution > p_action, final Set< IAnnotation<?>> p_annotation, final int p_hash)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
final List< IExecution > m_action
action list
final Map< IAnnotation.EType, IAnnotation<?> > m_annotation
map with annotation (enum value for getting annotation object)
Detailed Description
Definition at line 48 of file CRule.java.
Constructor & Destructor Documentation
CRule()
org.lightjason.agentspeak.language.instantiable.rule.CRule.CRule (@Nonnull final ILiteral p_id, @Nonnull final List< IExecution > p_action)
Parameters
p_id literal with signature
p_action action list
Definition at line 65 of file CRule.java.
Referenced by org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder().
Member Function Documentation
identifier()
final ILiteral org.lightjason.agentspeak.language.instantiable.rule.CRule.identifier ()
Returns
literal
Implements org.lightjason.agentspeak.language.instantiable.rule.IRule.
Definition at line 80 of file CRule.java.
References org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id.
Referenced by org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder().
replaceplaceholder()
final IRule org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder (@Nonnull final Multimap< IPath, IRule > p_rules)
Parameters
p_rules full instantiated rules
Returns
new object instance without placeholders
Implements org.lightjason.agentspeak.language.instantiable.rule.IRule.
Definition at line 88 of file CRule.java.
References org.lightjason.agentspeak.language.instantiable.rule.CRule.CRule(), org.lightjason.agentspeak.language.instantiable.rule.CRule.identifier(), and org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action.
toString()
final String org.lightjason.agentspeak.language.instantiable.rule.CRule.toString ()
Definition at line 113 of file CRule.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action, and org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.rule.CRule.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 103 of file CRule.java.
References org.lightjason.agentspeak.language.CCommon.flattenrecursive(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation, org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id, org.lightjason.agentspeak.language.ILiteral.orderedvalues(), org.lightjason.agentspeak.language.CCommon.streamconcat(), org.lightjason.agentspeak.language.ITerm.term(), and org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.variables().
Member Data Documentation
m_id
final ILiteral org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id private
Definition at line 57 of file CRule.java.
Referenced by org.lightjason.agentspeak.language.instantiable.rule.CRule.identifier(), org.lightjason.agentspeak.language.instantiable.rule.CRule.toString(), and org.lightjason.agentspeak.language.instantiable.rule.CRule.variables().
serialVersionUID
final long org.lightjason.agentspeak.language.instantiable.rule.CRule.serialVersionUID = -1165818799700126229L static private
Definition at line 53 of file CRule.java.