LightJason - AgentSpeak(L++): org.lightjason.agentspeak.common.IPath Interface Reference
org.lightjason.agentspeak.common.IPath Interface Reference
interface of a path
Public Member Functions
IPath append (@Nonnull final IPath p_path)
appends a path at the current and returns a new object
IPath append (@Nonnull final String p_path)
appends a string at the current path and returns the new object
boolean empty ()
check if the path is empty
boolean endswith (@Nonnull final IPath p_path)
check of a path ends with another path
String get (final int p_index)
returns an part of the path
IPath lower ()
changes all elements to lower-case
String path (final String p_separator)
returns the full path as string with an individual separator
String path ()
returns the full path as string
IPath pushback (@Nonnull final IPath p_path)
adds a path at the end
IPath pushback (@Nonnull final String p_path)
adds a path at the end
IPath pushfront (@Nonnull final String p_path)
adds a path at the front
IPath pushfront (@Nonnull final IPath p_path)
adds a path to the front of the path
IPath remove (final int p_index)
removes an element
IPath remove (final int p_start, final int p_end)
removes all elements from start index until end index (exclusive)
String removesuffix ()
remove the suffix from the path
IPath reverse ()
reverse path
String separator ()
returns the separator
IPath separator (@Nonnull final String p_separator)
sets the separator
int size ()
returns the number of path elements
boolean startswith (final IPath p_path)
check of a path starts with another path
boolean startswith (final String p_path)
check of a path starts with another path
Stream< String > stream ()
stream over elements
IPath subpath (final int p_fromindex)
creates a path of the start index until the end
IPath subpath (final int p_fromindex, final int p_toindex)
creates a path of the indices
String suffix ()
returns the last part of the path
IPath upper ()
changes all elements to uppercase
Public Attributes
String DEFAULTSEPERATOR = "/"
default seperator
IPath EMPTY
empty path
Detailed Description
Note
implement equals with String object, so a path object can be checked to a String
Definition at line 38 of file IPath.java.
Member Function Documentation
append() [1/2]
IPath org.lightjason.agentspeak.common.IPath.append (@Nonnull final IPath p_path)
Parameters
p_path path
Returns
new path
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopy(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.deepcopy(), and org.lightjason.agentspeak.language.variable.CVariable< T >.deepcopy().
append() [2/2]
IPath org.lightjason.agentspeak.common.IPath.append (@Nonnull final String p_path)
Parameters
p_path string with path
Returns
new path
Implemented in org.lightjason.agentspeak.common.CPath.
empty()
boolean org.lightjason.agentspeak.common.IPath.empty ()
Returns
empty flag
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.common.CCommon.actionusable().
endswith()
boolean org.lightjason.agentspeak.common.IPath.endswith (@Nonnull final IPath p_path)
Parameters
p_path path
Returns
boolean
Implemented in org.lightjason.agentspeak.common.CPath.
get()
String org.lightjason.agentspeak.common.IPath.get (final int p_index)
Parameters
p_index index position (negativ index is element from the end)
Returns
element
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.common.CCommon.actionusable().
lower()
IPath org.lightjason.agentspeak.common.IPath.lower ()
Returns
object
Implemented in org.lightjason.agentspeak.common.CPath.
path() [1/2]
String org.lightjason.agentspeak.common.IPath.path (final String p_separator)
Parameters
p_separator separator
Returns
string path
path() [2/2]
String org.lightjason.agentspeak.common.IPath.path ()
Returns
string path
Implemented in org.lightjason.agentspeak.common.CPath.
pushback() [1/2]
IPath org.lightjason.agentspeak.common.IPath.pushback (@Nonnull final IPath p_path)
Parameters
p_path path
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.common.CPath.CPathCollector.accumulator(), and org.lightjason.agentspeak.common.CPath.CPathCollector.combiner().
pushback() [2/2]
IPath org.lightjason.agentspeak.common.IPath.pushback (@Nonnull final String p_path)
Parameters
p_path string path
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
pushfront() [1/2]
IPath org.lightjason.agentspeak.common.IPath.pushfront (@Nonnull final String p_path)
Parameters
p_path string path
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
pushfront() [2/2]
IPath org.lightjason.agentspeak.common.IPath.pushfront (@Nonnull final IPath p_path)
Parameters
p_path path
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
remove() [1/2]
IPath org.lightjason.agentspeak.common.IPath.remove (final int p_index)
Parameters
p_index index position
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.common.CPath.remove(), and org.lightjason.agentspeak.beliefbase.view.CView.trigger().
remove() [2/2]
IPath org.lightjason.agentspeak.common.IPath.remove (final int p_start, final int p_end)
Parameters
p_start start index
p_end end index (exclusive)
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
removesuffix()
String org.lightjason.agentspeak.common.IPath.removesuffix ()
Returns
last item of the path
Implemented in org.lightjason.agentspeak.common.CPath.
reverse()
IPath org.lightjason.agentspeak.common.IPath.reverse ()
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.common.CPath.reverse().
separator() [1/2]
String org.lightjason.agentspeak.common.IPath.separator ()
Returns
separator
Implemented in org.lightjason.agentspeak.common.CPath.
separator() [2/2]
IPath org.lightjason.agentspeak.common.IPath.separator (@Nonnull final String p_separator)
Parameters
p_separator separator
Returns
path object
Implemented in org.lightjason.agentspeak.common.CPath.
size()
int org.lightjason.agentspeak.common.IPath.size ()
Returns
size
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.functorpath(), org.lightjason.agentspeak.language.variable.CVariable< T >.functorpath(), and org.lightjason.agentspeak.language.CLiteral.functorpath().
startswith() [1/2]
boolean org.lightjason.agentspeak.common.IPath.startswith (final IPath p_path)
Parameters
p_path path
Returns
boolean
startswith() [2/2]
boolean org.lightjason.agentspeak.common.IPath.startswith (final String p_path)
Parameters
p_path path
Returns
boolean
Implemented in org.lightjason.agentspeak.common.CPath.
stream()
Stream<String> org.lightjason.agentspeak.common.IPath.stream ()
Returns
sequential stream
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.language.CLiteral.allocate(), org.lightjason.agentspeak.common.CPath.pushback(), and org.lightjason.agentspeak.language.CLiteral.unify().
subpath() [1/2]
IPath org.lightjason.agentspeak.common.IPath.subpath (final int p_fromindex)
Parameters
p_fromindex start index
Returns
path
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.functorpath(), org.lightjason.agentspeak.language.variable.CVariable< T >.functorpath(), and org.lightjason.agentspeak.language.CLiteral.functorpath().
subpath() [2/2]
IPath org.lightjason.agentspeak.common.IPath.subpath (final int p_fromindex, final int p_toindex)
Parameters
p_fromindex start index
p_toindex end index (exclusive) / negative values from the end
Returns
path
Implemented in org.lightjason.agentspeak.common.CPath.
suffix()
String org.lightjason.agentspeak.common.IPath.suffix ()
Returns
string
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.CLiteral.deepcopysuffix(), org.lightjason.agentspeak.language.CRawTerm< T >.functor(), org.lightjason.agentspeak.language.variable.CVariable< T >.functor(), org.lightjason.agentspeak.language.CLiteral.functor(), org.lightjason.agentspeak.language.variable.CConstant< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CMutexVariable< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.shallowcopysuffix(), and org.lightjason.agentspeak.language.CLiteral.shallowcopysuffix().
upper()
IPath org.lightjason.agentspeak.common.IPath.upper ()
Returns
object
Implemented in org.lightjason.agentspeak.common.CPath.
Member Data Documentation
DEFAULTSEPERATOR
String org.lightjason.agentspeak.common.IPath.DEFAULTSEPERATOR = "/"
Definition at line 43 of file IPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.from().
EMPTY
IPath org.lightjason.agentspeak.common.IPath.EMPTY
Definition at line 48 of file IPath.java.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.CRawTerm(), and org.lightjason.agentspeak.common.CPath.from().