LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign Class Reference
org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign Class Reference
assign operator expression
Public Member Functions
COperatorAssign (final IVariable<?> p_lhs, final ITerm p_rhs, final EOperator p_operator)
ctor
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final IVariable<?> m_lhs
left-hand-side
final EOperator m_operator
operator
final ITerm m_rhs
right-hand-side
Static Private Attributes
static final long serialVersionUID = 720534461732785140L
serial id
Detailed Description
Definition at line 42 of file COperatorAssign.java.
Constructor & Destructor Documentation
COperatorAssign()
org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.COperatorAssign (final IVariable<?> p_lhs, final ITerm p_rhs, final EOperator p_operator)
Parameters
p_lhs left-hand-side variable
p_rhs right-hand-side data
p_operator operator
Definition at line 69 of file COperatorAssign.java.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 78 of file COperatorAssign.java.
References org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.apply(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), org.lightjason.agentspeak.language.ITerm.raw(), and org.lightjason.agentspeak.language.variable.IVariable< T >.set().
toString()
final String org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.toString ()
Definition at line 88 of file COperatorAssign.java.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 95 of file COperatorAssign.java.
References org.lightjason.agentspeak.language.ITerm.term().
Member Data Documentation
m_lhs
final IVariable<?> org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.m_lhs private
Definition at line 51 of file COperatorAssign.java.
m_operator
final EOperator org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.m_operator private
Definition at line 59 of file COperatorAssign.java.
m_rhs
final ITerm org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.m_rhs private
Definition at line 55 of file COperatorAssign.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.serialVersionUID = 720534461732785140L static private
Definition at line 47 of file COperatorAssign.java.