LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.TestCHanoiTowers Class Reference
org.lightjason.agentspeak.agent.TestCHanoiTowers Class Reference
abstract test for playing towers of hanoi If a file agentprintin.conf exists on the main directory alls print statements will be shown
Classes
class CAgent
agent class
class CEmptyPrint
empty print action
class CGenerator
agent generator
class CSlice
defines a slice
class CStop
stop action
class CTower
tower
class CTowerPop
pops an elements from a tower
class CTowerPush
pushs a slice to a tower
class CTowerSize
returns the number of elements of an tower
Public Member Functions
void initialize () throws Exception
test initialize
void play () throws InterruptedException
test execution
Static Package Functions
[static initializer]
Private Member Functions
void execute ()
running towers of hanoi
void setup (final int p_agentnumber, final long p_towernumber, final long p_slicenumber, final String p_asl, final Stream< IAction > p_action) throws Exception
initialize call
Private Attributes
Map< Integer, CAgent > m_agents
agent map
AtomicBoolean m_running
running flag (agent can disable execution)
Long m_slicenumber
number of slices
Map< Integer, CTower > m_tower
tower map
Long m_towernumber
number of towers
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 71 of file TestCHanoiTowers.java.
Member Function Documentation
[static initializer]()
org.lightjason.agentspeak.agent.TestCHanoiTowers.[static initializer] () static package
execute()
void org.lightjason.agentspeak.agent.TestCHanoiTowers.execute () private
Definition at line 179 of file TestCHanoiTowers.java.
References org.lightjason.agentspeak.IBaseTest.PRINTENABLE.
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.play().
initialize()
void org.lightjason.agentspeak.agent.TestCHanoiTowers.initialize () throws Exception
Exceptions
Exception on initialize error
Definition at line 108 of file TestCHanoiTowers.java.
References org.lightjason.agentspeak.agent.TestCHanoiTowers.setup().
play()
void org.lightjason.agentspeak.agent.TestCHanoiTowers.play () throws InterruptedException
Exceptions
InterruptedException is thrown on execution error
Definition at line 122 of file TestCHanoiTowers.java.
References org.lightjason.agentspeak.agent.TestCHanoiTowers.execute().
setup()
void org.lightjason.agentspeak.agent.TestCHanoiTowers.setup (final int p_agentnumber, final long p_towernumber, final long p_slicenumber, final String p_asl, final Stream< IAction > p_action) throws Exception private
Parameters
p_agentnumber number of agents
p_towernumber number of towers
p_slicenumber number of slices
p_asl asl file
p_action action stream
Exceptions
Exception thrown on initialize error
Definition at line 137 of file TestCHanoiTowers.java.
References org.lightjason.agentspeak.agent.TestCHanoiTowers.CGenerator.generatesingle(), and org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower.push().
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.initialize().
Member Data Documentation
m_agents
Map<Integer, CAgent> org.lightjason.agentspeak.agent.TestCHanoiTowers.m_agents private
Definition at line 76 of file TestCHanoiTowers.java.
m_running
AtomicBoolean org.lightjason.agentspeak.agent.TestCHanoiTowers.m_running private
Definition at line 92 of file TestCHanoiTowers.java.
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.CStop.execute().
m_slicenumber
Long org.lightjason.agentspeak.agent.TestCHanoiTowers.m_slicenumber private
Definition at line 84 of file TestCHanoiTowers.java.
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.CGenerator.CGenerator().
m_tower
Map<Integer, CTower> org.lightjason.agentspeak.agent.TestCHanoiTowers.m_tower private
Definition at line 88 of file TestCHanoiTowers.java.
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerSize.execute(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPush.execute(), and org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPop.execute().
m_towernumber
Long org.lightjason.agentspeak.agent.TestCHanoiTowers.m_towernumber private
Definition at line 80 of file TestCHanoiTowers.java.
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.CGenerator.CGenerator().