LightJason - AgentSpeak(L++): org.lightjason.agentspeak.TestCLanguageLabels Class Reference
org.lightjason.agentspeak.TestCLanguageLabels Class Reference
test all resource strings
Classes
class CJavaVistor
AST visitor class.
Public Member Functions
void testResourceString () throws IOException
test-case all resource strings
void testTranslation ()
check package translation configuration versus property items
Static Package Functions
[static initializer]
Static Private Attributes
static final String CLASSSEPARATOR = "."
static final Map< String, URI > LANGUAGEPROPERY = new HashMap<>()
property filenames with language data
static final URI SEARCHPATH
search path
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 68 of file TestCLanguageLabels.java.
Member Function Documentation
[static initializer]()
org.lightjason.agentspeak.TestCLanguageLabels.[static initializer] () static package
testResourceString()
void org.lightjason.agentspeak.TestCLanguageLabels.testResourceString () throws IOException
Exceptions
IOException throws on io errors
Definition at line 176 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.labels(), org.lightjason.agentspeak.common.CCommon.PACKAGEROOT, and org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit().
testTranslation()
void org.lightjason.agentspeak.TestCLanguageLabels.testTranslation ()
Definition at line 132 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.common.CCommon.configuration().
Member Data Documentation
CLASSSEPARATOR
final String org.lightjason.agentspeak.TestCLanguageLabels.CLASSSEPARATOR = "." static private
Definition at line 70 of file TestCLanguageLabels.java.
LANGUAGEPROPERY
final Map<String, URI> org.lightjason.agentspeak.TestCLanguageLabels.LANGUAGEPROPERY = new HashMap<>() static private
Definition at line 78 of file TestCLanguageLabels.java.
SEARCHPATH
final URI org.lightjason.agentspeak.TestCLanguageLabels.SEARCHPATH static private
Definition at line 74 of file TestCLanguageLabels.java.