LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.datetime.IBetween Class Reference
org.lightjason.agentspeak.action.builtin.datetime.IBetween Class Reference abstract
abstract class to calculate difference between date-time elements
Public Member Functions
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int minimalArgumentNumber ()
minimum number of arguments
Public Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Protected Member Functions
IBetween ()
ctor
abstract Stream<?> apply (@Nonnull final Stream< List< Instant >> p_datetime)
calculating method
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
IBuiltinAction ()
ctor
IBuiltinAction (final int p_length)
ctor
Static Private Attributes
static final long serialVersionUID = 2806678071531558364L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Static Protected Attributes inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
static final Logger LOGGER = CCommon.logger(IBuiltinAction.class)
logger
Static Protected Attributes inherited from org.lightjason.agentspeak.action.IBaseAction
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Detailed Description
Definition at line 50 of file IBetween.java.
Constructor & Destructor Documentation
IBetween()
org.lightjason.agentspeak.action.builtin.datetime.IBetween.IBetween () protected
Definition at line 60 of file IBetween.java.
Member Function Documentation
apply()
abstract Stream<?> org.lightjason.agentspeak.action.builtin.datetime.IBetween.apply (@Nonnull final Stream< List< Instant >> p_datetime) abstract protected
Parameters
p_datetime stream with list of date-time elements
Returns
output stream
Referenced by org.lightjason.agentspeak.action.builtin.datetime.IBetween.execute().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.action.builtin.datetime.IBetween.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 72 of file IBetween.java.
References org.lightjason.agentspeak.action.builtin.datetime.IBetween.apply(), org.lightjason.agentspeak.language.CCommon.flatten(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
minimalArgumentNumber()
final int org.lightjason.agentspeak.action.builtin.datetime.IBetween.minimalArgumentNumber ()
Returns
number of minimal arguments
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 65 of file IBetween.java.
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.action.builtin.datetime.IBetween.serialVersionUID = 2806678071531558364L static private
Definition at line 55 of file IBetween.java.