LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.view.CViewMap Class Reference
org.lightjason.agentspeak.beliefbase.view.CViewMap Class Reference
view which can use a map of maps to represent the hierarchical beliefbase structure
Classes
class CWrapperBeliefbase
wrapper beliefbase
Public Member Functions
CViewMap (@Nonnull final String p_name, @Nonnull final Map< String, Object > p_map)
ctor
CViewMap (@Nonnull final String p_name, @Nonnull final Map< String, Object > p_map, @Nullable final IView p_parent)
ctor
CViewMap (@Nonnull final String p_name, @Nonnull final Map< String, Object > p_map, @Nullable final IView p_parent, @Nonnull final BiConsumer< String, Map< String, Object >> p_addviewconsumer, @Nonnull final BiConsumer< Pair< String, Stream< ITerm >>, Map< String, Object >> p_addliteralconsumer, @Nonnull final BiConsumer< String, Map< String, Object >> p_removeviewconsumer, @Nonnull final BiConsumer< String, Map< String, Object >> p_removeliteralconsumer, @Nonnull final Consumer< Map< String, Object >> p_clearconsumer, @Nonnull final Function< String, String > p_literaltokey, @Nonnull final Function< String, String > p_keytoliteral)
ctor
final IView add (@Nonnull final Stream< ILiteral > p_literal)
adds a literal in the current structure
final IView add (@Nonnull final ILiteral... p_literal)
adds a literal in the current structure
final IView add (@Nonnull final IView... p_view)
adds view in the current structure
final IBeliefbase beliefbase ()
returns the beliefbase
final IView clear (@Nullable final IPath... p_path)
clears all elements
boolean containsLiteral (@Nonnull final IPath p_path)
checks if a literal exists
final boolean containsView (@Nonnull final IPath p_path)
view existing check
final boolean empty ()
checks if the structure empty
IView generate (@Nonnull final IViewGenerator p_generator, @Nonnull final IPath... p_paths)
generates path structure
final boolean hasParent ()
check if the view has got a parent
final String name ()
returns only the element name
final IView parent ()
returns the parent of the view
final IPath path ()
returns the full path
IView remove (@Nonnull final Stream< ILiteral > p_literal)
removes a literal in the current structure
IView remove (@Nonnull final ILiteral... p_literal)
removes a literal in the current structure
final IView remove (@Nonnull final IView... p_view)
removes a view in the current structure
final Stream< IView > root ()
returns a stream to the root node,
final int size ()
returns the size of literals
final Stream< ILiteral > stream (@Nullable final IPath... p_path)
returns stream of literal
final Stream< ILiteral > stream (final boolean p_negated, @Nullable final IPath... p_path)
returns stream of literal
final Stream< ITrigger > trigger ()
retruns all trigger of the beliefbase
final IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
final Stream< IView > walk (@Nonnull final IPath p_path, @Nullable final IViewGenerator... p_generator)
streams path walking
Private Member Functions
IView leafview (@Nonnull final Stream< IView > p_stream)
returns the leaf of a view path
Stream< IView > walkdown (final IPath p_path, @Nullable final IViewGenerator... p_generator)
Private Attributes
final BiConsumer< Pair< String, Stream< ITerm > >, Map< String, Object > > m_addliteralconsumer
add-literal consumer
final BiConsumer< String, Map< String, Object > > m_addviewconsumer
add-view consumer
final IBeliefbase m_beliefbase = new CWrapperBeliefbase()
beliefbase
final Consumer< Map< String, Object > > m_clearconsumer
clear consumer
final Map< String, Object > m_data
root map
final Function< String, String > m_keytoliteral
key to literal converting
final Function< String, String > m_literaltokey
path to key converting
final String m_name
view name
final IView m_parent
parent name
final BiConsumer< String, Map< String, Object > > m_removeliteralconsumer
remove-literal consumer
final BiConsumer< String, Map< String, Object > > m_removeviewconsumer
remove-view consumer
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.beliefbase.view.IView
IView EMPTY
empty view
Detailed Description
Note
given map should be thread-safe
Definition at line 60 of file CViewMap.java.
Constructor & Destructor Documentation
CViewMap() [1/3]
org.lightjason.agentspeak.beliefbase.view.CViewMap.CViewMap (@Nonnull final String p_name, @Nonnull final Map< String, Object > p_map)
Parameters
p_name name of the view
p_map map reference
Definition at line 113 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.size(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.streamView(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
CViewMap() [2/3]
org.lightjason.agentspeak.beliefbase.view.CViewMap.CViewMap (@Nonnull final String p_name, @Nonnull final Map< String, Object > p_map, @Nullable final IView p_parent)
Parameters
p_name view name
p_map map reference
p_parent parent view
Definition at line 125 of file CViewMap.java.
References org.lightjason.agentspeak.language.ITerm.raw().
CViewMap() [3/3]
org.lightjason.agentspeak.beliefbase.view.CViewMap.CViewMap (@Nonnull final String p_name, @Nonnull final Map< String, Object > p_map, @Nullable final IView p_parent, @Nonnull final BiConsumer< String, Map< String, Object >> p_addviewconsumer, @Nonnull final BiConsumer< Pair< String, Stream< ITerm >>, Map< String, Object >> p_addliteralconsumer, @Nonnull final BiConsumer< String, Map< String, Object >> p_removeviewconsumer, @Nonnull final BiConsumer< String, Map< String, Object >> p_removeliteralconsumer, @Nonnull final Consumer< Map< String, Object >> p_clearconsumer, @Nonnull final Function< String, String > p_literaltokey, @Nonnull final Function< String, String > p_keytoliteral)
Parameters
p_name view name
p_map map reference
p_parent parent view
p_addviewconsumer add-view consumer
p_addliteralconsumer add-literal consumer
p_removeviewconsumer remove-view consumer
p_removeliteralconsumer remove-view consumer
p_clearconsumer clear consumer
p_literaltokey converts a path (functor item to a map key
p_keytoliteral converts a map key to literal path
Definition at line 167 of file CViewMap.java.
Member Function Documentation
add() [1/3]
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.add (@Nonnull final Stream< ILiteral > p_literal)
Parameters
p_literal literal stream
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 287 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.add().
add() [2/3]
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.add (@Nonnull final ILiteral... p_literal)
Parameters
p_literal literal
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 295 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.add().
add() [3/3]
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.add (@Nonnull final IView... p_view)
Parameters
p_view existing view
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 303 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.IView.stream().
beliefbase()
final IBeliefbase org.lightjason.agentspeak.beliefbase.view.CViewMap.beliefbase ()
Returns
beliefbase
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 213 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_beliefbase.
clear()
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.clear (@Nullable final IPath... p_path)
Parameters
p_path path values
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 275 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_clearconsumer, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
containsLiteral()
boolean org.lightjason.agentspeak.beliefbase.view.CViewMap.containsLiteral (@Nonnull final IPath p_path)
Parameters
p_path path to a literal (suffix is literal name)
Returns
existance boolean
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 336 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CViewMap.leafview(), org.lightjason.agentspeak.beliefbase.view.CViewMap.m_beliefbase, and org.lightjason.agentspeak.beliefbase.view.CViewMap.walk().
containsView()
final boolean org.lightjason.agentspeak.beliefbase.view.CViewMap.containsView (@Nonnull final IPath p_path)
Parameters
p_path path to a view
Returns
existance boolean
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 348 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.containsView(), org.lightjason.agentspeak.beliefbase.view.CViewMap.leafview(), org.lightjason.agentspeak.beliefbase.view.CViewMap.m_beliefbase, and org.lightjason.agentspeak.beliefbase.view.CViewMap.walk().
empty()
final boolean org.lightjason.agentspeak.beliefbase.view.CViewMap.empty ()
Returns
empty boolean
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 359 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.IStructure.empty(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_beliefbase.
generate()
IView org.lightjason.agentspeak.beliefbase.view.CViewMap.generate (@Nonnull final IViewGenerator p_generator, @Nonnull final IPath... p_paths)
Parameters
p_generator generator for views
p_paths paths items
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 197 of file CViewMap.java.
hasParent()
final boolean org.lightjason.agentspeak.beliefbase.view.CViewMap.hasParent ()
Returns
boolean flag of the parent
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 240 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.root().
leafview()
IView org.lightjason.agentspeak.beliefbase.view.CViewMap.leafview (@Nonnull final Stream< IView > p_stream) private
Parameters
p_stream stream of views
Returns
last / leaf view
Definition at line 384 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CViewMap.containsView(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
name()
final String org.lightjason.agentspeak.beliefbase.view.CViewMap.name ()
Returns
name
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 227 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_name.
parent()
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.parent ()
Returns
parent object or null
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 234 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_parent.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.root().
path()
final IPath org.lightjason.agentspeak.beliefbase.view.CViewMap.path ()
Returns
path
Note
the path is relative to the root node, exclusive root element
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 220 of file CViewMap.java.
References org.lightjason.agentspeak.common.CPath.collect(), org.lightjason.agentspeak.beliefbase.view.IView.name(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.root().
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
remove() [1/3]
IView org.lightjason.agentspeak.beliefbase.view.CViewMap.remove (@Nonnull final Stream< ILiteral > p_literal)
Parameters
p_literal literal stream
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 311 of file CViewMap.java.
remove() [2/3]
IView org.lightjason.agentspeak.beliefbase.view.CViewMap.remove (@Nonnull final ILiteral... p_literal)
Parameters
p_literal literal
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 320 of file CViewMap.java.
remove() [3/3]
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.remove (@Nonnull final IView... p_view)
Parameters
p_view view
Returns
self reference
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 328 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.IView.stream().
root()
final Stream<IView> org.lightjason.agentspeak.beliefbase.view.CViewMap.root ()
Returns
stream of views
Note
the stream is exclusive of the root node and starts with the current node
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 204 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.hasParent(), org.lightjason.agentspeak.beliefbase.view.CViewMap.parent(), and org.lightjason.agentspeak.beliefbase.view.IView.root().
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.path().
size()
final int org.lightjason.agentspeak.beliefbase.view.CViewMap.size ()
Returns
size
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 365 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_beliefbase, and org.lightjason.agentspeak.beliefbase.IStructure.size().
stream() [1/2]
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.CViewMap.stream (@Nullable final IPath... p_path)
Parameters
p_path paths of the literals
Returns
literal stream
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 255 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.IView.beliefbase(), org.lightjason.agentspeak.beliefbase.view.CViewMap.leafview(), org.lightjason.agentspeak.beliefbase.IBeliefbase.literal(), org.lightjason.agentspeak.beliefbase.view.CViewMap.path(), org.lightjason.agentspeak.beliefbase.IBeliefbase.streamLiteral(), org.lightjason.agentspeak.beliefbase.IBeliefbase.streamView(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walk().
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
stream() [2/2]
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.CViewMap.stream (final boolean p_negated, @Nullable final IPath... p_path)
Parameters
p_negated negated flag
p_path paths of the literals
Returns
literal stream
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 268 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
trigger()
final Stream<ITrigger> org.lightjason.agentspeak.beliefbase.view.CViewMap.trigger ()
Returns
set with trigger events
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 247 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.IBeliefbase.trigger().
update()
final IAgent<?> org.lightjason.agentspeak.beliefbase.view.CViewMap.update (@Nonnull final IAgent<?> p_agent)
Parameters
p_agent agent which runs the update call
Returns
agent
Warning
call update on a storage and on all storage-view, if exists different views which are point to the same storage, the update is called more than once, so the storage must limit the number of update calls
Implements org.lightjason.agentspeak.beliefbase.IStructure.
Definition at line 372 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.m_beliefbase, and org.lightjason.agentspeak.beliefbase.IStructure.update().
walk()
final Stream<IView> org.lightjason.agentspeak.beliefbase.view.CViewMap.walk (@Nonnull final IPath p_path, @Nullable final IViewGenerator... p_generator)
Parameters
p_path path
p_generator generator for view creating (first argument is used, orther elements will be ignored)
Returns
stream of views
Implements org.lightjason.agentspeak.beliefbase.view.IView.
Definition at line 190 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CViewMap.containsView(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
walkdown()
Stream<IView> org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown (final IPath p_path, @Nullable final IViewGenerator... p_generator) private
Definition at line 392 of file CViewMap.java.
References org.lightjason.agentspeak.beliefbase.view.CViewMap.CViewMap(), org.lightjason.agentspeak.beliefbase.view.CViewMap.m_addliteralconsumer, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_addviewconsumer, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_clearconsumer, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_keytoliteral, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_literaltokey, org.lightjason.agentspeak.beliefbase.view.CViewMap.m_removeliteralconsumer, and org.lightjason.agentspeak.beliefbase.view.CViewMap.m_removeviewconsumer.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.clear(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walk().
Member Data Documentation
m_addliteralconsumer
final BiConsumer<Pair<String, Stream<ITerm> >, Map<String, Object> > org.lightjason.agentspeak.beliefbase.view.CViewMap.m_addliteralconsumer private
Definition at line 97 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.add(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
m_addviewconsumer
final BiConsumer<String, Map<String, Object> > org.lightjason.agentspeak.beliefbase.view.CViewMap.m_addviewconsumer private
Definition at line 93 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.add(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
m_beliefbase
final IBeliefbase org.lightjason.agentspeak.beliefbase.view.CViewMap.m_beliefbase = new CWrapperBeliefbase() private
Definition at line 73 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.beliefbase(), org.lightjason.agentspeak.beliefbase.view.CViewMap.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CViewMap.containsView(), org.lightjason.agentspeak.beliefbase.view.CViewMap.empty(), org.lightjason.agentspeak.beliefbase.view.CViewMap.size(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.update().
m_clearconsumer
final Consumer<Map<String, Object> > org.lightjason.agentspeak.beliefbase.view.CViewMap.m_clearconsumer private
Definition at line 89 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.clear(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
m_data
final Map<String, Object> org.lightjason.agentspeak.beliefbase.view.CViewMap.m_data private
Definition at line 77 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.add(), org.lightjason.agentspeak.beliefbase.view.CViewMap.clear(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.clear(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.containsView(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.empty(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.literal(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.remove(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.size(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.streamLiteral(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.streamView(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
m_keytoliteral
final Function<String, String> org.lightjason.agentspeak.beliefbase.view.CViewMap.m_keytoliteral private
Definition at line 85 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.add(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.streamLiteral(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.streamView(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.toterm(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
m_literaltokey
final Function<String, String> org.lightjason.agentspeak.beliefbase.view.CViewMap.m_literaltokey private
Definition at line 81 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.add(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.containsLiteral(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.containsView(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.literal(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.remove(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
m_name
final String org.lightjason.agentspeak.beliefbase.view.CViewMap.m_name private
Definition at line 65 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.name().
m_parent
final IView org.lightjason.agentspeak.beliefbase.view.CViewMap.m_parent private
Definition at line 69 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.parent().
m_removeliteralconsumer
final BiConsumer<String, Map<String, Object> > org.lightjason.agentspeak.beliefbase.view.CViewMap.m_removeliteralconsumer private
Definition at line 105 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.remove(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().
m_removeviewconsumer
final BiConsumer<String, Map<String, Object> > org.lightjason.agentspeak.beliefbase.view.CViewMap.m_removeviewconsumer private
Definition at line 101 of file CViewMap.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.remove(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.walkdown().