LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.variable.IVariable< T > Interface Template Reference
org.lightjason.agentspeak.language.variable.IVariable< T > Interface Template Reference
variable defintion
Public Member Functions
boolean any ()
flag to define a "any variable"
boolean mutex ()
flag to check if variable has is concurrency- / thread-safe
IVariable< T > set (@Nullable final T p_value)
sets the value
Public Member Functions inherited from org.lightjason.agentspeak.language.ITerm
IPath fqnfunctor ()
returns the full-qualified functor with path and name
String functor ()
returns the functor without path
IPath functorpath ()
returns the path of the functor
boolean hasVariable ()
checks if the literal has variables
< T > T raw ()
cast to any raw value type
default< T extends ITerm > T term ()
casts the object to a term-type
Public Member Functions inherited from org.lightjason.agentspeak.language.IStructureHash
int structurehash ()
returns a hash value which defines a hash ove rthe structure
Public Member Functions inherited from org.lightjason.agentspeak.language.IDeepCopy< ITerm >
T deepcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T deepcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Public Member Functions inherited from org.lightjason.agentspeak.language.IRawStructure< T >
boolean allocated ()
returns allocated state
T thrownotallocated () throws IllegalStateException
throws an illegal state exception iif the variable is not allocated
Public Member Functions inherited from org.lightjason.agentspeak.language.IAssignable< T >
T throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Public Member Functions inherited from org.lightjason.agentspeak.language.IShallowCopy< T >
T shallowcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.ITerm
ITerm EMPTY
empty term
long serialVersionUID = -3640918490398129717L
serial id
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Detailed Description
Template Parameters
T data type
Definition at line 39 of file IVariable.java.
Member Function Documentation
any()
boolean org.lightjason.agentspeak.language.variable.IVariable< T >.any ()
Returns
flag for any variable
Implemented in org.lightjason.agentspeak.language.variable.CVariable< T >.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.variableany().
mutex()
boolean org.lightjason.agentspeak.language.variable.IVariable< T >.mutex ()
Returns
mutex flag
Implemented in org.lightjason.agentspeak.language.variable.CMutexVariable< T >, and org.lightjason.agentspeak.language.variable.CVariable< T >.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.mutex(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variable(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablemutex().
set()
IVariable<T> org.lightjason.agentspeak.language.variable.IVariable< T >.set (@Nullable final T p_value)
Parameters
p_value value
Returns
the object itself
Implemented in org.lightjason.agentspeak.language.variable.CVariable< T >.
Referenced by org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.execute(), org.lightjason.agentspeak.language.execution.action.CSingleAssignment< M extends IExecution >.execute(), org.lightjason.agentspeak.language.execution.expressionunary.CIncrement< T extends Number >.execute(), org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.execute(), org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.execute(), org.lightjason.agentspeak.language.execution.action.CLambdaExpression.execute(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.relocate(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.relocate(), org.lightjason.agentspeak.language.variable.CMutexVariable< T >.set(), org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.set(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variable(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablemutex().