LightJason - AgentSpeak(L++): org.lightjason.agentspeak.grammar.CASTVisitorAgent Class Reference
org.lightjason.agentspeak.grammar.CASTVisitorAgent Class Reference
default abstract-syntax-tree (AST) visitor for agent scripts
Public Member Functions
CASTVisitorAgent (@Nonnull final Set< IAction > p_actions)
ctor
final Set< ILiteral > initialbeliefs ()
returns initial beliefs
final ILiteral initialgoal ()
returns the initial goal
final Set< IPlan > plans ()
get a multimap with event-plan matching
final Set< IRule > rules ()
returns the rules / principles
final Object visitAchievement_goal_action (final AgentParser.Achievement_goal_actionContext p_context)
final Object visitAgent (final AgentParser.AgentContext p_context)
final Object visitAnnotation_atom (final AgentParser.Annotation_atomContext p_context)
final Object visitAnnotation_literal (final AgentParser.Annotation_literalContext p_context)
Object visitAnnotation_value_literal (final AgentParser.Annotation_value_literalContext p_context)
final Object visitAnnotations (final AgentParser.AnnotationsContext p_context)
final Object visitAssignment_expression (final AgentParser.Assignment_expressionContext p_context)
final Object visitAssignment_expression_multivariable (final AgentParser.Assignment_expression_multivariableContext p_context)
final Object visitAssignment_expression_singlevariable (final AgentParser.Assignment_expression_singlevariableContext p_context)
final Object visitAtom (final AgentParser.AtomContext p_context)
final Object visitBelief (final AgentParser.BeliefContext p_context)
final Object visitBelief_action (final AgentParser.Belief_actionContext p_context)
final Object visitBinary_expression (final AgentParser.Binary_expressionContext p_context)
final Object visitBlock_formula (final AgentParser.Block_formulaContext p_context)
final Object visitBody (final AgentParser.BodyContext p_context)
final Object visitBody_formula (final AgentParser.Body_formulaContext p_context)
final Object visitDeconstruct_expression (final AgentParser.Deconstruct_expressionContext p_context)
final Object visitDigitsequence (final AgentParser.DigitsequenceContext p_context)
final Object visitExecutable_action (final AgentParser.Executable_actionContext p_context)
final Object visitExecutable_rule (final AgentParser.Executable_ruleContext p_context)
final Object visitExecutable_term (final AgentParser.Executable_termContext p_context)
final Object visitExpression (final AgentParser.ExpressionContext p_context)
final Object visitExpression_bracket (final AgentParser.Expression_bracketContext p_context)
final Object visitExpression_logical_and (final AgentParser.Expression_logical_andContext p_context)
final Object visitExpression_logical_element (final AgentParser.Expression_logical_elementContext p_context)
final Object visitExpression_logical_negation (final AgentParser.Expression_logical_negationContext p_context)
final Object visitExpression_logical_xor (final AgentParser.Expression_logical_xorContext p_context)
final Object visitExpression_numeric (final AgentParser.Expression_numericContext p_context)
final Object visitExpression_numeric_additive (final AgentParser.Expression_numeric_additiveContext p_context)
final Object visitExpression_numeric_element (final AgentParser.Expression_numeric_elementContext p_context)
final Object visitExpression_numeric_multiplicative (final AgentParser.Expression_numeric_multiplicativeContext p_context)
final Object visitExpression_numeric_power (final AgentParser.Expression_numeric_powerContext p_context)
final Object visitExpression_numeric_relation (final AgentParser.Expression_numeric_relationContext p_context)
final Object visitInitial_beliefs (final AgentParser.Initial_beliefsContext p_context)
final Object visitInitial_goal (final AgentParser.Initial_goalContext p_context)
final Object visitLambda (final AgentParser.LambdaContext p_context)
final Object visitLambda_initialization (final AgentParser.Lambda_initializationContext p_context)
final Object visitLambda_return (final AgentParser.Lambda_returnContext p_context)
final Object visitLiteral (final AgentParser.LiteralContext p_context)
final Object visitLogicalruledefinition (final AgentParser.LogicalruledefinitionContext p_context)
final Object visitLogicrule (final AgentParser.LogicruleContext p_context)
final Object visitLogicrules (final AgentParser.LogicrulesContext p_context)
final Object visitNumber (final AgentParser.NumberContext p_context)
final Object visitPlan (final AgentParser.PlanContext p_context)
final Object visitPlan_belief_trigger (final AgentParser.Plan_belief_triggerContext p_context)
final Object visitPlan_goal_trigger (final AgentParser.Plan_goal_triggerContext p_context)
final Object visitPlan_trigger (final AgentParser.Plan_triggerContext p_context)
final Object visitPlandefinition (final AgentParser.PlandefinitionContext p_context)
final Object visitPlans (final AgentParser.PlansContext p_context)
final Object visitRepair_formula (final AgentParser.Repair_formulaContext p_context)
final Object visitTerm (final AgentParser.TermContext p_context)
final Object visitTermlist (final AgentParser.TermlistContext p_context)
final Object visitTernary_operation (final AgentParser.Ternary_operationContext p_context)
final Object visitTernary_operation_false (final AgentParser.Ternary_operation_falseContext p_context)
final Object visitTernary_operation_true (final AgentParser.Ternary_operation_trueContext p_context)
final Object visitTest_action (final AgentParser.Test_actionContext p_context)
final Object visitUnary_expression (final AgentParser.Unary_expressionContext p_context)
final Object visitUnification (final AgentParser.UnificationContext p_context)
final Object visitUnification_constraint (final AgentParser.Unification_constraintContext p_context)
final Object visitVariable (final AgentParser.VariableContext p_context)
final Object visitVariable_evaluate (final AgentParser.Variable_evaluateContext p_context)
final Object visitVariableatom (final AgentParser.VariableatomContext p_context)
final Object visitVariablelist (final AgentParser.VariablelistContext p_context)
Protected Member Functions
Object visitLogicrulePlaceHolder (final AgentParser.LogicruleContext p_context)
create a rule placeholder object
Static Private Member Functions
static boolean logicalvalue (@Nonnull final String p_value)
converts a string token to the type
static Number numericonstant (@Nonnull final String p_value)
returns the value of a numeric constant
static String stringvalue (@Nonnull final String p_value)
create a string value without quotes
Private Attributes
final Map< IPath, IAction > m_actions
map with action definition
final Set< ILiteral > m_initialbeliefs = new LinkedHashSet<>()
set with initial beliefs
ILiteral m_initialgoal
initial goal
final Set< IPlan > m_plans = new HashSet<>()
map with plans
final Multimap< IPath, IRule > m_rules = LinkedHashMultimap.create()
map with logical rules
Static Private Attributes
static final Logger LOGGER = CCommon.logger(IASTVisitorAgent.class)
logger
Detailed Description
Note
methods are implemented twice agent and plan-bundle, because both use equal AgentSpeak(L) grammer, but AntLR visitor does not support inheritance by the grammar definition
Definition at line 111 of file CASTVisitorAgent.java.
Constructor & Destructor Documentation
CASTVisitorAgent()
org.lightjason.agentspeak.grammar.CASTVisitorAgent.CASTVisitorAgent (@Nonnull final Set< IAction > p_actions)
Parameters
p_actions set with actions
Definition at line 143 of file CASTVisitorAgent.java.
Member Function Documentation
initialbeliefs()
final Set<ILiteral> org.lightjason.agentspeak.grammar.CASTVisitorAgent.initialbeliefs ()
Returns
set with initial beliefs
Implements org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.
Definition at line 1059 of file CASTVisitorAgent.java.
initialgoal()
final ILiteral org.lightjason.agentspeak.grammar.CASTVisitorAgent.initialgoal ()
Returns
literal or null
Implements org.lightjason.agentspeak.grammar.IASTVisitorAgent.
Definition at line 1079 of file CASTVisitorAgent.java.
logicalvalue()
static boolean org.lightjason.agentspeak.grammar.CASTVisitorAgent.logicalvalue (@Nonnull final String p_value) static private
Parameters
p_value string value
Returns
boolean value
Definition at line 1036 of file CASTVisitorAgent.java.
numericonstant()
static Number org.lightjason.agentspeak.grammar.CASTVisitorAgent.numericonstant (@Nonnull final String p_value) static private
Parameters
p_value constant name
Returns
number value
Definition at line 1021 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.grammar.CCommon.NUMERICCONSTANT.
plans()
final Set<IPlan> org.lightjason.agentspeak.grammar.CASTVisitorAgent.plans ()
Returns
plan set
Implements org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.
Definition at line 1066 of file CASTVisitorAgent.java.
rules()
final Set<IRule> org.lightjason.agentspeak.grammar.CASTVisitorAgent.rules ()
Returns
rule set
Implements org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.
Definition at line 1073 of file CASTVisitorAgent.java.
stringvalue()
static String org.lightjason.agentspeak.grammar.CASTVisitorAgent.stringvalue (@Nonnull final String p_value) static private
Parameters
p_value string
Returns
string without quotes
Definition at line 1047 of file CASTVisitorAgent.java.
visitAchievement_goal_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAchievement_goal_action (final AgentParser.Achievement_goal_actionContext p_context)
Definition at line 576 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitAgent()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAgent (final AgentParser.AgentContext p_context)
Definition at line 155 of file CASTVisitorAgent.java.
visitAnnotation_atom()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAnnotation_atom (final AgentParser.Annotation_atomContext p_context)
Definition at line 293 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.ATOMIC, org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.PARALLEL.
visitAnnotation_literal()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAnnotation_literal (final AgentParser.Annotation_literalContext p_context)
Definition at line 305 of file CASTVisitorAgent.java.
visitAnnotation_value_literal()
Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAnnotation_value_literal (final AgentParser.Annotation_value_literalContext p_context)
Definition at line 311 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.CONSTANT, and org.lightjason.agentspeak.common.CCommon.languagestring().
visitAnnotations()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAnnotations (final AgentParser.AnnotationsContext p_context)
Definition at line 275 of file CASTVisitorAgent.java.
visitAssignment_expression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAssignment_expression (final AgentParser.Assignment_expressionContext p_context)
Definition at line 522 of file CASTVisitorAgent.java.
visitAssignment_expression_multivariable()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAssignment_expression_multivariable (final AgentParser.Assignment_expression_multivariableContext p_context)
Definition at line 537 of file CASTVisitorAgent.java.
visitAssignment_expression_singlevariable()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAssignment_expression_singlevariable (final AgentParser.Assignment_expression_singlevariableContext p_context)
Definition at line 528 of file CASTVisitorAgent.java.
visitAtom()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAtom (final AgentParser.AtomContext p_context)
Definition at line 726 of file CASTVisitorAgent.java.
visitBelief()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBelief (final AgentParser.BeliefContext p_context)
Definition at line 186 of file CASTVisitorAgent.java.
visitBelief_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBelief_action (final AgentParser.Belief_actionContext p_context)
Definition at line 622 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.ADD, org.lightjason.agentspeak.language.execution.action.CBeliefAction.EAction.DELETE, and org.lightjason.agentspeak.common.CCommon.languagestring().
visitBinary_expression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBinary_expression (final AgentParser.Binary_expressionContext p_context)
Definition at line 563 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.from(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
visitBlock_formula()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBlock_formula (final AgentParser.Block_formulaContext p_context)
Definition at line 448 of file CASTVisitorAgent.java.
visitBody()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBody (final AgentParser.BodyContext p_context)
Definition at line 361 of file CASTVisitorAgent.java.
visitBody_formula()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBody_formula (final AgentParser.Body_formulaContext p_context)
Definition at line 374 of file CASTVisitorAgent.java.
visitDeconstruct_expression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitDeconstruct_expression (final AgentParser.Deconstruct_expressionContext p_context)
Definition at line 634 of file CASTVisitorAgent.java.
visitDigitsequence()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitDigitsequence (final AgentParser.DigitsequenceContext p_context)
Definition at line 720 of file CASTVisitorAgent.java.
visitExecutable_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExecutable_action (final AgentParser.Executable_actionContext p_context)
Definition at line 973 of file CASTVisitorAgent.java.
visitExecutable_rule()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExecutable_rule (final AgentParser.Executable_ruleContext p_context)
Definition at line 979 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExecutable_term()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExecutable_term (final AgentParser.Executable_termContext p_context)
Definition at line 499 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression (final AgentParser.ExpressionContext p_context)
Definition at line 746 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression(), and org.lightjason.agentspeak.language.execution.expression.EOperator.OR.
visitExpression_bracket()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_bracket (final AgentParser.Expression_bracketContext p_context)
Definition at line 763 of file CASTVisitorAgent.java.
visitExpression_logical_and()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_and (final AgentParser.Expression_logical_andContext p_context)
Definition at line 769 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.AND, and org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression().
visitExpression_logical_element()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_element (final AgentParser.Expression_logical_elementContext p_context)
Definition at line 808 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression_logical_negation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_negation (final AgentParser.Expression_logical_negationContext p_context)
Definition at line 802 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.NEGATION.
visitExpression_logical_xor()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_xor (final AgentParser.Expression_logical_xorContext p_context)
Definition at line 781 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression(), org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.execution.expression.EOperator.XOR.
visitExpression_numeric()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric (final AgentParser.Expression_numericContext p_context)
Definition at line 829 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.EQUAL, org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.execution.expression.EOperator.NOTEQUAL.
visitExpression_numeric_additive()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_additive (final AgentParser.Expression_numeric_additiveContext p_context)
Definition at line 889 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.MINUS, and org.lightjason.agentspeak.language.execution.expression.EOperator.PLUS.
visitExpression_numeric_element()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_element (final AgentParser.Expression_numeric_elementContext p_context)
Definition at line 955 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression_numeric_multiplicative()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_multiplicative (final AgentParser.Expression_numeric_multiplicativeContext p_context)
Definition at line 912 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.DIVIDE, org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.MODULO, and org.lightjason.agentspeak.language.execution.expression.EOperator.MULTIPLY.
visitExpression_numeric_power()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_power (final AgentParser.Expression_numeric_powerContext p_context)
Definition at line 942 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.POWER.
visitExpression_numeric_relation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_relation (final AgentParser.Expression_numeric_relationContext p_context)
Definition at line 852 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.GREATER, org.lightjason.agentspeak.language.execution.expression.EOperator.GREATEREQUAL, org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.LESS, and org.lightjason.agentspeak.language.execution.expression.EOperator.LESSEQUAL.
visitInitial_beliefs()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitInitial_beliefs (final AgentParser.Initial_beliefsContext p_context)
Definition at line 163 of file CASTVisitorAgent.java.
visitInitial_goal()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitInitial_goal (final AgentParser.Initial_goalContext p_context)
Definition at line 173 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.CLiteral.from().
visitLambda()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLambda (final AgentParser.LambdaContext p_context)
Definition at line 461 of file CASTVisitorAgent.java.
visitLambda_initialization()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLambda_initialization (final AgentParser.Lambda_initializationContext p_context)
Definition at line 481 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitLambda_return()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLambda_return (final AgentParser.Lambda_returnContext p_context)
Definition at line 493 of file CASTVisitorAgent.java.
visitLiteral()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLiteral (final AgentParser.LiteralContext p_context)
Definition at line 648 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CPath.from().
visitLogicalruledefinition()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLogicalruledefinition (final AgentParser.LogicalruledefinitionContext p_context)
Definition at line 239 of file CASTVisitorAgent.java.
visitLogicrule()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLogicrule (final AgentParser.LogicruleContext p_context)
Definition at line 230 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.IDeepCopy< T >.deepcopy().
visitLogicrulePlaceHolder()
Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLogicrulePlaceHolder (final AgentParser.LogicruleContext p_context) protected
Parameters
p_context logical rule context
Returns
placeholder rule
Definition at line 1010 of file CASTVisitorAgent.java.
visitLogicrules()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLogicrules (final AgentParser.LogicrulesContext p_context)
Definition at line 207 of file CASTVisitorAgent.java.
visitNumber()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitNumber (final AgentParser.NumberContext p_context)
Definition at line 708 of file CASTVisitorAgent.java.
visitPlan()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlan (final AgentParser.PlanContext p_context)
Definition at line 245 of file CASTVisitorAgent.java.
visitPlan_belief_trigger()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlan_belief_trigger (final AgentParser.Plan_belief_triggerContext p_context)
Definition at line 349 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDBELIEF, org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEBELIEF, and org.lightjason.agentspeak.common.CCommon.languagestring().
visitPlan_goal_trigger()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlan_goal_trigger (final AgentParser.Plan_goal_triggerContext p_context)
Definition at line 337 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL, org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEGOAL, and org.lightjason.agentspeak.common.CCommon.languagestring().
visitPlan_trigger()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlan_trigger (final AgentParser.Plan_triggerContext p_context)
Definition at line 331 of file CASTVisitorAgent.java.
visitPlandefinition()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlandefinition (final AgentParser.PlandefinitionContext p_context)
Definition at line 264 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.execution.expression.IExpression.EMPTY.
visitPlans()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlans (final AgentParser.PlansContext p_context)
Definition at line 194 of file CASTVisitorAgent.java.
visitRepair_formula()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitRepair_formula (final AgentParser.Repair_formulaContext p_context)
Definition at line 380 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitTerm()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTerm (final AgentParser.TermContext p_context)
Definition at line 659 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitTermlist()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTermlist (final AgentParser.TermlistContext p_context)
Definition at line 684 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
visitTernary_operation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTernary_operation (final AgentParser.Ternary_operationContext p_context)
Definition at line 591 of file CASTVisitorAgent.java.
visitTernary_operation_false()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTernary_operation_false (final AgentParser.Ternary_operation_falseContext p_context)
Definition at line 607 of file CASTVisitorAgent.java.
visitTernary_operation_true()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTernary_operation_true (final AgentParser.Ternary_operation_trueContext p_context)
Definition at line 601 of file CASTVisitorAgent.java.
visitTest_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTest_action (final AgentParser.Test_actionContext p_context)
Definition at line 613 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CPath.from().
visitUnary_expression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitUnary_expression (final AgentParser.Unary_expressionContext p_context)
Definition at line 547 of file CASTVisitorAgent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitUnification()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitUnification (final AgentParser.UnificationContext p_context)
Definition at line 411 of file CASTVisitorAgent.java.
visitUnification_constraint()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitUnification_constraint (final AgentParser.Unification_constraintContext p_context)
Definition at line 433 of file CASTVisitorAgent.java.
visitVariable()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitVariable (final AgentParser.VariableContext p_context)
Definition at line 732 of file CASTVisitorAgent.java.
visitVariable_evaluate()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitVariable_evaluate (final AgentParser.Variable_evaluateContext p_context)
Definition at line 991 of file CASTVisitorAgent.java.
visitVariableatom()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitVariableatom (final AgentParser.VariableatomContext p_context)
Definition at line 740 of file CASTVisitorAgent.java.
visitVariablelist()
final Object org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitVariablelist (final AgentParser.VariablelistContext p_context)
Definition at line 697 of file CASTVisitorAgent.java.
Member Data Documentation
LOGGER
final Logger org.lightjason.agentspeak.grammar.CASTVisitorAgent.LOGGER = CCommon.logger(IASTVisitorAgent.class) static private
Definition at line 116 of file CASTVisitorAgent.java.
m_actions
final Map<IPath, IAction> org.lightjason.agentspeak.grammar.CASTVisitorAgent.m_actions private
Definition at line 136 of file CASTVisitorAgent.java.
m_initialbeliefs
final Set<ILiteral> org.lightjason.agentspeak.grammar.CASTVisitorAgent.m_initialbeliefs = new LinkedHashSet<>() private
Definition at line 124 of file CASTVisitorAgent.java.
m_initialgoal
ILiteral org.lightjason.agentspeak.grammar.CASTVisitorAgent.m_initialgoal private
Definition at line 120 of file CASTVisitorAgent.java.
m_plans
final Set<IPlan> org.lightjason.agentspeak.grammar.CASTVisitorAgent.m_plans = new HashSet<>() private
Definition at line 128 of file CASTVisitorAgent.java.
m_rules
final Multimap<IPath, IRule> org.lightjason.agentspeak.grammar.CASTVisitorAgent.m_rules = LinkedHashMultimap.create() private
Definition at line 132 of file CASTVisitorAgent.java.