LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expressionbinary.EOperator Enum Reference
org.lightjason.agentspeak.language.execution.expressionbinary.EOperator Enum Reference
binary operator
Inherits BiFunction< Number, Number, Number >.
Public Member Functions
EOperator (final String p_operator)
ctor
final Number apply (final Number p_lhs, final Number p_rhs)
final String toString ()
Static Public Member Functions
static EOperator from (@Nonnull final String p_value)
returns operator from string
Public Attributes
ASSIGNDECREMENT =("-=")
ASSIGNDIVIDE =("/=")
ASSIGNINCREMENT =("+=")
ASSIGNMODULO =("%=")
ASSIGNMULTIPLY =("*=")
ASSIGNPOW =("^=")
Private Attributes
final String m_operator
operator
Detailed Description
Definition at line 37 of file inary/EOperator.java.
Constructor & Destructor Documentation
EOperator()
org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.EOperator (final String p_operator)
Parameters
p_operator operator string
Definition at line 56 of file inary/EOperator.java.
Member Function Documentation
apply()
final Number org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.apply (final Number p_lhs, final Number p_rhs)
Definition at line 62 of file inary/EOperator.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.execute().
from()
static EOperator org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.from (@Nonnull final String p_value) static
Parameters
p_value string
Returns
operator
Definition at line 101 of file inary/EOperator.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBinary_expression(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBinary_expression().
toString()
final String org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.toString ()
Definition at line 90 of file inary/EOperator.java.
Member Data Documentation
ASSIGNDECREMENT
org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.ASSIGNDECREMENT =("-=")
Definition at line 40 of file inary/EOperator.java.
ASSIGNDIVIDE
org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.ASSIGNDIVIDE =("/=")
Definition at line 42 of file inary/EOperator.java.
ASSIGNINCREMENT
org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.ASSIGNINCREMENT =("+=")
Definition at line 39 of file inary/EOperator.java.
ASSIGNMODULO
org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.ASSIGNMODULO =("%=")
Definition at line 43 of file inary/EOperator.java.
ASSIGNMULTIPLY
org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.ASSIGNMULTIPLY =("*=")
Definition at line 41 of file inary/EOperator.java.
ASSIGNPOW
org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.ASSIGNPOW =("^=")
Definition at line 44 of file inary/EOperator.java.
m_operator
final String org.lightjason.agentspeak.language.execution.expressionbinary.EOperator.m_operator private
Definition at line 49 of file inary/EOperator.java.