LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CRepair Class Reference
org.lightjason.agentspeak.language.execution.action.CRepair Class Reference
defines an execution element with a repair call
Public Member Functions
CRepair (@Nonnull final IExecution p_value, @Nonnull final IExecution p_fallback)
ctor
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
final String toString ()
final Stream< IVariable<?> > variables ()
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExecution >
final T getValue ()
returns the value of the action
final boolean isValueAssignableTo (final Class<?> p_class)
checkes assinable of the value
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final IExecution m_fallback
fallback execution
Static Private Attributes
static final long serialVersionUID = 7095678561033158953L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExecution >
IBaseExecution (@Nullable final T p_value)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExecution >
final T m_value
data
Detailed Description
Definition at line 42 of file CRepair.java.
Constructor & Destructor Documentation
CRepair()
org.lightjason.agentspeak.language.execution.action.CRepair.CRepair (@Nonnull final IExecution p_value, @Nonnull final IExecution p_fallback)
Parameters
p_value execution element
p_fallback fallback execution
Definition at line 59 of file CRepair.java.
Member Function Documentation
execute()
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CRepair.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Definition at line 67 of file CRepair.java.
References org.lightjason.agentspeak.language.execution.IExecution.execute(), org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExecution >.m_value, and org.lightjason.agentspeak.language.fuzzy.IFuzzyValue< T >.value().
toString()
final String org.lightjason.agentspeak.language.execution.action.CRepair.toString ()
Definition at line 85 of file CRepair.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExecution >.m_value.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CRepair.variables ()
Definition at line 76 of file CRepair.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExecution >.m_value, and org.lightjason.agentspeak.language.execution.IExecution.variables().
Member Data Documentation
m_fallback
final IExecution org.lightjason.agentspeak.language.execution.action.CRepair.m_fallback private
Definition at line 51 of file CRepair.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.CRepair.serialVersionUID = 7095678561033158953L static private
Definition at line 47 of file CRepair.java.