LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes Enum Reference
org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes Enum Reference
graph types
Public Member Functions
final Graph<?, ?> get ()
returns a new graph instance
Static Public Member Functions
static boolean exist (@Nonnull final String p_value)
checks if a key exists
static EGraphTypes from (@Nonnull final String p_value)
returns graph type
Public Attributes
DIRECTEDSPARSE
DIRECTEDSPARSEMULTI
SPARSE
SPARSEMULTI
UNDIRECTEDSPARSE
Static Private Attributes
static final Set< String > TYPES
graph names
Detailed Description
Definition at line 98 of file graph/CCreate.java.
Member Function Documentation
exist()
static boolean org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.exist (@Nonnull final String p_value) static
Parameters
p_value name value
Returns
existance flag
Definition at line 155 of file graph/CCreate.java.
Referenced by org.lightjason.agentspeak.action.builtin.graph.CCreate.execute().
from()
static EGraphTypes org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.from (@Nonnull final String p_value) static
Parameters
p_value name value
Returns
graph type
Definition at line 167 of file graph/CCreate.java.
Referenced by org.lightjason.agentspeak.action.builtin.graph.CCreate.execute().
get()
final Graph<?, ?> org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.get ()
Returns
graph instance
Definition at line 122 of file graph/CCreate.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.action.builtin.graph.CCreate.execute().
Member Data Documentation
DIRECTEDSPARSE
org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.DIRECTEDSPARSE
Definition at line 102 of file graph/CCreate.java.
DIRECTEDSPARSEMULTI
org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.DIRECTEDSPARSEMULTI
Definition at line 103 of file graph/CCreate.java.
SPARSE
org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.SPARSE
Definition at line 100 of file graph/CCreate.java.
Referenced by org.lightjason.agentspeak.action.builtin.graph.CCreate.execute().
SPARSEMULTI
org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.SPARSEMULTI
Definition at line 101 of file graph/CCreate.java.
TYPES
static final Set<String> org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.TYPES static private
Initial value:
= Collections.unmodifiableSet(
            Arrays.stream( EGraphTypes.values() )
                  .map( i -> i.name().toUpperCase( Locale.ROOT ) )
                  .collect( Collectors.toSet() )
        )
Definition at line 110 of file graph/CCreate.java.
UNDIRECTEDSPARSE
org.lightjason.agentspeak.action.builtin.graph.CCreate.EGraphTypes.UNDIRECTEDSPARSE
Definition at line 104 of file graph/CCreate.java.