LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower Class Reference
org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower Class Reference
tower
Inherits Stack< CSlice >.
Public Member Functions
final synchronized boolean empty ()
final synchronized CSlice peek ()
final synchronized CSlice pop ()
final synchronized CSlice push (final CSlice p_item)
final synchronized int search (final Object p_object)
Static Private Attributes
static final transient long serialVersionUID = 1361367629042813689L
serial id
Detailed Description
Definition at line 554 of file TestCHanoiTowers.java.
Member Function Documentation
empty()
final synchronized boolean org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower.empty ()
Definition at line 586 of file TestCHanoiTowers.java.
peek()
final synchronized CSlice org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower.peek ()
Definition at line 580 of file TestCHanoiTowers.java.
pop()
final synchronized CSlice org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower.pop ()
Definition at line 571 of file TestCHanoiTowers.java.
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPop.execute().
push()
final synchronized CSlice org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower.push (final CSlice p_item)
Definition at line 562 of file TestCHanoiTowers.java.
References org.lightjason.agentspeak.agent.TestCHanoiTowers.CSlice.size().
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPush.execute(), and org.lightjason.agentspeak.agent.TestCHanoiTowers.setup().
search()
final synchronized int org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower.search (final Object p_object)
Definition at line 592 of file TestCHanoiTowers.java.
Member Data Documentation
serialVersionUID
final transient long org.lightjason.agentspeak.agent.TestCHanoiTowers.CTower.serialVersionUID = 1361367629042813689L static private
Definition at line 559 of file TestCHanoiTowers.java.