LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap Class Reference
test action map
Public Member Functions
final void create ()
test map create
final void getmultiple ()
test get-multiple
final void getsingle ()
test get-single
final void keysvalues ()
test map keys
final void putmultiple ()
test multiple put
final void putsingle ()
test map putsingle
final void remove ()
test remove
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 58 of file TestCActionCollectionMap.java.
Member Function Documentation
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.create ()
Definition at line 65 of file TestCActionCollectionMap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
getmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.getmultiple ()
Definition at line 236 of file TestCActionCollectionMap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.IMapGetMultiple< T >.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
getsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.getsingle ()
Definition at line 262 of file TestCActionCollectionMap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.IMapGetSingle< T >.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
keysvalues()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.keysvalues ()
Definition at line 107 of file TestCActionCollectionMap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.map.CKeys.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CValues.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
putmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.putmultiple ()
Definition at line 180 of file TestCActionCollectionMap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.IMapApplyMultiple< T >.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
putsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.putsingle ()
Definition at line 145 of file TestCActionCollectionMap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.IMapApplySingle< T >.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
remove()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.remove ()
Definition at line 211 of file TestCActionCollectionMap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CRemove.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().