LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionCollection Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionCollection Class Reference
test collection action
Public Member Functions
final void clear ()
test clear
final void empty ()
test empty
final void size (final Pair< List< ITerm >, int[]> p_input)
test size
Static Public Member Functions
static Object [] generate ()
data provider generator
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 62 of file TestCActionCollection.java.
Member Function Documentation
clear()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollection.clear ()
Definition at line 174 of file TestCActionCollection.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.CClear.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
empty()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollection.empty ()
Definition at line 153 of file TestCActionCollection.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.CIsEmpty.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
generate()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionCollection.generate () static
Returns
data
Definition at line 70 of file TestCActionCollection.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
size()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollection.size (final Pair< List< ITerm >, int[]> p_input)
Parameters
p_input pair input data term and results
Definition at line 131 of file TestCActionCollection.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.action.builtin.collection.CSize.execute().