LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.variable.CVariableEvaluate Class Reference
org.lightjason.agentspeak.language.variable.CVariableEvaluate Class Reference
structure for creating evaluate variables
Public Member Functions
CVariableEvaluate (@Nonnull final IVariable<?> p_variable)
ctor
CVariableEvaluate (@Nonnull final IVariable<?> p_variable, @Nonnull final List< ITerm > p_parameter)
ctor
final ITerm deepcopy (final IPath... p_prefix)
final ITerm deepcopysuffix ()
final boolean equals (final Object p_object)
final ILiteral evaluate (final IContext p_context)
evaluates the content of the variable
final IPath fqnfunctor ()
returns the full-qualified functor with path and name
final String functor ()
returns the functor without path
final IPath functorpath ()
returns the path of the functor
final int hashCode ()
final boolean hasVariable ()
checks if the literal has variables
final boolean mutex ()
returns mutex flag
final< T > T raw ()
cast to any raw value type
final int structurehash ()
returns a hash value which defines a hash ove rthe structure
final String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.ITerm
default< T extends ITerm > T term ()
casts the object to a term-type
Public Member Functions inherited from org.lightjason.agentspeak.language.IDeepCopy< ITerm >
T deepcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T deepcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Private Member Functions
ILiteral fromLiteral (final ILiteral p_literal, final IContext p_context)
creates the result literal from an input literal
ILiteral fromString (final String p_value, final IContext p_context)
creates the result literal from an input string
Private Attributes
final List< ITerm > m_parameter
optional parameter list
final IVariable<?> m_variable
content variable with a string or literal
Static Private Attributes
static final long serialVersionUID = 7310663182659231951L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.ITerm
ITerm EMPTY
empty term
long serialVersionUID = -3640918490398129717L
serial id
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Detailed Description
Definition at line 44 of file CVariableEvaluate.java.
Constructor & Destructor Documentation
CVariableEvaluate() [1/2]
org.lightjason.agentspeak.language.variable.CVariableEvaluate.CVariableEvaluate (@Nonnull final IVariable<?> p_variable)
Parameters
p_variable variable
Definition at line 64 of file CVariableEvaluate.java.
CVariableEvaluate() [2/2]
org.lightjason.agentspeak.language.variable.CVariableEvaluate.CVariableEvaluate (@Nonnull final IVariable<?> p_variable, @Nonnull final List< ITerm > p_parameter)
Parameters
p_variable variable
p_parameter optional parameter list
Definition at line 75 of file CVariableEvaluate.java.
Member Function Documentation
deepcopy()
final ITerm org.lightjason.agentspeak.language.variable.CVariableEvaluate.deepcopy (final IPath... p_prefix)
Definition at line 172 of file CVariableEvaluate.java.
deepcopysuffix()
final ITerm org.lightjason.agentspeak.language.variable.CVariableEvaluate.deepcopysuffix ()
Definition at line 179 of file CVariableEvaluate.java.
equals()
final boolean org.lightjason.agentspeak.language.variable.CVariableEvaluate.equals (final Object p_object)
Definition at line 126 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.hashCode().
evaluate()
final ILiteral org.lightjason.agentspeak.language.variable.CVariableEvaluate.evaluate (final IContext p_context)
Parameters
p_context execution context
Returns
unified literal
Implements org.lightjason.agentspeak.language.variable.IVariableEvaluate.
Definition at line 90 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral(), and org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromString().
fqnfunctor()
final IPath org.lightjason.agentspeak.language.variable.CVariableEvaluate.fqnfunctor ()
Returns
fqn functor
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 153 of file CVariableEvaluate.java.
fromLiteral()
ILiteral org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral (final ILiteral p_literal, final IContext p_context) private
Parameters
p_literal input literal
p_context execution context
Returns
result literal
Definition at line 209 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.ITerm.fqnfunctor(), org.lightjason.agentspeak.language.ILiteral.hasAt(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter, org.lightjason.agentspeak.language.ILiteral.negated(), and org.lightjason.agentspeak.language.ILiteral.unify().
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.evaluate().
fromString()
ILiteral org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromString (final String p_value, final IContext p_context) private
Parameters
p_value input string (literal functor)
p_context execution context
Returns
result literal
Definition at line 197 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.CLiteral.from(), and org.lightjason.agentspeak.language.ILiteral.unify().
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.evaluate().
functor()
final String org.lightjason.agentspeak.language.variable.CVariableEvaluate.functor ()
Returns
functor
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 139 of file CVariableEvaluate.java.
functorpath()
final IPath org.lightjason.agentspeak.language.variable.CVariableEvaluate.functorpath ()
Returns
path
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 146 of file CVariableEvaluate.java.
hashCode()
final int org.lightjason.agentspeak.language.variable.CVariableEvaluate.hashCode ()
Definition at line 120 of file CVariableEvaluate.java.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.equals().
hasVariable()
final boolean org.lightjason.agentspeak.language.variable.CVariableEvaluate.hasVariable ()
Returns
variable flag
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 159 of file CVariableEvaluate.java.
mutex()
final boolean org.lightjason.agentspeak.language.variable.CVariableEvaluate.mutex ()
Returns
mutex flag
Implements org.lightjason.agentspeak.language.variable.IVariableEvaluate.
Definition at line 83 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.IVariable< T >.mutex().
raw()
final<T> T org.lightjason.agentspeak.language.variable.CVariableEvaluate.raw ()
Template Parameters
raw type
Returns
any type
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 165 of file CVariableEvaluate.java.
structurehash()
final int org.lightjason.agentspeak.language.variable.CVariableEvaluate.structurehash ()
Returns
structure hash value
Implements org.lightjason.agentspeak.language.IStructureHash.
Definition at line 185 of file CVariableEvaluate.java.
toString()
final String org.lightjason.agentspeak.language.variable.CVariableEvaluate.toString ()
Definition at line 132 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter.
variables()
Stream<IVariable<?> > org.lightjason.agentspeak.language.variable.CVariableEvaluate.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.variable.IVariableEvaluate.
Definition at line 108 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.ITerm.term().
Member Data Documentation
m_parameter
final List<ITerm> org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter private
Definition at line 57 of file CVariableEvaluate.java.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral(), and org.lightjason.agentspeak.language.variable.CVariableEvaluate.toString().
m_variable
final IVariable<?> org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_variable private
Definition at line 53 of file CVariableEvaluate.java.
serialVersionUID
final long org.lightjason.agentspeak.language.variable.CVariableEvaluate.serialVersionUID = 7310663182659231951L static private
Definition at line 49 of file CVariableEvaluate.java.