LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple Class Reference
test collection tuple
Public Member Functions
final void create ()
test tuple creating
final void createerror ()
test tuple creating error
final void flat ()
test tuple flat
final void set ()
test tuple set
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 47 of file TestCActionCollectionTuple.java.
Member Function Documentation
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.create ()
Definition at line 54 of file TestCActionCollectionTuple.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
createerror()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.createerror ()
Definition at line 77 of file TestCActionCollectionTuple.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN.
flat()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.flat ()
Definition at line 111 of file TestCActionCollectionTuple.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CFlat.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
set()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.set ()
Definition at line 93 of file TestCActionCollectionTuple.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CSet.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().