LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionGenericType Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionGenericType Class Reference
test generic-type actions
Public Member Functions
final void createliteral ()
test create literal action
final void is ()
test "is" action
final void isnull ()
test "isnull"action
final void isnumeric ()
test "isnumeric" action
final void isstring ()
test "isstring" action
final void parsefloat ()
test parse-float action
final void parseliteral ()
test parse literal action
final void parseliteralerror ()
test parse literal action with error
final void tofloat ()
test "tofloat"
final void tofloaterror ()
test "tofloat" error
final void tostring ()
test "tostring"
final void type ()
test type action
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 56 of file TestCActionGenericType.java.
Member Function Documentation
createliteral()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.createliteral ()
Definition at line 63 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.type.CCreateLiteral.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.CLiteral.from().
is()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.is ()
Definition at line 179 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
isnull()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isnull ()
Definition at line 203 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
isnumeric()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isnumeric ()
Definition at line 227 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
isstring()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isstring ()
Definition at line 251 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
parsefloat()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.parsefloat ()
Definition at line 135 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.type.IParse.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
parseliteral()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.parseliteral ()
Definition at line 90 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.type.IParse.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.CLiteral.from().
parseliteralerror()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.parseliteralerror ()
Definition at line 117 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
tofloat()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.tofloat ()
Definition at line 298 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.type.ICast.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
tofloaterror()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.tofloaterror ()
Definition at line 319 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
tostring()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.tostring ()
Definition at line 276 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.type.ICast.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
type()
final void org.lightjason.agentspeak.action.builtin.TestCActionGenericType.type ()
Definition at line 157 of file TestCActionGenericType.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.type.CType.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().