LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CRawAction< T > Class Template Reference
org.lightjason.agentspeak.language.execution.action.CRawAction< T > Class Template Reference
encapsulate class for any non-executable data type e.g.
Public Member Functions
CRawAction (@Nullable final T p_data)
ctor
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
final T getValue ()
returns the value of the action
final boolean isValueAssignableTo (final Class<?> p_class)
checkes assinable of the value
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Member Functions
IFuzzyValue< Boolean > getTypedResult (@Nonnull final Boolean p_execution, @Nonnull final List< ITerm > p_return)
fixed type result
IFuzzyValue< Boolean > getTypedResult (@Nonnull final IVariable<?> p_execution, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_return)
fixed type result
IFuzzyValue< Boolean > getTypedResult (@Nonnull final IExpression p_execution, @Nonnull final IContext p_context, @Nonnull final Boolean p_parallel, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
fixed type result
IFuzzyValue< Boolean > getTypedResult (@Nullable final T p_execution, @Nonnull final List< ITerm > p_return)
fixed type result
Static Private Attributes
static final long serialVersionUID = 7181432659241612718L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
IBaseExecution (@Nullable final T p_value)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
final T m_value
data
Detailed Description
boolean and caching of execution results
Definition at line 47 of file CRawAction.java.
Constructor & Destructor Documentation
CRawAction()
org.lightjason.agentspeak.language.execution.action.CRawAction< T >.CRawAction (@Nullable final T p_data)
Parameters
p_data any object data
Definition at line 59 of file CRawAction.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.action.CRawAction< T >.equals (final Object p_object)
Definition at line 85 of file CRawAction.java.
References org.lightjason.agentspeak.language.execution.action.CRawAction< T >.hashCode().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CRawAction< T >.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 99 of file CRawAction.java.
References org.lightjason.agentspeak.language.execution.action.CRawAction< T >.getTypedResult(), and org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value.
getTypedResult() [1/4]
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CRawAction< T >.getTypedResult (@Nonnull final Boolean p_execution, @Nonnull final List< ITerm > p_return) private
Parameters
p_execution boolean value
p_return native return
Returns
fuzzy-boolean
Definition at line 120 of file CRawAction.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
Referenced by org.lightjason.agentspeak.language.execution.action.CRawAction< T >.execute().
getTypedResult() [2/4]
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CRawAction< T >.getTypedResult (@Nonnull final IVariable<?> p_execution, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_return) private
Parameters
p_execution variable value
p_context context
p_return native return
Returns
fuzzy-boolean
Definition at line 135 of file CRawAction.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
getTypedResult() [3/4]
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CRawAction< T >.getTypedResult (@Nonnull final IExpression p_execution, @Nonnull final IContext p_context, @Nonnull final Boolean p_parallel, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return) private
Parameters
p_execution execution element
p_context context
p_parallel paralle execution
p_argument arguments
p_return native return
Returns
fuzzy-boolean
Definition at line 162 of file CRawAction.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
getTypedResult() [4/4]
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CRawAction< T >.getTypedResult (@Nullable final T p_execution, @Nonnull final List< ITerm > p_return) private
Parameters
p_execution any other value
p_return native return
Returns
fuzzy-boolean
Definition at line 183 of file CRawAction.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
hashCode()
final int org.lightjason.agentspeak.language.execution.action.CRawAction< T >.hashCode ()
Definition at line 79 of file CRawAction.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value.
Referenced by org.lightjason.agentspeak.language.execution.action.CRawAction< T >.equals().
toString()
final String org.lightjason.agentspeak.language.execution.action.CRawAction< T >.toString ()
Definition at line 91 of file CRawAction.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CRawAction< T >.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 67 of file CRawAction.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value.
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.CRawAction< T >.serialVersionUID = 7181432659241612718L static private
Definition at line 52 of file CRawAction.java.