LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathShape Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathShape Class Reference
test math shape functions
Public Member Functions
final void incircle ()
test in circle
final void inrechtangle ()
test in rechtangle
final void intriangle ()
test in triangle
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 44 of file TestCActionMathShape.java.
Member Function Documentation
incircle()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathShape.incircle ()
Definition at line 51 of file TestCActionMathShape.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.shape.CInCircle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
inrechtangle()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathShape.inrechtangle ()
Definition at line 70 of file TestCActionMathShape.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.shape.CInRectangle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
intriangle()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathShape.intriangle ()
Definition at line 89 of file TestCActionMathShape.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.shape.CInTriangle.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().