LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic Interface Reference
org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic Interface Reference
plan statistic
Public Member Functions
long count ()
returns the number of executions
long fail ()
returns number of failed execution
double failratio ()
returns the ratio of failed executions
IPlanStatistic incrementfail ()
increments the failed executions
IPlanStatistic incrementsuccessful ()
increments the successful executions
IPlan plan ()
plan reference
long successful ()
returns number of successful execution
double successfulratio ()
returns the ratio of successful execution
Stream< IVariable<?> > variables ()
returns a stream with variables of the internal data
Detailed Description
Definition at line 37 of file IPlanStatistic.java.
Member Function Documentation
count()
long org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.count ()
Returns
number of executions
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.
fail()
long org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.fail ()
Returns
number of executions
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.
Referenced by org.lightjason.agentspeak.action.builtin.agent.CPlanStatistic.statistic().
failratio()
double org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.failratio ()
Returns
ratio
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.
incrementfail()
IPlanStatistic org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.incrementfail ()
Returns
self reference
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.
incrementsuccessful()
IPlanStatistic org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.incrementsuccessful ()
Returns
self reference
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.
plan()
IPlan org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.plan ()
Returns
plan
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.addplan(), and org.lightjason.agentspeak.action.builtin.agent.CGetPlan.query().
successful()
long org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.successful ()
Returns
number of executions
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.
Referenced by org.lightjason.agentspeak.action.builtin.agent.CPlanStatistic.statistic().
successfulratio()
double org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.successfulratio ()
Returns
ratio
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.
variables()
Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.variables ()
Returns
variable stream
Implemented in org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.