LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.IBaseAction Class Reference
org.lightjason.agentspeak.action.IBaseAction Class Reference abstract
default implementation of an action
Public Member Functions
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default int minimalArgumentNumber ()
minimum number of arguments
IPath name ()
returns the name with path of the action
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.IExecution
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Static Protected Attributes
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Static Private Attributes
static final long serialVersionUID = -1706803039397374484L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Detailed Description
Definition at line 32 of file IBaseAction.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.action.IBaseAction.equals (final Object p_object)
Definition at line 51 of file IBaseAction.java.
References org.lightjason.agentspeak.action.IBaseAction.hashCode().
Referenced by org.lightjason.agentspeak.action.binding.CMethodAction.returnvalues().
hashCode()
final int org.lightjason.agentspeak.action.IBaseAction.hashCode ()
Definition at line 45 of file IBaseAction.java.
References org.lightjason.agentspeak.action.IAction.name().
Referenced by org.lightjason.agentspeak.action.IBaseAction.equals(), and org.lightjason.agentspeak.action.builtin.generic.CPrint.IFormatter< Boolean >.equals().
toString()
final String org.lightjason.agentspeak.action.IBaseAction.toString ()
Definition at line 57 of file IBaseAction.java.
References org.lightjason.agentspeak.action.IAction.name().
Referenced by org.lightjason.agentspeak.action.builtin.string.CReverse.execute().
Member Data Documentation
LOGGER
final Logger org.lightjason.agentspeak.action.IBaseAction.LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class) static protected
Definition at line 37 of file IBaseAction.java.
Referenced by org.lightjason.agentspeak.action.binding.CMethodAction.execute().
serialVersionUID
final long org.lightjason.agentspeak.action.IBaseAction.serialVersionUID = -1706803039397374484L static private
Definition at line 41 of file IBaseAction.java.