LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.CRawTerm< T > Class Template Reference
org.lightjason.agentspeak.language.CRawTerm< T > Class Template Reference
term structure for simple datatypes
Public Member Functions
final boolean allocated ()
final ITerm deepcopy (final IPath... p_prefix)
final ITerm deepcopysuffix ()
final boolean equals (final Object p_object)
final IPath fqnfunctor ()
returns the full-qualified functor with path and name
final String functor ()
returns the functor without path
final IPath functorpath ()
returns the path of the functor
final int hashCode ()
final boolean hasVariable ()
checks if the literal has variables
final< N > N raw ()
cast to any raw value type
final int structurehash ()
returns a hash value which defines a hash ove rthe structure
final IRawTerm< T > thrownotallocated () throws IllegalStateException
final IRawTerm< T > throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
final String toString ()
final boolean valueassignableto (@Nonnull final Class<?>... p_class)
Public Member Functions inherited from org.lightjason.agentspeak.language.ITerm
default< T extends ITerm > T term ()
casts the object to a term-type
Public Member Functions inherited from org.lightjason.agentspeak.language.IDeepCopy< ITerm >
T deepcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T deepcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Public Member Functions inherited from org.lightjason.agentspeak.language.IRawStructure< IRawTerm< T > >
boolean allocated ()
returns allocated state
T thrownotallocated () throws IllegalStateException
throws an illegal state exception iif the variable is not allocated
Static Public Member Functions
static< N > CRawTerm< N > from (final N p_value)
factory for a raw term
Static Public Attributes
static final ITerm EMPTY = new CRawTerm<>(null)
empty raw term
Package Functions
public< N > CRawTerm (@Nullable final N p_value)
ctor
Private Attributes
final IPath m_functor
functor
final int m_hashcode
hash code cache
final T m_value
value data
Static Private Attributes
static final long serialVersionUID = 8660012856755452965L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.IRawTerm< T >
IRawTerm<?> EMPTY = new CRawTerm<>(null)
empty raw term
Public Attributes inherited from org.lightjason.agentspeak.language.ITerm
ITerm EMPTY
empty term
long serialVersionUID = -3640918490398129717L
serial id
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Detailed Description
Warning
hash code is defined on the input data type
Definition at line 45 of file CRawTerm.java.
Constructor & Destructor Documentation
CRawTerm()
public<N> org.lightjason.agentspeak.language.CRawTerm< T >.CRawTerm (@Nullable final N p_value) package
Parameters
p_value any value tue
Template Parameters
N value type
Definition at line 77 of file CRawTerm.java.
References org.lightjason.agentspeak.common.IPath.EMPTY, org.lightjason.agentspeak.language.ITerm.fqnfunctor(), org.lightjason.agentspeak.common.CPath.from(), and org.lightjason.agentspeak.language.ITerm.raw().
Member Function Documentation
allocated()
final boolean org.lightjason.agentspeak.language.CRawTerm< T >.allocated ()
Definition at line 173 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.m_value.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.equals(), and org.lightjason.agentspeak.language.CRawTerm< T >.thrownotallocated().
deepcopy()
final ITerm org.lightjason.agentspeak.language.CRawTerm< T >.deepcopy (final IPath... p_prefix)
Definition at line 206 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CCommon.deepclone(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.CRawTerm< T >.m_value.
deepcopysuffix()
final ITerm org.lightjason.agentspeak.language.CRawTerm< T >.deepcopysuffix ()
Definition at line 213 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.CRawTerm< T >.m_value.
equals()
final boolean org.lightjason.agentspeak.language.CRawTerm< T >.equals (final Object p_object)
Definition at line 119 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.allocated(), org.lightjason.agentspeak.language.CRawTerm< T >.hashCode(), and org.lightjason.agentspeak.language.CRawTerm< T >.raw().
fqnfunctor()
final IPath org.lightjason.agentspeak.language.CRawTerm< T >.fqnfunctor ()
Returns
fqn functor
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 154 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.m_functor.
from()
static <N> CRawTerm<N> org.lightjason.agentspeak.language.CRawTerm< T >.from (final N p_value) static
Parameters
p_value any value
Returns
raw term
Template Parameters
N type
Definition at line 104 of file CRawTerm.java.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.add(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.add(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.addedgemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.addedgesingle(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.addplan(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.addstatisticvalue(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.addvertexmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.addvertexsingle(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithkeystrean(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithoutkeys(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.adjacencymatrix(), org.lightjason.agentspeak.action.builtin.TestCActionMath.aggregationvaluetestcase(), org.lightjason.agentspeak.action.builtin.collection.map.CGetMultiple.apply(), org.lightjason.agentspeak.action.builtin.collection.map.CGetSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CSuccessorCountMultiple.apply(), org.lightjason.agentspeak.action.builtin.collection.multimap.CGetMultiple.apply(), org.lightjason.agentspeak.action.builtin.collection.multimap.CGetSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CIsNeighborMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CIsPredecessorMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CIsNeighborSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CIsPredecessorSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CIsSuccessorMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CIsSuccessorSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CIsIncidentMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.COppositeMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.COppositeSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.COutDegreeMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.COutDegreeSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CPredecessorCountMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CPredecessorCountSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CFindEdgeMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CIncidentCountMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CIncidentCountSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CSuccessorCountSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CInDegreeSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CInDegreeMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CDegreeMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CIsIncidentSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CNeighborsCountMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CDegreeSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CNeighborsCountSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CEndPointMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CEndPointSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.COutEdgesMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CFindEdgeSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CIncidentVerticesMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CIncidentVerticesSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CEdgeListMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CNeighborsMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.CNeighborsSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CInEdgesMultiple.apply(), org.lightjason.agentspeak.action.builtin.graph.COutEdgesSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CInEdgesSingle.apply(), org.lightjason.agentspeak.action.builtin.graph.CEdgeListSingle.apply(), org.lightjason.agentspeak.action.builtin.string.CBase64Decode.apply(), org.lightjason.agentspeak.action.builtin.math.blas.CElementWise.apply(), org.lightjason.agentspeak.action.builtin.math.blas.CMultiply.apply(), org.lightjason.agentspeak.action.builtin.TestCActionDateTime.applyplus(), org.lightjason.agentspeak.action.builtin.TestCActionDateTime.applysminus(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.asmap(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.assignmatrix(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.assignscalar(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.assignscalar(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.assignvector(), org.lightjason.agentspeak.action.builtin.TestCActionString.base64(), org.lightjason.agentspeak.action.builtin.TestCActionString.base64decodeerror(), org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.belieflist(), org.lightjason.agentspeak.action.builtin.TestCActionMath.binomial(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.boolValue(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.boolValue(), org.lightjason.agentspeak.action.builtin.TestCActionDateTime.build(), org.lightjason.agentspeak.action.builtin.generic.type.CToNumber.cast(), org.lightjason.agentspeak.action.builtin.generic.type.CToString.cast(), org.lightjason.agentspeak.language.execution.expression.CAtom.CAtom(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.clear(), org.lightjason.agentspeak.action.builtin.TestCActionCollection.clear(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.clear(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.column(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.column(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.columsum(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.complement(), org.lightjason.agentspeak.action.builtin.TestCActionString.concat(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.contains(), org.lightjason.agentspeak.action.builtin.TestCActionString.contains(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.containsedge(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.containsvertex(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.copy(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.copy(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.create(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.create(), org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate.create(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.create(), org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.create(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.create(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.create(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.create(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.create(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.create(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.create(), org.lightjason.agentspeak.action.builtin.TestCActionDateTime.create(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.createdistribution(), org.lightjason.agentspeak.action.builtin.TestCActionDateTime.createerror(), org.lightjason.agentspeak.action.builtin.TestCActionCrypto.createkey(), org.lightjason.agentspeak.action.builtin.TestCActionCrypto.createkeyError(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.createliteral(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.createstatistics(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.createsynchronized(), org.lightjason.agentspeak.action.builtin.crypto.CDecrypt.decrypt(), org.lightjason.agentspeak.action.builtin.TestCActionCrypto.decryptexecutionerror(), org.lightjason.agentspeak.language.CRawTerm< T >.deepcopy(), org.lightjason.agentspeak.language.CRawTerm< T >.deepcopysuffix(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.degreemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.degreesingle(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.descriptivemultiplestatisticvalue(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.diagonal(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.distancepath(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.edgecount(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.edgelistmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.edgelistsingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.edges(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.eigen(), org.lightjason.agentspeak.action.builtin.datetime.CDate.elements(), org.lightjason.agentspeak.action.builtin.datetime.CZoneid.elements(), org.lightjason.agentspeak.action.builtin.datetime.CCreate.elements(), org.lightjason.agentspeak.action.builtin.datetime.CTime.elements(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.elementwisematrix(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.elementwisevector(), org.lightjason.agentspeak.action.builtin.TestCActionCollection.empty(), org.lightjason.agentspeak.action.builtin.crypto.CEncrypt.encrypt(), org.lightjason.agentspeak.action.builtin.TestCActionCrypto.encryptdecreypt(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.endpointmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.endpointsingle(), org.lightjason.agentspeak.action.builtin.TestCActionString.endswidth(), org.lightjason.agentspeak.action.builtin.TestCActionBool.equal(), org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.equationconstraint(), org.lightjason.agentspeak.action.builtin.agent.CCycleTime.execute(), org.lightjason.agentspeak.action.builtin.generic.CUuid.execute(), org.lightjason.agentspeak.action.builtin.agent.CPlanList.execute(), org.lightjason.agentspeak.action.builtin.datetime.IDateTime.execute(), org.lightjason.agentspeak.action.builtin.math.CSum.execute(), org.lightjason.agentspeak.action.builtin.bool.CCountTrue.execute(), org.lightjason.agentspeak.action.builtin.string.CUpper.execute(), org.lightjason.agentspeak.action.builtin.math.CAbs.execute(), org.lightjason.agentspeak.action.builtin.string.CLower.execute(), org.lightjason.agentspeak.action.builtin.agent.CBeliefList.execute(), org.lightjason.agentspeak.action.builtin.math.CCos.execute(), org.lightjason.agentspeak.action.builtin.string.CReverse.execute(), org.lightjason.agentspeak.action.builtin.bool.CCountFalse.execute(), org.lightjason.agentspeak.action.builtin.math.CSin.execute(), org.lightjason.agentspeak.action.builtin.string.CSize.execute(), org.lightjason.agentspeak.action.builtin.math.CSqrt.execute(), org.lightjason.agentspeak.action.builtin.math.CASin.execute(), org.lightjason.agentspeak.action.builtin.math.CDegrees.execute(), org.lightjason.agentspeak.action.builtin.math.CACos.execute(), org.lightjason.agentspeak.action.builtin.math.CLog10.execute(), org.lightjason.agentspeak.action.builtin.string.CContains.execute(), org.lightjason.agentspeak.action.builtin.string.CEndsWith.execute(), org.lightjason.agentspeak.action.builtin.math.CExp.execute(), org.lightjason.agentspeak.action.builtin.math.CCosh.execute(), org.lightjason.agentspeak.action.builtin.math.CRadians.execute(), org.lightjason.agentspeak.action.builtin.math.CFloor.execute(), org.lightjason.agentspeak.action.builtin.math.CATan.execute(), org.lightjason.agentspeak.action.builtin.math.CCeil.execute(), org.lightjason.agentspeak.action.builtin.math.CSignum.execute(), org.lightjason.agentspeak.action.builtin.math.CSinh.execute(), org.lightjason.agentspeak.action.builtin.string.CStartsWith.execute(), org.lightjason.agentspeak.action.builtin.math.CHypot.execute(), org.lightjason.agentspeak.action.builtin.math.CTanh.execute(), org.lightjason.agentspeak.action.builtin.graph.CVertexCount.execute(), org.lightjason.agentspeak.action.builtin.bool.CXor.execute(), org.lightjason.agentspeak.action.builtin.string.CConcat.execute(), org.lightjason.agentspeak.action.builtin.math.CLog.execute(), org.lightjason.agentspeak.action.builtin.math.CMax.execute(), org.lightjason.agentspeak.action.builtin.math.CMin.execute(), org.lightjason.agentspeak.action.builtin.math.CAverage.execute(), org.lightjason.agentspeak.action.builtin.graph.CEdgeCount.execute(), org.lightjason.agentspeak.action.builtin.bool.CNot.execute(), org.lightjason.agentspeak.action.builtin.bool.COr.execute(), org.lightjason.agentspeak.action.builtin.math.CFactorial.execute(), org.lightjason.agentspeak.action.builtin.math.CPow.execute(), org.lightjason.agentspeak.action.builtin.math.CGeometricMean.execute(), org.lightjason.agentspeak.action.builtin.math.CRound.execute(), org.lightjason.agentspeak.action.builtin.bool.CAnd.execute(), org.lightjason.agentspeak.action.builtin.math.CHarmonicMean.execute(), org.lightjason.agentspeak.action.builtin.math.CTan.execute(), org.lightjason.agentspeak.action.builtin.graph.CVertices.execute(), org.lightjason.agentspeak.action.builtin.math.CIsPrime.execute(), org.lightjason.agentspeak.action.builtin.bool.CAllMatch.execute(), org.lightjason.agentspeak.action.builtin.math.CNextPrime.execute(), org.lightjason.agentspeak.action.builtin.string.CBase64Encode.execute(), org.lightjason.agentspeak.action.builtin.string.CRandom.execute(), org.lightjason.agentspeak.action.builtin.string.CReplace.execute(), org.lightjason.agentspeak.action.builtin.bool.CAnyMatch.execute(), org.lightjason.agentspeak.action.builtin.collection.CIsEmpty.execute(), org.lightjason.agentspeak.action.builtin.math.CMaxIndex.execute(), org.lightjason.agentspeak.action.builtin.math.CMinIndex.execute(), org.lightjason.agentspeak.action.builtin.graph.CEdges.execute(), org.lightjason.agentspeak.action.builtin.graph.CContainsEdge.execute(), org.lightjason.agentspeak.action.builtin.graph.CContainsVertex.execute(), org.lightjason.agentspeak.action.builtin.math.CPrimeFactors.execute(), org.lightjason.agentspeak.action.builtin.math.CBinomial.execute(), org.lightjason.agentspeak.language.execution.expression.CProxyReturnExpression< T extends IExecution >.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CHammingDistance.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CHammingDistance.execute(), org.lightjason.agentspeak.language.execution.expression.CAtom.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CComparable.execute(), org.lightjason.agentspeak.action.builtin.string.CNCD.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CPower.execute(), org.lightjason.agentspeak.language.execution.expression.logical.CBinary.execute(), org.lightjason.agentspeak.language.execution.expression.logical.CUnary.execute(), org.lightjason.agentspeak.action.builtin.datetime.CBuild.execute(), org.lightjason.agentspeak.action.builtin.math.CSigmoid.execute(), org.lightjason.agentspeak.action.builtin.collection.CSize.execute(), org.lightjason.agentspeak.action.builtin.math.CStirling.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToVector.execute(), org.lightjason.agentspeak.action.builtin.crypto.CCreateKey.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CCreate.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CCreate.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CType.execute(), org.lightjason.agentspeak.action.builtin.graph.IApplyPathAlgorithm.execute(), org.lightjason.agentspeak.action.builtin.string.CLevenshtein.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CMultiplicative.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CRandomSimple.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), org.lightjason.agentspeak.action.builtin.datetime.IPlusMinus.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.IRowColumn.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CMultiplePercentile.execute(), org.lightjason.agentspeak.action.builtin.collection.multimap.CCreate.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CAdditive.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CSinglePercentile.execute(), org.lightjason.agentspeak.action.builtin.math.blas.CSize.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSolve.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CDimension.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDimension.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CNonZero.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CTrueCount.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CFalseCount.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CFalseCount.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CRows.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CIdentity.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSum.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CSum.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CColumns.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CTrueCount.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CInvert.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumns.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumnSum.execute(), org.lightjason.agentspeak.action.builtin.datetime.IBetween.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CKeys.execute(), org.lightjason.agentspeak.action.builtin.collection.multimap.CKeys.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDeterminant.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CMatrixNorm.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDiagonal.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCondition.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.COneNorm.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CCopy.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCopy.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CCopy.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CCopy.execute(), org.lightjason.agentspeak.action.builtin.collection.tuple.CFlat.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRank.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CGet.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CRemove.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRows.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRowSum.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CSize.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CSize.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CToList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTrace.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTranspose.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTwoNorm.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CUnique.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CCreateStatistic.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CValues.execute(), org.lightjason.agentspeak.action.builtin.collection.multimap.CValues.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CContains.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CFlatConcat.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CBoolValue.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CRemove.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CGet.execute(), org.lightjason.agentspeak.action.builtin.collection.tuple.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSubMatrix.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumn.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CInfinityNorm.execute(), org.lightjason.agentspeak.action.builtin.math.shape.CInTriangle.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CUnion.execute(), org.lightjason.agentspeak.action.builtin.collection.multimap.CAsMap.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CEigen.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CNumericValue.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRow.execute(), org.lightjason.agentspeak.action.builtin.graph.CSpanningTree.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CToList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CToList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CToList.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.ISelection.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CComplement.execute(), org.lightjason.agentspeak.action.builtin.math.interpolate.CMultipleInterpolate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CDotProduct.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNormalizedGraphLaplacian.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CNumericValue.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CPower.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CBoolValue.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CGet.execute(), org.lightjason.agentspeak.action.builtin.math.interpolate.CSingleInterpolate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CGraphLaplacian.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSingularValue.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.shape.CInCircle.execute(), org.lightjason.agentspeak.action.builtin.math.shape.CInRectangle.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CIntersect.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CZip.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CMultipleStatisticValue.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CRange.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CFromList.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CRemove.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CSubList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CParse.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CSingleStatisticValue.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CSymmetricDifference.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CRange.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CToBlas.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToBlas.execute(), org.lightjason.agentspeak.action.builtin.graph.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.linearprogram.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CParse.execute(), org.lightjason.agentspeak.action.builtin.crypto.CHash.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CPerronFrobenius.execute(), org.lightjason.agentspeak.action.builtin.math.interpolate.CCreate.execute(), org.lightjason.agentspeak.action.builtin.graph.CAdjacencyMatrix.execute(), org.lightjason.agentspeak.action.builtin.math.linearprogram.CSolve.execute(), org.lightjason.agentspeak.action.builtin.storage.CExists.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerSize.execute(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPop.execute(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeystream(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithoutkeys(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.exponentialselectionlazy(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.exponentialselectionstrict(), org.lightjason.agentspeak.action.builtin.TestCActionMath.factorial(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.findedgemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.findedgesingle(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.flat(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.flat(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.flatconcat(), org.lightjason.agentspeak.language.CCommon.flattenstream(), org.lightjason.agentspeak.action.builtin.web.IBaseWeb.flatterm(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.fromlist(), org.lightjason.agentspeak.action.builtin.TestCActionCollection.generate(), org.lightjason.agentspeak.action.builtin.TestCActionMath.geometricmean(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.get(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.get(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.get(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.getmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.getmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.getplan(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.getsingle(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.getsingle(), org.lightjason.agentspeak.language.execution.action.CRawAction< T >.getTypedResult(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.graphlaplacian(), org.lightjason.agentspeak.action.builtin.TestCActionMath.harmonicmean(), org.lightjason.agentspeak.action.builtin.TestCActionCrypto.hash(), org.lightjason.agentspeak.action.builtin.TestCActionCrypto.hashexception(), org.lightjason.agentspeak.action.builtin.TestCActionMath.hypot(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.identity(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentcountmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentcountsingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentverticesmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentverticessingle(), org.lightjason.agentspeak.action.builtin.TestCActionMathShape.incircle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.indegreemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.indegreesingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.inedgesmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.inedgessingle(), org.lightjason.agentspeak.action.builtin.TestCActionMathShape.inrechtangle(), org.lightjason.agentspeak.action.builtin.TestCActionMathShape.intriangle(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.invert(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.is(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.isincidentmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.isincidentsingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.isneighbormultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.isneighborsingle(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isnull(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isnumeric(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.ispredecessormultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.ispredecessorsingle(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isstring(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.issuccesormultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.issuccessorsingle(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlisterror(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlistmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlistsingle(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjecterror(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjectmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjectsingle(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.keysvalues(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.keysvalues(), org.lightjason.agentspeak.action.builtin.TestCActionString.levenshtein(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.linearselection(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.literal(), org.lightjason.agentspeak.beliefbase.storage.CClassStorage< M >.literal(), org.lightjason.agentspeak.action.builtin.TestCActionString.lower(), org.lightjason.agentspeak.action.builtin.TestCActionMath.maxIndex(), org.lightjason.agentspeak.action.builtin.TestCActionMath.minIndex(), org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate.multipleinterpolate(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.multiply(), org.lightjason.agentspeak.action.builtin.TestCActionString.ncd(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.neigborsmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.neigborssingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.neighborscountmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.neighborscountsingle(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.normalizedgraphlaplacian(), org.lightjason.agentspeak.action.builtin.TestCActionBool.notequal(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.numericvalue(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.numericvalue(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.oppositemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.oppositesingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.outdegreemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.outdegreesingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.outedgemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.outedgessingle(), org.lightjason.agentspeak.action.builtin.bool.CEqual.pack(), org.lightjason.agentspeak.action.builtin.generic.type.CParseNumber.parse(), org.lightjason.agentspeak.action.builtin.generic.type.CParseLiteral.parse(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.parse(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.parse(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.parsefloat(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.parseliteral(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.parseliteralerror(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.percentile(), org.lightjason.agentspeak.action.builtin.TestCActionMath.pow(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.power(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.predecessorcountmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.predecessorcountsingle(), org.lightjason.agentspeak.action.builtin.TestCActionMath.primefactors(), org.lightjason.agentspeak.action.builtin.TestCActionGeneric.print(), org.lightjason.agentspeak.action.builtin.TestCActionGeneric.printformatter(), org.lightjason.agentspeak.beliefbase.storage.CClassStorage< M >.putMultiElement(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.putmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.putmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.putsingle(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.putsingle(), org.lightjason.agentspeak.action.builtin.agent.CGetPlan.query(), org.lightjason.agentspeak.action.builtin.TestCActionWebGraphQL.queryliteral(), org.lightjason.agentspeak.action.builtin.TestCActionWebGraphQL.querymanual(), org.lightjason.agentspeak.action.builtin.TestCActionString.random(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.randomsample(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.randomsimple(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.range(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.range(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.rangeerror(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.rawterm(), org.lightjason.agentspeak.action.builtin.storage.CRemove.remove(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.remove(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.remove(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.remove(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.removeedgemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.removeedgesingle(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplan(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplanerror(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithkeystream(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithoutkeys(), org.lightjason.agentspeak.action.binding.CMethodAction.returnvalues(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.reverse(), org.lightjason.agentspeak.action.builtin.TestCActionString.reverse(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.row(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.row(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.rowsum(), org.lightjason.agentspeak.action.builtin.math.statistic.CRandomSample.samples(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.set(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.set(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.set(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.set(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.set(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.shortestpath(), org.lightjason.agentspeak.action.builtin.TestCActionMath.sigmoid(), org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate.singleinterpolate(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.singlestatisticvalue(), org.lightjason.agentspeak.action.builtin.TestCActionMath.singlevaluetestcase(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.singularvalue(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.size(), org.lightjason.agentspeak.action.builtin.TestCActionString.size(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.solve(), org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.solvemaximize(), org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.solveminimize(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.spanningtree(), org.lightjason.agentspeak.action.builtin.TestCActionString.startswith(), org.lightjason.agentspeak.action.builtin.agent.CPlanStatistic.statistic(), org.lightjason.agentspeak.action.builtin.TestCActionMath.stirling(), org.lightjason.agentspeak.beliefbase.TestCViewMap.stream(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.sublist(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.sublisterror(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.submatrix(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.successorcountmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.successorcountsingle(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.summarymultiplestatisticvalue(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.testcase(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.testcase(), org.lightjason.agentspeak.action.builtin.TestCActionBool.testcase(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.testcase(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.testcase(), org.lightjason.agentspeak.action.builtin.TestCActionDateTime.testcasebetween(), org.lightjason.agentspeak.action.builtin.TestCActionGeneric.thrownot(), org.lightjason.agentspeak.action.builtin.TestCActionGeneric.throwparameter(), org.lightjason.agentspeak.action.builtin.TestCActionGeneric.throwwithoutparameter(), org.lightjason.agentspeak.action.builtin.TestCActionDateTime.time(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.tobitvector(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.toblas(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.toblas(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.tofloat(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.tofloaterror(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.tolist(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.tolist(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.tolist(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.tolist(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.tostring(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.toterm(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.transpose(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.type(), org.lightjason.agentspeak.language.CLiteral.unify(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.unique(), org.lightjason.agentspeak.action.builtin.TestCActionString.upper(), org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.valueconstraint(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.vertexcount(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.vertexremovemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.vertextremovesingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.vertices(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitBinary_expression(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitBinary_expression(), org.lightjason.agentspeak.grammar.CASTVisitorType.visitTermlist(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTermlist(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTermlist(), org.lightjason.agentspeak.action.builtin.TestCActionCrypto.wrongalgorithm(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjecterror(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjectmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjectsingle(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.zip(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.ziperror(), and org.lightjason.agentspeak.action.builtin.TestCActionDateTime.zoneid().
functor()
final String org.lightjason.agentspeak.language.CRawTerm< T >.functor ()
Returns
functor
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 140 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.m_functor, and org.lightjason.agentspeak.common.IPath.suffix().
functorpath()
final IPath org.lightjason.agentspeak.language.CRawTerm< T >.functorpath ()
Returns
path
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 147 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.m_functor, org.lightjason.agentspeak.common.IPath.size(), and org.lightjason.agentspeak.common.IPath.subpath().
hashCode()
final int org.lightjason.agentspeak.language.CRawTerm< T >.hashCode ()
Definition at line 111 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.m_hashcode.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.equals().
hasVariable()
final boolean org.lightjason.agentspeak.language.CRawTerm< T >.hasVariable ()
Returns
variable flag
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 160 of file CRawTerm.java.
raw()
final<N> N org.lightjason.agentspeak.language.CRawTerm< T >.raw ()
Template Parameters
raw type
Returns
any type
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 167 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.m_value.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.equals().
structurehash()
final int org.lightjason.agentspeak.language.CRawTerm< T >.structurehash ()
Returns
structure hash value
Implements org.lightjason.agentspeak.language.IStructureHash.
Definition at line 219 of file CRawTerm.java.
thrownotallocated()
final IRawTerm<T> org.lightjason.agentspeak.language.CRawTerm< T >.thrownotallocated () throws IllegalStateException
Definition at line 180 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.allocated(), and org.lightjason.agentspeak.common.CCommon.languagestring().
throwvaluenotassignableto()
final IRawTerm<T> org.lightjason.agentspeak.language.CRawTerm< T >.throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
Definition at line 196 of file CRawTerm.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.CRawTerm< T >.valueassignableto().
toString()
final String org.lightjason.agentspeak.language.CRawTerm< T >.toString ()
Definition at line 133 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.m_value.
valueassignableto()
final boolean org.lightjason.agentspeak.language.CRawTerm< T >.valueassignableto (@Nonnull final Class<?>... p_class)
Definition at line 189 of file CRawTerm.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.m_value.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.throwvaluenotassignableto().
Member Data Documentation
EMPTY
final ITerm org.lightjason.agentspeak.language.CRawTerm< T >.EMPTY = new CRawTerm<>(null) static
Definition at line 50 of file CRawTerm.java.
Referenced by org.lightjason.agentspeak.language.CLiteral.allocate(), org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.belieflist(), and org.lightjason.agentspeak.beliefbase.storage.CClassStorage< M >.literal().
m_functor
final IPath org.lightjason.agentspeak.language.CRawTerm< T >.m_functor private
Definition at line 62 of file CRawTerm.java.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.fqnfunctor(), org.lightjason.agentspeak.language.CRawTerm< T >.functor(), and org.lightjason.agentspeak.language.CRawTerm< T >.functorpath().
m_hashcode
final int org.lightjason.agentspeak.language.CRawTerm< T >.m_hashcode private
Definition at line 66 of file CRawTerm.java.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.hashCode().
m_value
final T org.lightjason.agentspeak.language.CRawTerm< T >.m_value private
Definition at line 58 of file CRawTerm.java.
Referenced by org.lightjason.agentspeak.language.CRawTerm< T >.allocated(), org.lightjason.agentspeak.language.CRawTerm< T >.deepcopy(), org.lightjason.agentspeak.language.CRawTerm< T >.deepcopysuffix(), org.lightjason.agentspeak.language.CRawTerm< T >.raw(), org.lightjason.agentspeak.language.CRawTerm< T >.toString(), and org.lightjason.agentspeak.language.CRawTerm< T >.valueassignableto().
serialVersionUID
final long org.lightjason.agentspeak.language.CRawTerm< T >.serialVersionUID = 8660012856755452965L static private
Definition at line 54 of file CRawTerm.java.