LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.IBeliefbase Interface Reference
org.lightjason.agentspeak.beliefbase.IBeliefbase Interface Reference
interface of beliefbase definition, that create the trigger events for the agent
Public Member Functions
ILiteral add (@Nonnull final ILiteral p_literal)
adds a literal
IView add (@Nonnull final IView p_view)
adds a view
IBeliefbase clear ()
clears all elements
boolean containsLiteral (@Nonnull final String p_key)
contains a multi-element
boolean containsView (@Nonnull final String p_key)
contains a single-element
IView create (@Nonnull final String p_name)
returns a new view of the belief base
IView create (@Nonnull final String p_name, @Nullable final IView p_parent)
returns a new view of the belief base
Collection< ILiteral > literal (@Nonnull final String p_key)
returns a literal by the name
ILiteral remove (@Nonnull final ILiteral p_literal)
removes a literal
IView remove (@Nonnull final IView p_view)
removes a view
Stream< ILiteral > streamLiteral ()
returns a stream over all literals
Stream< IView > streamView ()
returns a stream over all views
Stream< ITrigger > trigger (@Nonnull final IView p_view)
returns all trigger of the beliefbase
IView view (@Nonnull final String p_key)
returns a view element
IView viewOrDefault (@Nonnull final String p_key, @Nullable final IView p_default)
returns a view element
Public Member Functions inherited from org.lightjason.agentspeak.beliefbase.IStructure
boolean empty ()
checks if the structure empty
int size ()
returns the size of literals
IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
Public Attributes
IBeliefbase EMPY
empty beliefbase
Detailed Description
Template Parameters
T agent type
Definition at line 44 of file IBeliefbase.java.
Member Function Documentation
add() [1/2]
ILiteral org.lightjason.agentspeak.beliefbase.IBeliefbase.add (@Nonnull final ILiteral p_literal)
Parameters
p_literal literal without path
Returns
beliefbase reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.IBaseBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add(), and org.lightjason.agentspeak.beliefbase.view.CView.walkdown().
add() [2/2]
IView org.lightjason.agentspeak.beliefbase.IBeliefbase.add (@Nonnull final IView p_view)
Parameters
p_view view
Returns
beliefbase reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>, and org.lightjason.agentspeak.beliefbase.CBeliefbase.
clear()
IBeliefbase org.lightjason.agentspeak.beliefbase.IBeliefbase.clear ()
Returns
beliefbase reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.clear().
containsLiteral()
boolean org.lightjason.agentspeak.beliefbase.IBeliefbase.containsLiteral (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.containsLiteral(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.containsLiteral().
containsView()
boolean org.lightjason.agentspeak.beliefbase.IBeliefbase.containsView (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>, and org.lightjason.agentspeak.beliefbase.CBeliefbase.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.containsView(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.containsView().
create() [1/2]
IView org.lightjason.agentspeak.beliefbase.IBeliefbase.create (@Nonnull final String p_name)
Parameters
p_name name of the view
Returns
created view
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, and org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.
create() [2/2]
IView org.lightjason.agentspeak.beliefbase.IBeliefbase.create (@Nonnull final String p_name, @Nullable final IView p_parent)
Parameters
p_name name of the view
p_parent parent view
Returns
view
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase.
literal()
Collection<ILiteral> org.lightjason.agentspeak.beliefbase.IBeliefbase.literal (@Nonnull final String p_key)
Parameters
p_key name of the literal
Returns
collection of pairs with negated and literal
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.stream(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
remove() [1/2]
ILiteral org.lightjason.agentspeak.beliefbase.IBeliefbase.remove (@Nonnull final ILiteral p_literal)
Parameters
p_literal without path
Returns
beliefbase reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.IBaseBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.remove().
remove() [2/2]
IView org.lightjason.agentspeak.beliefbase.IBeliefbase.remove (@Nonnull final IView p_view)
Parameters
p_view view
Returns
beliefbase reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>, and org.lightjason.agentspeak.beliefbase.CBeliefbase.
streamLiteral()
Stream<ILiteral> org.lightjason.agentspeak.beliefbase.IBeliefbase.streamLiteral ()
Returns
literal stream
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.stream(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
streamView()
Stream<IView> org.lightjason.agentspeak.beliefbase.IBeliefbase.streamView ()
Returns
view stream
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.stream(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
trigger()
Stream<ITrigger> org.lightjason.agentspeak.beliefbase.IBeliefbase.trigger (@Nonnull final IView p_view)
Parameters
p_view mask for events
Returns
set with trigger events
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.trigger(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.trigger().
view()
IView org.lightjason.agentspeak.beliefbase.IBeliefbase.view (@Nonnull final String p_key)
Parameters
p_key name of the view
Returns
view or null
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
viewOrDefault()
IView org.lightjason.agentspeak.beliefbase.IBeliefbase.viewOrDefault (@Nonnull final String p_key, @Nullable final IView p_default)
Parameters
p_key name of the view
p_default view
Returns
view or default element
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, and org.lightjason.agentspeak.beliefbase.CBeliefbase.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.walkdown().
Member Data Documentation
EMPY
IBeliefbase org.lightjason.agentspeak.beliefbase.IBeliefbase.EMPY
Definition at line 49 of file IBeliefbase.java.