LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathBlas Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathBlas Class Reference
test math blas functions
Public Member Functions
final void elementwisematrix ()
test elementwise for matrix
final void elementwisevector ()
test elementwise for vector
final void initialize ()
test initialize
final void multiply ()
test multiply
final void size ()
test size
Private Attributes
DoubleMatrix2D m_matrix1
testing matrix
DoubleMatrix2D m_matrix2
testing matrix
DoubleMatrix1D m_vector
testing vector
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 49 of file TestCActionMathBlas.java.
Member Function Documentation
elementwisematrix()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.elementwisematrix ()
Definition at line 121 of file TestCActionMathBlas.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.CElementWise.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
elementwisevector()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.elementwisevector ()
Definition at line 158 of file TestCActionMathBlas.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.CElementWise.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
initialize()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.initialize ()
Definition at line 71 of file TestCActionMathBlas.java.
multiply()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.multiply ()
Definition at line 100 of file TestCActionMathBlas.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.CMultiply.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
size()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.size ()
Definition at line 82 of file TestCActionMathBlas.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.CSize.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
Member Data Documentation
m_matrix1
DoubleMatrix2D org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.m_matrix1 private
Definition at line 54 of file TestCActionMathBlas.java.
m_matrix2
DoubleMatrix2D org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.m_matrix2 private
Definition at line 59 of file TestCActionMathBlas.java.
m_vector
DoubleMatrix1D org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.m_vector private
Definition at line 64 of file TestCActionMathBlas.java.