LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution Class Reference
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution Class Reference
creates a distribution object.
Classes
enum EDistribution
usable distributions
enum EGenerator
number generator
Public Member Functions
CCreateDistribution ()
ctor
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int minimalArgumentNumber ()
minimum number of arguments
Public Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Static Private Attributes
static final long serialVersionUID = 614460992147593598L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
IBuiltinAction ()
ctor
IBuiltinAction (final int p_length)
ctor
Static Protected Attributes inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
static final Logger LOGGER = CCommon.logger(IBuiltinAction.class)
logger
Static Protected Attributes inherited from org.lightjason.agentspeak.action.IBaseAction
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Detailed Description
The action creates a distribution objects, with an individual pseudo-random generator and different distribution paramter, the action never fails, the following distributions are supported with the following number of numeric arguments
beta distribution with 2 arguments (\(\alpha \) and \(\beta \))
cauchy distribution with 2 arguments (media and scale)
chi-square distribution with 1 argument (degree off freedom)
exponential distribution with 1 argument (mean)
f distribution with 2 arguments (degrees of freedom, denominator degrees of freedom)
gamma distribution with 2 arguments (shape and scale)
gumble distribution with 2 arguments (\(\mu \) and \(\beta \))
laplace distirbution with 2 arguments (\(\mu \) and \(\beta \))
levy distirbution with 2 arguments (\(\mu \) and \(c \))
logistic distirbution with 2 arguments (\(\mu \) and \(s \))
lognormal distirbution with 2 arguments (scale and shape)
nakagami distribution with 2 arguments (\(\mu \) and \(\omega \))
normal distribution with 2 arguments (expected value, variance)
pareto distribution with 2 arguments (scale and shape)
t distribution with 1 argument (degrees of freedom)
triangular distribution with 3 arguments (a, b, c)
uniform distribution with 2 arguments (lower and upper)
weibull distribution with 2 arguments (\(\alpha \) and \(\beta \))
The following pseudo-random number generators are supported:
mersennetwister (default)
synchronizedmersennetwister
isaac
synchronizedisaac
internal
synchronizedinternal
well512a
synchronizedwell512a
well1024a
synchronizedwell1024a
well19937a
synchronizedwell19937a
well19937c
synchronizedwell19937c
well4449a
synchronizedwell4449a
well44497b
synchronizedwell44497b
[D1|D2] = math/statistic/createdistribution("normal", 20, 10, ["beta", "isaac", [8, 12]]);
See also
https://en.wikipedia.org/wiki/Beta_distribution
https://en.wikipedia.org/wiki/Cauchy_distribution
https://en.wikipedia.org/wiki/Chi-squared_distribution
https://en.wikipedia.org/wiki/Exponential_distribution
https://en.wikipedia.org/wiki/F-distribution
https://en.wikipedia.org/wiki/Gamma_distribution
https://en.wikipedia.org/wiki/Gumbel_distribution
https://en.wikipedia.org/wiki/L%C3%A9vy_distribution
https://en.wikipedia.org/wiki/Logistic_distribution
https://en.wikipedia.org/wiki/Log-normal_distribution
https://en.wikipedia.org/wiki/Nakagami_distribution
https://en.wikipedia.org/wiki/Normal_distribution
https://en.wikipedia.org/wiki/Pareto_distribution
https://en.wikipedia.org/wiki/Student%27s_t-distribution
https://en.wikipedia.org/wiki/Triangular_distribution
https://en.wikipedia.org/wiki/Uniform_distribution_(continuous)
https://en.wikipedia.org/wiki/Weibull_distribution
Definition at line 143 of file CCreateDistribution.java.
Constructor & Destructor Documentation
CCreateDistribution()
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.CCreateDistribution ()
Definition at line 153 of file CCreateDistribution.java.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 167 of file CCreateDistribution.java.
References org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.exist(), org.lightjason.agentspeak.language.CCommon.flatten(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.from(), org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.from(), org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.get(), org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EGenerator.MERSENNETWISTER, and org.lightjason.agentspeak.language.CCommon.rawvalueAssignableTo().
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.createdistribution().
minimalArgumentNumber()
final int org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.minimalArgumentNumber ()
Returns
number of minimal arguments
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 160 of file CCreateDistribution.java.
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.serialVersionUID = 614460992147593598L static private
Definition at line 148 of file CCreateDistribution.java.