LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic Class Reference
org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic Class Reference
plan statistic to count execution values
Public Member Functions
final int compareTo (@Nonnull final IPlanStatistic p_other)
final long count ()
returns the number of executions
final boolean equals (final Object p_object)
final long fail ()
returns number of failed execution
final double failratio ()
returns the ratio of failed executions
final int hashCode ()
final IPlanStatistic incrementfail ()
increments the failed executions
final IPlanStatistic incrementsuccessful ()
increments the successful executions
final IPlan plan ()
plan reference
final long successful ()
returns number of successful execution
final double successfulratio ()
returns the ratio of successful execution
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with variables of the internal data
Static Public Member Functions
static IPlanStatistic from (@Nonnull final IPlan p_plan)
factory
Private Member Functions
CPlanStatistic (@Nonnull final IPlan p_plan)
ctor
Private Attributes
final AtomicLong m_fail = new AtomicLong()
count of fail exeuctions
final IPlan m_plan
plan reference
final AtomicLong m_successful = new AtomicLong()
count of successful exeuctions
Detailed Description
Definition at line 42 of file language/instantiable/plan/statistic/CPlanStatistic.java.
Constructor & Destructor Documentation
CPlanStatistic()
org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.CPlanStatistic (@Nonnull final IPlan p_plan) private
Parameters
p_plan plan reference
Definition at line 63 of file language/instantiable/plan/statistic/CPlanStatistic.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.from().
Member Function Documentation
compareTo()
final int org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.compareTo (@Nonnull final IPlanStatistic p_other)
Definition at line 180 of file language/instantiable/plan/statistic/CPlanStatistic.java.
References org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.hashCode().
count()
final long org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.count ()
Returns
number of executions
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 77 of file language/instantiable/plan/statistic/CPlanStatistic.java.
equals()
final boolean org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.equals (final Object p_object)
Definition at line 154 of file language/instantiable/plan/statistic/CPlanStatistic.java.
References org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.hashCode().
fail()
final long org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.fail ()
Returns
number of executions
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 101 of file language/instantiable/plan/statistic/CPlanStatistic.java.
failratio()
final double org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.failratio ()
Returns
ratio
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 107 of file language/instantiable/plan/statistic/CPlanStatistic.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.variables().
from()
static IPlanStatistic org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.from (@Nonnull final IPlan p_plan) static
Parameters
p_plan plan object
Returns
statistic object
Definition at line 173 of file language/instantiable/plan/statistic/CPlanStatistic.java.
References org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.CPlanStatistic().
Referenced by org.lightjason.agentspeak.action.builtin.agent.CAddPlan.execute(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.getplan(), org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.IBaseAgent(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist(), and org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplan().
hashCode()
final int org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.hashCode ()
Definition at line 147 of file language/instantiable/plan/statistic/CPlanStatistic.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.compareTo(), and org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.equals().
incrementfail()
final IPlanStatistic org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.incrementfail ()
Returns
self reference
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 125 of file language/instantiable/plan/statistic/CPlanStatistic.java.
incrementsuccessful()
final IPlanStatistic org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.incrementsuccessful ()
Returns
self reference
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 117 of file language/instantiable/plan/statistic/CPlanStatistic.java.
plan()
final IPlan org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.plan ()
Returns
plan
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 70 of file language/instantiable/plan/statistic/CPlanStatistic.java.
References org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.m_plan.
successful()
final long org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.successful ()
Returns
number of executions
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 84 of file language/instantiable/plan/statistic/CPlanStatistic.java.
successfulratio()
final double org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.successfulratio ()
Returns
ratio
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 91 of file language/instantiable/plan/statistic/CPlanStatistic.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.variables().
toString()
final String org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.toString ()
Definition at line 161 of file language/instantiable/plan/statistic/CPlanStatistic.java.
References org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.m_fail, org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.m_plan, and org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.m_successful.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.variables ()
Returns
variable stream
Implements org.lightjason.agentspeak.language.instantiable.plan.statistic.IPlanStatistic.
Definition at line 133 of file language/instantiable/plan/statistic/CPlanStatistic.java.
References org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.failratio(), and org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.successfulratio().
Member Data Documentation
m_fail
final AtomicLong org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.m_fail = new AtomicLong() private
Definition at line 55 of file language/instantiable/plan/statistic/CPlanStatistic.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.toString().
m_plan
final IPlan org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.m_plan private
Definition at line 47 of file language/instantiable/plan/statistic/CPlanStatistic.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.plan(), and org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.toString().
m_successful
final AtomicLong org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.m_successful = new AtomicLong() private
Definition at line 51 of file language/instantiable/plan/statistic/CPlanStatistic.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.statistic.CPlanStatistic.toString().