LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CTernaryOperation Class Reference
org.lightjason.agentspeak.language.execution.action.CTernaryOperation Class Reference
if-else structure
Public Member Functions
CTernaryOperation (@Nonnull final IExpression p_expression, @Nonnull final IExecution p_true, @Nonnull final IExecution p_false)
ctor
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExpression >
final T getValue ()
returns the value of the action
final boolean isValueAssignableTo (final Class<?> p_class)
checkes assinable of the value
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final IExecution m_false
false execution block
final IExecution m_true
true execution block
Static Private Attributes
static final long serialVersionUID = 5518298371186501138L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExpression >
IBaseExecution (@Nullable final T p_value)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExpression >
final T m_value
data
Detailed Description
Definition at line 46 of file CTernaryOperation.java.
Constructor & Destructor Documentation
CTernaryOperation()
org.lightjason.agentspeak.language.execution.action.CTernaryOperation.CTernaryOperation (@Nonnull final IExpression p_expression, @Nonnull final IExecution p_true, @Nonnull final IExecution p_false)
Parameters
p_expression expression
p_true true execution block
p_false false execution block
Definition at line 69 of file CTernaryOperation.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.action.CTernaryOperation.equals (final Object p_object)
Definition at line 98 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.action.CTernaryOperation.hashCode().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CTernaryOperation.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Definition at line 78 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.IExecution.execute(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), and org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExpression >.m_value.
hashCode()
final int org.lightjason.agentspeak.language.execution.action.CTernaryOperation.hashCode ()
Definition at line 92 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExpression >.m_value.
Referenced by org.lightjason.agentspeak.language.execution.action.CTernaryOperation.equals().
toString()
final String org.lightjason.agentspeak.language.execution.action.CTernaryOperation.toString ()
Definition at line 104 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.action.IBaseExecution< IExpression >.m_value.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CTernaryOperation.variables ()
Definition at line 111 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.IExecution.variables().
Member Data Documentation
m_false
final IExecution org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_false private
Definition at line 59 of file CTernaryOperation.java.
m_true
final IExecution org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_true private
Definition at line 55 of file CTernaryOperation.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.CTernaryOperation.serialVersionUID = 5518298371186501138L static private
Definition at line 51 of file CTernaryOperation.java.