LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap Class Reference
test multimap action
Public Member Functions
final void asmap ()
test as-map
final void create ()
test create
final void createsynchronized ()
test synchronized create
final void getmultiple ()
test get-multiple
final void getsingle ()
test get-single
final void keysvalues ()
test key and values
final void putmultiple ()
test put-multiple
final void putsingle ()
test put-single
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 60 of file TestCActionCollectionMultimap.java.
Member Function Documentation
asmap()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.asmap ()
Definition at line 139 of file TestCActionCollectionMultimap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.multimap.CAsMap.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.create ()
Definition at line 67 of file TestCActionCollectionMultimap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute().
createsynchronized()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.createsynchronized ()
Definition at line 86 of file TestCActionCollectionMultimap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute().
getmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.getmultiple ()
Definition at line 212 of file TestCActionCollectionMultimap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.IMapGetMultiple< T >.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
getsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.getsingle ()
Definition at line 238 of file TestCActionCollectionMultimap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.IMapGetSingle< T >.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
keysvalues()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.keysvalues ()
Definition at line 105 of file TestCActionCollectionMultimap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.map.CKeys.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CValues.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
putmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.putmultiple ()
Definition at line 192 of file TestCActionCollectionMultimap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.IMapApplyMultiple< T >.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
putsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.putsingle ()
Definition at line 169 of file TestCActionCollectionMultimap.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.IMapApplySingle< T >.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().