LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.IRawStructure< T > Interface Template Reference
org.lightjason.agentspeak.language.IRawStructure< T > Interface Template Reference
interface to define a structure with native data
Public Member Functions
boolean allocated ()
returns allocated state
T thrownotallocated () throws IllegalStateException
throws an illegal state exception iif the variable is not allocated
Public Member Functions inherited from org.lightjason.agentspeak.language.IAssignable< T >
T throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Detailed Description
Definition at line 32 of file IRawStructure.java.
Member Function Documentation
allocated()
boolean org.lightjason.agentspeak.language.IRawStructure< T >.allocated ()
Returns
boolean flag
Implemented in org.lightjason.agentspeak.language.variable.CVariable< T >, and org.lightjason.agentspeak.language.variable.CMutexVariable< T >.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variable(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablemutex().
thrownotallocated()
T org.lightjason.agentspeak.language.IRawStructure< T >.thrownotallocated () throws IllegalStateException
Returns
object itself
Exceptions
IllegalStateException on non-allocated
Implemented in org.lightjason.agentspeak.language.variable.CVariable< T >, and org.lightjason.agentspeak.language.variable.CMutexVariable< T >.
Referenced by org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.execute(), and org.lightjason.agentspeak.language.execution.expressionunary.CIncrement< T extends Number >.execute().