LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger Class Reference
org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger Class Reference
event with literal data
Public Member Functions
CTrigger (@Nonnull final EType p_event, @Nonnull final ILiteral p_literal)
ctor
final int compareTo (@Nonnull final ITrigger p_other)
final boolean equals (final Object p_object)
final int hashCode ()
final ILiteral literal ()
returns the literal of the event
final ITrigger shallowcopy (final IPath... p_prefix)
final ITrigger shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
final int structurehash ()
returns a hash value which defines a hash ove rthe structure
final String toString ()
final EType type ()
returns the type of the event
final int variablesize ()
returns variable number
Public Member Functions inherited from org.lightjason.agentspeak.language.IShallowCopy< T >
T shallowcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
Static Public Member Functions
static ITrigger from (@Nonnull final EType p_event, @Nonnull final ILiteral p_literal)
creates a trigger event^
Private Attributes
final EType m_event
event type
final int m_hashcode
hashcode
final ILiteral m_literal
literal with unified variables
final int m_structurehash
content hashcode
final int m_variables
variable number
Static Private Attributes
static final long serialVersionUID = -4216265954626567558L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger
ITrigger EMPTY
empty trigger
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Detailed Description
Definition at line 37 of file CTrigger.java.
Constructor & Destructor Documentation
CTrigger()
org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger (@Nonnull final EType p_event, @Nonnull final ILiteral p_literal)
Parameters
p_event type
p_literal literal with unified variables
Definition at line 71 of file CTrigger.java.
References org.lightjason.agentspeak.language.IStructureHash.structurehash().
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopy(), and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopysuffix().
Member Function Documentation
compareTo()
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.compareTo (@Nonnull final ITrigger p_other)
Definition at line 149 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.toString().
equals()
final boolean org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.equals (final Object p_object)
Definition at line 99 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.hashCode().
from()
static ITrigger org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from (@Nonnull final EType p_event, @Nonnull final ILiteral p_literal) static
Parameters
p_event event
p_literal trigger literal
Returns
trigger object
Definition at line 87 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger().
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.active(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.addplan(), org.lightjason.agentspeak.configuration.CDefaultAgentConfiguration< T extends IAgent<?>.CDefaultAgentConfiguration(), org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.event(), org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementGoalLiteral.execute(), org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementGoalVariable.execute(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.execute(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.getplan(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.initialize(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.initialize(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist(), org.lightjason.agentspeak.action.builtin.agent.CGetPlan.query(), org.lightjason.agentspeak.action.builtin.agent.CRemovePlan.remove(), and org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplan().
hashCode()
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.hashCode ()
Definition at line 93 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_hashcode.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.equals().
literal()
final ILiteral org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.literal ()
Returns
literal
Implements org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.
Definition at line 117 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_literal.
shallowcopy()
final ITrigger org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopy (final IPath... p_prefix)
Definition at line 136 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger(), and org.lightjason.agentspeak.language.IShallowCopy< T >.shallowcopy().
shallowcopysuffix()
final ITrigger org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopysuffix ()
Returns
new instance of the object
Implements org.lightjason.agentspeak.language.IShallowCopy< T >.
Definition at line 143 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger(), and org.lightjason.agentspeak.language.IShallowCopy< T >.shallowcopysuffix().
structurehash()
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.structurehash ()
Returns
structure hash value
Implements org.lightjason.agentspeak.language.IStructureHash.
Definition at line 129 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_structurehash.
toString()
final String org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.toString ()
Definition at line 105 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.compareTo().
type()
final EType org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.type ()
Returns
type
Implements org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.
Definition at line 111 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_event.
variablesize()
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.variablesize ()
Returns
number
Implements org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.
Definition at line 123 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_variables.
Member Data Documentation
m_event
final EType org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_event private
Definition at line 54 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.type().
m_hashcode
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_hashcode private
Definition at line 58 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.hashCode().
m_literal
final ILiteral org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_literal private
Definition at line 50 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.literal().
m_structurehash
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_structurehash private
Definition at line 62 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.structurehash().
m_variables
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_variables private
Definition at line 46 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.variablesize().
serialVersionUID
final long org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.serialVersionUID = -4216265954626567558L static private
Definition at line 42 of file CTrigger.java.