LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral Class Reference
org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral Class Reference
action to run graphql query by a literal.
Public Member Functions
CQueryLiteral ()
ctor
Public Member Functions inherited from org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int minimalArgumentNumber ()
minimum number of arguments
Public Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Protected Member Functions
final String argumentquery (@Nonnull final ITerm p_argument)
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL
IBaseGraphQL (final int p_length)
ctor
abstract String argumentquery (@Nonnull final ITerm p_argument)
convert argument into graphql query
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.web.IBaseWeb
IBaseWeb (final int p_length)
ctor
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
IBuiltinAction ()
ctor
IBuiltinAction (final int p_length)
ctor
Static Private Member Functions
static String fields (@Nonnull final Stream< ITerm > p_stream)
creates the field list
static String root (@Nonnull final ILiteral p_literal)
converts a literal query structure
static String typeformat (final Object p_value)
type mapping
static String valueformat (@Nonnull final ILiteral p_literal)
format query argument
static String values (@Nonnull final Stream< ITerm > p_stream)
argument values
Static Private Attributes
static final long serialVersionUID = -6514047475694739845L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Static Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL
static Stream< ITerm > sendquery (@Nonnull final String p_url, @Nonnull final String p_query) throws IOException
executes graphql query and returns a stream of terms of the result
Static Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.web.IBaseWeb
static ITerm baseliteral (@Nonnull final Stream< String > p_functor, @Nonnull final Stream< ITerm > p_values)
creates a literal structure from a stream of string elements, the string stream will be build in a tree structure
static Stream< ITerm > flatterm (@Nullable final Object p_object)
converts an object into a term stream
static HttpGet httpget (@Nonnull final String p_url)
returns a http-get connection
static String httpgetexecute (@Nonnull final String p_url) throws IOException
execute http-get request
static String httpgetexecute (@Nonnull final HttpGet p_get) throws IOException
execute http-get request
static HttpPost httppost (@Nonnull final String p_url)
returns a http-post connection
static String httppostexecute (@Nonnull final HttpPost p_post) throws IOException
execute http-post request
Static Protected Attributes inherited from org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL
static final ObjectMapper JSONMAPPER = new ObjectMapper()
json mapper
Static Protected Attributes inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
static final Logger LOGGER = CCommon.logger(IBuiltinAction.class)
logger
Static Protected Attributes inherited from org.lightjason.agentspeak.action.IBaseAction
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Detailed Description
The calls the data of a graphql service and returns a literal based on the query result, the input argument is at the first position the graphql service url, the second argument a literal, which defines the query structure and all other arguments the literal functor structure. The action fails on connection and parsing errors.
L = generic/type/parseliteral("allUsers(id, firstName, lastName)"); GQ = web/graphql/queryliteral("https://fakerql.com/graphql", L, "graphql-fake");
See also
http://graphql.org/
Definition at line 48 of file CQueryLiteral.java.
Constructor & Destructor Documentation
CQueryLiteral()
org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.CQueryLiteral ()
Definition at line 58 of file CQueryLiteral.java.
Member Function Documentation
argumentquery()
final String org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.argumentquery (@Nonnull final ITerm p_argument) protected
Definition at line 64 of file CQueryLiteral.java.
References org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.root().
fields()
static String org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.fields (@Nonnull final Stream< ITerm > p_stream) static private
Parameters
p_stream field stream
Returns
string definition
Definition at line 116 of file CQueryLiteral.java.
References org.lightjason.agentspeak.language.ITerm.functor(), org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.root(), and org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.values().
Referenced by org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.root().
root()
static String org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.root (@Nonnull final ILiteral p_literal) static private
Parameters
p_literal literal
Returns
query string
Definition at line 76 of file CQueryLiteral.java.
References org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.fields(), and org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.values().
Referenced by org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.argumentquery(), and org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.fields().
typeformat()
static String org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.typeformat (final Object p_value) static private
Parameters
p_value any value
Returns
graphql string
Definition at line 151 of file CQueryLiteral.java.
Referenced by org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.valueformat().
valueformat()
static String org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.valueformat (@Nonnull final ILiteral p_literal) static private
Parameters
p_literal literal
Returns
functor with value
Definition at line 134 of file CQueryLiteral.java.
References org.lightjason.agentspeak.language.ITerm.raw(), and org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.typeformat().
Referenced by org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.values().
values()
static String org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.values (@Nonnull final Stream< ITerm > p_stream) static private
Parameters
p_stream term stream
Returns
string arguemnts
Definition at line 98 of file CQueryLiteral.java.
References org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.valueformat().
Referenced by org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.fields(), and org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.root().
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.serialVersionUID = -6514047475694739845L static private
Definition at line 53 of file CQueryLiteral.java.