LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?> Interface Template Reference
org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?> Interface Template Reference
agent interface
Public Member Functions
IView beliefbase ()
returns the beliefbase
long cycletime ()
returns the time in nano seconds at the last cycle
IFuzzyBundle< Boolean > fuzzy ()
return fuzzy operator
< N extends IInspector > Stream< N > inspect (@Nonnull final N... p_inspector)
inspector method
Multimap< ITrigger, IPlanStatistic > plans ()
returns the internal map of plans
< N extends IAgent<?> N raw ()
cast the interface agent object to a specified agent object
Multimap< IPath, IRule > rules ()
returns amultimap with literal-rule functor and rle objects
Multimap< IPath, ILiteral > runningplans ()
returns a map of the current running plans
IAgent< T > sleep (final long p_cycles, @Nullable final ITerm... p_term)
pushs the agent into sleeping state
IAgent< T > sleep (final long p_cycles, @Nonnull final Stream< ITerm > p_term)
pushs the agent into sleeping state
boolean sleeping ()
returns sleeping state
Map< String, Object > storage ()
storage access
IFuzzyValue< Boolean > trigger (@Nonnull final ITrigger p_trigger, @Nullable final boolean... p_immediately)
trigger an event
IUnifier unifier ()
returns an unifier
IVariableBuilder variablebuilder ()
returns the variable builder function
IAgent< T > wakeup (@Nullable final ITerm... p_term)
wake-up the agent by generating wakeup-goal
IAgent< T > wakeup (@Nonnull final Stream< ITerm > p_term)
wake-up the agent by generating wakeup-goal
Public Attributes
IAgent<?> EMPTY
empty agent
Detailed Description
Template Parameters
T agent type
Definition at line 58 of file IAgent.java.
Member Function Documentation
beliefbase()
IView org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.beliefbase ()
Returns
beliefbase
Referenced by org.lightjason.agentspeak.consistency.filter.CBelief.apply(), org.lightjason.agentspeak.consistency.filter.CAll.apply(), org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.belieflist(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.belieflist(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.clearbeliefbase(), and org.lightjason.agentspeak.language.unify.CUnifier.variables().
cycletime()
long org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.cycletime ()
Returns
nano seconds
fuzzy()
IFuzzyBundle<Boolean> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.fuzzy ()
Returns
operator
inspect()
<N extends IInspector> Stream<N> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.inspect (@Nonnull final N... p_inspector)
Parameters
p_inspector inspector object
Returns
inspector stream or empty stream
plans()
Multimap<ITrigger, IPlanStatistic> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.plans ()
Returns
plan map
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.addplan(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.getplan(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist(), and org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplan().
raw()
<N extends IAgent<?> N org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.raw ()
Returns
specified agent
rules()
Multimap<IPath, IRule> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.rules ()
Returns
multimap
runningplans()
Multimap<IPath, ILiteral> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.runningplans ()
Returns
map with running plans and the instance literal
Referenced by org.lightjason.agentspeak.consistency.filter.CPlan.apply(), and org.lightjason.agentspeak.consistency.filter.CAll.apply().
sleep() [1/2]
IAgent<T> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.sleep (final long p_cycles, @Nullable final ITerm... p_term)
Parameters
p_cycles number of cycles for sleeping - if is set to maximum the sleeping time is infinity
p_term literal list for wake-up calls
Returns
agent reference
sleep() [2/2]
IAgent<T> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.sleep (final long p_cycles, @Nonnull final Stream< ITerm > p_term)
Parameters
p_cycles number of cycles for sleeping - if is set to maximum the sleeping time is infinity
p_term term stream for wake-up calls
Returns
agent reference
sleeping()
boolean org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.sleeping ()
Returns
sleeping flag
storage()
Map<String, Object> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage ()
Returns
storage map
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithkeystrean(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithoutkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.clearwithkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.clearwithkeystream(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.clearwithoutkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeystream(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithoutkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithkeystream(), and org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithoutkeys().
trigger()
IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.trigger (@Nonnull final ITrigger p_trigger, @Nullable final boolean... p_immediately)
Parameters
p_trigger event trigger
p_immediately run element immediately
Returns
execution finished correctly
Note
the trigger is ignored iif the agent is sleeping
unifier()
IUnifier org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.unifier ()
Returns
unification algorithm
variablebuilder()
IVariableBuilder org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.variablebuilder ()
Returns
variable builder function
wakeup() [1/2]
IAgent<T> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.wakeup (@Nullable final ITerm... p_term)
Parameters
p_term any term value which will push into the wake-up plan
Returns
agent reference
wakeup() [2/2]
IAgent<T> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.wakeup (@Nonnull final Stream< ITerm > p_term)
Parameters
p_term stream to call wake-up plan
Returns
agent reference
Member Data Documentation
EMPTY
IAgent<?> org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.EMPTY
Definition at line 63 of file IAgent.java.