LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T > Class Template Reference
org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T > Class Template Reference
immutable fuzzy value
Public Member Functions
CFuzzyValue (@Nonnull final IFuzzyValue< T > p_value)
ctor
CFuzzyValue (@Nonnull final T p_value)
ctor
CFuzzyValue (@Nonnull final T p_value, final double p_fuzzy)
ctor
final double fuzzy ()
returns the fuzziness
final T throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
final String toString ()
final T value ()
returns the result
final boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Static Public Member Functions
static< N > IFuzzyValue< N > from (@Nonnull final N p_value)
factory
static< N > IFuzzyValue< N > from (@Nonnull final N p_value, final double p_fuzzy)
factory
Private Attributes
final double m_fuzzy
fuzzy value
final T m_value
value
Detailed Description
Definition at line 39 of file CFuzzyValue.java.
Constructor & Destructor Documentation
CFuzzyValue() [1/3]
org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.CFuzzyValue (@Nonnull final IFuzzyValue< T > p_value)
Parameters
p_value fuzzy value
Definition at line 55 of file CFuzzyValue.java.
CFuzzyValue() [2/3]
org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.CFuzzyValue (@Nonnull final T p_value)
Parameters
p_value value
Definition at line 65 of file CFuzzyValue.java.
CFuzzyValue() [3/3]
org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.CFuzzyValue (@Nonnull final T p_value, final double p_fuzzy)
Parameters
p_value value
p_fuzzy fuzzy
Definition at line 76 of file CFuzzyValue.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Function Documentation
from() [1/2]
static <N> IFuzzyValue<N> org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from (@Nonnull final N p_value) static
Parameters
p_value value
Returns
fuzzy value
Template Parameters
N fuzzy type
Definition at line 129 of file CFuzzyValue.java.
Referenced by org.lightjason.agentspeak.language.fuzzy.operator.bool.CComplement.complement(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.condition(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.CEmptyPlan.condition(), org.lightjason.agentspeak.action.builtin.agent.CCycleTime.execute(), org.lightjason.agentspeak.action.builtin.agent.CClearBeliefbase.execute(), org.lightjason.agentspeak.action.builtin.agent.CSleep.execute(), org.lightjason.agentspeak.action.builtin.generic.CUuid.execute(), org.lightjason.agentspeak.action.builtin.agent.CPlanList.execute(), org.lightjason.agentspeak.action.builtin.graph.IApplySingle.execute(), org.lightjason.agentspeak.language.execution.action.achievement_test.CTestRule.execute(), org.lightjason.agentspeak.action.builtin.graph.IApplyMultiple.execute(), org.lightjason.agentspeak.action.builtin.datetime.IDateTime.execute(), org.lightjason.agentspeak.action.builtin.bool.CCountTrue.execute(), org.lightjason.agentspeak.action.builtin.math.CSum.execute(), org.lightjason.agentspeak.action.builtin.string.CLower.execute(), org.lightjason.agentspeak.action.builtin.agent.CBeliefList.execute(), org.lightjason.agentspeak.action.builtin.math.CAbs.execute(), org.lightjason.agentspeak.action.builtin.string.CReverse.execute(), org.lightjason.agentspeak.action.builtin.math.CSin.execute(), org.lightjason.agentspeak.action.builtin.math.CCos.execute(), org.lightjason.agentspeak.action.builtin.bool.CCountFalse.execute(), org.lightjason.agentspeak.action.builtin.string.CSize.execute(), org.lightjason.agentspeak.action.builtin.math.CSqrt.execute(), org.lightjason.agentspeak.action.builtin.generic.CThrow.execute(), org.lightjason.agentspeak.action.builtin.string.CUpper.execute(), org.lightjason.agentspeak.action.builtin.math.CATan.execute(), org.lightjason.agentspeak.action.builtin.math.CLog10.execute(), org.lightjason.agentspeak.action.builtin.math.CDegrees.execute(), org.lightjason.agentspeak.action.builtin.math.CACos.execute(), org.lightjason.agentspeak.action.builtin.string.CEndsWith.execute(), org.lightjason.agentspeak.action.builtin.math.CRadians.execute(), org.lightjason.agentspeak.action.builtin.math.CExp.execute(), org.lightjason.agentspeak.action.builtin.string.CContains.execute(), org.lightjason.agentspeak.action.builtin.collection.tuple.CSet.execute(), org.lightjason.agentspeak.action.builtin.math.CFloor.execute(), org.lightjason.agentspeak.action.builtin.math.CSignum.execute(), org.lightjason.agentspeak.action.builtin.math.CSinh.execute(), org.lightjason.agentspeak.action.builtin.math.CASin.execute(), org.lightjason.agentspeak.action.builtin.math.CCosh.execute(), org.lightjason.agentspeak.action.builtin.string.CStartsWith.execute(), org.lightjason.agentspeak.action.builtin.math.CHypot.execute(), org.lightjason.agentspeak.action.builtin.math.CTanh.execute(), org.lightjason.agentspeak.action.builtin.math.CCeil.execute(), org.lightjason.agentspeak.action.builtin.graph.CVertexCount.execute(), org.lightjason.agentspeak.action.builtin.bool.CXor.execute(), org.lightjason.agentspeak.action.builtin.math.CLog.execute(), org.lightjason.agentspeak.action.builtin.math.CMax.execute(), org.lightjason.agentspeak.action.builtin.math.CMin.execute(), org.lightjason.agentspeak.action.builtin.math.CAverage.execute(), org.lightjason.agentspeak.action.builtin.bool.CNot.execute(), org.lightjason.agentspeak.action.builtin.bool.COr.execute(), org.lightjason.agentspeak.action.builtin.graph.CEdgeCount.execute(), org.lightjason.agentspeak.action.builtin.math.CPow.execute(), org.lightjason.agentspeak.action.builtin.string.CConcat.execute(), org.lightjason.agentspeak.action.builtin.bool.CAnd.execute(), org.lightjason.agentspeak.action.builtin.math.CFactorial.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CFlat.execute(), org.lightjason.agentspeak.action.builtin.math.CRound.execute(), org.lightjason.agentspeak.action.builtin.math.CGeometricMean.execute(), org.lightjason.agentspeak.action.builtin.agent.CAddPlan.execute(), org.lightjason.agentspeak.action.builtin.math.CHarmonicMean.execute(), org.lightjason.agentspeak.action.builtin.math.CTan.execute(), org.lightjason.agentspeak.action.builtin.collection.CClear.execute(), org.lightjason.agentspeak.action.builtin.graph.CVertices.execute(), org.lightjason.agentspeak.action.builtin.web.rest.CXMLObject.execute(), org.lightjason.agentspeak.action.builtin.math.CNextPrime.execute(), org.lightjason.agentspeak.action.builtin.string.CBase64Encode.execute(), org.lightjason.agentspeak.action.builtin.string.CRandom.execute(), org.lightjason.agentspeak.action.builtin.bool.CAllMatch.execute(), org.lightjason.agentspeak.action.builtin.string.CReplace.execute(), org.lightjason.agentspeak.action.builtin.bool.CAnyMatch.execute(), org.lightjason.agentspeak.language.execution.action.achievement_test.CTestGoal.execute(), org.lightjason.agentspeak.action.builtin.math.CIsPrime.execute(), org.lightjason.agentspeak.action.builtin.math.CMaxIndex.execute(), org.lightjason.agentspeak.action.builtin.generic.type.IParse.execute(), org.lightjason.agentspeak.action.builtin.math.CMinIndex.execute(), org.lightjason.agentspeak.action.builtin.graph.CEdges.execute(), org.lightjason.agentspeak.action.builtin.string.CBase64Decode.execute(), org.lightjason.agentspeak.action.builtin.math.CPrimeFactors.execute(), org.lightjason.agentspeak.action.builtin.graph.CContainsEdge.execute(), org.lightjason.agentspeak.action.builtin.graph.CContainsVertex.execute(), org.lightjason.agentspeak.action.builtin.math.CBinomial.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CHammingDistance.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CHammingDistance.execute(), org.lightjason.agentspeak.action.builtin.collection.CIsEmpty.execute(), org.lightjason.agentspeak.action.builtin.web.rest.CJsonObject.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.IOperator.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.IOperator.execute(), org.lightjason.agentspeak.action.builtin.string.CNCD.execute(), org.lightjason.agentspeak.language.execution.expression.CAtom.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CComparable.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CPower.execute(), org.lightjason.agentspeak.action.builtin.math.CSigmoid.execute(), org.lightjason.agentspeak.language.execution.expression.logical.CBinary.execute(), org.lightjason.agentspeak.action.builtin.collection.CSize.execute(), org.lightjason.agentspeak.action.builtin.math.CStirling.execute(), org.lightjason.agentspeak.action.builtin.datetime.CBuild.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToVector.execute(), org.lightjason.agentspeak.language.execution.expression.logical.CUnary.execute(), org.lightjason.agentspeak.action.builtin.web.rest.CJsonList.execute(), org.lightjason.agentspeak.action.builtin.crypto.CCreateKey.execute(), org.lightjason.agentspeak.action.builtin.collection.IMapApplySingle< Map< Object, Object > >.execute(), org.lightjason.agentspeak.action.builtin.collection.IMapGetMultiple< Map< Object, Object > >.execute(), org.lightjason.agentspeak.action.builtin.collection.IMapGetSingle< Map< Object, Object > >.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CCreate.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CCreate.execute(), org.lightjason.agentspeak.action.builtin.string.CLevenshtein.execute(), org.lightjason.agentspeak.action.builtin.graph.IApplyPathAlgorithm.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CMultiplicative.execute(), org.lightjason.agentspeak.action.builtin.agent.CPlanStatistic.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CRandomSimple.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CAdd.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CType.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CIsString.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CAdd.execute(), org.lightjason.agentspeak.action.builtin.generic.type.ICast.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.IRowColumn.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CMultiplePercentile.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CIsNumeric.execute(), org.lightjason.agentspeak.action.builtin.datetime.IPlusMinus.execute(), org.lightjason.agentspeak.language.execution.expression.numerical.CAdditive.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CSet.execute(), org.lightjason.agentspeak.action.builtin.collection.IMapApplyMultiple< Map< Object, Object > >.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CSinglePercentile.execute(), org.lightjason.agentspeak.action.builtin.math.blas.CSize.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSolve.execute(), org.lightjason.agentspeak.action.builtin.collection.multimap.CCreate.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CIsNull.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CColumns.execute(), org.lightjason.agentspeak.language.execution.expressionunary.CDecrement< T extends Number >.execute(), org.lightjason.agentspeak.action.builtin.crypto.CDecrypt.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNonZero.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CNonZero.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CNot.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CNot.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CDimension.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDimension.execute(), org.lightjason.agentspeak.action.builtin.agent.CRemovePlan.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CFalseCount.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CFalseCount.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CRows.execute(), org.lightjason.agentspeak.language.execution.action.CSingleAssignment< M extends IExecution >.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CClearStatistic.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSum.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CSum.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CIdentity.execute(), org.lightjason.agentspeak.language.execution.expressionunary.CIncrement< T extends Number >.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CTrueCount.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CTrueCount.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRows.execute(), org.lightjason.agentspeak.action.builtin.collection.multimap.CKeys.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CKeys.execute(), org.lightjason.agentspeak.action.builtin.datetime.IBetween.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CMatrixNorm.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CCreateLiteral.execute(), org.lightjason.agentspeak.language.execution.action.CDeconstruct< M extends ITerm >.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumns.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumnSum.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDeterminant.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDiagonal.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.COneNorm.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CGet.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTranspose.execute(), org.lightjason.agentspeak.action.builtin.crypto.CEncrypt.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCondition.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRank.execute(), org.lightjason.agentspeak.language.execution.action.CBeliefAction.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CRemove.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CReverse.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CCopy.execute(), org.lightjason.agentspeak.action.builtin.collection.tuple.CFlat.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRowSum.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CCopy.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CFuzzyReturn.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCopy.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CCopy.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CSize.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CSize.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CToList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CInvert.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTrace.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumn.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CFlatConcat.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CUnique.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CCreateStatistic.execute(), org.lightjason.agentspeak.language.execution.action.CMultiAssignment< M extends IExecution >.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CValues.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTwoNorm.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CContains.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CBoolValue.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CRemove.execute(), org.lightjason.agentspeak.action.builtin.collection.tuple.CCreate.execute(), org.lightjason.agentspeak.action.builtin.collection.multimap.CValues.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSet.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CSet.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CGet.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSubMatrix.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CInfinityNorm.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CIs.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CClear.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CUnion.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CToList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.CMultiply.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CNumericValue.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CEigen.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CToList.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CToList.execute(), org.lightjason.agentspeak.action.builtin.math.shape.CInTriangle.execute(), org.lightjason.agentspeak.action.builtin.graph.CSpanningTree.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRow.execute(), org.lightjason.agentspeak.action.builtin.collection.multimap.CAsMap.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CSet.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSingularValue.execute(), org.lightjason.agentspeak.action.builtin.math.interpolate.CMultipleInterpolate.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.ISelection.execute(), org.lightjason.agentspeak.action.builtin.math.interpolate.CSingleInterpolate.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CGet.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNormalizedGraphLaplacian.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CDotProduct.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CComplement.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CPower.execute(), org.lightjason.agentspeak.language.execution.action.achievement_test.IAchievementRule< IVariableEvaluate >.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CGraphLaplacian.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CNumericValue.execute(), org.lightjason.agentspeak.action.builtin.math.shape.CInCircle.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CIntersect.execute(), org.lightjason.agentspeak.action.builtin.math.shape.CInRectangle.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CBoolValue.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CZip.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CRemove.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CFromList.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CRange.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CAssign.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CAssign.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CMultipleStatisticValue.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CSubList.execute(), org.lightjason.agentspeak.action.builtin.math.linearprogram.CEquationConstraint.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CCreate.execute(), org.lightjason.agentspeak.action.builtin.agent.CGetPlan.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CAddStatisticValue.execute(), org.lightjason.agentspeak.action.builtin.math.linearprogram.CValueConstraint.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CSingleStatisticValue.execute(), org.lightjason.agentspeak.action.builtin.math.blas.vector.CParse.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CRandomSample.execute(), org.lightjason.agentspeak.language.execution.action.unify.CVariableUnify.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CRange.execute(), org.lightjason.agentspeak.action.builtin.math.blas.CElementWise.execute(), org.lightjason.agentspeak.language.execution.action.CTernaryOperation.execute(), org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CSymmetricDifference.execute(), org.lightjason.agentspeak.action.builtin.math.bit.vector.CToBlas.execute(), org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToBlas.execute(), org.lightjason.agentspeak.action.builtin.graph.CCreate.execute(), org.lightjason.agentspeak.action.builtin.math.linearprogram.CCreate.execute(), org.lightjason.agentspeak.action.builtin.crypto.CHash.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CParse.execute(), org.lightjason.agentspeak.action.builtin.math.blas.matrix.CPerronFrobenius.execute(), org.lightjason.agentspeak.action.builtin.math.interpolate.CCreate.execute(), org.lightjason.agentspeak.action.builtin.storage.CClear.execute(), org.lightjason.agentspeak.action.builtin.graph.CAdjacencyMatrix.execute(), org.lightjason.agentspeak.language.instantiable.rule.CRulePlaceholder.execute(), org.lightjason.agentspeak.action.builtin.math.linearprogram.CSolve.execute(), org.lightjason.agentspeak.action.builtin.web.graphql.IBaseGraphQL.execute(), org.lightjason.agentspeak.action.builtin.storage.CAdd.execute(), org.lightjason.agentspeak.action.builtin.storage.CExists.execute(), org.lightjason.agentspeak.action.builtin.storage.CRemove.execute(), org.lightjason.agentspeak.language.execution.action.CLambdaExpression.execute(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute(), org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.execute(), org.lightjason.agentspeak.action.builtin.generic.CPrint.execute(), org.lightjason.agentspeak.action.binding.CMethodAction.execute(), org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute(), org.lightjason.agentspeak.agent.TestCAgent.CEmptyPrint.execute(), org.lightjason.agentspeak.beliefbase.TestCViewMap.CEmptyPrint.execute(), org.lightjason.agentspeak.agent.TestCAgent.CTestResult.execute(), org.lightjason.agentspeak.beliefbase.TestCViewMap.CTestResult.execute(), org.lightjason.agentspeak.agent.TestCAgentExecution.CStop.execute(), org.lightjason.agentspeak.agent.TestCAgentExecution.CLog.execute(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CEmptyPrint.execute(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CStop.execute(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerSize.execute(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPush.execute(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPop.execute(), org.lightjason.agentspeak.language.execution.action.CRawAction< T >.getTypedResult(), org.lightjason.agentspeak.action.builtin.bool.CEqual.pack(), org.lightjason.agentspeak.action.binding.CMethodAction.returnvalues(), org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.trigger(), and org.lightjason.agentspeak.language.unify.CUnifier.unify().
from() [2/2]
static <N> IFuzzyValue<N> org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from (@Nonnull final N p_value, final double p_fuzzy) static
Parameters
p_value value
p_fuzzy fuzzy value
Returns
fuzzy value
Template Parameters
N fuzzy type
Definition at line 144 of file CFuzzyValue.java.
fuzzy()
final double org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.fuzzy ()
Returns
fuzzy value in [0,1]
Implements org.lightjason.agentspeak.language.fuzzy.IFuzzyValue< T >.
Definition at line 93 of file CFuzzyValue.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.m_fuzzy.
throwvaluenotassignableto()
final T org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
Parameters
p_class assignable class
Returns
object itself
Exceptions
IllegalArgumentException on assignable error
Implements org.lightjason.agentspeak.language.IAssignable< T >.
Definition at line 106 of file CFuzzyValue.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.m_value, and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.valueassignableto().
toString()
final String org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.toString ()
Definition at line 115 of file CFuzzyValue.java.
value()
final T org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.value ()
Returns
value
Implements org.lightjason.agentspeak.language.fuzzy.IFuzzyValue< T >.
Definition at line 87 of file CFuzzyValue.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.m_value.
valueassignableto()
final boolean org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.valueassignableto (@Nonnull final Class<?>... p_class)
Parameters
p_class class
Returns
assignable (on null always true)
Implements org.lightjason.agentspeak.language.IAssignable< T >.
Definition at line 99 of file CFuzzyValue.java.
Referenced by org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.throwvaluenotassignableto().
Member Data Documentation
m_fuzzy
final double org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.m_fuzzy private
Definition at line 48 of file CFuzzyValue.java.
Referenced by org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.fuzzy().
m_value
final T org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.m_value private
Definition at line 44 of file CFuzzyValue.java.
Referenced by org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.throwvaluenotassignableto(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.value().