LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion Class Reference
org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion Class Reference
fuzzy-boolean disjunction / union
Public Member Functions
final BiConsumer< IFuzzyValueMutable< Boolean >, IFuzzyValue< Boolean > > accumulator ()
final Set< Characteristics > characteristics ()
final BinaryOperator< IFuzzyValueMutable< Boolean > > combiner ()
final Function< IFuzzyValueMutable< Boolean >, IFuzzyValue< Boolean > > finisher ()
final IFuzzyValue< Boolean > result (@Nonnull final IFuzzyValue< Boolean >... p_values)
final Supplier< IFuzzyValueMutable< Boolean > > supplier ()
Public Member Functions inherited from org.lightjason.agentspeak.language.fuzzy.operator.IFuzzyOperator< T >
IFuzzyValue< T > result (@Nonnull final IFuzzyValue< T >... p_values)
calculates for a array of values the result
Static Private Member Functions
static IFuzzyValueMutable< Boolean > factory ()
factory of the initialize value
Detailed Description
Definition at line 44 of file language/fuzzy/operator/bool/CUnion.java.
Member Function Documentation
accumulator()
final BiConsumer<IFuzzyValueMutable<Boolean>, IFuzzyValue<Boolean> > org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.accumulator ()
Definition at line 54 of file language/fuzzy/operator/bool/CUnion.java.
characteristics()
final Set<Characteristics> org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.characteristics ()
Definition at line 72 of file language/fuzzy/operator/bool/CUnion.java.
combiner()
final BinaryOperator<IFuzzyValueMutable<Boolean> > org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.combiner ()
Definition at line 60 of file language/fuzzy/operator/bool/CUnion.java.
factory()
static IFuzzyValueMutable<Boolean> org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.factory () static private
Returns
fuzzy value
Definition at line 91 of file language/fuzzy/operator/bool/CUnion.java.
References org.lightjason.agentspeak.language.fuzzy.CFuzzyValueMutable< T >.from().
Referenced by org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.supplier().
finisher()
final Function<IFuzzyValueMutable<Boolean>, IFuzzyValue<Boolean> > org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.finisher ()
Definition at line 66 of file language/fuzzy/operator/bool/CUnion.java.
References org.lightjason.agentspeak.language.fuzzy.IFuzzyValueMutable< T >.immutable().
result()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.result (@Nonnull final IFuzzyValue< Boolean >... p_values)
Definition at line 81 of file language/fuzzy/operator/bool/CUnion.java.
supplier()
final Supplier<IFuzzyValueMutable<Boolean> > org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.supplier ()
Definition at line 48 of file language/fuzzy/operator/bool/CUnion.java.
References org.lightjason.agentspeak.language.fuzzy.operator.bool.CUnion.factory().