LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.ILiteral Interface Reference
org.lightjason.agentspeak.language.ILiteral Interface Reference
literal interface
Public Member Functions
ILiteral allocate (@Nonnull final IContext p_context)
allocate all variables with the current context
boolean emptyValues ()
check for empty values
boolean hasAt ()
returns if the literal has an @ prefix
boolean negated ()
getter of the literal for the negation
Stream< ITerm > orderedvalues (@Nullable final IPath... p_path)
returns a stream over the ordered values in sequential ordering
ILiteral unify (@Nonnull final IContext p_context)
unifies variables if exists
Stream< ITerm > values (final IPath... p_path)
returns a stream over value items
Public Member Functions inherited from org.lightjason.agentspeak.language.ITerm
IPath fqnfunctor ()
returns the full-qualified functor with path and name
String functor ()
returns the functor without path
IPath functorpath ()
returns the path of the functor
boolean hasVariable ()
checks if the literal has variables
< T > T raw ()
cast to any raw value type
default< T extends ITerm > T term ()
casts the object to a term-type
Public Member Functions inherited from org.lightjason.agentspeak.language.IStructureHash
int structurehash ()
returns a hash value which defines a hash ove rthe structure
Public Member Functions inherited from org.lightjason.agentspeak.language.IDeepCopy< ITerm >
T deepcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T deepcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Public Member Functions inherited from org.lightjason.agentspeak.language.IShallowCopy< ILiteral >
T shallowcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Public Attributes
ILiteral EMPTY
empty literal
Public Attributes inherited from org.lightjason.agentspeak.language.ITerm
ITerm EMPTY
empty term
long serialVersionUID = -3640918490398129717L
serial id
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Detailed Description
Note
closed world assumption, no negation marker needed
Definition at line 39 of file ILiteral.java.
Member Function Documentation
allocate()
ILiteral org.lightjason.agentspeak.language.ILiteral.allocate (@Nonnull final IContext p_context)
Parameters
p_context current execution context
Returns
literal with replaced variable
Implemented in org.lightjason.agentspeak.language.CLiteral.
Referenced by org.lightjason.agentspeak.language.execution.action.achievement_test.IAchievementRule< IVariableEvaluate >.execute().
emptyValues()
boolean org.lightjason.agentspeak.language.ILiteral.emptyValues ()
Returns
empty flag
Implemented in org.lightjason.agentspeak.language.CLiteral.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.literal(), org.lightjason.agentspeak.beliefbase.storage.CClassStorage< M >.putMultiElement(), and org.lightjason.agentspeak.language.unify.CUnifier.variables().
hasAt()
boolean org.lightjason.agentspeak.language.ILiteral.hasAt ()
Returns
prefix is set
Implemented in org.lightjason.agentspeak.language.CLiteral.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.literal().
negated()
boolean org.lightjason.agentspeak.language.ILiteral.negated ()
Returns
negated flag
Implemented in org.lightjason.agentspeak.language.CLiteral.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral(), and org.lightjason.agentspeak.language.unify.CUnifier.variables().
orderedvalues()
Stream<ITerm> org.lightjason.agentspeak.language.ILiteral.orderedvalues (@Nullable final IPath... p_path)
Returns
term stream
Implemented in org.lightjason.agentspeak.language.CLiteral.
Referenced by org.lightjason.agentspeak.agent.TestCUnifier.literalvaluesequentialtraversing(), org.lightjason.agentspeak.language.unify.CRecursive.unify(), org.lightjason.agentspeak.language.instantiable.rule.CRule.variables(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables().
unify()
ILiteral org.lightjason.agentspeak.language.ILiteral.unify (@Nonnull final IContext p_context)
Parameters
p_context current execution context
Returns
new literal instance with unified variables
Note
un-unifyable variables passwd into the result literal
Implemented in org.lightjason.agentspeak.language.CLiteral.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.CPlan.execute(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral(), and org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromString().
values()
Stream<ITerm> org.lightjason.agentspeak.language.ILiteral.values (final IPath... p_path)
Parameters
p_path optional filtering value names (filtering values within values)
Returns
stream
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlistmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjectmultiple(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.literal(), org.lightjason.agentspeak.agent.TestCUnifier.literalvaluetraversing(), org.lightjason.agentspeak.beliefbase.storage.CClassStorage< M >.putMultiElement(), and org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjectmultiple().
Member Data Documentation
EMPTY
ILiteral org.lightjason.agentspeak.language.ILiteral.EMPTY
Definition at line 44 of file ILiteral.java.