LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix Class Reference
test math blas matrix functions
Public Member Functions
final void action (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
test all input actions
final void assignmatrix ()
test assign matrix
final void assignscalar ()
test assign scalar
final void column ()
test column
final void columsum ()
test column sum
final void copy ()
test copy
final void create ()
test create
final void diagonal ()
test diagonal
final void eigen ()
test eigen
final void get ()
test get
final void graphlaplacian ()
test graph-laplacian
final void identity ()
test identity
final void invert ()
test invert
final void normalizedgraphlaplacian ()
test normalized graph-laplacian
final void parse ()
test parse
final void power ()
test power
final void row ()
test row
final void rowsum ()
test row sum
final void set ()
test set
final void singularvalue ()
test singularvalue
final void solve ()
test solve
final void submatrix ()
test submatrix
final void tolist ()
test toList
final void transpose ()
test transpose
Static Public Member Functions
static Object [] generator ()
data provider generator
Static Private Member Functions
static Stream< Object > testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult)
method to generate test-cases
Static Private Attributes
static final DoubleMatrix2D MATRIX1 = new DenseDoubleMatrix2D(new double[][]{{2, 6}, {3, 8}})
testing matrix
static final DoubleMatrix2D MATRIX2 = new DenseDoubleMatrix2D(new double[][]{{2, 2}, {3, 1}})
testing matrix
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 97 of file TestCActionMathBlasMatrix.java.
Member Function Documentation
action()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.action (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
Parameters
p_input tripel of input data, actions and results
Exceptions
IllegalAccessException is thrwon on instantiation error
InstantiationException is thrwon on instantiation error
NoSuchMethodException is thrwon on instantiation error
InvocationTargetException is thrwon on instantiation error
Definition at line 189 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.ITerm.raw().
assignmatrix()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.assignmatrix ()
Definition at line 426 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CAssign.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
assignscalar()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.assignscalar ()
Definition at line 409 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CAssign.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
column()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.column ()
Definition at line 233 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.IRowColumn.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
columsum()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.columsum ()
Definition at line 687 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CColumnSum.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
copy()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.copy ()
Definition at line 563 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CCopy.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.create ()
Definition at line 211 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
diagonal()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.diagonal ()
Definition at line 748 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CDiagonal.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
eigen()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.eigen ()
Definition at line 506 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CEigen.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
generator()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.generator () static
Returns
data
Definition at line 117 of file TestCActionMathBlasMatrix.java.
get()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.get ()
Definition at line 443 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CGet.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
graphlaplacian()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.graphlaplacian ()
Definition at line 582 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CGraphLaplacian.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
identity()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.identity ()
Definition at line 718 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CIdentity.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
invert()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.invert ()
Definition at line 484 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CInvert.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
normalizedgraphlaplacian()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.normalizedgraphlaplacian ()
Definition at line 622 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CNormalizedGraphLaplacian.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
parse()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.parse ()
Definition at line 462 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CParse.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
power()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.power ()
Definition at line 277 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CPower.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
row()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.row ()
Definition at line 255 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.IRowColumn.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
rowsum()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.rowsum ()
Definition at line 656 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CRowSum.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
set()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.set ()
Definition at line 302 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CSet.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
singularvalue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.singularvalue ()
Definition at line 531 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSingularValue.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
solve()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.solve ()
Definition at line 386 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSolve.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
submatrix()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.submatrix ()
Definition at line 363 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSubMatrix.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
testcase()
static Stream<Object> org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult) static private
Parameters
p_input input data
p_classes matching test-classes / test-cases
p_classresult result for each class
Returns
test-object
Definition at line 166 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
tolist()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.tolist ()
Definition at line 317 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.set.CToList.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
transpose()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.transpose ()
Definition at line 340 of file TestCActionMathBlasMatrix.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CTranspose.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
Member Data Documentation
MATRIX1
final DoubleMatrix2D org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.MATRIX1 = new DenseDoubleMatrix2D(new double[][]{{2, 6}, {3, 8}}) static private
Note
static because of usage in data-provider
Definition at line 104 of file TestCActionMathBlasMatrix.java.
MATRIX2
final DoubleMatrix2D org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.MATRIX2 = new DenseDoubleMatrix2D(new double[][]{{2, 2}, {3, 1}}) static private
Note
static because of usage in data-provider
Definition at line 110 of file TestCActionMathBlasMatrix.java.