LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionGeneric Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionGeneric Class Reference
test generic actions
Classes
class CBooleanFormatter
test formatter for boolean (translate each boolean to an yes/no string)
class CStringFormatter
test formatter for strings (translate each string to an upper-case string)
Public Member Functions
final void print () throws Exception
test print action
final void printformatter () throws Exception
test print action with formatter
final void thrownot ()
test throw without throwing
final void throwparameter ()
test throw action
final void throwwithoutparameter ()
test throw action
final void uuid ()
test single uuid
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 49 of file TestCActionGeneric.java.
Member Function Documentation
print()
final void org.lightjason.agentspeak.action.builtin.TestCActionGeneric.print () throws Exception
Exceptions
Exception is thrown on encoding errors
Definition at line 100 of file TestCActionGeneric.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.CPrint.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
printformatter()
final void org.lightjason.agentspeak.action.builtin.TestCActionGeneric.printformatter () throws Exception
Exceptions
Exception is thrown on encoding errors
Definition at line 119 of file TestCActionGeneric.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.CPrint.execute(), org.lightjason.agentspeak.action.builtin.generic.CPrint.formatter(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
thrownot()
final void org.lightjason.agentspeak.action.builtin.TestCActionGeneric.thrownot ()
Definition at line 84 of file TestCActionGeneric.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.CThrow.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
throwparameter()
final void org.lightjason.agentspeak.action.builtin.TestCActionGeneric.throwparameter ()
Definition at line 56 of file TestCActionGeneric.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.CThrow.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
throwwithoutparameter()
final void org.lightjason.agentspeak.action.builtin.TestCActionGeneric.throwwithoutparameter ()
Definition at line 70 of file TestCActionGeneric.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.generic.CThrow.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
uuid()
final void org.lightjason.agentspeak.action.builtin.TestCActionGeneric.uuid ()
Definition at line 146 of file TestCActionGeneric.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.action.builtin.generic.CUuid.execute().