LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.IStructure Interface Reference
org.lightjason.agentspeak.beliefbase.IStructure Interface Reference
interface for equal method on views and beliefbases
Public Member Functions
boolean empty ()
checks if the structure empty
int size ()
returns the size of literals
IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
Detailed Description
Template Parameters
T agent type
Definition at line 36 of file IStructure.java.
Member Function Documentation
empty()
boolean org.lightjason.agentspeak.beliefbase.IStructure.empty ()
Returns
empty boolean
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.view.CViewMap, org.lightjason.agentspeak.beliefbase.view.CView, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.empty(), org.lightjason.agentspeak.beliefbase.view.CViewMap.empty(), and org.lightjason.agentspeak.beliefbase.view.CView.walkdown().
size()
int org.lightjason.agentspeak.beliefbase.IStructure.size ()
Returns
size
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.view.CViewMap, org.lightjason.agentspeak.beliefbase.view.CView, org.lightjason.agentspeak.beliefbase.CBeliefbase, and org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?>.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.belieflist(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.clearbeliefbase(), org.lightjason.agentspeak.beliefbase.CBeliefbase.size(), org.lightjason.agentspeak.beliefbase.view.CView.size(), org.lightjason.agentspeak.beliefbase.view.CViewMap.size(), org.lightjason.agentspeak.beliefbase.TestCView.testManual(), and org.lightjason.agentspeak.beliefbase.TestCView.testTree().
update()
IAgent<?> org.lightjason.agentspeak.beliefbase.IStructure.update (@Nonnull final IAgent<?> p_agent)
Parameters
p_agent agent which runs the update call
Returns
agent
Warning
call update on a storage and on all storage-view, if exists different views which are point to the same storage, the update is called more than once, so the storage must limit the number of update calls
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap.CWrapperBeliefbase, org.lightjason.agentspeak.beliefbase.view.CViewMap, org.lightjason.agentspeak.beliefbase.CBeliefbase, org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.call(), org.lightjason.agentspeak.beliefbase.view.CView.update(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.update().