LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.TestCView Class Reference
org.lightjason.agentspeak.beliefbase.TestCView Class Reference
test of beliefbase view
Classes
class CGenerator
test belief generator
Public Member Functions
final void testManual ()
manual test of tree structure
final void testTree ()
random test tree structure
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 43 of file TestCView.java.
Member Function Documentation
testManual()
final void org.lightjason.agentspeak.beliefbase.TestCView.testManual ()
Definition at line 69 of file TestCView.java.
References org.lightjason.agentspeak.beliefbase.view.IView.add(), org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.create(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.common.CPath.from(), and org.lightjason.agentspeak.beliefbase.IStructure.size().
testTree()
final void org.lightjason.agentspeak.beliefbase.TestCView.testTree ()
Definition at line 50 of file TestCView.java.
References org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.create(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.beliefbase.view.IView.generate(), and org.lightjason.agentspeak.beliefbase.IStructure.size().