LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger Interface Reference
org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger Interface Reference
event definition
Classes
enum EType
event types
Public Member Functions
ILiteral literal ()
returns the literal of the event
EType type ()
returns the type of the event
int variablesize ()
returns variable number
Public Member Functions inherited from org.lightjason.agentspeak.language.IStructureHash
int structurehash ()
returns a hash value which defines a hash ove rthe structure
Public Member Functions inherited from org.lightjason.agentspeak.language.IShallowCopy< T >
T shallowcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Public Attributes
ITrigger EMPTY
empty trigger
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Detailed Description
Note
trigger are equal iif type and literal functor are equal and number of arguments are equal, otherwise unification is used to define the literal variables
Definition at line 50 of file ITrigger.java.
Member Function Documentation
literal()
ILiteral org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.literal ()
Returns
literal
Implemented in org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.CPlan.execute(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables().
type()
EType org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.type ()
Returns
type
Implemented in org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist().
variablesize()
int org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.variablesize ()
Returns
number
Implemented in org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.
Member Data Documentation
EMPTY
ITrigger org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EMPTY
Definition at line 55 of file ITrigger.java.