LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionCrypto Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionCrypto Class Reference
test action crypto
Public Member Functions
final void createkey (final Triple< String, Integer, Integer > p_crypt)
test crypt key generation
final void createkeyError ()
test key generation on error call
final void decryptexecutionerror () throws NoSuchAlgorithmException
test decrypt execution array
final void encryptdecreypt (final Triple< String, Integer, Integer > p_crypt)
test encrypting and decrypting
final void hash (final Pair< String, String[]> p_hash)
test hashing
final void hashexception ()
test hash exception
final void wrongalgorithm () throws NoSuchAlgorithmException
test wrong algorithm
Static Public Member Functions
static Object [] generatecrypt ()
data provider generator of crypt key definition
static Object [] generatehash ()
data provider generator of hash definition
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 62 of file TestCActionCrypto.java.
Member Function Documentation
createkey()
final void org.lightjason.agentspeak.action.builtin.TestCActionCrypto.createkey (final Triple< String, Integer, Integer > p_crypt)
Parameters
p_crypt crypt definition
Definition at line 92 of file TestCActionCrypto.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.crypto.CCreateKey.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
createkeyError()
final void org.lightjason.agentspeak.action.builtin.TestCActionCrypto.createkeyError ()
Definition at line 213 of file TestCActionCrypto.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
decryptexecutionerror()
final void org.lightjason.agentspeak.action.builtin.TestCActionCrypto.decryptexecutionerror () throws NoSuchAlgorithmException
Exceptions
NoSuchAlgorithmException is thrown on key generator error
Definition at line 140 of file TestCActionCrypto.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.crypto.CEncrypt.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.action.builtin.crypto.EAlgorithm.RSA.
encryptdecreypt()
final void org.lightjason.agentspeak.action.builtin.TestCActionCrypto.encryptdecreypt (final Triple< String, Integer, Integer > p_crypt)
Parameters
p_crypt tripel with input data
Definition at line 232 of file TestCActionCrypto.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.crypto.CCreateKey.execute(), org.lightjason.agentspeak.action.builtin.crypto.CDecrypt.execute(), org.lightjason.agentspeak.action.builtin.crypto.CEncrypt.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
generatecrypt()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionCrypto.generatecrypt () static
Returns
data
Definition at line 200 of file TestCActionCrypto.java.
generatehash()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionCrypto.generatehash () static
Returns
data
Definition at line 71 of file TestCActionCrypto.java.
hash()
final void org.lightjason.agentspeak.action.builtin.TestCActionCrypto.hash (final Pair< String, String[]> p_hash)
Parameters
p_hash hash value
Definition at line 168 of file TestCActionCrypto.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.crypto.CHash.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
hashexception()
final void org.lightjason.agentspeak.action.builtin.TestCActionCrypto.hashexception ()
Definition at line 185 of file TestCActionCrypto.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.crypto.CHash.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
wrongalgorithm()
final void org.lightjason.agentspeak.action.builtin.TestCActionCrypto.wrongalgorithm () throws NoSuchAlgorithmException
Exceptions
NoSuchAlgorithmException is thrown on key generator error
Definition at line 112 of file TestCActionCrypto.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().