LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector Class Reference
test for bit vector actions
Public Member Functions
final void action (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
test all single-input actions
final void boolValue ()
test boolean value
final void clear ()
test clear
final void create ()
test create
final void initialize ()
initialize
final void numericvalue ()
test numericvalue
final void range ()
test range
final void set ()
test set
final void toblas ()
test toblas
final void tolist ()
test toList
Static Public Member Functions
static Object [] generator ()
data provider generator
Static Private Member Functions
static Stream< Object > testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult)
method to generate test-cases
Static Private Attributes
static final BitVector VECTOR1 = new BitVector(3)
testing vector
static final BitVector VECTOR2 = new BitVector(3)
testing matrix
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 75 of file TestCActionMathBitVector.java.
Member Function Documentation
action()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.action (final Triple< List< ITerm >, Class<? extends IAction >, Stream< Object >> p_input) throws IllegalAccessException, InstantiationException, NoSuchMethodException, InvocationTargetException
Parameters
p_input tripel of input data, actions classes and results
Exceptions
IllegalAccessException is thrwon on instantiation error
InstantiationException is thrwon on instantiation error
NoSuchMethodException is thrwon on instantiation error
InvocationTargetException is thrwon on instantiation error
Definition at line 174 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.ITerm.raw().
boolValue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.boolValue ()
Definition at line 215 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CBoolValue.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
clear()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.clear ()
Definition at line 248 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.CClear.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.create ()
Definition at line 196 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
generator()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.generator () static
Returns
data
Definition at line 109 of file TestCActionMathBitVector.java.
initialize()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.initialize ()
Definition at line 93 of file TestCActionMathBitVector.java.
numericvalue()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.numericvalue ()
Definition at line 281 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CNumericValue.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
range()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.range ()
Definition at line 263 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CRange.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
set()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.set ()
Definition at line 232 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CSet.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
testcase()
static Stream<Object> org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.testcase (final Stream< Object > p_input, final Stream< Class<?>> p_classes, final Stream< Object >... p_classresult) static private
Parameters
p_input input data
p_classes matching test-classes / test-cases
p_classresult result for each class
Returns
test-object
Definition at line 151 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
toblas()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.toblas ()
Definition at line 317 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.bit.matrix.CToBlas.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
tolist()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.tolist ()
Definition at line 298 of file TestCActionMathBitVector.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.set.CToList.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
Member Data Documentation
VECTOR1
final BitVector org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.VECTOR1 = new BitVector(3) static private
Note
static because of usage in data-provider and test-initialize
Definition at line 81 of file TestCActionMathBitVector.java.
VECTOR2
final BitVector org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.VECTOR2 = new BitVector(3) static private
Note
static because of usage in data-provider and test-initialize
Definition at line 86 of file TestCActionMathBitVector.java.