LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionCollectionList Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionCollectionList Class Reference
test collection list
Public Member Functions
final void add ()
test add action
final void complement ()
test complement action
final void create ()
test create non-empty list
final void createempty ()
test create empty list
final void createemptysynchronize ()
test create empty synchronized list
final void flat ()
test flat action
final void flatconcat ()
test flatconcat action
final void get ()
test get action
final void range ()
test range
final void rangeerror ()
test range error
final void remove ()
test remove action
final void reverse ()
test reverse action
final void set ()
test set action
final void sublist ()
test sublist
final void sublisterror ()
test sublist error
final void unique ()
test unique action
final void zip ()
test zip action
final void ziperror ()
test zip action error
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 62 of file TestCActionCollectionList.java.
Member Function Documentation
add()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.add ()
Definition at line 262 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CAdd.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
complement()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.complement ()
Definition at line 137 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CComplement.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.create ()
Definition at line 110 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
createempty()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.createempty ()
Definition at line 69 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute().
createemptysynchronize()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.createemptysynchronize ()
Definition at line 89 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute().
flat()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.flat ()
Definition at line 369 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CFlat.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
flatconcat()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.flatconcat ()
Definition at line 393 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CFlatConcat.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
get()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.get ()
Definition at line 161 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CGet.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
range()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.range ()
Definition at line 297 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CRange.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
rangeerror()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.rangeerror ()
Definition at line 281 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
remove()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.remove ()
Definition at line 201 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CRemove.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
reverse()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.reverse ()
Definition at line 182 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CReverse.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
set()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.set ()
Definition at line 239 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CSet.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
sublist()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.sublist ()
Definition at line 341 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CSubList.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
sublisterror()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.sublisterror ()
Definition at line 326 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
unique()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.unique ()
Definition at line 473 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CUnique.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
zip()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.zip ()
Definition at line 433 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CZip.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
ziperror()
final void org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.ziperror ()
Definition at line 417 of file TestCActionCollectionList.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().