LightJason - AgentSpeak(L++): org.lightjason.agentspeak.grammar.CASTVisitorType Class Reference
org.lightjason.agentspeak.grammar.CASTVisitorType Class Reference
parser for complex-datatypes
Public Member Functions
CASTVisitorType ()
ctor
CASTVisitorType (@Nonnull final Set< IAction > p_actions, @Nonnull final Set< IRule > p_rules)
ctor
final IExpression expression ()
get the parsed expression
final ILiteral literal ()
get the parsed literal
final ITerm term ()
get the parsed term
final Object visitAtom (final TypeParser.AtomContext p_context)
final Object visitDigitsequence (final TypeParser.DigitsequenceContext p_context)
final Object visitExecutable_action (final TypeParser.Executable_actionContext p_context)
final Object visitExecutable_rule (final TypeParser.Executable_ruleContext p_context)
final Object visitExecutable_term (final TypeParser.Executable_termContext p_context)
final Object visitExpression (final TypeParser.ExpressionContext p_context)
final Object visitExpression_bracket (final TypeParser.Expression_bracketContext p_context)
final Object visitExpression_logical_and (final TypeParser.Expression_logical_andContext p_context)
final Object visitExpression_logical_element (final TypeParser.Expression_logical_elementContext p_context)
final Object visitExpression_logical_negation (final TypeParser.Expression_logical_negationContext p_context)
final Object visitExpression_logical_xor (final TypeParser.Expression_logical_xorContext p_context)
final Object visitExpression_numeric (final TypeParser.Expression_numericContext p_context)
final Object visitExpression_numeric_additive (final TypeParser.Expression_numeric_additiveContext p_context)
final Object visitExpression_numeric_element (final TypeParser.Expression_numeric_elementContext p_context)
final Object visitExpression_numeric_multiplicative (final TypeParser.Expression_numeric_multiplicativeContext p_context)
final Object visitExpression_numeric_power (final TypeParser.Expression_numeric_powerContext p_context)
final Object visitExpression_numeric_relation (final TypeParser.Expression_numeric_relationContext p_context)
final Object visitExpression_term (final TypeParser.Expression_termContext p_context)
final Object visitExpression_type (final TypeParser.Expression_typeContext p_context)
final Object visitLiteral (final TypeParser.LiteralContext p_context)
final Object visitLiteral_type (final TypeParser.Literal_typeContext p_context)
final Object visitNumber (final TypeParser.NumberContext p_context)
final Object visitTerm (final TypeParser.TermContext p_context)
final Object visitTermlist (final TypeParser.TermlistContext p_context)
final Object visitTernary_operation (final TypeParser.Ternary_operationContext p_context)
final Object visitTernary_operation_false (final TypeParser.Ternary_operation_falseContext p_context)
final Object visitTernary_operation_true (final TypeParser.Ternary_operation_trueContext p_context)
final Object visitUnification (final TypeParser.UnificationContext p_context)
final Object visitUnification_constraint (final TypeParser.Unification_constraintContext p_context)
final Object visitVariable (final TypeParser.VariableContext p_context)
final Object visitVariable_evaluate (final TypeParser.Variable_evaluateContext p_context)
final Object visitVariableatom (final TypeParser.VariableatomContext p_context)
final Object visitVariablelist (final TypeParser.VariablelistContext p_context)
Static Private Member Functions
static boolean logicalvalue (@Nonnull final String p_value)
converts a string token to the type
static Number numericonstant (@Nonnull final String p_value)
returns the value of a numeric constant
static String stringvalue (@Nonnull final String p_value)
create a string value without quotes
Private Attributes
final Map< IPath, IAction > m_actions
map with action definition
IExpression m_expression = IExpression.EMPTY
parsed expression
ILiteral m_literal = ILiteral.EMPTY
parsed literal
final Multimap< IPath, IRule > m_rules = LinkedHashMultimap.create()
map with logical rules
ITerm m_term = ITerm.EMPTY
parsed term
Detailed Description
Definition at line 74 of file CASTVisitorType.java.
Constructor & Destructor Documentation
CASTVisitorType() [1/2]
org.lightjason.agentspeak.grammar.CASTVisitorType.CASTVisitorType ()
Definition at line 101 of file CASTVisitorType.java.
CASTVisitorType() [2/2]
org.lightjason.agentspeak.grammar.CASTVisitorType.CASTVisitorType (@Nonnull final Set< IAction > p_actions, @Nonnull final Set< IRule > p_rules)
Parameters
p_actions set with actions
p_rules set with rules
Definition at line 112 of file CASTVisitorType.java.
Member Function Documentation
expression()
final IExpression org.lightjason.agentspeak.grammar.CASTVisitorType.expression ()
Returns
expression
Implements org.lightjason.agentspeak.grammar.IASTVisitorType.
Definition at line 639 of file CASTVisitorType.java.
literal()
final ILiteral org.lightjason.agentspeak.grammar.CASTVisitorType.literal ()
Returns
literal
Implements org.lightjason.agentspeak.grammar.IASTVisitorType.
Definition at line 632 of file CASTVisitorType.java.
logicalvalue()
static boolean org.lightjason.agentspeak.grammar.CASTVisitorType.logicalvalue (@Nonnull final String p_value) static private
Parameters
p_value string value
Returns
boolean value
Definition at line 609 of file CASTVisitorType.java.
numericonstant()
static Number org.lightjason.agentspeak.grammar.CASTVisitorType.numericonstant (@Nonnull final String p_value) static private
Parameters
p_value constant name
Returns
number value
Definition at line 594 of file CASTVisitorType.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.grammar.CCommon.NUMERICCONSTANT.
stringvalue()
static String org.lightjason.agentspeak.grammar.CASTVisitorType.stringvalue (@Nonnull final String p_value) static private
Parameters
p_value string
Returns
string without quotes
Definition at line 620 of file CASTVisitorType.java.
term()
final ITerm org.lightjason.agentspeak.grammar.CASTVisitorType.term ()
Returns
any term
Implements org.lightjason.agentspeak.grammar.IASTVisitorType.
Definition at line 646 of file CASTVisitorType.java.
visitAtom()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitAtom (final TypeParser.AtomContext p_context)
Definition at line 313 of file CASTVisitorType.java.
visitDigitsequence()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitDigitsequence (final TypeParser.DigitsequenceContext p_context)
Definition at line 307 of file CASTVisitorType.java.
visitExecutable_action()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExecutable_action (final TypeParser.Executable_actionContext p_context)
Definition at line 563 of file CASTVisitorType.java.
visitExecutable_rule()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExecutable_rule (final TypeParser.Executable_ruleContext p_context)
Definition at line 569 of file CASTVisitorType.java.
visitExecutable_term()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExecutable_term (final TypeParser.Executable_termContext p_context)
Definition at line 143 of file CASTVisitorType.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression (final TypeParser.ExpressionContext p_context)
Definition at line 333 of file CASTVisitorType.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.OR.
visitExpression_bracket()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_bracket (final TypeParser.Expression_bracketContext p_context)
Definition at line 351 of file CASTVisitorType.java.
visitExpression_logical_and()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_logical_and (final TypeParser.Expression_logical_andContext p_context)
Definition at line 357 of file CASTVisitorType.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.AND.
visitExpression_logical_element()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_logical_element (final TypeParser.Expression_logical_elementContext p_context)
Definition at line 398 of file CASTVisitorType.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression_logical_negation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_logical_negation (final TypeParser.Expression_logical_negationContext p_context)
Definition at line 392 of file CASTVisitorType.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.NEGATION.
visitExpression_logical_xor()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_logical_xor (final TypeParser.Expression_logical_xorContext p_context)
Definition at line 370 of file CASTVisitorType.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.execution.expression.EOperator.XOR.
visitExpression_numeric()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric (final TypeParser.Expression_numericContext p_context)
Definition at line 419 of file CASTVisitorType.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.EQUAL, org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.execution.expression.EOperator.NOTEQUAL.
visitExpression_numeric_additive()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_additive (final TypeParser.Expression_numeric_additiveContext p_context)
Definition at line 479 of file CASTVisitorType.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.MINUS, and org.lightjason.agentspeak.language.execution.expression.EOperator.PLUS.
visitExpression_numeric_element()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_element (final TypeParser.Expression_numeric_elementContext p_context)
Definition at line 545 of file CASTVisitorType.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitExpression_numeric_multiplicative()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_multiplicative (final TypeParser.Expression_numeric_multiplicativeContext p_context)
Definition at line 502 of file CASTVisitorType.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.DIVIDE, org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.MODULO, and org.lightjason.agentspeak.language.execution.expression.EOperator.MULTIPLY.
visitExpression_numeric_power()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_power (final TypeParser.Expression_numeric_powerContext p_context)
Definition at line 532 of file CASTVisitorType.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.POWER.
visitExpression_numeric_relation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_relation (final TypeParser.Expression_numeric_relationContext p_context)
Definition at line 442 of file CASTVisitorType.java.
References org.lightjason.agentspeak.language.execution.expression.EOperator.GREATER, org.lightjason.agentspeak.language.execution.expression.EOperator.GREATEREQUAL, org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.execution.expression.EOperator.LESS, and org.lightjason.agentspeak.language.execution.expression.EOperator.LESSEQUAL.
visitExpression_term()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_term (final TypeParser.Expression_termContext p_context)
Definition at line 136 of file CASTVisitorType.java.
visitExpression_type()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_type (final TypeParser.Expression_typeContext p_context)
Definition at line 129 of file CASTVisitorType.java.
visitLiteral()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitLiteral (final TypeParser.LiteralContext p_context)
Definition at line 235 of file CASTVisitorType.java.
References org.lightjason.agentspeak.common.CPath.from().
visitLiteral_type()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitLiteral_type (final TypeParser.Literal_typeContext p_context)
Definition at line 122 of file CASTVisitorType.java.
visitNumber()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitNumber (final TypeParser.NumberContext p_context)
Definition at line 295 of file CASTVisitorType.java.
visitTerm()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitTerm (final TypeParser.TermContext p_context)
Definition at line 246 of file CASTVisitorType.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
visitTermlist()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitTermlist (final TypeParser.TermlistContext p_context)
Definition at line 271 of file CASTVisitorType.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
visitTernary_operation()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitTernary_operation (final TypeParser.Ternary_operationContext p_context)
Definition at line 208 of file CASTVisitorType.java.
visitTernary_operation_false()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitTernary_operation_false (final TypeParser.Ternary_operation_falseContext p_context)
Definition at line 224 of file CASTVisitorType.java.
visitTernary_operation_true()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitTernary_operation_true (final TypeParser.Ternary_operation_trueContext p_context)
Definition at line 218 of file CASTVisitorType.java.
visitUnification()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitUnification (final TypeParser.UnificationContext p_context)
Definition at line 171 of file CASTVisitorType.java.
visitUnification_constraint()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitUnification_constraint (final TypeParser.Unification_constraintContext p_context)
Definition at line 193 of file CASTVisitorType.java.
visitVariable()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitVariable (final TypeParser.VariableContext p_context)
Definition at line 319 of file CASTVisitorType.java.
visitVariable_evaluate()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitVariable_evaluate (final TypeParser.Variable_evaluateContext p_context)
Definition at line 578 of file CASTVisitorType.java.
visitVariableatom()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitVariableatom (final TypeParser.VariableatomContext p_context)
Definition at line 327 of file CASTVisitorType.java.
visitVariablelist()
final Object org.lightjason.agentspeak.grammar.CASTVisitorType.visitVariablelist (final TypeParser.VariablelistContext p_context)
Definition at line 284 of file CASTVisitorType.java.
Member Data Documentation
m_actions
final Map<IPath, IAction> org.lightjason.agentspeak.grammar.CASTVisitorType.m_actions private
Definition at line 79 of file CASTVisitorType.java.
m_expression
IExpression org.lightjason.agentspeak.grammar.CASTVisitorType.m_expression = IExpression.EMPTY private
Definition at line 91 of file CASTVisitorType.java.
m_literal
ILiteral org.lightjason.agentspeak.grammar.CASTVisitorType.m_literal = ILiteral.EMPTY private
Definition at line 87 of file CASTVisitorType.java.
m_rules
final Multimap<IPath, IRule> org.lightjason.agentspeak.grammar.CASTVisitorType.m_rules = LinkedHashMultimap.create() private
Definition at line 83 of file CASTVisitorType.java.
m_term
ITerm org.lightjason.agentspeak.grammar.CASTVisitorType.m_term = ITerm.EMPTY private
Definition at line 95 of file CASTVisitorType.java.