LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expression.CAtom Class Reference
org.lightjason.agentspeak.language.execution.expression.CAtom Class Reference
atom expression
Public Member Functions
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Package Functions
public< T > CAtom (final T p_value)
ctor
Private Attributes
final ITerm m_value
value
Static Private Attributes
static final long serialVersionUID = -469420004121224419L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.execution.expression.IExpression
IExpression EMPTY
empty expression, is always true
Detailed Description
Definition at line 42 of file CAtom.java.
Constructor & Destructor Documentation
CAtom()
public<T> org.lightjason.agentspeak.language.execution.expression.CAtom.CAtom (final T p_value) package
Parameters
p_value any atomic value
Definition at line 60 of file CAtom.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from().
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.execution.expression.CAtom.equals (final Object p_object)
Definition at line 90 of file CAtom.java.
References org.lightjason.agentspeak.language.execution.expression.CAtom.hashCode().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.expression.CAtom.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 67 of file CAtom.java.
References org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from().
hashCode()
final int org.lightjason.agentspeak.language.execution.expression.CAtom.hashCode ()
Definition at line 84 of file CAtom.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.CAtom.equals().
toString()
final String org.lightjason.agentspeak.language.execution.expression.CAtom.toString ()
Definition at line 96 of file CAtom.java.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.expression.CAtom.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 76 of file CAtom.java.
Member Data Documentation
m_value
final ITerm org.lightjason.agentspeak.language.execution.expression.CAtom.m_value private
Definition at line 51 of file CAtom.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.expression.CAtom.serialVersionUID = -469420004121224419L static private
Definition at line 47 of file CAtom.java.