LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T > Class Template Reference
org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T > Class Template Reference
annotation without parameter
Public Member Functions
CAtomAnnotation (@Nonnull final EType p_type)
ctor
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream of variables
Public Member Functions inherited from org.lightjason.agentspeak.language.instantiable.plan.annotation.IBaseAnnotation< T >
final EType id ()
returns the type of the annotation
final T throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
final< N > N value ()
returns the data of the annotation if exists
final boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.instantiable.plan.annotation.IBaseAnnotation< T >
IBaseAnnotation (@Nonnull final EType p_type, @Nullable final T p_value)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.instantiable.plan.annotation.IBaseAnnotation< T >
final EType m_type
annotation type
final T m_value
number data
Detailed Description
Definition at line 36 of file CAtomAnnotation.java.
Constructor & Destructor Documentation
CAtomAnnotation()
org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T >.CAtomAnnotation (@Nonnull final EType p_type)
Parameters
p_type type
Definition at line 44 of file CAtomAnnotation.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T >.equals (final Object p_object)
Definition at line 62 of file CAtomAnnotation.java.
References org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T >.hashCode().
hashCode()
final int org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T >.hashCode ()
Definition at line 56 of file CAtomAnnotation.java.
References org.lightjason.agentspeak.language.instantiable.plan.annotation.IBaseAnnotation< T >.m_type.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T >.equals().
toString()
final String org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T >.toString ()
Definition at line 50 of file CAtomAnnotation.java.
References org.lightjason.agentspeak.language.instantiable.plan.annotation.IBaseAnnotation< T >.m_type, and org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.toString().
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T >.variables ()
Returns
variabel stream
Implements org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.
Definition at line 69 of file CAtomAnnotation.java.