LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionString Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionString Class Reference
test for string actions
Public Member Functions
final void base64 (final List< String > p_input)
test base64 en- and decode
final void base64decodeerror () throws UnsupportedEncodingException
test base64 decode with errors
final void concat (final List< String > p_input)
test concat
final void contains (final List< String > p_input)
test concat
final void endswidth ()
test ends-with
final void levenshtein ()
test levenshtein distance
final void levenshteinerror ()
tets for levenshtein distance error
final void lower (final List< String > p_input)
test lower
final void ncd ()
test normalized compression distance
final void ncderror ()
test normalized compression distance error
final void random (final List< String > p_input)
test random
final void reverse (final List< String > p_input)
test reverse
final void size (final List< String > p_input)
test size
final void startswith ()
test starts-with
final void upper (final List< String > p_input)
test upper
Static Public Member Functions
static Object [] generate ()
data provider generator
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 65 of file TestCActionString.java.
Member Function Documentation
base64()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.base64 (final List< String > p_input)
Parameters
p_input test arguments
Definition at line 87 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CBase64Encode.execute(), org.lightjason.agentspeak.action.builtin.string.CBase64Decode.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
base64decodeerror()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.base64decodeerror () throws UnsupportedEncodingException
Exceptions
UnsupportedEncodingException is thrown on test data encoding
Definition at line 118 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
concat()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.concat (final List< String > p_input)
Parameters
p_input test arguments
Definition at line 139 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CConcat.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
contains()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.contains (final List< String > p_input)
Parameters
p_input test arguments
Definition at line 163 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.set.CContains.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
endswidth()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.endswidth ()
Definition at line 340 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CEndsWith.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
generate()
static Object [] org.lightjason.agentspeak.action.builtin.TestCActionString.generate () static
Returns
data
Definition at line 73 of file TestCActionString.java.
levenshtein()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.levenshtein ()
Definition at line 377 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CLevenshtein.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
levenshteinerror()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.levenshteinerror ()
Definition at line 361 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN.
lower()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.lower (final List< String > p_input)
Parameters
p_input test arguments
Definition at line 190 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CLower.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
ncd()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.ncd ()
Definition at line 397 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CNCD.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
ncderror()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.ncderror ()
Definition at line 430 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN.
random()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.random (final List< String > p_input)
Parameters
p_input test arguments
Definition at line 268 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CRandom.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
reverse()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.reverse (final List< String > p_input)
Parameters
p_input test arguments
Definition at line 216 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CReverse.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
size()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.size (final List< String > p_input)
Parameters
p_input test arguments
Definition at line 242 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.CSize.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
startswith()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.startswith ()
Definition at line 319 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CStartsWith.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
upper()
final void org.lightjason.agentspeak.action.builtin.TestCActionString.upper (final List< String > p_input)
Parameters
p_input test arguments
Definition at line 296 of file TestCActionString.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.string.CUpper.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().