LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionWebGraphQL Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionWebGraphQL Class Reference
test graphql actions
Public Member Functions
final void queryliteral ()
run graphql query test with literal
final void querymanual ()
run graphql query test with native query
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 46 of file TestCActionWebGraphQL.java.
Member Function Documentation
queryliteral()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebGraphQL.queryliteral ()
Definition at line 53 of file TestCActionWebGraphQL.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), and org.lightjason.agentspeak.language.ITerm.functor().
querymanual()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebGraphQL.querymanual ()
Definition at line 85 of file TestCActionWebGraphQL.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.IStructureHash.structurehash().