LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.TestCHanoiTowers.CGenerator Class Reference
org.lightjason.agentspeak.agent.TestCHanoiTowers.CGenerator Class Reference
agent generator
Public Member Functions
final CAgent generatesingle (final Object... p_data)
Public Member Functions inherited from org.lightjason.agentspeak.generator.IBaseAgentGenerator< T extends IAgent<?>
IBaseAgentGenerator (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions) throws Exception
ctor
IBaseAgentGenerator (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, @Nonnull final IVariableBuilder p_variablebuilder) throws Exception
ctor
IBaseAgentGenerator (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, @Nonnull final Set< IPlanBundle > p_planbundle, @Nonnull final IVariableBuilder p_variablebuilder) throws Exception
ctor
final Stream< T > generatemultiple (final int p_number, @Nullable final Object... p_data)
Package Functions
CGenerator (final InputStream p_stream, final Stream< IAction > p_action) throws Exception
ctor
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.generator.IAgentGenerator< T >
IFuzzyBundle< Boolean > DEFAULTFUZZYBUNDLE
default fuzzy bundle
IUnifier DEFAULTUNIFIER
default unification
Protected Member Functions inherited from org.lightjason.agentspeak.generator.IBaseAgentGenerator< T extends IAgent<?>
IAgentConfiguration< T > configuration (@Nonnull final IFuzzyBundle< Boolean > p_fuzzy, @Nonnull final Collection< ILiteral > p_initalbeliefs, @Nonnull final Set< IPlan > p_plans, @Nonnull final Set< IRule > p_rules, @Nullable final ILiteral p_initialgoal, @Nonnull final IUnifier p_unifier, @Nonnull final IVariableBuilder p_variablebuilder)
builds the configuraion, configuration runs cloning of objects if needed
Protected Attributes inherited from org.lightjason.agentspeak.generator.IBaseAgentGenerator< T extends IAgent<?>
final IAgentConfiguration< T > m_configuration
configuration of an agent
Detailed Description
Warning
variable builder within anonymous class cannot be defined with lambda expression, because of stack memory error
Definition at line 246 of file TestCHanoiTowers.java.
Constructor & Destructor Documentation
CGenerator()
org.lightjason.agentspeak.agent.TestCHanoiTowers.CGenerator.CGenerator (final InputStream p_stream, final Stream< IAction > p_action) throws Exception package
Parameters
p_stream asl stream
p_action stream of action
Exceptions
Exception on any error
Definition at line 256 of file TestCHanoiTowers.java.
References org.lightjason.agentspeak.common.CCommon.actionsFromPackage(), org.lightjason.agentspeak.agent.TestCHanoiTowers.m_slicenumber, org.lightjason.agentspeak.agent.TestCHanoiTowers.m_towernumber, org.lightjason.agentspeak.IBaseTest.PRINTENABLE, and org.lightjason.agentspeak.agent.IBaseAgent< CAgent >.raw().
Member Function Documentation
generatesingle()
final CAgent org.lightjason.agentspeak.agent.TestCHanoiTowers.CGenerator.generatesingle (final Object... p_data)
Definition at line 295 of file TestCHanoiTowers.java.
References org.lightjason.agentspeak.agent.TestCHanoiTowers.CAgent.CAgent().
Referenced by org.lightjason.agentspeak.agent.TestCHanoiTowers.setup().