LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.variable.CVariable< T > Class Template Reference
org.lightjason.agentspeak.language.variable.CVariable< T > Class Template Reference
default variable definition
Public Member Functions
CVariable (@Nonnull final String p_functor)
ctor
CVariable (@Nonnull final String p_functor, @Nullable final T p_value)
ctor
CVariable (@Nonnull final IPath p_functor)
ctor
CVariable (@Nonnull final IPath p_functor, @Nullable final T p_value)
ctor
boolean allocated ()
returns allocated state
final boolean any ()
flag to define a "any variable"
ITerm deepcopy (final IPath... p_prefix)
ITerm deepcopysuffix ()
final boolean equals (final Object p_object)
final IPath fqnfunctor ()
returns the full-qualified functor with path and name
final String functor ()
returns the functor without path
final IPath functorpath ()
returns the path of the functor
final int hashCode ()
final boolean hasVariable ()
checks if the literal has variables
boolean mutex ()
flag to check if variable has is concurrency- / thread-safe
IVariable< T > set (@Nullable final T p_value)
sets the value
IVariable< T > shallowcopy (final IPath... p_prefix)
IVariable< T > shallowcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
final int structurehash ()
returns a hash value which defines a hash ove rthe structure
IVariable< T > thrownotallocated () throws IllegalStateException
throws an illegal state exception iif the variable is not allocated
IVariable< T > throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
throws an illegal argument exception iif the value is not assignable to the class
String toString ()
boolean valueassignableto (@Nonnull final Class<?>... p_class)
checkes assignable of the value
Public Member Functions inherited from org.lightjason.agentspeak.language.ITerm
default< T extends ITerm > T term ()
casts the object to a term-type
Public Member Functions inherited from org.lightjason.agentspeak.language.IDeepCopy< ITerm >
T deepcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T deepcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Public Member Functions inherited from org.lightjason.agentspeak.language.IShallowCopy< T >
T shallowcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
Protected Attributes
final boolean m_any
boolean flag, that defines an variable which matchs always
final IPath m_functor
variable / functor name
T m_value
value of the variable
Package Functions
public< N > N raw ()
cast to any raw value type
Private Member Functions
IVariable< T > internalset (final T p_value)
internel set for avoid any exception throwing
Static Private Attributes
static final long serialVersionUID = -5542578381343603600L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.language.ITerm
ITerm EMPTY
empty term
long serialVersionUID = -3640918490398129717L
serial id
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Detailed Description
Note
variable set is not thread-safe on default
Definition at line 46 of file CVariable.java.
Constructor & Destructor Documentation
CVariable() [1/4]
org.lightjason.agentspeak.language.variable.CVariable< T >.CVariable (@Nonnull final String p_functor)
Parameters
p_functor name
Definition at line 70 of file CVariable.java.
References org.lightjason.agentspeak.common.CPath.from().
CVariable() [2/4]
org.lightjason.agentspeak.language.variable.CVariable< T >.CVariable (@Nonnull final String p_functor, @Nullable final T p_value)
Parameters
p_functor name
p_value value
Definition at line 81 of file CVariable.java.
References org.lightjason.agentspeak.common.CPath.from().
CVariable() [3/4]
org.lightjason.agentspeak.language.variable.CVariable< T >.CVariable (@Nonnull final IPath p_functor)
Parameters
p_functor name
Definition at line 91 of file CVariable.java.
CVariable() [4/4]
org.lightjason.agentspeak.language.variable.CVariable< T >.CVariable (@Nonnull final IPath p_functor, @Nullable final T p_value)
Parameters
p_functor name
p_value value
Definition at line 103 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.equals(), and org.lightjason.agentspeak.language.variable.CVariable< T >.internalset().
Member Function Documentation
allocated()
boolean org.lightjason.agentspeak.language.variable.CVariable< T >.allocated ()
Returns
boolean flag
Implements org.lightjason.agentspeak.language.IRawStructure< T >.
Definition at line 118 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate(), and org.lightjason.agentspeak.language.variable.CVariable< T >.thrownotallocated().
any()
final boolean org.lightjason.agentspeak.language.variable.CVariable< T >.any ()
Returns
flag for any variable
Implements org.lightjason.agentspeak.language.variable.IVariable< T >.
Definition at line 124 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_any.
deepcopy()
ITerm org.lightjason.agentspeak.language.variable.CVariable< T >.deepcopy (final IPath... p_prefix)
Definition at line 231 of file CVariable.java.
References org.lightjason.agentspeak.common.IPath.append(), org.lightjason.agentspeak.language.CCommon.deepclone(), org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, and org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
deepcopysuffix()
ITerm org.lightjason.agentspeak.language.variable.CVariable< T >.deepcopysuffix ()
Definition at line 243 of file CVariable.java.
References org.lightjason.agentspeak.language.CCommon.deepclone(), org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, org.lightjason.agentspeak.language.variable.CVariable< T >.m_value, and org.lightjason.agentspeak.common.IPath.suffix().
equals()
final boolean org.lightjason.agentspeak.language.variable.CVariable< T >.equals (final Object p_object)
Definition at line 168 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.hashCode().
Referenced by org.lightjason.agentspeak.language.variable.CVariable< T >.CVariable().
fqnfunctor()
final IPath org.lightjason.agentspeak.language.variable.CVariable< T >.fqnfunctor ()
Returns
fqn functor
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 195 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor.
functor()
final String org.lightjason.agentspeak.language.variable.CVariable< T >.functor ()
Returns
functor
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 181 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, and org.lightjason.agentspeak.common.IPath.suffix().
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate().
functorpath()
final IPath org.lightjason.agentspeak.language.variable.CVariable< T >.functorpath ()
Returns
path
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 188 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, org.lightjason.agentspeak.common.IPath.size(), and org.lightjason.agentspeak.common.IPath.subpath().
hashCode()
final int org.lightjason.agentspeak.language.variable.CVariable< T >.hashCode ()
Definition at line 162 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor.
Referenced by org.lightjason.agentspeak.language.variable.CVariable< T >.equals().
hasVariable()
final boolean org.lightjason.agentspeak.language.variable.CVariable< T >.hasVariable ()
Returns
variable flag
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 201 of file CVariable.java.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate().
internalset()
IVariable<T> org.lightjason.agentspeak.language.variable.CVariable< T >.internalset (final T p_value) private
Parameters
p_value value
Returns
self reference
Definition at line 261 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_any, org.lightjason.agentspeak.language.variable.CVariable< T >.m_value, and org.lightjason.agentspeak.language.ITerm.raw().
Referenced by org.lightjason.agentspeak.language.variable.CVariable< T >.CVariable(), and org.lightjason.agentspeak.language.variable.CVariable< T >.set().
mutex()
boolean org.lightjason.agentspeak.language.variable.CVariable< T >.mutex ()
Returns
mutex flag
Implements org.lightjason.agentspeak.language.variable.IVariable< T >.
Definition at line 130 of file CVariable.java.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate().
raw()
public<N> N org.lightjason.agentspeak.language.variable.CVariable< T >.raw () package
Template Parameters
raw type
Returns
any type
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 208 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
Referenced by org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.relocate(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate().
set()
IVariable<T> org.lightjason.agentspeak.language.variable.CVariable< T >.set (@Nullable final T p_value)
Parameters
p_value value
Returns
the object itself
Implements org.lightjason.agentspeak.language.variable.IVariable< T >.
Definition at line 112 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.internalset().
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate().
shallowcopy()
IVariable<T> org.lightjason.agentspeak.language.variable.CVariable< T >.shallowcopy (final IPath... p_prefix)
Definition at line 215 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, and org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
shallowcopysuffix()
IVariable<T> org.lightjason.agentspeak.language.variable.CVariable< T >.shallowcopysuffix ()
Returns
new instance of the object
Implements org.lightjason.agentspeak.language.IShallowCopy< T >.
Definition at line 224 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, org.lightjason.agentspeak.language.variable.CVariable< T >.m_value, and org.lightjason.agentspeak.common.IPath.suffix().
structurehash()
final int org.lightjason.agentspeak.language.variable.CVariable< T >.structurehash ()
Returns
structure hash value
Implements org.lightjason.agentspeak.language.IStructureHash.
Definition at line 249 of file CVariable.java.
thrownotallocated()
IVariable<T> org.lightjason.agentspeak.language.variable.CVariable< T >.thrownotallocated () throws IllegalStateException
Returns
object itself
Exceptions
IllegalStateException on non-allocated
Implements org.lightjason.agentspeak.language.IRawStructure< T >.
Definition at line 137 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.allocated(), org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor.
throwvaluenotassignableto()
IVariable<T> org.lightjason.agentspeak.language.variable.CVariable< T >.throwvaluenotassignableto (@Nonnull final Class<?>... p_class) throws IllegalArgumentException
Parameters
p_class assignable class
Returns
object itself
Exceptions
IllegalArgumentException on assignable error
Implements org.lightjason.agentspeak.language.IAssignable< T >.
Definition at line 153 of file CVariable.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, and org.lightjason.agentspeak.language.variable.CVariable< T >.valueassignableto().
toString()
String org.lightjason.agentspeak.language.variable.CVariable< T >.toString ()
Definition at line 174 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor, and org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.constantcopy().
valueassignableto()
boolean org.lightjason.agentspeak.language.variable.CVariable< T >.valueassignableto (@Nonnull final Class<?>... p_class)
Parameters
p_class class
Returns
assignable (on null always true)
Implements org.lightjason.agentspeak.language.IAssignable< T >.
Definition at line 146 of file CVariable.java.
References org.lightjason.agentspeak.language.variable.CVariable< T >.m_value.
Referenced by org.lightjason.agentspeak.language.variable.CVariable< T >.throwvaluenotassignableto().
Member Data Documentation
m_any
final boolean org.lightjason.agentspeak.language.variable.CVariable< T >.m_any protected
Definition at line 59 of file CVariable.java.
Referenced by org.lightjason.agentspeak.language.variable.CVariable< T >.any(), and org.lightjason.agentspeak.language.variable.CVariable< T >.internalset().
m_functor
final IPath org.lightjason.agentspeak.language.variable.CVariable< T >.m_functor protected
Definition at line 55 of file CVariable.java.
Referenced by org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopy(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.deepcopy(), org.lightjason.agentspeak.language.variable.CVariable< T >.deepcopy(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.fqnfunctor(), org.lightjason.agentspeak.language.variable.CVariable< T >.functor(), org.lightjason.agentspeak.language.variable.CVariable< T >.functorpath(), org.lightjason.agentspeak.language.variable.CVariable< T >.hashCode(), org.lightjason.agentspeak.language.variable.CConstant< T >.set(), org.lightjason.agentspeak.language.variable.CConstant< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CMutexVariable< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CVariable< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CConstant< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CMutexVariable< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.thrownotallocated(), org.lightjason.agentspeak.language.variable.CVariable< T >.throwvaluenotassignableto(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.toString(), and org.lightjason.agentspeak.language.variable.CVariable< T >.toString().
m_value
T org.lightjason.agentspeak.language.variable.CVariable< T >.m_value protected
Definition at line 63 of file CVariable.java.
Referenced by org.lightjason.agentspeak.language.variable.CVariable< T >.allocated(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.deepcopy(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopy(), org.lightjason.agentspeak.language.variable.CVariable< T >.deepcopy(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.internalset(), org.lightjason.agentspeak.language.variable.CVariable< T >.raw(), org.lightjason.agentspeak.language.variable.CConstant< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CMutexVariable< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CVariable< T >.shallowcopy(), org.lightjason.agentspeak.language.variable.CConstant< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CMutexVariable< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CVariable< T >.shallowcopysuffix(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.toString(), org.lightjason.agentspeak.language.variable.CVariable< T >.toString(), and org.lightjason.agentspeak.language.variable.CVariable< T >.valueassignableto().
serialVersionUID
final long org.lightjason.agentspeak.language.variable.CVariable< T >.serialVersionUID = -5542578381343603600L static private
Definition at line 51 of file CVariable.java.