LightJason - AgentSpeak(L++): org.lightjason.agentspeak.consistency.TestCMetric Class Reference
org.lightjason.agentspeak.consistency.TestCMetric Class Reference
metric tests
Classes
class CAgent
agent class
class CGenerator
test belief generator
Public Member Functions
void initialize () throws Exception
test initialize
final void symmetricweightequality ()
test symmetric weight metric equality
final void symmetricweightinequality ()
test symmetric weight metric inequality
final void weightequality ()
test symmetric metric equality
final void weightinequality ()
test symmetric metric equality
Private Member Functions
CAgent agent (final Collection< ILiteral > p_literals)
generates an agent
void check (final String p_message, final IFilter p_filter, final IMetric p_metric, final Collection< ILiteral > p_belief1, final Collection< ILiteral > p_belief2, final double p_excepted, final double p_delta)
runs the check
Private Attributes
CAgent.CAgentGenerator m_agentgenerator
agent generator
IViewGenerator m_generator
literal view generator
Set< ILiteral > m_literals
set with testing literals
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 61 of file TestCMetric.java.
Member Function Documentation
agent()
CAgent org.lightjason.agentspeak.consistency.TestCMetric.agent (final Collection< ILiteral > p_literals) private
Parameters
p_literals literal collection
Returns
agent
Definition at line 202 of file TestCMetric.java.
References org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.beliefbase(), org.lightjason.agentspeak.beliefbase.view.IView.generate(), and org.lightjason.agentspeak.consistency.TestCMetric.m_agentgenerator.
check()
void org.lightjason.agentspeak.consistency.TestCMetric.check (final String p_message, final IFilter p_filter, final IMetric p_metric, final Collection< ILiteral > p_belief1, final Collection< ILiteral > p_belief2, final double p_excepted, final double p_delta) private
Parameters
p_message error / successful message
p_filter agent filter
p_metric metric value
p_belief1 belief set 1
p_belief2 belief set 2
p_excepted expected value
p_delta delta
Definition at line 185 of file TestCMetric.java.
Referenced by org.lightjason.agentspeak.consistency.TestCMetric.symmetricweightequality(), org.lightjason.agentspeak.consistency.TestCMetric.symmetricweightinequality(), org.lightjason.agentspeak.consistency.TestCMetric.weightequality(), and org.lightjason.agentspeak.consistency.TestCMetric.weightinequality().
initialize()
void org.lightjason.agentspeak.consistency.TestCMetric.initialize () throws Exception
Exceptions
Exception on any parsing error
Definition at line 82 of file TestCMetric.java.
References org.lightjason.agentspeak.language.CLiteral.from(), and org.lightjason.agentspeak.consistency.TestCMetric.m_agentgenerator.
symmetricweightequality()
final void org.lightjason.agentspeak.consistency.TestCMetric.symmetricweightequality ()
Definition at line 103 of file TestCMetric.java.
References org.lightjason.agentspeak.consistency.TestCMetric.check().
symmetricweightinequality()
final void org.lightjason.agentspeak.consistency.TestCMetric.symmetricweightinequality ()
Definition at line 121 of file TestCMetric.java.
References org.lightjason.agentspeak.consistency.TestCMetric.check(), and org.lightjason.agentspeak.language.CLiteral.from().
weightequality()
final void org.lightjason.agentspeak.consistency.TestCMetric.weightequality ()
Definition at line 139 of file TestCMetric.java.
References org.lightjason.agentspeak.consistency.TestCMetric.check().
weightinequality()
final void org.lightjason.agentspeak.consistency.TestCMetric.weightinequality ()
Definition at line 158 of file TestCMetric.java.
References org.lightjason.agentspeak.consistency.TestCMetric.check(), and org.lightjason.agentspeak.language.CLiteral.from().
Member Data Documentation
m_agentgenerator
CAgent.CAgentGenerator org.lightjason.agentspeak.consistency.TestCMetric.m_agentgenerator private
Definition at line 66 of file TestCMetric.java.
Referenced by org.lightjason.agentspeak.consistency.TestCMetric.agent(), and org.lightjason.agentspeak.consistency.TestCMetric.initialize().
m_generator
IViewGenerator org.lightjason.agentspeak.consistency.TestCMetric.m_generator private
Definition at line 70 of file TestCMetric.java.
m_literals
Set<ILiteral> org.lightjason.agentspeak.consistency.TestCMetric.m_literals private
Definition at line 74 of file TestCMetric.java.