LightJason - AgentSpeak(L++): org.lightjason.agentspeak.common.CPath Class Reference
org.lightjason.agentspeak.common.CPath Class Reference
class to create a path structure
Classes
class CPathCollector
path collector
Public Member Functions
CPath (final IPath p_path, final String... p_varargs)
copy-ctor with arguments
CPath (@Nonnull final IPath p_path)
copy-ctor
CPath (@Nullable final String... p_varargs)
ctor
CPath (@Nonnull final Stream< String > p_stream)
ctor
final IPath append (@Nonnull final IPath p_path)
appends a path at the current and returns a new object
final IPath append (@Nonnull final String p_path)
appends a string at the current path and returns the new object
final int compareTo (@Nonnull final IPath p_path)
final boolean empty ()
check if the path is empty
final synchronized boolean endswith (@Nonnull final IPath p_path)
check of a path ends with another path
final boolean equals (final Object p_object)
final String get (final int p_index)
returns an part of the path
final int hashCode ()
final synchronized IPath lower ()
changes all elements to lower-case
final String path (@Nonnull final String p_separator)
final String path ()
returns the full path as string
final IPath pushback (@Nonnull final IPath p_path)
adds a path at the end
final IPath pushback (@Nonnull final String p_path)
adds a path at the end
final IPath pushfront (@Nonnull final String p_path)
adds a path at the front
final synchronized IPath pushfront (@Nonnull final IPath p_path)
adds a path to the front of the path
final IPath remove (final int p_index)
removes an element
final IPath remove (final int p_start, final int p_end)
removes all elements from start index until end index (exclusive)
final String removesuffix ()
remove the suffix from the path
final IPath reverse ()
reverse path
final String separator ()
returns the separator
final IPath separator (@Nonnull final String p_separator)
sets the separator
final int size ()
returns the number of path elements
final boolean startswith (@Nonnull final IPath p_path)
final boolean startswith (final String p_path)
check of a path starts with another path
final Stream< String > stream ()
stream over elements
final IPath subpath (final int p_fromindex)
creates a path of the start index until the end
final IPath subpath (final int p_fromindex, final int p_toindex)
creates a path of the indices
final synchronized String suffix ()
returns the last part of the path
final String toString ()
final synchronized IPath upper ()
changes all elements to uppercase
Public Member Functions inherited from org.lightjason.agentspeak.common.IPath
String path (final String p_separator)
returns the full path as string with an individual separator
boolean startswith (final IPath p_path)
check of a path starts with another path
Static Public Member Functions
static Collector< String, IPath, IPath > collect ()
returns a collector to build a path from strings
static IPath createPath (@Nonnull final String... p_varargs)
creates a path object from different items
static IPath createPathWithSeperator (@Nonnull final String... p_varargs)
creates a path object by splitting a string
static IPath from (@Nonnull final String p_string)
factor method to build path
Private Member Functions
CPath ()
private ctor for empty path
synchronized void normalize ()
normalize the internal path
Static Private Member Functions
static Collector< String, List< String >, List< String > > collectorfactory ()
collector factory
static List< String > listfactory ()
list factory
Private Attributes
final List< String > m_path
list with path parts *
String m_separator = DEFAULTSEPERATOR
separator of the path elements *
Static Private Attributes
static final long serialVersionUID = -8502900889333744887L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.common.IPath
String DEFAULTSEPERATOR = "/"
default seperator
IPath EMPTY
empty path
Detailed Description
Definition at line 53 of file CPath.java.
Constructor & Destructor Documentation
CPath() [1/5]
org.lightjason.agentspeak.common.CPath.CPath (final IPath p_path, final String... p_varargs)
Parameters
p_path path object
p_varargs string arguments
Definition at line 74 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.normalize().
CPath() [2/5]
org.lightjason.agentspeak.common.CPath.CPath (@Nonnull final IPath p_path)
Parameters
p_path path object
Definition at line 86 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.collectorfactory().
CPath() [3/5]
org.lightjason.agentspeak.common.CPath.CPath (@Nullable final String... p_varargs)
Parameters
p_varargs path component
Definition at line 97 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.collect(), org.lightjason.agentspeak.common.CPath.collectorfactory(), org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.common.CPath.listfactory(), and org.lightjason.agentspeak.common.CPath.normalize().
CPath() [4/5]
org.lightjason.agentspeak.common.CPath.CPath (@Nonnull final Stream< String > p_stream)
Parameters
p_stream string collection
Definition at line 118 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.collectorfactory(), and org.lightjason.agentspeak.common.CPath.normalize().
CPath() [5/5]
org.lightjason.agentspeak.common.CPath.CPath () private
Definition at line 127 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.append(), org.lightjason.agentspeak.common.CPath.createPath(), org.lightjason.agentspeak.common.CPath.createPathWithSeperator(), org.lightjason.agentspeak.common.CPath.pushback(), org.lightjason.agentspeak.common.CPath.pushfront(), org.lightjason.agentspeak.common.CPath.startswith(), org.lightjason.agentspeak.common.CPath.subpath(), and org.lightjason.agentspeak.common.CPath.CPathCollector.supplier().
Member Function Documentation
append() [1/2]
final IPath org.lightjason.agentspeak.common.CPath.append (@Nonnull final IPath p_path)
Parameters
p_path path
Returns
new path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 173 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
append() [2/2]
final IPath org.lightjason.agentspeak.common.CPath.append (@Nonnull final String p_path)
Parameters
p_path string with path
Returns
new path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 180 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
collect()
static Collector<String, IPath, IPath> org.lightjason.agentspeak.common.CPath.collect () static
Returns
collector
Definition at line 506 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.TestCPath.collector(), org.lightjason.agentspeak.common.CPath.CPath(), org.lightjason.agentspeak.beliefbase.view.CViewMap.path(), org.lightjason.agentspeak.beliefbase.view.CView.path(), and org.lightjason.agentspeak.common.CPath.pushfront().
collectorfactory()
static Collector<String, List<String>, List<String> > org.lightjason.agentspeak.common.CPath.collectorfactory () static private
Returns
collector
Definition at line 450 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.CPath().
compareTo()
final int org.lightjason.agentspeak.common.CPath.compareTo (@Nonnull final IPath p_path)
Definition at line 410 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.hashCode().
createPath()
static IPath org.lightjason.agentspeak.common.CPath.createPath (@Nonnull final String... p_varargs) static
Parameters
p_varargs list of strings
Returns
path object
Definition at line 139 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
createPathWithSeperator()
static IPath org.lightjason.agentspeak.common.CPath.createPathWithSeperator (@Nonnull final String... p_varargs) static
Parameters
p_varargs list of string (first element is the seperator)
Returns
path object
Definition at line 151 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
Referenced by org.lightjason.agentspeak.common.CPath.from().
empty()
final boolean org.lightjason.agentspeak.common.CPath.empty ()
Returns
empty flag
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 330 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
Referenced by org.lightjason.agentspeak.common.CPath.removesuffix().
endswith()
final synchronized boolean org.lightjason.agentspeak.common.CPath.endswith (@Nonnull final IPath p_path)
Parameters
p_path path
Returns
boolean
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 203 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.equals(), and org.lightjason.agentspeak.common.CPath.size().
equals()
final boolean org.lightjason.agentspeak.common.CPath.equals (final Object p_object)
Definition at line 313 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.hashCode(), and org.lightjason.agentspeak.common.CPath.path().
Referenced by org.lightjason.agentspeak.common.CPath.endswith(), org.lightjason.agentspeak.common.CPath.normalize(), and org.lightjason.agentspeak.common.CPath.startswith().
from()
static IPath org.lightjason.agentspeak.common.CPath.from (@Nonnull final String p_string) static
Parameters
p_string input string
Returns
path
Definition at line 166 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.createPathWithSeperator(), org.lightjason.agentspeak.common.IPath.DEFAULTSEPERATOR, and org.lightjason.agentspeak.common.IPath.EMPTY.
Referenced by org.lightjason.agentspeak.action.binding.CMethodAction.CMethodAction(), org.lightjason.agentspeak.common.TestCPath.collision(), org.lightjason.agentspeak.common.TestCPath.comparing(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.constantcopy(), org.lightjason.agentspeak.beliefbase.TestCViewMap.containsliteral(), org.lightjason.agentspeak.beliefbase.TestCViewMap.containsview(), org.lightjason.agentspeak.language.CRawTerm< T >.CRawTerm(), org.lightjason.agentspeak.language.variable.CVariable< T >.CVariable(), org.lightjason.agentspeak.language.variable.CRelocateMutexVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.variable.CRelocateVariable< T >.deepcopysuffix(), org.lightjason.agentspeak.language.CLiteral.deepcopysuffix(), org.lightjason.agentspeak.action.builtin.agent.CClearBeliefbase.execute(), org.lightjason.agentspeak.action.builtin.agent.CBeliefList.execute(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.literal(), org.lightjason.agentspeak.agent.TestCUnifier.literalvaluesequentialtraversing(), org.lightjason.agentspeak.agent.TestCUnifier.literalvaluetraversing(), org.lightjason.agentspeak.agent.TestCAgent.CEmptyPrint.name(), org.lightjason.agentspeak.beliefbase.TestCViewMap.CEmptyPrint.name(), org.lightjason.agentspeak.agent.TestCAgent.CTestResult.name(), org.lightjason.agentspeak.beliefbase.TestCViewMap.CTestResult.name(), org.lightjason.agentspeak.agent.TestCAgentExecution.CStop.name(), org.lightjason.agentspeak.agent.TestCAgentExecution.CLog.name(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CEmptyPrint.name(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CStop.name(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerSize.name(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPush.name(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CTowerPop.name(), org.lightjason.agentspeak.language.CLiteral.shallowcopysuffix(), org.lightjason.agentspeak.beliefbase.TestCView.testManual(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablecopy(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablefunctor(), org.lightjason.agentspeak.grammar.CASTVisitorType.visitLiteral(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLiteral(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLiteral(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTest_action(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTest_action().
get()
final String org.lightjason.agentspeak.common.CPath.get (final int p_index)
Parameters
p_index index position (negativ index is element from the end)
Returns
element
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 219 of file CPath.java.
hashCode()
final int org.lightjason.agentspeak.common.CPath.hashCode ()
Definition at line 304 of file CPath.java.
References org.lightjason.agentspeak.language.CCommon.getTermHashing().
Referenced by org.lightjason.agentspeak.common.CPath.compareTo(), and org.lightjason.agentspeak.common.CPath.equals().
listfactory()
static List<String> org.lightjason.agentspeak.common.CPath.listfactory () static private
Returns
list
Definition at line 496 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.CPath().
lower()
final synchronized IPath org.lightjason.agentspeak.common.CPath.lower ()
Returns
object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 258 of file CPath.java.
normalize()
synchronized void org.lightjason.agentspeak.common.CPath.normalize () private
Definition at line 418 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.equals(), and org.lightjason.agentspeak.common.CPath.m_path.
Referenced by org.lightjason.agentspeak.common.CPath.CPath().
path() [1/2]
final String org.lightjason.agentspeak.common.CPath.path (@Nonnull final String p_separator)
Definition at line 226 of file CPath.java.
path() [2/2]
final String org.lightjason.agentspeak.common.CPath.path ()
Returns
string path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 233 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.equals(), and org.lightjason.agentspeak.common.CPath.toString().
pushback() [1/2]
final IPath org.lightjason.agentspeak.common.CPath.pushback (@Nonnull final IPath p_path)
Parameters
p_path path
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 337 of file CPath.java.
References org.lightjason.agentspeak.common.IPath.stream().
Referenced by org.lightjason.agentspeak.common.CPath.pushback().
pushback() [2/2]
final IPath org.lightjason.agentspeak.common.CPath.pushback (@Nonnull final String p_path)
Parameters
p_path string path
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 345 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath(), and org.lightjason.agentspeak.common.CPath.pushback().
pushfront() [1/2]
final IPath org.lightjason.agentspeak.common.CPath.pushfront (@Nonnull final String p_path)
Parameters
p_path string path
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 353 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
pushfront() [2/2]
final synchronized IPath org.lightjason.agentspeak.common.CPath.pushfront (@Nonnull final IPath p_path)
Parameters
p_path path
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 361 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.collect(), and org.lightjason.agentspeak.common.CPath.m_path.
remove() [1/2]
final IPath org.lightjason.agentspeak.common.CPath.remove (final int p_index)
Parameters
p_index index position
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 187 of file CPath.java.
References org.lightjason.agentspeak.common.IPath.remove().
remove() [2/2]
final IPath org.lightjason.agentspeak.common.CPath.remove (final int p_start, final int p_end)
Parameters
p_start start index
p_end end index (exclusive)
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 196 of file CPath.java.
removesuffix()
final String org.lightjason.agentspeak.common.CPath.removesuffix ()
Returns
last item of the path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 371 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.empty(), org.lightjason.agentspeak.common.CPath.m_path, and org.lightjason.agentspeak.common.CPath.suffix().
reverse()
final IPath org.lightjason.agentspeak.common.CPath.reverse ()
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 384 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path, and org.lightjason.agentspeak.common.IPath.reverse().
separator() [1/2]
final String org.lightjason.agentspeak.common.CPath.separator ()
Returns
separator
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 240 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_separator.
Referenced by org.lightjason.agentspeak.common.CPath.subpath().
separator() [2/2]
final IPath org.lightjason.agentspeak.common.CPath.separator (@Nonnull final String p_separator)
Parameters
p_separator separator
Returns
path object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 247 of file CPath.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
size()
final int org.lightjason.agentspeak.common.CPath.size ()
Returns
size
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 391 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
Referenced by org.lightjason.agentspeak.common.CPath.endswith(), org.lightjason.agentspeak.common.CPath.startswith(), and org.lightjason.agentspeak.common.CPath.subpath().
startswith() [1/2]
final boolean org.lightjason.agentspeak.common.CPath.startswith (@Nonnull final IPath p_path)
Definition at line 210 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.equals(), and org.lightjason.agentspeak.common.CPath.size().
Referenced by org.lightjason.agentspeak.common.CPath.startswith().
startswith() [2/2]
final boolean org.lightjason.agentspeak.common.CPath.startswith (final String p_path)
Parameters
p_path path
Returns
boolean
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 397 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath(), and org.lightjason.agentspeak.common.CPath.startswith().
stream()
final Stream<String> org.lightjason.agentspeak.common.CPath.stream ()
Returns
sequential stream
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 404 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
subpath() [1/2]
final IPath org.lightjason.agentspeak.common.CPath.subpath (final int p_fromindex)
Parameters
p_fromindex start index
Returns
path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 274 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.size().
subpath() [2/2]
final IPath org.lightjason.agentspeak.common.CPath.subpath (final int p_fromindex, final int p_toindex)
Parameters
p_fromindex start index
p_toindex end index (exclusive) / negative values from the end
Returns
path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 281 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath(), org.lightjason.agentspeak.common.CPath.separator(), and org.lightjason.agentspeak.common.CPath.size().
suffix()
final synchronized String org.lightjason.agentspeak.common.CPath.suffix ()
Returns
string
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 296 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.removesuffix().
toString()
final String org.lightjason.agentspeak.common.CPath.toString ()
Definition at line 320 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.path().
upper()
final synchronized IPath org.lightjason.agentspeak.common.CPath.upper ()
Returns
object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 266 of file CPath.java.
Member Data Documentation
m_path
final List<String> org.lightjason.agentspeak.common.CPath.m_path private
Definition at line 62 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.empty(), org.lightjason.agentspeak.common.CPath.normalize(), org.lightjason.agentspeak.common.CPath.pushfront(), org.lightjason.agentspeak.common.CPath.removesuffix(), org.lightjason.agentspeak.common.CPath.reverse(), org.lightjason.agentspeak.common.CPath.size(), and org.lightjason.agentspeak.common.CPath.stream().
m_separator
String org.lightjason.agentspeak.common.CPath.m_separator = DEFAULTSEPERATOR private
Definition at line 66 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.separator().
serialVersionUID
final long org.lightjason.agentspeak.common.CPath.serialVersionUID = -8502900889333744887L static private
Definition at line 58 of file CPath.java.