LightJason - AgentSpeak(L++): org.lightjason.agentspeak.consistency.CConsistency Class Reference
org.lightjason.agentspeak.consistency.CConsistency Class Reference
layer with consistency data based a markov-chain
Classes
enum EAlgorithm
numeric algorithm structure
Public Member Functions
final IConsistency add (@Nonnull final IAgent<?> p_object)
adds a new object
final IConsistency call () throws Exception
final IConsistency clear ()
clear
final Stream< Map.Entry< IAgent<?>, Double > > consistency ()
stream over all data
final double consistency (@Nonnull final IAgent<?> p_object)
returns the consistency of an object
final IFilter filter ()
returns the used metric filter
final double inconsistency (@Nonnull final IAgent<?> p_object)
returns the inconsistency of an object
final Stream< Map.Entry< IAgent<?>, Double > > inconsistency ()
stream over all data
final IMetric metric ()
returns the used metric
final IConsistency remove (@Nonnull final IAgent<?> p_object)
removes an object
final DescriptiveStatistics statistic ()
returns statistic data of the consistency values
final String toString ()
Static Public Member Functions
static IConsistency heuristic (final IFilter p_filter, final IMetric p_metric)
factory heuristic algorithm
static IConsistency heuristic (final IFilter p_filter, final IMetric p_metric, final int p_iteration)
factory heuristic algorithm
static IConsistency heuristic (final IFilter p_filter, final IMetric p_metric, final int p_iteration, final double p_epsilon)
factory numerical algorithm
static IConsistency numeric (final IFilter p_filter, final IMetric p_metric)
factory numerical algorithm
Private Member Functions
CConsistency (@Nonnull final EAlgorithm p_algorithm, @Nonnull final IFilter p_filter, @Nonnull final IMetric p_metric, final int p_iteration, final double p_epsilon)
ctor
double getMetricValue (final IAgent<?> p_first, final IAgent<?> p_second)
returns metric consistency
Private Attributes
final EAlgorithm m_algorithm
algorithm to calculate stationary probability
final Map< IAgent<?>, Map.Entry< Double, Double > > m_data = new ConcurrentHashMap<>()
map with object and consistency & inconsistency value
final double m_epsilon
epsilon consistency to create an aperiodic markow-chain
final IFilter m_filter
metric filter
final int m_iteration
number of iterations of the stochastic algorithm
final IMetric m_metric
metric object to create the consistency of two objects
final DescriptiveStatistics m_statistic = new SynchronizedDescriptiveStatistics()
descriptive statistic
Static Private Attributes
static final DenseDoubleAlgebra ALGEBRA = DenseDoubleAlgebra.DEFAULT
algebra
static final Map.Entry< Double, Double > DEFAULTNONEXISTING = new AbstractMap.SimpleImmutableEntry<>(1.0, 0.0)
default value on non-existing objects
static final DoubleFunction PROBABILITYINVERT = p_value -> 1 - p_value
function for inverting probability
Detailed Description
Definition at line 58 of file CConsistency.java.
Constructor & Destructor Documentation
CConsistency()
org.lightjason.agentspeak.consistency.CConsistency.CConsistency (@Nonnull final EAlgorithm p_algorithm, @Nonnull final IFilter p_filter, @Nonnull final IMetric p_metric, final int p_iteration, final double p_epsilon) private
Parameters
p_algorithm algorithm
p_filter metric filter
p_metric object metric
p_iteration iterations
p_epsilon epsilon consistency
Definition at line 111 of file CConsistency.java.
Referenced by org.lightjason.agentspeak.consistency.CConsistency.heuristic(), and org.lightjason.agentspeak.consistency.CConsistency.numeric().
Member Function Documentation
add()
final IConsistency org.lightjason.agentspeak.consistency.CConsistency.add (@Nonnull final IAgent<?> p_object)
Parameters
p_object new object
Returns
self reference
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 130 of file CConsistency.java.
call()
final IConsistency org.lightjason.agentspeak.consistency.CConsistency.call () throws Exception
Definition at line 137 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.getMetricValue(), and org.lightjason.agentspeak.consistency.CConsistency.EAlgorithm.getStationaryDistribution().
clear()
final IConsistency org.lightjason.agentspeak.consistency.CConsistency.clear ()
Returns
self reference
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 204 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.IConsistency.clear().
consistency() [1/2]
final Stream<Map.Entry<IAgent<?>, Double> > org.lightjason.agentspeak.consistency.CConsistency.consistency ()
Returns
entry with agent and consistency
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 227 of file CConsistency.java.
consistency() [2/2]
final double org.lightjason.agentspeak.consistency.CConsistency.consistency (@Nonnull final IAgent<?> p_object)
Parameters
p_object object
Returns
consistency or default consistency
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 234 of file CConsistency.java.
filter()
final IFilter org.lightjason.agentspeak.consistency.CConsistency.filter ()
Returns
filter
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 220 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.m_filter.
getMetricValue()
double org.lightjason.agentspeak.consistency.CConsistency.getMetricValue (final IAgent<?> p_first, final IAgent<?> p_second) private
Parameters
p_first first element
p_second secend element
Returns
metric consistency
Definition at line 266 of file CConsistency.java.
Referenced by org.lightjason.agentspeak.consistency.CConsistency.call().
heuristic() [1/3]
static IConsistency org.lightjason.agentspeak.consistency.CConsistency.heuristic (final IFilter p_filter, final IMetric p_metric) static
Parameters
p_filter metric filter
p_metric object metric
Returns
consistency
Definition at line 296 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.CConsistency(), and org.lightjason.agentspeak.consistency.CConsistency.EAlgorithm.FIXPOINT.
heuristic() [2/3]
static IConsistency org.lightjason.agentspeak.consistency.CConsistency.heuristic (final IFilter p_filter, final IMetric p_metric, final int p_iteration) static
Parameters
p_filter metric filter
p_metric object metric
p_iteration number of iterations
Returns
consistency
Definition at line 309 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.CConsistency(), and org.lightjason.agentspeak.consistency.CConsistency.EAlgorithm.FIXPOINT.
heuristic() [3/3]
static IConsistency org.lightjason.agentspeak.consistency.CConsistency.heuristic (final IFilter p_filter, final IMetric p_metric, final int p_iteration, final double p_epsilon) static
Parameters
p_filter metric filter
p_metric object metric
p_iteration number of iterations
p_epsilon epsilon
Returns
consistency
Definition at line 323 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.CConsistency(), and org.lightjason.agentspeak.consistency.CConsistency.EAlgorithm.FIXPOINT.
inconsistency() [1/2]
final double org.lightjason.agentspeak.consistency.CConsistency.inconsistency (@Nonnull final IAgent<?> p_object)
Parameters
p_object object
Returns
consistency or default consistency
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 241 of file CConsistency.java.
inconsistency() [2/2]
final Stream<Map.Entry<IAgent<?>, Double> > org.lightjason.agentspeak.consistency.CConsistency.inconsistency ()
Returns
entry with agent and inconsistency
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 248 of file CConsistency.java.
metric()
final IMetric org.lightjason.agentspeak.consistency.CConsistency.metric ()
Returns
metric
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 213 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.m_metric.
numeric()
static IConsistency org.lightjason.agentspeak.consistency.CConsistency.numeric (final IFilter p_filter, final IMetric p_metric) static
Parameters
p_filter metric filter
p_metric object metric
Returns
consistency
Definition at line 284 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.CConsistency(), and org.lightjason.agentspeak.consistency.CConsistency.EAlgorithm.NUMERICAL.
remove()
final IConsistency org.lightjason.agentspeak.consistency.CConsistency.remove (@Nonnull final IAgent<?> p_object)
Parameters
p_object removing object
Returns
self reference
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 196 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.IConsistency.remove().
statistic()
final DescriptiveStatistics org.lightjason.agentspeak.consistency.CConsistency.statistic ()
Returns
statistic
Implements org.lightjason.agentspeak.consistency.IConsistency.
Definition at line 123 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.m_statistic.
toString()
final String org.lightjason.agentspeak.consistency.CConsistency.toString ()
Definition at line 254 of file CConsistency.java.
References org.lightjason.agentspeak.consistency.CConsistency.m_data.
Member Data Documentation
ALGEBRA
final DenseDoubleAlgebra org.lightjason.agentspeak.consistency.CConsistency.ALGEBRA = DenseDoubleAlgebra.DEFAULT static private
Definition at line 67 of file CConsistency.java.
DEFAULTNONEXISTING
final Map.Entry<Double, Double> org.lightjason.agentspeak.consistency.CConsistency.DEFAULTNONEXISTING = new AbstractMap.SimpleImmutableEntry<>(1.0, 0.0) static private
Definition at line 63 of file CConsistency.java.
m_algorithm
final EAlgorithm org.lightjason.agentspeak.consistency.CConsistency.m_algorithm private
Definition at line 75 of file CConsistency.java.
m_data
final Map<IAgent<?>, Map.Entry<Double, Double> > org.lightjason.agentspeak.consistency.CConsistency.m_data = new ConcurrentHashMap<>() private
Definition at line 79 of file CConsistency.java.
Referenced by org.lightjason.agentspeak.consistency.CConsistency.toString().
m_epsilon
final double org.lightjason.agentspeak.consistency.CConsistency.m_epsilon private
Definition at line 95 of file CConsistency.java.
m_filter
final IFilter org.lightjason.agentspeak.consistency.CConsistency.m_filter private
Definition at line 87 of file CConsistency.java.
Referenced by org.lightjason.agentspeak.consistency.CConsistency.filter().
m_iteration
final int org.lightjason.agentspeak.consistency.CConsistency.m_iteration private
Definition at line 99 of file CConsistency.java.
m_metric
final IMetric org.lightjason.agentspeak.consistency.CConsistency.m_metric private
Definition at line 91 of file CConsistency.java.
Referenced by org.lightjason.agentspeak.consistency.CConsistency.metric().
m_statistic
final DescriptiveStatistics org.lightjason.agentspeak.consistency.CConsistency.m_statistic = new SynchronizedDescriptiveStatistics() private
Definition at line 83 of file CConsistency.java.
Referenced by org.lightjason.agentspeak.consistency.CConsistency.statistic().
PROBABILITYINVERT
final DoubleFunction org.lightjason.agentspeak.consistency.CConsistency.PROBABILITYINVERT = p_value -> 1 - p_value static private
Definition at line 71 of file CConsistency.java.