LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.ITerm Interface Reference
org.lightjason.agentspeak.language.ITerm Interface Reference
term interface
Public Member Functions
IPath fqnfunctor ()
returns the full-qualified functor with path and name
String functor ()
returns the functor without path
IPath functorpath ()
returns the path of the functor
boolean hasVariable ()
checks if the literal has variables
< T > T raw ()
cast to any raw value type
default< T extends ITerm > T term ()
casts the object to a term-type
Public Member Functions inherited from org.lightjason.agentspeak.language.IStructureHash
int structurehash ()
returns a hash value which defines a hash ove rthe structure
Public Member Functions inherited from org.lightjason.agentspeak.language.IDeepCopy< ITerm >
T deepcopy (@Nullable final IPath... p_prefix)
clones the object (shallow-copy)
T deepcopysuffix ()
clones the object (shallow-copy) without full-qualified path, only suffix is used
Public Attributes
ITerm EMPTY
empty term
long serialVersionUID = -3640918490398129717L
serial id
Public Attributes inherited from org.lightjason.agentspeak.language.IStructureHash
Comparator< IStructureHash > COMPARATOR = Comparator.comparingInt(IStructureHash::structurehash)
comparator
Detailed Description
Definition at line 36 of file ITerm.java.
Member Function Documentation
fqnfunctor()
IPath org.lightjason.agentspeak.language.ITerm.fqnfunctor ()
Returns
fqn functor
Implemented in org.lightjason.agentspeak.language.CLiteral, org.lightjason.agentspeak.language.variable.CVariable< T >, org.lightjason.agentspeak.language.CRawTerm< T >, and org.lightjason.agentspeak.language.variable.CVariableEvaluate.
Referenced by org.lightjason.agentspeak.language.execution.CContext.CContext(), org.lightjason.agentspeak.language.CRawTerm< T >.CRawTerm(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.literal(), org.lightjason.agentspeak.language.unify.CRecursive.unify(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablecopy(), and org.lightjason.agentspeak.language.unify.CUnifier.variables().
functor()
String org.lightjason.agentspeak.language.ITerm.functor ()
Returns
functor
Implemented in org.lightjason.agentspeak.language.CLiteral, org.lightjason.agentspeak.language.variable.CVariable< T >, org.lightjason.agentspeak.language.CRawTerm< T >, and org.lightjason.agentspeak.language.variable.CVariableEvaluate.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.constant(), org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.fields(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlistmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlistsingle(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjectmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjectsingle(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.literal(), org.lightjason.agentspeak.action.builtin.TestCActionWebGraphQL.queryliteral(), org.lightjason.agentspeak.action.builtin.TestCActionWebGraphQL.querymanual(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate(), org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.values(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variable(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablemutex(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjectmultiple(), and org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjectsingle().
functorpath()
IPath org.lightjason.agentspeak.language.ITerm.functorpath ()
Returns
path
Implemented in org.lightjason.agentspeak.language.CLiteral, org.lightjason.agentspeak.language.variable.CVariable< T >, org.lightjason.agentspeak.language.CRawTerm< T >, and org.lightjason.agentspeak.language.variable.CVariableEvaluate.
hasVariable()
boolean org.lightjason.agentspeak.language.ITerm.hasVariable ()
Returns
variable flag
Implemented in org.lightjason.agentspeak.language.CLiteral, org.lightjason.agentspeak.language.variable.CVariable< T >, org.lightjason.agentspeak.language.CRawTerm< T >, and org.lightjason.agentspeak.language.variable.CVariableEvaluate.
Referenced by org.lightjason.agentspeak.language.TestCTermVariablesConstant.constant(), org.lightjason.agentspeak.language.CLiteral.hasVariable(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variable(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablemutex().
raw()
<T> T org.lightjason.agentspeak.language.ITerm.raw ()
Template Parameters
raw type
Returns
any type
Implemented in org.lightjason.agentspeak.language.CLiteral, org.lightjason.agentspeak.language.variable.CVariable< T >, org.lightjason.agentspeak.language.CRawTerm< T >, org.lightjason.agentspeak.language.variable.CVariableEvaluate, and org.lightjason.agentspeak.language.variable.CMutexVariable< T >.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.action(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.action(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.action(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.action(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.asmap(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.constant(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.contains(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.copy(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.copy(), org.lightjason.agentspeak.language.CRawTerm< T >.CRawTerm(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.create(), org.lightjason.agentspeak.beliefbase.view.CViewMap.CViewMap(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.degreemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.degreesingle(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.descriptivemultiplestatisticvalue(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.endpointmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.endpointsingle(), org.lightjason.agentspeak.action.builtin.bool.CAllMatch.execute(), org.lightjason.agentspeak.action.builtin.bool.CAnyMatch.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CCreate.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CType.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CIsString.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CAdd.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CIsNumeric.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CIsNull.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CRemove.execute(), org.lightjason.agentspeak.action.builtin.collection.tuple.CCreate.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CFlatConcat.execute(), org.lightjason.agentspeak.action.builtin.collection.set.CContains.execute(), org.lightjason.agentspeak.action.builtin.collection.map.CRemove.execute(), org.lightjason.agentspeak.action.builtin.generic.type.CIs.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CUnique.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CUnion.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CIntersect.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CZip.execute(), org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.execute(), org.lightjason.agentspeak.action.builtin.collection.list.CSymmetricDifference.execute(), org.lightjason.agentspeak.action.binding.CMethodAction.execute(), org.lightjason.agentspeak.action.builtin.TestCActionBool.execute(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeys(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeystream(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.exponentialselectionlazy(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.exponentialselectionstrict(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.findedgemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.findedgesingle(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.flat(), org.lightjason.agentspeak.language.CCommon.flattenstream(), org.lightjason.agentspeak.action.builtin.generic.CPrint.format(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentcountmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.incidentcountsingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.indegreemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.indegreesingle(), org.lightjason.agentspeak.language.variable.CVariable< T >.internalset(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.isincidentmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.isincidentsingle(), org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlistsingle(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.linearselection(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.oppositemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.oppositesingle(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.outdegreemultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.outdegreesingle(), org.lightjason.agentspeak.action.builtin.TestCActionMath.pow(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.predecessorcountmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.predecessorcountsingle(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.rawterm(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablemutex(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.relocatevariablerelocate(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.remove(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.remove(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.reverse(), org.lightjason.agentspeak.action.builtin.TestCActionMath.singlevalueaction(), org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.solvemaximize(), org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.solveminimize(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.successorcountmultiple(), org.lightjason.agentspeak.action.builtin.TestCActionGraph.successorcountsingle(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.summarymultiplestatisticvalue(), org.lightjason.agentspeak.action.builtin.web.graphql.CQueryLiteral.valueformat(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.variable(), and org.lightjason.agentspeak.language.TestCTermVariablesConstant.variablemutex().
term()
default<T extends ITerm> T org.lightjason.agentspeak.language.ITerm.term ()
Returns
casted object
Template Parameters
T term type
Definition at line 158 of file ITerm.java.
Referenced by org.lightjason.agentspeak.language.execution.expressionbinary.COperatorAssign.variables(), org.lightjason.agentspeak.language.instantiable.rule.CRule.variables(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.variables(), and org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.variables().
Member Data Documentation
EMPTY
ITerm org.lightjason.agentspeak.language.ITerm.EMPTY
Definition at line 46 of file ITerm.java.
serialVersionUID
long org.lightjason.agentspeak.language.ITerm.serialVersionUID = -3640918490398129717L
Definition at line 41 of file ITerm.java.