LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.datetime.IDateTime Class Reference
org.lightjason.agentspeak.action.builtin.datetime.IDateTime Class Reference abstract
abstract class for date-time access
Public Member Functions
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
Public Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final String toString ()
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
default int minimalArgumentNumber ()
minimum number of arguments
default Stream< IVariable<?> > variables ()
returns a stream with all used variables
Protected Member Functions
IDateTime ()
ctor
abstract boolean elements (@Nonnull final ZonedDateTime p_datetime, @Nonnull final List< ITerm > p_return)
transfers the date-time element to term elements
Protected Member Functions inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
IBuiltinAction ()
ctor
IBuiltinAction (final int p_length)
ctor
Private Member Functions
boolean getdatetime (@Nonnull final ITerm p_value, @Nonnull final List< ITerm > p_return)
creates the date representation
Static Private Attributes
static final long serialVersionUID = -5384242048535616689L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.action.IAction
long serialVersionUID = -6374480398439703170L
serial id
Static Protected Attributes inherited from org.lightjason.agentspeak.action.builtin.IBuiltinAction
static final Logger LOGGER = CCommon.logger(IBuiltinAction.class)
logger
Static Protected Attributes inherited from org.lightjason.agentspeak.action.IBaseAction
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAction.class)
logger
Detailed Description
Definition at line 44 of file IDateTime.java.
Constructor & Destructor Documentation
IDateTime()
org.lightjason.agentspeak.action.builtin.datetime.IDateTime.IDateTime () protected
Definition at line 54 of file IDateTime.java.
Member Function Documentation
elements()
abstract boolean org.lightjason.agentspeak.action.builtin.datetime.IDateTime.elements (@Nonnull final ZonedDateTime p_datetime, @Nonnull final List< ITerm > p_return) abstract protected
Parameters
p_datetime date-time definition
p_return return arguments
Returns
successfull return
Referenced by org.lightjason.agentspeak.action.builtin.datetime.IDateTime.execute(), and org.lightjason.agentspeak.action.builtin.datetime.IDateTime.getdatetime().
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.action.builtin.datetime.IDateTime.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 59 of file IDateTime.java.
References org.lightjason.agentspeak.action.builtin.datetime.IDateTime.elements(), org.lightjason.agentspeak.language.CCommon.flatten(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), and org.lightjason.agentspeak.action.builtin.datetime.IDateTime.getdatetime().
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionDateTime.zoneid().
getdatetime()
boolean org.lightjason.agentspeak.action.builtin.datetime.IDateTime.getdatetime (@Nonnull final ITerm p_value, @Nonnull final List< ITerm > p_return) private
Parameters
p_value date value, empty or now returns the current date
p_return return arguments
Returns
successfull execution
Definition at line 91 of file IDateTime.java.
References org.lightjason.agentspeak.action.builtin.datetime.IDateTime.elements(), and org.lightjason.agentspeak.language.CCommon.rawvalueAssignableTo().
Referenced by org.lightjason.agentspeak.action.builtin.datetime.IDateTime.execute().
Member Data Documentation
serialVersionUID
final long org.lightjason.agentspeak.action.builtin.datetime.IDateTime.serialVersionUID = -5384242048535616689L static private
Definition at line 49 of file IDateTime.java.