LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.view.IView Interface Reference
org.lightjason.agentspeak.beliefbase.view.IView Interface Reference
view for a beliefbase that creates any access to the underlying data structures
Public Member Functions
IView add (@Nonnull final ILiteral... p_literal)
adds a literal in the current structure
IView add (@Nonnull final Stream< ILiteral > p_literal)
adds a literal in the current structure
IView add (@Nonnull final IView... p_view)
adds view in the current structure
IBeliefbase beliefbase ()
returns the beliefbase
IView clear (@Nullable final IPath... p_path)
clears all elements
boolean containsLiteral (@Nonnull final IPath p_path)
checks if a literal exists
boolean containsView (@Nonnull final IPath p_path)
view existing check
IView generate (@Nonnull final IViewGenerator p_generator, @Nonnull final IPath... p_paths)
generates path structure
boolean hasParent ()
check if the view has got a parent
String name ()
returns only the element name
IView parent ()
returns the parent of the view
IPath path ()
returns the full path
IView remove (@Nonnull final Stream< ILiteral > p_literal)
removes a literal in the current structure
IView remove (@Nonnull final ILiteral... p_literal)
removes a literal in the current structure
IView remove (@Nonnull final IView... p_view)
removes a view in the current structure
Stream< IView > root ()
returns a stream to the root node,
Stream< ILiteral > stream (@Nullable final IPath... p_path)
returns stream of literal
Stream< ILiteral > stream (final boolean p_negated, @Nullable final IPath... p_path)
returns stream of literal
Stream< ITrigger > trigger ()
retruns all trigger of the beliefbase
Stream< IView > walk (@Nonnull final IPath p_path, @Nullable final IViewGenerator... p_generator)
streams path walking
Public Member Functions inherited from org.lightjason.agentspeak.beliefbase.IStructure
boolean empty ()
checks if the structure empty
int size ()
returns the size of literals
IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
Public Attributes
IView EMPTY
empty view
Detailed Description
Template Parameters
T agent type
Definition at line 44 of file IView.java.
Member Function Documentation
add() [1/3]
IView org.lightjason.agentspeak.beliefbase.view.IView.add (@Nonnull final ILiteral... p_literal)
Parameters
p_literal literal
Returns
self reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
Referenced by org.lightjason.agentspeak.configuration.CDefaultAgentConfiguration< T extends IAgent<?>.beliefbase(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.belieflist(), org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.CAgent.CAgent(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.clearbeliefbase(), org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.eventreference(), and org.lightjason.agentspeak.beliefbase.TestCView.testManual().
add() [2/3]
IView org.lightjason.agentspeak.beliefbase.view.IView.add (@Nonnull final Stream< ILiteral > p_literal)
Parameters
p_literal literal stream
Returns
self reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
add() [3/3]
IView org.lightjason.agentspeak.beliefbase.view.IView.add (@Nonnull final IView... p_view)
Parameters
p_view existing view
Returns
self reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
beliefbase()
IBeliefbase org.lightjason.agentspeak.beliefbase.view.IView.beliefbase ()
Returns
beliefbase
Implemented in org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.view.CViewMap.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add(), org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.IBaseAgent(), org.lightjason.agentspeak.beliefbase.view.CView.remove(), org.lightjason.agentspeak.beliefbase.view.CView.stream(), and org.lightjason.agentspeak.beliefbase.view.CViewMap.stream().
clear()
IView org.lightjason.agentspeak.beliefbase.view.IView.clear (@Nullable final IPath... p_path)
Parameters
p_path path values
Returns
self reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
containsLiteral()
boolean org.lightjason.agentspeak.beliefbase.view.IView.containsLiteral (@Nonnull final IPath p_path)
Parameters
p_path path to a literal (suffix is literal name)
Returns
existance boolean
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
Referenced by org.lightjason.agentspeak.beliefbase.TestCViewMap.containsliteral().
containsView()
boolean org.lightjason.agentspeak.beliefbase.view.IView.containsView (@Nonnull final IPath p_path)
Parameters
p_path path to a view
Returns
existance boolean
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
Referenced by org.lightjason.agentspeak.beliefbase.TestCViewMap.containsview().
generate()
IView org.lightjason.agentspeak.beliefbase.view.IView.generate (@Nonnull final IViewGenerator p_generator, @Nonnull final IPath... p_paths)
Parameters
p_generator generator for views
p_paths paths items
Returns
self reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.view.CViewMap.
Referenced by org.lightjason.agentspeak.consistency.TestCMetric.agent(), and org.lightjason.agentspeak.beliefbase.TestCView.testTree().
hasParent()
boolean org.lightjason.agentspeak.beliefbase.view.IView.hasParent ()
Returns
boolean flag of the parent
Implemented in org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.view.CViewMap.
name()
String org.lightjason.agentspeak.beliefbase.view.IView.name ()
Returns
name
Implemented in org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.view.CViewMap.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.path(), and org.lightjason.agentspeak.beliefbase.view.CView.path().
parent()
IView org.lightjason.agentspeak.beliefbase.view.IView.parent ()
Returns
parent object or null
Implemented in org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.view.CViewMap.
path()
IPath org.lightjason.agentspeak.beliefbase.view.IView.path ()
Returns
path
Note
the path is relative to the root node, exclusive root element
Implemented in org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.view.CViewMap.
remove() [1/3]
IView org.lightjason.agentspeak.beliefbase.view.IView.remove (@Nonnull final Stream< ILiteral > p_literal)
Parameters
p_literal literal stream
Returns
self reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
Referenced by org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.internalremove(), and org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.update().
remove() [2/3]
IView org.lightjason.agentspeak.beliefbase.view.IView.remove (@Nonnull final ILiteral... p_literal)
Parameters
p_literal literal
Returns
self reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
remove() [3/3]
IView org.lightjason.agentspeak.beliefbase.view.IView.remove (@Nonnull final IView... p_view)
Parameters
p_view view
Returns
self reference
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
root()
Stream<IView> org.lightjason.agentspeak.beliefbase.view.IView.root ()
Returns
stream of views
Note
the stream is exclusive of the root node and starts with the current node
Implemented in org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.view.CViewMap.
Referenced by org.lightjason.agentspeak.beliefbase.view.CViewMap.root(), and org.lightjason.agentspeak.beliefbase.view.CView.root().
stream() [1/2]
Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.IView.stream (@Nullable final IPath... p_path)
Parameters
p_path paths of the literals
Returns
literal stream
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.add(), org.lightjason.agentspeak.beliefbase.view.CViewMap.add(), org.lightjason.agentspeak.consistency.filter.CBelief.apply(), org.lightjason.agentspeak.consistency.filter.CAll.apply(), org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.belieflist(), org.lightjason.agentspeak.beliefbase.view.CView.generate(), org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.inspect(), org.lightjason.agentspeak.beliefbase.view.CView.remove(), org.lightjason.agentspeak.beliefbase.view.CViewMap.remove(), and org.lightjason.agentspeak.language.unify.CUnifier.variables().
stream() [2/2]
Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.IView.stream (final boolean p_negated, @Nullable final IPath... p_path)
Parameters
p_negated negated flag
p_path paths of the literals
Returns
literal stream
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
trigger()
Stream<ITrigger> org.lightjason.agentspeak.beliefbase.view.IView.trigger ()
Returns
set with trigger events
Implemented in org.lightjason.agentspeak.beliefbase.view.CViewMap, and org.lightjason.agentspeak.beliefbase.view.CView.
Referenced by org.lightjason.agentspeak.configuration.CDefaultAgentConfiguration< T extends IAgent<?>.beliefbase(), org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.generateexecutionlist(), and org.lightjason.agentspeak.beliefbase.CBeliefbase.trigger().
walk()
Stream<IView> org.lightjason.agentspeak.beliefbase.view.IView.walk (@Nonnull final IPath p_path, @Nullable final IViewGenerator... p_generator)
Parameters
p_path path
p_generator generator for view creating (first argument is used, orther elements will be ignored)
Returns
stream of views
Implemented in org.lightjason.agentspeak.beliefbase.view.CView, and org.lightjason.agentspeak.beliefbase.view.CViewMap.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.walkdown().
Member Data Documentation
EMPTY
IView org.lightjason.agentspeak.beliefbase.view.IView.EMPTY
Definition at line 49 of file IView.java.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView.leafview().