LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution Enum Reference
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution Enum Reference
usable distributions
Public Member Functions
EDistribution (final int p_arguments)
ctor
final AbstractRealDistribution get (@Nonnull final RandomGenerator p_generator, final double[] p_arguments)
returns the distribution object
final int getArgumentNumber ()
return number of arguments
Static Public Member Functions
static boolean exist (@Nonnull final String p_value)
checks if a name exists within the enum
static EDistribution from (@Nonnull final String p_value)
additional factory
Public Attributes
BETA =(2)
CAUCHY =(2)
CHISQUARE =(1)
EXPONENTIAL =(1)
F =(2)
GAMMA =(2)
GUMBLE =(2)
LAPLACE =(2)
LEVY =(2)
LOGISTIC =(2)
LOGNORMAL =(2)
NAKAGAMI =(2)
NORMAL =(2)
PARETO =(2)
T =(1)
TRIANGULAR =(3)
UNIFORM =(2)
WEIBULL =(2)
Private Attributes
final int m_arguments
number of arguments
Static Private Attributes
static final Set< String > NAMES
enum name list
Detailed Description
Definition at line 218 of file CCreateDistribution.java.
Constructor & Destructor Documentation
EDistribution()
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.EDistribution (final int p_arguments)
Parameters
p_arguments number of arguments
Definition at line 258 of file CCreateDistribution.java.
Member Function Documentation
exist()
static boolean org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.exist (@Nonnull final String p_value) static
Parameters
p_value string name
Returns
exist boolean
Definition at line 281 of file CCreateDistribution.java.
Referenced by org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute().
from()
static EDistribution org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.from (@Nonnull final String p_value) static
Parameters
p_value string
Returns
enum
Definition at line 270 of file CCreateDistribution.java.
Referenced by org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.execute().
get()
final AbstractRealDistribution org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.get (@Nonnull final RandomGenerator p_generator, final double [] p_arguments)
Parameters
p_generator random generator
p_arguments arguments
Returns
real distribution
Definition at line 304 of file CCreateDistribution.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
getArgumentNumber()
final int org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.getArgumentNumber ()
Returns
argument number
Definition at line 291 of file CCreateDistribution.java.
Member Data Documentation
BETA
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.BETA =(2)
Definition at line 220 of file CCreateDistribution.java.
CAUCHY
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.CAUCHY =(2)
Definition at line 221 of file CCreateDistribution.java.
CHISQUARE
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.CHISQUARE =(1)
Definition at line 222 of file CCreateDistribution.java.
EXPONENTIAL
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.EXPONENTIAL =(1)
Definition at line 223 of file CCreateDistribution.java.
F
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.F =(2)
Definition at line 224 of file CCreateDistribution.java.
GAMMA
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.GAMMA =(2)
Definition at line 225 of file CCreateDistribution.java.
GUMBLE
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.GUMBLE =(2)
Definition at line 226 of file CCreateDistribution.java.
LAPLACE
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.LAPLACE =(2)
Definition at line 227 of file CCreateDistribution.java.
LEVY
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.LEVY =(2)
Definition at line 228 of file CCreateDistribution.java.
LOGISTIC
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.LOGISTIC =(2)
Definition at line 229 of file CCreateDistribution.java.
LOGNORMAL
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.LOGNORMAL =(2)
Definition at line 230 of file CCreateDistribution.java.
m_arguments
final int org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.m_arguments private
Definition at line 251 of file CCreateDistribution.java.
NAKAGAMI
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.NAKAGAMI =(2)
Definition at line 231 of file CCreateDistribution.java.
NAMES
static final Set<String> org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.NAMES static private
Initial value:
= Collections.unmodifiableSet(
                                                    Arrays.stream( EDistribution.values() )
                                                          .map( i -> i.name().toUpperCase( Locale.ROOT ) )
                                                          .collect( Collectors.toSet() )
        )
Definition at line 242 of file CCreateDistribution.java.
NORMAL
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.NORMAL =(2)
Definition at line 232 of file CCreateDistribution.java.
PARETO
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.PARETO =(2)
Definition at line 233 of file CCreateDistribution.java.
T
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.T =(1)
Definition at line 234 of file CCreateDistribution.java.
TRIANGULAR
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.TRIANGULAR =(3)
Definition at line 235 of file CCreateDistribution.java.
UNIFORM
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.UNIFORM =(2)
Definition at line 236 of file CCreateDistribution.java.
WEIBULL
org.lightjason.agentspeak.action.builtin.math.statistic.CCreateDistribution.EDistribution.WEIBULL =(2)
Definition at line 237 of file CCreateDistribution.java.