LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionStorage Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionStorage Class Reference
test action storage
Classes
class CAgent
test agent
class CGenerator
agent generator
Public Member Functions
final void addwithkeys ()
test add action with forbidden keys
final void addwithkeystrean ()
test add action with forbidden key strean
final void addwithoutkeys ()
test add action without forbidden keys
final void arguments ()
test for checking minimal arguments
final void clearwithkeys ()
test clear action with keys
final void clearwithkeystream ()
test clear action with key stream
final void clearwithoutkeys ()
test clear action without keys
final void existswithkeys ()
test exists action with keys
final void existswithkeystream ()
test exists action with key stream
final void existswithoutkeys ()
test exists action without keys
final void initialize () throws Exception
initialize
final void removewithkeys ()
test remove action without keys
final void removewithkeystream ()
test remove action without key stream
final void removewithoutkeys ()
test remove action without keys
final void resolver ()
test resolver access
Static Package Functions
[static initializer]
Private Attributes
IContext m_context
execution context
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 66 of file TestCActionStorage.java.
Member Function Documentation
[static initializer]()
org.lightjason.agentspeak.action.builtin.TestCActionStorage.[static initializer] () static package
addwithkeys()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithkeys ()
Definition at line 116 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.collection.list.CAdd.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
addwithkeystrean()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithkeystrean ()
Definition at line 133 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
addwithoutkeys()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithoutkeys ()
Definition at line 97 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.collection.list.CAdd.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
arguments()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.arguments ()
Definition at line 376 of file TestCActionStorage.java.
clearwithkeys()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.clearwithkeys ()
Definition at line 248 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.collection.CClear.execute(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
clearwithkeystream()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.clearwithkeystream ()
Definition at line 273 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
clearwithoutkeys()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.clearwithoutkeys ()
Definition at line 174 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.collection.CClear.execute(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
existswithkeys()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeys ()
Definition at line 324 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.storage.CExists.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.raw(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
existswithkeystream()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeystream ()
Definition at line 349 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.raw(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
existswithoutkeys()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithoutkeys ()
Definition at line 298 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.storage.CExists.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
initialize()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.initialize () throws Exception
Exceptions
Exception is thrown on any error
Definition at line 84 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL, org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), and org.lightjason.agentspeak.language.CLiteral.from().
removewithkeys()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithkeys ()
Definition at line 198 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.collection.list.CRemove.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
removewithkeystream()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithkeystream ()
Definition at line 223 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
removewithoutkeys()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithoutkeys ()
Definition at line 150 of file TestCActionStorage.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.builtin.collection.list.CRemove.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.agent.IAgent< T extends IAgent<?>.storage().
resolver()
final void org.lightjason.agentspeak.action.builtin.TestCActionStorage.resolver ()
Definition at line 398 of file TestCActionStorage.java.
Member Data Documentation
m_context
IContext org.lightjason.agentspeak.action.builtin.TestCActionStorage.m_context private
Definition at line 71 of file TestCActionStorage.java.