LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType Enum Reference
org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType Enum Reference
annotation types
Public Member Functions
EType (final String p_name)
ctor
final String toString ()
Public Attributes
ATOMIC =("@Atomic")
CONSTANT =("@Constant")
PARALLEL =("@Parallel")
Private Attributes
final String m_name
text name of the enum
Detailed Description
Definition at line 70 of file IAnnotation.java.
Constructor & Destructor Documentation
EType()
org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.EType (final String p_name)
Parameters
p_name text name
Definition at line 86 of file IAnnotation.java.
Member Function Documentation
toString()
final String org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.toString ()
Definition at line 92 of file IAnnotation.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.annotation.CAtomAnnotation< T >.toString().
Member Data Documentation
ATOMIC
org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.ATOMIC =("@Atomic")
Definition at line 73 of file IAnnotation.java.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAnnotation_atom(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAnnotation_atom().
CONSTANT
org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.CONSTANT =("@Constant")
Definition at line 72 of file IAnnotation.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAnnotation_value_literal(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAnnotation_value_literal().
m_name
final String org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.m_name private
Definition at line 79 of file IAnnotation.java.
PARALLEL
org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.PARALLEL =("@Parallel")
Definition at line 74 of file IAnnotation.java.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitAnnotation_atom(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitAnnotation_atom().