LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper Class Reference
org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper Class Reference
inner class for encapsulating action execution
Public Member Functions
final boolean equals (final Object p_object)
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Package Functions
CActionWrapper (@Nonnull final ILiteral p_literal, @Nonnull final Map< IPath, IAction > p_actions)
ctor
Private Member Functions
Map< Integer, IExecution > createSubExecutions (@Nonnull final Collection<? extends ITerm > p_elements, @Nonnull final Map< IPath, IAction > p_actions)
builds the map of execution arguments
List< ITerm > subexecute (@Nonnull final IContext p_context, @Nonnull final Map< Integer, IExecution > p_execution)
execute inner structures
Private Attributes
final IAction m_action
action
final Map< Integer, IExecution > m_arguments
arguments as map with index for prevent result order on parallel execution
final boolean m_parallel
parallel execution flag
Static Private Attributes
static final long serialVersionUID = 5531271525053969711L
serial id
Detailed Description
Warning
execution must run variable repacing before action calling
Definition at line 176 of file CProxyAction.java.
Constructor & Destructor Documentation
CActionWrapper()
org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.CActionWrapper (@Nonnull final ILiteral p_literal, @Nonnull final Map< IPath, IAction > p_actions) package
Parameters
p_literal action literal
p_actions actions
Definition at line 203 of file CProxyAction.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.action.IAction.minimalArgumentNumber().
Member Function Documentation
createSubExecutions()
Map<Integer, IExecution> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.createSubExecutions (@Nonnull final Collection<? extends ITerm > p_elements, @Nonnull final Map< IPath, IAction > p_actions) private
Parameters
p_elements collection with literal elements (term- / literal list of attributes & annotations)
p_actions map with actions
Returns
ordered execution structure
Definition at line 269 of file CProxyAction.java.
equals()
final boolean org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.equals (final Object p_object)
Definition at line 236 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >.hashCode().
execute()
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 243 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.IExecution.execute().
hashCode()
final int org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.hashCode ()
Definition at line 224 of file CProxyAction.java.
subexecute()
List<ITerm> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.subexecute (@Nonnull final IContext p_context, @Nonnull final Map< Integer, IExecution > p_execution) private
Parameters
p_context context structure
p_execution map with execution elements
Returns
return arguments of execution (flat list)
Definition at line 298 of file CProxyAction.java.
toString()
final String org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.toString ()
Definition at line 230 of file CProxyAction.java.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 256 of file CProxyAction.java.
References org.lightjason.agentspeak.action.IAction.variables().
Member Data Documentation
m_action
final IAction org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_action private
Definition at line 189 of file CProxyAction.java.
m_arguments
final Map<Integer, IExecution> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_arguments private
Definition at line 194 of file CProxyAction.java.
m_parallel
final boolean org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_parallel private
Definition at line 185 of file CProxyAction.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.serialVersionUID = 5531271525053969711L static private
Definition at line 181 of file CProxyAction.java.