LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify Class Reference
org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify Class Reference
unify expression
Public Member Functions
CExpressionUnify (final boolean p_parallel, @Nonnull final ILiteral p_literal, @Nonnull final IExpression p_expression)
ctor
final IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify
CDefaultUnify (final boolean p_parallel, @Nonnull final ILiteral p_literal)
ctor
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
final T getValue ()
returns the value of the action
final boolean isValueAssignableTo (final Class<?> p_class)
checkes assinable of the value
String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final IExpression m_expression
unification expression
Static Private Attributes
static final long serialVersionUID = 6897299610175239719L
serial id
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
IBaseExecution (@Nullable final T p_value)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify
final boolean m_parallel
parallel unification
final long m_variablenumber
number of variables
Protected Attributes inherited from org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >
final T m_value
data
Detailed Description
Definition at line 42 of file CExpressionUnify.java.
Constructor & Destructor Documentation
CExpressionUnify()
org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.CExpressionUnify (final boolean p_parallel, @Nonnull final ILiteral p_literal, @Nonnull final IExpression p_expression)
Parameters
p_parallel parallel execution
p_literal literal
p_expression expression
Definition at line 60 of file CExpressionUnify.java.
Member Function Documentation
execute()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 75 of file CExpressionUnify.java.
References org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.m_parallel, org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value, and org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.m_variablenumber.
toString()
final String org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.toString ()
Definition at line 68 of file CExpressionUnify.java.
References org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.m_parallel, and org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >.m_value.
variables()
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 84 of file CExpressionUnify.java.
References org.lightjason.agentspeak.language.execution.IExecution.variables(), and org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.variables().
Referenced by org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.variables().
Member Data Documentation
m_expression
final IExpression org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.m_expression private
Definition at line 51 of file CExpressionUnify.java.
serialVersionUID
final long org.lightjason.agentspeak.language.execution.action.unify.CExpressionUnify.serialVersionUID = 6897299610175239719L static private
Definition at line 47 of file CExpressionUnify.java.