LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram Class Reference
test math linear program functions
Public Member Functions
final void create ()
test create
final void equationconstraint ()
test equation constraint
final void initialize ()
initialize
final void solvemaximize ()
test solve maximum
final void solveminimize ()
test solve minimize
final void valueconstraint ()
test value constraint
Private Attributes
ImmutablePair< LinearObjectiveFunction, Collection< LinearConstraint > > m_linearprogram
testing linear program
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 53 of file TestCActionMathLinearprogram.java.
Member Function Documentation
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.create ()
Definition at line 76 of file TestCActionMathLinearprogram.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
equationconstraint()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.equationconstraint ()
Definition at line 112 of file TestCActionMathLinearprogram.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.linearprogram.CEquationConstraint.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
initialize()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.initialize ()
Definition at line 65 of file TestCActionMathLinearprogram.java.
solvemaximize()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.solvemaximize ()
Definition at line 143 of file TestCActionMathLinearprogram.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSolve.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
solveminimize()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.solveminimize ()
Definition at line 173 of file TestCActionMathLinearprogram.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.blas.matrix.CSolve.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.raw().
valueconstraint()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.valueconstraint ()
Definition at line 95 of file TestCActionMathLinearprogram.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.linearprogram.CValueConstraint.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
Member Data Documentation
m_linearprogram
ImmutablePair<LinearObjectiveFunction, Collection<LinearConstraint> > org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.m_linearprogram private
Definition at line 58 of file TestCActionMathLinearprogram.java.