LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.CCommon.ECompression Enum Reference
org.lightjason.agentspeak.language.CCommon.ECompression Enum Reference
compression algorithm
Public Member Functions
final OutputStream get (@Nonnull final DataOutputStream p_datastream) throws IOException
creates a compression stream
Static Public Member Functions
static boolean exist (@Nonnull final String p_value)
checks if a compression exists
static ECompression from (@Nonnull final String p_value)
returns a compression value
Public Attributes
BZIP
DEFLATE
GZIP
PACK200
Static Private Attributes
static final Set< String > ALGORITHMS
enum names
Detailed Description
Definition at line 450 of file language/CCommon.java.
Member Function Documentation
exist()
static boolean org.lightjason.agentspeak.language.CCommon.ECompression.exist (@Nonnull final String p_value) static
Parameters
p_value compression name
Returns
existance flag
Definition at line 513 of file language/CCommon.java.
Referenced by org.lightjason.agentspeak.action.builtin.string.CNCD.execute().
from()
static ECompression org.lightjason.agentspeak.language.CCommon.ECompression.from (@Nonnull final String p_value) static
Parameters
p_value string name
Returns
compression value
Definition at line 501 of file language/CCommon.java.
Referenced by org.lightjason.agentspeak.action.builtin.string.CNCD.execute().
get()
final OutputStream org.lightjason.agentspeak.language.CCommon.ECompression.get (@Nonnull final DataOutputStream p_datastream) throws IOException
Parameters
p_datastream data-counting stream
Returns
compression output stream
Exceptions
IOException throws on any io error
Definition at line 475 of file language/CCommon.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Data Documentation
ALGORITHMS
static final Set<String> org.lightjason.agentspeak.language.CCommon.ECompression.ALGORITHMS static private
Initial value:
= Collections.unmodifiableSet(
                                                          Arrays.stream( ECompression.values() )
                                                                .map( i -> i.name().toUpperCase( Locale.ROOT ) )
                                                                .collect( Collectors.toSet() )
                                                      )
Definition at line 461 of file language/CCommon.java.
BZIP
org.lightjason.agentspeak.language.CCommon.ECompression.BZIP
Definition at line 452 of file language/CCommon.java.
Referenced by org.lightjason.agentspeak.consistency.metric.CNCD.CNCD(), and org.lightjason.agentspeak.action.builtin.string.CNCD.execute().
DEFLATE
org.lightjason.agentspeak.language.CCommon.ECompression.DEFLATE
Definition at line 454 of file language/CCommon.java.
GZIP
org.lightjason.agentspeak.language.CCommon.ECompression.GZIP
Definition at line 453 of file language/CCommon.java.
PACK200
org.lightjason.agentspeak.language.CCommon.ECompression.PACK200
Definition at line 455 of file language/CCommon.java.