LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType Enum Reference
org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType Enum Reference
event types
Public Member Functions
EType (final String p_name)
ctor
final String sequence ()
returns the trigger sequence
String toString ()
Static Public Member Functions
static EType from (@Nonnull final String p_sequence)
returns a trigger type by the char sequence
Public Attributes
ADDBELIEF =("+")
ADDGOAL =("+!")
DELETEBELIEF =("-")
DELETEGOAL =("-!")
EMPTY =("")
Private Attributes
final String m_name
text name of the enum
Static Private Attributes
static final Map< String, EType > ELEMENTS
math with elements for intantiation
Detailed Description
Definition at line 145 of file ITrigger.java.
Constructor & Destructor Documentation
EType()
org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.EType (final String p_name)
Parameters
p_name text name
Definition at line 171 of file ITrigger.java.
Member Function Documentation
from()
static EType org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.from (@Nonnull final String p_sequence) static
Parameters
p_sequence sequence
Returns
trigger type
Definition at line 197 of file ITrigger.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.action.builtin.agent.CRemovePlan.execute(), and org.lightjason.agentspeak.action.builtin.agent.CGetPlan.execute().
sequence()
final String org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.sequence ()
Returns
trigger sequence string
Definition at line 187 of file ITrigger.java.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist().
toString()
String org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.toString ()
Definition at line 177 of file ITrigger.java.
Member Data Documentation
ADDBELIEF
org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDBELIEF =("+")
Definition at line 147 of file ITrigger.java.
Referenced by org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.add(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlan_belief_trigger(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlan_belief_trigger().
ADDGOAL
org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ADDGOAL =("+!")
Definition at line 149 of file ITrigger.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.active(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.addplan(), org.lightjason.agentspeak.configuration.CDefaultAgentConfiguration< T extends IAgent<?>.CDefaultAgentConfiguration(), org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementGoalLiteral.execute(), org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementGoalVariable.execute(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.getplan(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.initialize(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.initialize(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.planlist(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplan(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlan_goal_trigger(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlan_goal_trigger().
DELETEBELIEF
org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEBELIEF =("-")
Definition at line 148 of file ITrigger.java.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.clear(), org.lightjason.agentspeak.beliefbase.IBaseBeliefbase.remove(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlan_belief_trigger(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlan_belief_trigger().
DELETEGOAL
org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.DELETEGOAL =("-!")
Definition at line 150 of file ITrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.CPlan.execute(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitPlan_goal_trigger(), and org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitPlan_goal_trigger().
ELEMENTS
static final Map<String, EType> org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.ELEMENTS static private
Initial value:
= Collections.unmodifiableMap(
                                                                Arrays.stream( EType.values() )
                                                                      .collect( Collectors.toMap( EType::sequence, i -> i ) )
                                                           )
Definition at line 156 of file ITrigger.java.
EMPTY
org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.EMPTY =("")
Definition at line 151 of file ITrigger.java.
m_name
final String org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.EType.m_name private
Definition at line 164 of file ITrigger.java.