LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionWebRest Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionWebRest Class Reference
REST-API test.
Public Member Functions
final void jsonlisterror ()
test json list error
final void jsonlistmultiple ()
test json list with multiple argument
final void jsonlistsingle ()
test json list with single argument
final void jsonobjecterror ()
test json object error
final void jsonobjectmultiple ()
test json object with multiple arguments
final void jsonobjectsingle ()
test json object with single argument
final void xmlobjecterror ()
test xml object error
final void xmlobjectmultiple ()
test xml object with single argument
final void xmlobjectsingle ()
test xml object with single argument
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 47 of file TestCActionWebRest.java.
Member Function Documentation
jsonlisterror()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlisterror ()
Definition at line 54 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
jsonlistmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlistmultiple ()
Definition at line 93 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.web.rest.CJsonList.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.ILiteral.values().
jsonlistsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonlistsingle ()
Definition at line 71 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.web.rest.CJsonList.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.ITerm.raw().
jsonobjecterror()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjecterror ()
Definition at line 116 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
jsonobjectmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjectmultiple ()
Definition at line 156 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.web.rest.CJsonObject.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.ILiteral.values().
jsonobjectsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.jsonobjectsingle ()
Definition at line 134 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.web.rest.CJsonObject.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.functor().
xmlobjecterror()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjecterror ()
Definition at line 183 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, and org.lightjason.agentspeak.language.CRawTerm< T >.from().
xmlobjectmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjectmultiple ()
Definition at line 223 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.web.rest.CXMLObject.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.ILiteral.values().
xmlobjectsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionWebRest.xmlobjectsingle ()
Definition at line 201 of file TestCActionWebRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.web.rest.CXMLObject.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.functor().