LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.IBaseInstantiable Class Reference
org.lightjason.agentspeak.language.instantiable.IBaseInstantiable Class Reference abstract
base structure of instantiable elements
Public Member Functions
final boolean equals (final Object p_object)
IFuzzyValue< Boolean > execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
defines a plan-body operation
final int hashCode ()
final IContext instantiate (@Nonnull final IAgent<?> p_agent, @Nonnull final Stream< IVariable<?>> p_variable)
creates an individual execution context
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Protected Member Functions
IBaseInstantiable (final List< IExecution > p_action, final Set< IAnnotation<?>> p_annotation, final int p_hash)
ctor
Protected Attributes
final List< IExecution > m_action
action list
final Map< IAnnotation.EType, IAnnotation<?> > m_annotation
map with annotation (enum value for getting annotation object)
Private Member Functions
List< IFuzzyValue< Boolean > > executeparallel (final IContext p_context)
execute plan parallel
List< IFuzzyValue< Boolean > > executesequential (final IContext p_context)
execute plan sequential
Private Attributes
final int m_hash
hash code
Static Private Attributes
static final long serialVersionUID = 8843291880722926104L
serial id
Detailed Description
Definition at line 50 of file IBaseInstantiable.java.
Constructor & Destructor Documentation
IBaseInstantiable()
org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.IBaseInstantiable (final List< IExecution > p_action, final Set< IAnnotation<?>> p_annotation, final int p_hash) protected
Parameters
p_action executed actions
p_annotation annotation map
p_hash hash code
Definition at line 78 of file IBaseInstantiable.java.
Member Function Documentation
equals()
final boolean org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.equals (final Object p_object)
Definition at line 92 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.hashCode().
execute()
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute (final boolean p_parallel, @Nonnull final IContext p_context, @Nonnull final List< ITerm > p_argument, @Nonnull final List< ITerm > p_return)
Parameters
p_parallel parallel execution
p_context current execution context
p_argument parameter of the action
p_return return values
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 113 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.ATOMIC, org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.executeparallel(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.executesequential(), org.lightjason.agentspeak.language.fuzzy.CFuzzyValue< T >.from(), and org.lightjason.agentspeak.language.instantiable.plan.annotation.IAnnotation< T >.EType.PARALLEL.
executeparallel()
List<IFuzzyValue<Boolean> > org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.executeparallel (final IContext p_context) private
Parameters
p_context execution context
Returns
list with execution results
Note
each element is executed
Definition at line 163 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute().
executesequential()
List<IFuzzyValue<Boolean> > org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.executesequential (final IContext p_context) private
Parameters
p_context execution context
Returns
list with execution results
Note
stream is stopped iif an execution is failed
Definition at line 138 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.fuzzy.IFuzzyValue< T >.fuzzy().
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute().
hashCode()
final int org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.hashCode ()
Definition at line 86 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_hash.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.equals().
instantiate()
final IContext org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.instantiate (@Nonnull final IAgent<?> p_agent, @Nonnull final Stream< IVariable<?>> p_variable)
Parameters
p_agent agent
p_variable variable stream
Returns
individual context
Implements org.lightjason.agentspeak.language.instantiable.IInstantiable.
Definition at line 99 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.CCommon.instantiate().
variables()
Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 106 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.execution.IExecution.variables().
Member Data Documentation
m_action
final List<IExecution> org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action protected
Definition at line 59 of file IBaseInstantiable.java.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.executeparallel(), org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder(), org.lightjason.agentspeak.language.instantiable.rule.CRule.toString(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString().
m_annotation
final Map<IAnnotation.EType, IAnnotation<?> > org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation protected
Definition at line 64 of file IBaseInstantiable.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString(), org.lightjason.agentspeak.language.instantiable.rule.CRule.variables(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables().
m_hash
final int org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_hash private
Definition at line 68 of file IBaseInstantiable.java.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.hashCode().
serialVersionUID
final long org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.serialVersionUID = 8843291880722926104L static private
Definition at line 55 of file IBaseInstantiable.java.