LightJason - AgentSpeak(L++): org.lightjason.agentspeak.generator.IBasePlanBundleGenerator Class Reference
org.lightjason.agentspeak.generator.IBasePlanBundleGenerator Class Reference abstract
plan bundle generator
Public Member Functions
IBasePlanBundleGenerator (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions) throws Exception
ctor
final Stream< IPlanBundle > generatemultiple (final int p_number, @Nullable final Object... p_data)
Public Member Functions inherited from org.lightjason.agentspeak.generator.IGenerator< IPlanBundle >
Stream< T > generatemultiple (final int p_number, @Nullable final Object... p_data)
generates a stream of objects
T generatesingle (@Nullable final Object... p_data)
generates a single object
Protected Member Functions
IBasePlanBundleGenerator (@Nonnull final IPlanBundleConfiguration p_configuration)
ctor
Protected Attributes
final IPlanBundleConfiguration m_configuration
configuration
Detailed Description
Definition at line 47 of file IBasePlanBundleGenerator.java.
Constructor & Destructor Documentation
IBasePlanBundleGenerator() [1/2]
org.lightjason.agentspeak.generator.IBasePlanBundleGenerator.IBasePlanBundleGenerator (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions) throws Exception
Parameters
p_stream input stream
p_actions set with actions
Exceptions
Exception thrown on error
Definition at line 62 of file IBasePlanBundleGenerator.java.
References org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.initialbeliefs(), org.lightjason.agentspeak.grammar.CParserPlanBundle.parse(), org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.plans(), and org.lightjason.agentspeak.grammar.IASTVisitorAgentSpeak.rules().
IBasePlanBundleGenerator() [2/2]
org.lightjason.agentspeak.generator.IBasePlanBundleGenerator.IBasePlanBundleGenerator (@Nonnull final IPlanBundleConfiguration p_configuration) protected
Parameters
p_configuration configuration
Definition at line 78 of file IBasePlanBundleGenerator.java.
Member Function Documentation
generatemultiple()
final Stream<IPlanBundle> org.lightjason.agentspeak.generator.IBasePlanBundleGenerator.generatemultiple (final int p_number, @Nullable final Object... p_data)
Definition at line 85 of file IBasePlanBundleGenerator.java.
Member Data Documentation
m_configuration
final IPlanBundleConfiguration org.lightjason.agentspeak.generator.IBasePlanBundleGenerator.m_configuration protected
Definition at line 52 of file IBasePlanBundleGenerator.java.