LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate Class Reference
test for math interpolate
Public Member Functions
final void create ()
test create
final void multipleinterpolate ()
test multiple interpolate
final void singleinterpolate ()
test single interpolate
Additional Inherited Members
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 51 of file TestCActionMathInterpolate.java.
Member Function Documentation
create()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate.create ()
Definition at line 58 of file TestCActionMathInterpolate.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.collection.list.CCreate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
multipleinterpolate()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate.multipleinterpolate ()
Definition at line 124 of file TestCActionMathInterpolate.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.interpolate.CMultipleInterpolate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
singleinterpolate()
final void org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate.singleinterpolate ()
Definition at line 104 of file TestCActionMathInterpolate.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.math.interpolate.CSingleInterpolate.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().