LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> Class Template Reference
org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> Class Template Reference abstract
agent base structure
Public Member Functions
IBaseAgent (@Nonnull final IAgentConfiguration< T > p_configuration)
ctor
final IView beliefbase ()
T call () throws Exception
final long cycletime ()
final IFuzzyBundle< Boolean > fuzzy ()
final< N extends IInspector > Stream< N > inspect (@Nonnull final N... p_inspector)
final Multimap< ITrigger, IPlanStatistic > plans ()
final< N extends IAgent<?> > N raw ()
final Multimap< IPath, IRule > rules ()
final Multimap< IPath, ILiteral > runningplans ()
final IAgent< T > sleep (final long p_cycles, final ITerm... p_term)
final IAgent< T > sleep (final long p_cycles, @Nonnull final Stream< ITerm > p_literal)
final boolean sleeping ()
final Map< String, Object > storage ()
String toString ()
final IFuzzyValue< Boolean > trigger (@Nonnull final ITrigger p_trigger, @Nullable final boolean... p_immediately)
final IUnifier unifier ()
final IVariableBuilder variablebuilder ()
final IAgent< T > wakeup (@Nullable final ITerm... p_term)
final IAgent< T > wakeup (@Nonnull final Stream< ITerm > p_term)
Public Member Functions inherited from org.lightjason.agentspeak.agent.IAgent< T >
IView beliefbase ()
returns the beliefbase
long cycletime ()
returns the time in nano seconds at the last cycle
IFuzzyBundle< Boolean > fuzzy ()
return fuzzy operator
< N extends IInspector > Stream< N > inspect (@Nonnull final N... p_inspector)
inspector method
Multimap< ITrigger, IPlanStatistic > plans ()
returns the internal map of plans
< N extends IAgent<?> N raw ()
cast the interface agent object to a specified agent object
Multimap< IPath, IRule > rules ()
returns amultimap with literal-rule functor and rle objects
Multimap< IPath, ILiteral > runningplans ()
returns a map of the current running plans
IAgent< T > sleep (final long p_cycles, @Nullable final ITerm... p_term)
pushs the agent into sleeping state
IAgent< T > sleep (final long p_cycles, @Nonnull final Stream< ITerm > p_term)
pushs the agent into sleeping state
boolean sleeping ()
returns sleeping state
Map< String, Object > storage ()
storage access
IFuzzyValue< Boolean > trigger (@Nonnull final ITrigger p_trigger, @Nullable final boolean... p_immediately)
trigger an event
IUnifier unifier ()
returns an unifier
IVariableBuilder variablebuilder ()
returns the variable builder function
IAgent< T > wakeup (@Nullable final ITerm... p_term)
wake-up the agent by generating wakeup-goal
IAgent< T > wakeup (@Nonnull final Stream< ITerm > p_term)
wake-up the agent by generating wakeup-goal
Protected Attributes
final IView m_beliefbase
beliefbase
final Multimap< ITrigger, IPlanStatistic > m_plans
map with all existing plans and successful / fail runs
final Multimap< IPath, IRule > m_rules = Multimaps.synchronizedMultimap(LinkedHashMultimap.create())
multimap with rules
final Map< String, Object > m_storage = new ConcurrentHashMap<>()
storage map
final Map< Integer, ITrigger > m_trigger = new ConcurrentHashMap<>()
execution trigger with content hash
Static Protected Attributes
static final Logger LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAgent.class)
logger
Private Member Functions
boolean active (final boolean p_immediatly)
runs the wakeup goal
IFuzzyValue< Boolean > execute (@Nonnull final Collection< Pair< IPlanStatistic, IContext >> p_execution)
execute list of plans
Collection< Pair< IPlanStatistic, IContext > > generateexecution (@Nonnull final Stream< ITrigger > p_trigger)
create execution list with plan and context
synchronized Collection< Pair< IPlanStatistic, IContext > > generateexecutionlist ()
create the plan executionlist with clearing internal structures
Private Attributes
final AtomicLong m_cycletime = new AtomicLong()
nano seconds at the last cycle
final IFuzzyBundle< Boolean > m_fuzzy
fuzzy result collector
final Multimap< IPath, ILiteral > m_runningplans = Multimaps.synchronizedSetMultimap(HashMultimap.create())
running plans (thread-safe)
final AtomicLong m_sleepingcycles = new AtomicLong(Long.MIN_VALUE)
number of sleeping cycles
final Set< ITerm > m_sleepingterm = Collections.synchronizedSet(new HashSet<>())
set for waking-up literals
final IUnifier m_unifier
unifier
final IVariableBuilder m_variablebuilder
variable builder
Static Private Attributes
static final long serialVersionUID = -304366902555398136L
serial id
Additional Inherited Members
Public Attributes inherited from org.lightjason.agentspeak.agent.IAgent< T >
IAgent<?> EMPTY
empty agent
Detailed Description
Template Parameters
T agent type
Definition at line 81 of file IBaseAgent.java.
Constructor & Destructor Documentation
IBaseAgent()
org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.IBaseAgent (@Nonnull final IAgentConfiguration< T > p_configuration)
Parameters
p_configuration agent configuration
Definition at line 153 of file IBaseAgent.java.
Member Function Documentation
active()
boolean org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.active (final boolean p_immediatly) private
Parameters
p_immediatly runs the wake always
Returns
returns true if the agent is active
Definition at line 458 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.call(), and org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.wakeup().
beliefbase()
final IView org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.beliefbase ()
Definition at line 170 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.consistency.TestCMetric.agent().
call()
T org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.call () throws Exception
Definition at line 349 of file IBaseAgent.java.
cycletime()
final long org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.cycletime ()
Definition at line 265 of file IBaseAgent.java.
execute()
IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.execute (@Nonnull final Collection< Pair< IPlanStatistic, IContext >> p_execution) private
Parameters
p_execution execution collection with instantiated plans and context
Returns
fuzzy result for each executaed plan
Definition at line 427 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.call(), and org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.trigger().
fuzzy()
final IFuzzyBundle<Boolean> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.fuzzy ()
Definition at line 279 of file IBaseAgent.java.
generateexecution()
Collection<Pair<IPlanStatistic, IContext> > org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.generateexecution (@Nonnull final Stream< ITrigger > p_trigger) private
Parameters
p_trigger trigger stream
Returns
collection with excutable plans, instantiated execution context and plan statistic
Definition at line 400 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.generateexecutionlist(), and org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.trigger().
generateexecutionlist()
synchronized Collection<Pair<IPlanStatistic, IContext> > org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.generateexecutionlist () private
Note
must be synchronized for avoid indeterministic trigger list
Returns
collection with execution plan and context
Definition at line 378 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.call().
inspect()
final<N extends IInspector> Stream<N> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.inspect (@Nonnull final N... p_inspector)
Definition at line 179 of file IBaseAgent.java.
plans()
final Multimap<ITrigger, IPlanStatistic> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.plans ()
Definition at line 272 of file IBaseAgent.java.
raw()
final<N extends IAgent<?> > N org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.raw ()
Definition at line 301 of file IBaseAgent.java.
rules()
final Multimap<IPath, IRule> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.rules ()
Definition at line 293 of file IBaseAgent.java.
runningplans()
final Multimap<IPath, ILiteral> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.runningplans ()
Definition at line 197 of file IBaseAgent.java.
sleep() [1/2]
final IAgent<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.sleep (final long p_cycles, final ITerm... p_term)
Definition at line 210 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.sleep().
sleep() [2/2]
final IAgent<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.sleep (final long p_cycles, @Nonnull final Stream< ITerm > p_literal)
Definition at line 222 of file IBaseAgent.java.
sleeping()
final boolean org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.sleeping ()
Definition at line 203 of file IBaseAgent.java.
storage()
final Map<String, Object> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.storage ()
Definition at line 251 of file IBaseAgent.java.
toString()
String org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.toString ()
Definition at line 307 of file IBaseAgent.java.
trigger()
final IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.trigger (@Nonnull final ITrigger p_trigger, @Nullable final boolean... p_immediately)
Definition at line 325 of file IBaseAgent.java.
unifier()
final IUnifier org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.unifier ()
Definition at line 258 of file IBaseAgent.java.
variablebuilder()
final IVariableBuilder org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.variablebuilder ()
Definition at line 286 of file IBaseAgent.java.
wakeup() [1/2]
final IAgent<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.wakeup (@Nullable final ITerm... p_term)
Definition at line 231 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.wakeup().
wakeup() [2/2]
final IAgent<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.wakeup (@Nonnull final Stream< ITerm > p_term)
Definition at line 242 of file IBaseAgent.java.
Member Data Documentation
LOGGER
final Logger org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.LOGGER = org.lightjason.agentspeak.common.CCommon.logger(IAgent.class) static protected
Definition at line 86 of file IBaseAgent.java.
m_beliefbase
final IView org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_beliefbase protected
Definition at line 94 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.beliefbase(), org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.CAgent.CAgent(), and org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.toString().
m_cycletime
final AtomicLong org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_cycletime = new AtomicLong() private
Definition at line 117 of file IBaseAgent.java.
m_fuzzy
final IFuzzyBundle<Boolean> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_fuzzy private
Definition at line 140 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.call(), org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.execute(), org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.fuzzy(), and org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.generateexecution().
m_plans
final Multimap<ITrigger, IPlanStatistic> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_plans protected
Initial value:
= Multimaps.synchronizedMultimap(
                                                                    TreeMultimap.create( IStructureHash.COMPARATOR, Comparator.<IPlanStatistic>naturalOrder() ) )
Definition at line 112 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.plans().
m_rules
final Multimap<IPath, IRule> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_rules = Multimaps.synchronizedMultimap(LinkedHashMultimap.create()) protected
Definition at line 108 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.rules().
m_runningplans
final Multimap<IPath, ILiteral> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_runningplans = Multimaps.synchronizedSetMultimap(HashMultimap.create()) private
Definition at line 144 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.execute(), org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.generateexecutionlist(), and org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.toString().
m_sleepingcycles
final AtomicLong org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_sleepingcycles = new AtomicLong(Long.MIN_VALUE) private
Note
values >= 0 defines the sleeping time, Long.MAX_VALUE is infinity sleeping negative values defines the activity
Definition at line 124 of file IBaseAgent.java.
m_sleepingterm
final Set<ITerm> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_sleepingterm = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 128 of file IBaseAgent.java.
m_storage
final Map<String, Object> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_storage = new ConcurrentHashMap<>() protected
Note
must be thread-safe
Definition at line 100 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.storage().
m_trigger
final Map<Integer, ITrigger> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_trigger = new ConcurrentHashMap<>() protected
Definition at line 104 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionAgent.CEmptyPlan.trigger().
m_unifier
final IUnifier org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_unifier private
Definition at line 132 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.generateexecution(), and org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.unifier().
m_variablebuilder
final IVariableBuilder org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.m_variablebuilder private
Definition at line 136 of file IBaseAgent.java.
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< CMethodBindingBlacklist >.variablebuilder().
serialVersionUID
final long org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?>.serialVersionUID = -304366902555398136L static private
Definition at line 90 of file IBaseAgent.java.