LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M > Interface Template Reference
org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M > Interface Template Reference
interface of a physical beliefbase storage
Public Member Functions
void clear ()
clears all elements
boolean containsMultiElement (@Nonnull final String p_key)
contains a multi-element
boolean containsSingleElement (@Nonnull final String p_key)
contains a single-element
boolean empty ()
checks if a storage is empty
Collection< N > getMultiElement (@Nonnull final String p_key)
returns a collection of multi-elementy by name
M getSingleElement (@Nonnull final String p_key)
returns a single-element by the name
M getSingleElementOrDefault (@Nonnull final String p_key, final M p_default)
returns a single-element by the name
boolean putMultiElement (@Nonnull final String p_key, final N p_value)
puts a multi-element into the storage
boolean putSingleElement (@Nonnull final String p_key, final M p_value)
puts a single-element into the storage
boolean putSingleElementIfAbsent (@Nonnull final String p_key, final M p_value)
puts a single-element if it is absent
boolean removeMultiElement (@Nonnull final String p_key, final N p_value)
removes a multi-element from the storage
boolean removeSingleElement (@Nonnull final String p_key)
removes a single-element from the storage
int size ()
number of multi elements
Stream< N > streamMultiElements ()
returns a stream over all multi-elements
Stream< M > streamSingleElements ()
returns a stream over all single-elements
IAgent<?> update (@Nonnull final IAgent<?> p_agent)
updates all items
Detailed Description
Template Parameters
N multiple elements
M single elements
T agent type
Warning
internal data structure must be thread-safe
Definition at line 41 of file beliefbase/storage/IStorage.java.
Member Function Documentation
clear()
void org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.clear ()
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.clear().
containsMultiElement()
boolean org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.containsMultiElement (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.containsLiteral().
containsSingleElement()
boolean org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.containsSingleElement (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean existing flag
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.containsView().
empty()
boolean org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.empty ()
Returns
empty boolean
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.empty().
getMultiElement()
Collection<N> org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.getMultiElement (@Nonnull final String p_key)
Parameters
p_key name
Returns
collection of multi-elements
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.literal().
getSingleElement()
M org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.getSingleElement (@Nonnull final String p_key)
Parameters
p_key key
Returns
single-element or null
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.view().
getSingleElementOrDefault()
M org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.getSingleElementOrDefault (@Nonnull final String p_key, final M p_default)
Parameters
p_key key
p_default default element
Returns
single-element or the default element
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.viewOrDefault().
putMultiElement()
boolean org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.putMultiElement (@Nonnull final String p_key, final N p_value)
Parameters
p_key key
p_value multi-element
Returns
boolean if the element can be stored
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.add().
putSingleElement()
boolean org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.putSingleElement (@Nonnull final String p_key, final M p_value)
Parameters
p_key key
p_value single-element
Returns
boolean if the element can be stored
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.add().
putSingleElementIfAbsent()
boolean org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.putSingleElementIfAbsent (@Nonnull final String p_key, final M p_value)
Parameters
p_key key
p_value single-element
Returns
boolean if the element can be stored
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
removeMultiElement()
boolean org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.removeMultiElement (@Nonnull final String p_key, final N p_value)
Parameters
p_key key
p_value multi-element
Returns
boolean if the element can removed
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.remove().
removeSingleElement()
boolean org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.removeSingleElement (@Nonnull final String p_key)
Parameters
p_key key
Returns
boolean if the element can be removed
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.remove().
size()
int org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.size ()
Returns
element number
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.size().
streamMultiElements()
Stream<N> org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamMultiElements ()
Returns
multi-element stream
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.clear(), and org.lightjason.agentspeak.beliefbase.CBeliefbase.streamLiteral().
streamSingleElements()
Stream<M> org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.streamSingleElements ()
Returns
single-element stream
Implemented in org.lightjason.agentspeak.beliefbase.storage.CSingleStorage< N, M >, org.lightjason.agentspeak.beliefbase.storage.CMultiStorage< N, M >, and org.lightjason.agentspeak.beliefbase.storage.CSingleOnlyStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.clear(), org.lightjason.agentspeak.beliefbase.CBeliefbase.size(), org.lightjason.agentspeak.beliefbase.CBeliefbase.streamView(), org.lightjason.agentspeak.beliefbase.CBeliefbase.trigger(), and org.lightjason.agentspeak.beliefbase.CBeliefbase.update().
update()
IAgent<?> org.lightjason.agentspeak.beliefbase.storage.IStorage< N, M >.update (@Nonnull final IAgent<?> p_agent)
Parameters
p_agent agent which calls the update
Returns
agent
Implemented in org.lightjason.agentspeak.beliefbase.storage.IBaseStorage< N, M >.
Referenced by org.lightjason.agentspeak.beliefbase.CBeliefbase.update().